### ISSUE TITLE
Editing arrays in the Neon Console is broken

### ISSUE THREAD

**Issue by Emilcrafter** [neondatabase/neon#10047]
## Steps to reproduce
- Create a table in a neon postgres database, where one of the columns is a string array
- Populate the table with at least one row
- Attempt to edit the array value in the Neon console

## Expected result
- Code editor shows up, allowing the user to edit the array
- Saving the changes persists the value in the database

## Actual result
- Array value is converted from `["value1", "value2", "value3"]` into `value1, value2, value3` and is editable in a field similar to a normal string value (as if editing `array.join(", ")`
- Saving the changes to the array results in an error dialog `e.map is not a function`

## Environment
Neon Console, Arc Browser

## Logs, links
- 
https://github.com/user-attachments/assets/fff60c79-cb7f-4d09-b5a1-32d9526d89d4

**Comment by RomanNabukhotnyi** [comment]
@Emilcrafter Hey! Should be fixed by now.

**Comment by alexfedosov** [comment]
For reference, this has been fixed in 1.0.3 
- https://github.com/neondatabase/cloud/pull/21377
