### ISSUE TITLE
Epic: implement WAL offloading from safekeer to s3

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1009]
## Motivation
In case of unexpected loss of pageservers, or accidental data corruption, we want to preserve the full WAL in S3. Having it, we should be able to restore the timeline from WAL in most cases.

## Tasks

- [x] #37
- [x] #1010
- [x] #1011
- [x] #1680
- [x] #1644
- [x] Enable eager WAL cleanup based on WAL backup & commit lsn

this contibues in #1925

**Comment by stepashka** [comment]
this heavily depends on gossip implementation in safekeepers #543, so will be continued after some groundwork has been done there

**Comment by stepashka** [comment]
adding @antons-antons as he's done a writeup for the s3 syn for safekeppers
what are our nexts steps?

**Comment by antons-antons** [comment]
https://github.com/neondatabase/neon/pull/1583

**Comment by stepashka** [comment]
consider putting the remainders into the separate task @stepashka
