### ISSUE TITLE
Epic: page-level CRC

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1083]
We need CRCs to detect data corruption in two cases:
* for the data on disk
* for the data going thorough network

There is some amount of disagreement about our failure model, so it is better to start from RFC.

**Comment by patins** [comment]
Some progess was made on this here: https://github.com/zenithdb/bookfile/pull/1

**Comment by kelvich** [comment]
Good way to report a checksum error is to try flipping each bit in a page and checksum to see if it would match: https://github.com/ClickHouse/ClickHouse/blob/master/src/Compression/CompressedReadBufferBase.cpp#L54

**Comment by stepashka** [comment]
could be a dup of #987

**Comment by stepashka** [comment]
closing this in favor of https://github.com/neondatabase/neon/issues/2784
