### ISSUE TITLE
think of any changes to checkpoint generation algorithm to avoid bloat by frequent full layer

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#1137]

**Comment by kelvich** [comment]
https://github.com/zenithdb/zenith/pull/1133

**Comment by stepashka** [comment]
@kelvich @hlinnaka is this at all relevant in view of the new developments in storage? what should we do with this task and the corresponding PR?

**Comment by bojanserafimov** [comment]
@stepashka This issue becomes irrelevant with https://github.com/zenithdb/zenith/pull/1350 . AFAIK we can close the issue when that merges.

Any remaining work on bloat minimization should spill into https://github.com/zenithdb/zenith/issues/1357
