### ISSUE TITLE
Long startup time (slow loading of the layer map)

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1155]
startup is slow because of loading layer map
50 minutes for compressed database 1 TB
4 minutes for uncompressed database 1 TB

**Comment by stepashka** [comment]
@hlinnaka is this relevant for the new storage implemtation?

**Comment by hlinnaka** [comment]
> @hlinnaka is this relevant for the new storage implemtation?

Don't think so. Closing.
