### ISSUE TITLE
Confusion about end LSNs of an XLOG_SWITCH record

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1190]
While I was looking at the code around WAL decoding, and which LSNs are record start LSNs and which ones are end LSNs, and where we restart replication (https://github.com/zenithdb/zenith/pull/1182), I noticed an issue with XLOG_SWITCH records:

When `WalStreamDecoder::poll_decode` has successfully decoded a record, it returns its end-LSN to the caller. After the record is processed in the pageserver, that end LSN become the current `last_record_lsn`, and if a checkpoint happens, it is stored as the `disk_consistent_lsn`. After restart, we will restart replication from the safekeepers at that LSN.

However, if the last record was an XLOG_SWITCH record, that won't work. An XLOG_SWITCH record is special, in that it "consumes" the rest of the WAL segment, so that the next record will start at the beginning of the next segment. However, for an XLOG_SWITCH record, `poll_decode` returns the position of the end of the record, not the end of the segment. If you try to restart replication from the end of the record, I believe it will fail.

Safekeeper uses the same code, so there might be issues there too.

I haven't tested that, but it seems wrong to me. Needs to be verified and fixed if necessary.

**Comment by yeputons** [comment]
@hlinnaka Do we have a test where `XLOG_SWITCH` is emitted? I see that corresponding lines are triggered somewhere in the coverage reports, but I'm not sure where exactly.

**Comment by hlinnaka** [comment]
> @hlinnaka Do we have a test where `XLOG_SWITCH` is emitted? I see that corresponding lines are triggered somewhere in the coverage reports, but I'm not sure where exactly.

It's emitted by the `pg_switch_wal()` SQL function, like `SELECT pg_switch_wal();`. Grepping around, we have one such call in `test_runner/batch_others/test_subxacts.py` at least. There are probably more in the Postgres regression tests.
