### ISSUE TITLE
insert select into itself generates this warning

### ISSUE THREAD

**Issue by nikitashamgunov** [neondatabase/neon#1195]
snowy-sunset-088328=> insert into nikita select * from nikita;
WARNING:  invalid page in block 20 of relation base/16385/24576_fsm; zeroing out page

Repro is 
create table nikita(id int);
insert into nikita values(1);
do $$
begin
for i in 1..100 loop
   insert into nikita select * from nikita;
end loop;
end;
$$;

**Comment by stepashka** [comment]
could this be related to #1215 ?

**Comment by shanyp** [comment]
@koivunej please see if this still happens

**Comment by koivunej** [comment]
Let the original reproduction run for quite some time, this seems fixed so closing.
