### ISSUE TITLE
 add reporting of the LSN metrics to all storage components, per timeline

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1217]

**Comment by stepashka** [comment]
some of the metrics were added/fixed in zenithdb/zenith#541

**Comment by petuhovskiy** [comment]
LSN metric in pageserver was added in https://github.com/neondatabase/neon/pull/1430

**Comment by petuhovskiy** [comment]
I've added test for pageserver/safekeeper LSN metrics in https://github.com/neondatabase/neon/pull/1722. The only component without LSN metrics is compute, but let's create another issue for that
