### ISSUE TITLE
t_xmin XXX is uncommitted in tuple to be updated in table

### ISSUE THREAD

**Issue by knizhnik** [neondatabase/neon#1227]
I trying to test work with CLOG with wal_log_hints=off.
I am using the following function:
```
create or replace function do_update(id integer, level integer) returns void as $$
begin
	begin
        if level > 0 then
	        perform do_update(id, level-1);
	    else
		    update pgbench_accounts SET abalance = abalance + 1 WHERE aid = id;
	    end if;
	exception WHEN OTHERS THEN
	    raise notice '% %', SQLERRM, SQLSTATE;
	end;
end; $$ language plpgsql;
```

and the following update.sql script for pgbench:
```
\set aid random(1, 1000)
select do_update(:aid,100)
```
With the following command:
```
pgbench  -h 127.0.0.1 -p 55432   -U zenith_admin postgres -f update.sql -c 100 -T 100 -P 1 -M prepared
```

I sometimes get errors:
```
NOTICE:  t_xmin 8307626 is uncommitted in tuple (0,112) to be updated in table "pgbench_accounts" XX001
```

Also zenith shows at this test ~100 times smaller TPS than vanilla.

**Comment by knizhnik** [comment]
Update:
Setting wal_log_hints=on neither prevents this error, neither improve performance

**Comment by knizhnik** [comment]
I thought that this bug can be not zenith specific, but can be cause by race condition in setting status of subtransactions.
I have inserted sleeps in TransactionIdSetPageStatusInternal but still failed to reproduce the problem with vanilla.

Also I have traced that no page of `pgbench_account` was evicted during this test. So it is not caused by loosing hint bits.

Some strange thing (not related to this problem) is that zenith still request few pages of `pgbench_accounts_pkey` from pageserver, although all database fits in shared buffer.

**Comment by hlinnaka** [comment]
Good find! :+1:

**Comment by stepashka** [comment]
@lubennikovaav will review the status of this

**Comment by hlinnaka** [comment]
Committed a fix to PostgreSQL (https://github.com/postgres/postgres/commit/adf6d5dfb2094cc2bb28b4dea0565dcd0e775ed9). It will appear in the next minor versions.
