### ISSUE TITLE
Consider exporting opentelemetry data from services

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#1250]
Here's a draft example of how all our tracing-based systems can export every tracing span to Jaeger automatically: https://github.com/zenithdb/zenith/compare/kb/bump-deps...kb/jaeger-example?expand=1

We need to consider, if we need it and how to do it better on our staging, then propagate the changes and test them.

**Comment by hlinnaka** [comment]
I took another stab at OpenTelemery, but not for the storage servers but for the control plane and the compute startup. See:

https://github.com/neondatabase/neon/pull/3353
https://github.com/neondatabase/cloud/pull/3572
