### ISSUE TITLE
Client is stuck and instance is shut down while running vacuum full

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1304]
Extracted from https://github.com/zenithdb/zenith/issues/1215

Repro:
1. pgbench init with scale 500 with no vacuum
2. vacuum full

Result:
client is stuck without returning the result
instance is shutdown

Now I see this error in compute logs:

```
2022-02-21 17:04:45.376 GMT [35] ERROR:  could not extend file because cluster size limit (10000 MB) has been exceeded
2022-02-21 17:04:45.376 GMT [35] HINT:  This limit is defined by zenith.max_cluster_size GUC
2022-02-21 17:04:45.376 GMT [35] STATEMENT:  VACUUM FULL;
``` 

And this error is not propagated to client. After some time instance is shut down

**Comment by knizhnik** [comment]
Can't reproduce it now: error is  delivered to the client.
```
postgres=# vacuum full;
ERROR:  could not extend file because cluster size limit (10000 MB) has been exceeded
HINT:  This limit is defined by zenith.max_cluster_size GUC
```

**Comment by LizardWizzard** [comment]
I tried it with scale 500 and now it is larger than the limit used in our clusters by default so I cannot use exactly the same steps to reproduce the error. @ololobus is there a way to allow larger instances for particular users?

**Comment by ololobus** [comment]
@LizardWizzard you can do it with Edit button on the cluster page in admin, e.g.: https://console.zenith.tech/admin/clusters/lively-dream-771350

It shows some weird wording and wrong units, also max_cluster_size isn't updated on the admin page, but units are MB and if you change it, `max_cluster_size` seems to be updated and limit will be changed on the public cluster page

cc @seymourisdead

**Comment by LizardWizzard** [comment]
@ololobus It seems that I can reproduce this even without cluster size change. Steps:
* I filled cluster with data up to 97% 
* Did `SELECT count(*) FROM foo;`
* And after some time cluster is shown as Idle without any updates to the client

cc @funbringer 

It reproduces consistently, so I can give access to the cluster

**Comment by dhammika** [comment]
> 
>     * Did `SELECT count(*) FROM foo;`
> 
>     * And after some time cluster is shown as Idle without any updates to the client
> 

Did  the select query hang or cluster marked as idle in console UX? Do you see same behavior if you run select in psql?

**Comment by LizardWizzard** [comment]
Both :)

I've run a select query through psql, and after some time, the cluster becomes idle in console UI, and the query hangs.

I had a chat with @funbringer, and he suggested that AWS timeouts might be taking place. The PR above tries to address that. I'll check whether the PR fixed the issue or not.

**Comment by LizardWizzard** [comment]
@funbringer That didn't work for me. Intuitively I think that this is the right direction of thinking, but something is missing

**Comment by funbringer** [comment]
@LizardWizzard thanks, it didn't help me either. I'm starting to think we have to tune `tcp_keepalive_time`. I've already asked for @cicdteam's help.

**Comment by LizardWizzard** [comment]
Fixed by enabling keep-alive and corresponding config changes
