### ISSUE TITLE
Log records should record LSNs of the pages being modified

### ISSUE THREAD

**Issue by antons-antons** [neondatabase/neon#1312]
in order to detect inconsistencies in per-page transaction log records, LSNs of the pages should be recorded as part of the log records.

for example, heap insert into page X with LSN A will result in a Log record with block 0 recording previous page LSN A.
On the page server in turn, when wal redo is replaying a log record it would validate that previous page LSN matches what's in the log record (redo should fail if mismatch is detected)

Note: currently we depend on Postgres transaction log format which could pose a challenge to implement this functionality cleanly

**Comment by jcsp** [comment]
We're not planning on deviating from the postgres binary WAL format any time soon
