### ISSUE TITLE
Implement correct reading beyond EOF handling on compute/page server

### ISSUE THREAD

**Issue by antons-antons** [neondatabase/neon#1313]
Currently there's if compute is asking to read beyond EOF the page server will happily return a 0-page. 

If we by mistake compute requested a read at a wrong LSN it will go through undetected and may cause data corruption/wrong results.

To add extra protection relation extension should be explicitly logged (in addition to update to the relsize cache) such that future read can tell allocated page from a bogus read

**Comment by stepashka** [comment]
sent to backlog for now as this isn't the top prio
