### ISSUE TITLE
Avoid returning 0 pages from Storage

### ISSUE THREAD

**Issue by antons-antons** [neondatabase/neon#1338]
0 pages errors/warnings happen in Postgres in different circumstances. while some cases are harmless, others could lead to wrong results and data inconsistency.

In order to distinguish between different cases that produce a 0-page in the cache, use makers to for differentiation.

1. Page extension persistence - explicitly log a record with a new resource manager to avoid extension by reading beyond EOF. Redo of such log records will stamp the page with relfilenode/fork/block; this produces a non-0 page and thus a checksum could be calculated and set on such pages
_Note: VM and FSM forks, could be initialized to a valid page without a stamp_
_additionally heap multi-extend could happen with a valid empty page:_ https://github.com/zenithdb/postgres/pull/137 
2. Reading page with P_NEW or RBM_ZERO_AND[_CLEANUP]_LOCK in the buffer cache should not produce a 0 page but should stamp the buffer with relfilenode 
3. When a 0 page is returned by the buffer cache page's stamp is validated against buffer tag, panic when stamp doesn't match tag or stamp is missing

Page server would not return successful read requests beyond EOF, read requests will fail.

**Comment by stepashka** [comment]
I've detached this from the storage Epic as this is not exactly what we want to do there.
@antons-antons , for now sending to backlog
