### ISSUE TITLE
Improve heuristics for compaction

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1357]
The heuristics for when to compact, when to create image layers, etc. are very simplistic: If there are 10 delta layers at "level 0", they are compacted (or reshuffled, if you will). That merges the files and splits them again by key-dimension rather than LSN-dimension. And if there are more than 3 delta layers on top of the latest image layer of a partition, a new image layer is created. These heuristics could be improved a lot.

**Comment by shanyp** [comment]
will be handled by compaction work with Chi
