### ISSUE TITLE
Add pageserver component perf tests

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#1380]
Motivation:
We're currently only testing the pageserver as a part of a zenith cluster with 1 writer node and 0 reader nodes. But we want our work on the storage format to be able to support our future use cases without another major redesign, so we should test how it performs on workloads that will be required of it in the near future, like get_page_at_lsn for non-latest pages.

The scope of this issue is to create a minimal test suite for measuring get_page performance in isolation. That would help with perf work on the following issues:
- https://github.com/zenithdb/zenith/issues/1357
- https://github.com/zenithdb/zenith/issues/1142
- maybe https://github.com/zenithdb/zenith/issues/1339 (maybe not but it's a relevant issue)

I have some preliminary results, will share below.

**Comment by bojanserafimov** [comment]
![newplot(2)](https://user-images.githubusercontent.com/8680233/159082568-81bc48ee-9722-4a1a-adb5-cc97b3cd3df6.png)

Initial experiment: I wrote 10k updates to the same row that contains only an integer. Then I forced checkpoint and ran get_page for 0.1% of the relevant LSNs, where an update to that page was made. On the plot above, we have:
x: LSN
y: get_page runtime in microseconds

This test was ran on my laptop with release build, on top of the `heikki-kvstore` branch. To reproduce, here's my [wip branch](https://github.com/zenithdb/zenith/tree/bojan-psbench-over-kvstore).

takeaways:
- We can easily get 140ms latency for a get_page request. Not good, but fixable
- Latency grows linearly with number of updates, and there's room for more updates before pageserver takes an image
- NOTE: This test doesn't stress disk lookup time, since all the relevant wal is in the latest layer. But the test suite is capable of testing this, and that's what I'm planning to try next.

non-takeaways:
- Average redo time was 1.4 microseconds, but I'm only measuring one kind of wal entry, so don't take this number seriously at all.

**Comment by bojanserafimov** [comment]
> Not needed for 0.3 milestone. After some thinking I realized that it's not clear how probable it is that we'll ever have two compute nodes share a pageserver. A read node in a different region will require a local pageserver, since the safekeeper-pageserver connection is the only one that can afford latency. We might only need random LSN reads in a few niche cases:
> 
>     1. Read only repllica for stricter isolation of readers for security. Useful for sharing data across organizations
> 
>     2. Time travel queries
> 
>     3. ???

Resuming work on this issue. Random historical queries are maybe [not important](https://github.com/zenithdb/rfcs/pull/18), so I will only focus on more immediately impactful tests:
1. get_page performance for latest pages
2. get_page performance from recent wal

**Comment by bojanserafimov** [comment]
I tested `get_page` performance for the **latest** page for each key, for three different workloads:

## workload 1: pgbench small
pgbench -s5 -i
pgbench -c1 -t5000

### results
Total pages: 9742
Fastest: 19.925µs
Median: 44.113µs
99th percentile: 169.875µs
Slowest: 6.017257ms

## workload 2: pgbench big
pgbench -s100 -i
pgbench -c1 -t100000

### results
Total pages: 193366
Fastest: 17.465µs
Median: 33.979µs
99th percentile: 125.403µs
Slowest: 19.226091ms

## workload 3: pgbench big and long
pgbench -s100 -i
pgbench -c1 -t1000000

### results
Total pages: 200609
Fastest: 20.031µs
Median: 45.195µs
99th percentile: 103.583µs
Slowest: **38.300479ms**

Not sure how the cache is configured, and how that might obscure results I'd get on a bigger database. Now working on getting this test merged into main so others can play with it

**Comment by jcsp** [comment]
This is stale, the perf testing story has moved on.
