### ISSUE TITLE
Throttle ingesting new WAL if there is already a big backlog of in-memory layers

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1411]
If there are already many frozen in-memory layers, and new WAL is processed faster than the layer flushing thread can flush the old frozen in-memory layers to disk, start throttling the WAL receiver. Otherwise we will accumulate more and more in-memory layers until we run out of memory.

The "in-memory" layers are actually spilled to disk too, so it won't happen as quickly as you might think. But there's still a fair amount of in-memory data structures, so each in-memory layer still consumes a fair amount of memory even if all its data pages are spilled to disk.

**Comment by shanyp** [comment]
@hlinnaka does this need any protocol change ?
