### ISSUE TITLE
Strange failure of pg regress

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1415]
For unrelated PR pg regress has failed. 

CI job https://app.circleci.com/pipelines/github/zenithdb/zenith/5050/workflows/6f566fa8-6db3-4950-adf9-d6d826d7c83d/jobs/49023/artifacts

In regress.diff I see a lot of errors about missing relation.
e g
`ERROR:  relation "indtoasttest" does not exist`

@dhammika is it the same issue that you've reproduced locally? cc @hlinnaka

**Comment by hlinnaka** [comment]
The first error here seems to be this:
```
 CREATE TABLE indtoasttest(descr text, cnt int DEFAULT 0, f1 text, f2 text);
+ERROR:  cache lookup failed for attribute 2 of relation 28360
```
All the subsequent `relation "indtoasttest" does not exist` are because the CREATE TABLE failed.

I don't know what caused the "cache lookup failed" error.

**Comment by dhammika** [comment]
> 
> @dhammika is it the same issue that you've reproduced locally? cc @hlinnaka

Don't think they're identical. I probably had a bad build. Vendored pg submod was pointing to main branch's head.

**Comment by shanyp** [comment]
@LizardWizzard should we keep this ?
