### ISSUE TITLE
cannot complete vacuum full because size limit is reached

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1445]
@lubennikovaav AFAIK, we planned to allow vacuum operations even when size limit is reached, so I'm not sure if this already should work or it is in the TODO list
```
VACUUM FULL
Reconnecting...
Reconnected!
could not extend file because cluster size limit (10000 MB) has been exceeded
HINT:  This limit is defined by zenith.max_cluster_size GUC
```

**Comment by arssher** [comment]
dupe of https://github.com/neondatabase/neon/issues/1245
