### ISSUE TITLE
pageserver does not release memory

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1446]
That triggered an alert. After some time, CPU utilization settled near zero, but memory usage stayed high.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/19991702/161093152-0bed1800-a7bf-4b55-8e8e-489a3e05cc0a.png">

I can imagine some of the sources of such behavior. For example, we never unload timelines. Once it is loaded, we keep the layer map and other in-memory structures. 

Any other ideas on what else we might keep in memory for longer than needed?

**Comment by hlinnaka** [comment]
The "index" hashmaps in delta and image layers take quite a lot of memory. Those are released eventually, but could still be a problem. https://github.com/zenithdb/zenith/pull/1392 will address that.

**Comment by hlinnaka** [comment]
PR #1392 was pushed, so I think this has been fixed for now. Please re-open if it happens again
