### ISSUE TITLE
update safekeepers internal docs

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1475]
review the overview about teh safekeepers, update, change names https://github.com/zenithdb/zenith/blob/main/walkeeper/README
review and update the protocol too https://github.com/zenithdb/zenith/blob/main/walkeeper/README_PROTO.md

**Comment by banks** [comment]
Hey this project looks super cool!

I hope this is a useful place to note this but a few references still exist in the internal docs for `safekeeper/README_PROTO.md` (also linked in this issue) which is no longer in the source tree.

I'll clone the repo and go find it in history for now!

**Comment by hlinnaka** [comment]
> Hey this project looks super cool!
> 
> I hope this is a useful place to note this but a few references still exist in the internal docs for `safekeeper/README_PROTO.md` (also linked in this issue) which is no longer in the source tree.

Thanks! I opened PR #2188 to fix the references, and while at it, I turned them into links.

**Comment by aome510** [comment]
Fix in #2188

**Comment by problame** [comment]
Arthur will put together an outline of what he wants to write, then post it to Slack for feedback.

**Comment by jcsp** [comment]
Safekeeper internals docs live at https://docs.neon.build/storage/internals_safekeeper.html now.
