### ISSUE TITLE
Can't start compute node with error `lock file "/tmp/.s.PGSQL.5432.lock" already exists`

### ISSUE THREAD

**Issue by Daniel-ef** [neondatabase/neon#1486]
We have a test for availabity_checker, which start and stop compute node. After several times compute node can't start anymore and is stuck on `cannot connect to postgres: error connecting to server: Cannot assign requested address (os error 99), retrying`

You can see the whole compute logs downloading them from [run](https://github.com/zenithdb/console/runs/5821556407?check_suite_focus=true)  for cluster `lively-block-624385`

![image](https://user-images.githubusercontent.com/10731014/162730196-036e0d2a-317a-4677-a1af-850e1ab94366.png)

@ololobus assumed: 
> It seems to me that this is basically a docker problem. Mb, when you start the container many times, sometimes this log file remains on the file system, and there is a process with pid 13. Because of this, we fall on this

**Comment by ololobus** [comment]
Will be likely fixed by neondatabase/cloud#1048, but fill free to reopen
