### ISSUE TITLE
 rename the pg extension from zenith to neon

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1492]
as we're changing the name, the extension should change the name too

**Comment by lubennikovaav** [comment]
@kelvich,  do we want to change all Zenith mentions in vendor/postgres source code as well?

**Comment by kelvich** [comment]
> @kelvich, do we want to change all Zenith mentions in vendor/postgres source code as well?

I would rather touch only things that are potentially visible to the client through system views (extension names, function names, etc)

**Comment by antons-antons** [comment]
Ideally, we should avoid using code names in the code. Unfortunately, code names have different meanings for everyone and lump (sometimes unrelated) functionality together.

**Comment by lubennikovaav** [comment]
Done.
Though, I think that keeping obsolete names is not very friendly to future neon developers.

**Comment by stepashka** [comment]
the PRs need to land simultaneosly with https://github.com/neondatabase/cloud/pull/1041
