### ISSUE TITLE
Activity monitor in compute_ctl may panic and exit

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#1513]
From time to time it may panic with:
```
thread 'compute-monitor' panicked at 'error retrieving column state: error deserializing column 0: a Postgres value was `NULL`', /usr/local/cargo/git/checkouts/rust-postgres-256bc9bc9b85f694/9eb0dbf/tokio-postgres/src/row.rs:150:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After that it is never restarted (that's expected, there is no job to watch and restart service threads) and compute starts reporting the outdated last active timestamp. After that it will be shut down by control plane after 5 minutes independently of activity.

I reproduced it few times under pgbench load with enforced k8s RAM and CPU limits.

Not sure it's possible to make it never panic, so probably we should start watching these service threads.

**Comment by vadim2404** [comment]
@ololobus, does this issue still reproducible?

**Comment by vadim2404** [comment]
```
compute-node-ep-frosty-grass-834614	thread 'compute-monitor' panicked at 'error retrieving column state: error deserializing column 0: a Postgres value was `NULL`', /home/nonroot/.cargo/git/checkouts/rust-postgres-e2c00088c8e2b112/d052ee8/tokio-postgres/src/row.rs:151:25
```

we still have such logs

**Comment by ololobus** [comment]
There is a safety break in the control plane now, so not a really important issue, but thanks for bringing this up
