### ISSUE TITLE
Timeouts in test_pageserver_catchup_while_compute_down

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#1517]
It looks like this test tries to execute queries while pageserver is down and this sometimes makes query hang indefinitely. 

https://github.com/neondatabase/neon/blob/c9d897f9b6fecce83549aea725fd79cd8bdcdad8/test_runner/batch_others/test_pageserver_catchup.py#L31-L43

We tried to fix this by increasing shared_buffers in https://github.com/neondatabase/neon/pull/1422 to make chance of requesting page from pageserver smaller, but it didn't help.

CI timeout examples:
- https://app.circleci.com/pipelines/github/zenithdb/zenith/5362/workflows/ef9e41fd-9a24-4466-bbad-f5ea23ffa34e/jobs/51283/tests
- https://app.circleci.com/pipelines/github/neondatabase/neon/5524/workflows/f4b499c6-94b3-44c9-b199-768aec973968/jobs/53313

**Comment by arssher** [comment]
Strange, I made look up by test name before creating...

**Comment by hlinnaka** [comment]
Happened again here: https://app.circleci.com/pipelines/github/neondatabase/neon/6804/workflows/1004208c-5ea9-47c5-bf5c-95728a384d6b/jobs/69417

**Comment by shanyp** [comment]
@petuhovskiy I am closing this one as it hasn't reproduced
