### ISSUE TITLE
Page cache doesn't work as intended: redundant page reconstruction

### ISSUE THREAD

**Issue by knizhnik** [neondatabase/neon#1521]
Reconstructed image is saved in page cache with LSN of last applied record.
Next time this page is requested, page is located in page cache and it's LSN is compared with request LSN.
If them are the same, then we are done.
Otherwise we try to locate delta records which need to be applied.

In inmem layer there is the following check:
```
           for (entry_lsn, pos) in slice.iter().rev() {
                match &reconstruct_state.img {
                    Some((cached_lsn, _)) if entry_lsn <= cached_lsn => {
                        return Ok(ValueReconstructResult::Complete)
                    }
                    _ => {}
                }
```
So if record has the same LSN as image, then we are done.
But delta layer doesn't contain such check and so adds WAL record which we have to apply ... and save under the same LSN.
So page cache can not prevent page reconstruction.

**Comment by knizhnik** [comment]
pgbench -c 10 -S 
main: 5k TPS
with this patch:  18k TPS

**Comment by bojanserafimov** [comment]
Seems done to me, reopen if not https://github.com/neondatabase/neon/pull/1545
