### ISSUE TITLE
Implement better error handling for critical failures (out of upload retries)

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1559]
Implement better error handling for critical failures (out of upload retries). See https://github.com/zenithdb/zenith/pull/1163#discussion_r809821279. Desired behavior is to have infinite retries and let the back pressure do its thing to slow down compute if the upload can't keep up or have temporary failures.

**Comment by LizardWizzard** [comment]
Implemented. We retry uploads forever. Last part about backpressure may not be properly tested. Related https://github.com/neondatabase/neon/issues/3667. Though backpressure is more of an integration tests area
