### ISSUE TITLE
Prepare Grafana dashboard with historical data on operation attempts duration

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#1582]
Currently we report histogram of operation attempts duration, but it's an 'instant' metric. It will be helpful to have historical data, e.g. yesterday average duration of `start_compute` was 4 secs and today it's 3.5 s.

If we'll start doing some optimizations it'll be nice to compare trends in the real environment.

@stepashka is it possible with existing data?

**Comment by stepashka** [comment]
i think it's possible with the existing data
[here's an example of a query](https://observer.zenith.tech/explore?left=%5B%22now-30d%22,%22now%22,%22aws-production-us-west-2-service-01%22,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P729740868BA73BDC%22%7D,%22exemplar%22:true,%22expr%22:%22histogram_quantile(0.90,%20sum(rate(zenith_op_attempts_duration_bucket%7Baction%3D%5C%22start_compute%5C%22%7D%5B24h%5D))%20by%20(le))%22,%22hide%22:false,%22interval%22:%221d%22,%22refId%22:%22C%22%7D%5D&orgId=1) that reports 90th percentile of start operation attemp duration for each day

**Comment by Daniel-ef** [comment]
https://observer.zenith.tech/d/WH7cYcl7k/operation-metrics?orgId=1&var-percentile=95&var-action=check_availability&from=now-24h&to=now
