### ISSUE TITLE
pageserver status returns unknown command.

### ISSUE THREAD

**Issue by phoenix24** [neondatabase/neon#1591]
I just setup a new local setup of neon (building from `main` branch, on `ubuntu`). while going through the cli, `pageserver` states following commands,

```
➜ /workspaces/neon (main ✗) $ ./target/debug/zenith pageserver 
zenith-pageserver 
Manage pageserver

USAGE:
    zenith pageserver [SUBCOMMAND]

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    help       Print this message or the help of the given subcommand(s)
    restart    Restart local pageserver
    start      Start local pageserver
    status     
    stop       Stop local pageserver
```

but upon executing, i get the following error,
```
➜ /workspaces/neon (main) $ ./target/debug/zenith pageserver status
command failed: Unexpected pageserver subcommand 'status'
```

on [further inspection](https://github.com/neondatabase/neon/blob/main/zenith/src/main.rs#L790-L826), i realize the command is not implemented.

question - are there plans to implement it, and is this the [expected output](https://github.com/neondatabase/neon/issues/1488)?

**Comment by phoenix24** [comment]
ah, thank you. I could give it a shot, if you're good with it :)

**Comment by LizardWizzard** [comment]
Yup, go for it! Let me know in case you need help or have any questions

**Comment by vadim2404** [comment]
The issue should be closed because of merged PR that adds this command.
