### ISSUE TITLE
build neon on osx

### ISSUE THREAD

**Issue by phoenix24** [neondatabase/neon#1592]
at the moment, `neon` supports [dev builds](https://github.com/neondatabase/neon#running-local-installation) on `ubuntu` / `debian`. are there any plans for osx?

**Comment by LizardWizzard** [comment]
Many folks use osx to develop neon from both x86 and arm macs. But you're right, there is no instruction on how to set it up. We run rust-based unit tests on osx: https://github.com/neondatabase/neon/blob/main/.github/workflows/testing.yml#L12 workflow includes installation of necessary packages so it would be great if you can extract necessary steps from there and add them to the readme. If you have problems with arm based setup you can ask @SomeoneToIgnore or @antons-antons for help

**Comment by SomeoneToIgnore** [comment]
I'm actively developing on M1 and osx without issues, yet I did not run the entire test suite for a while.
We've had experimental runs on GitHub actions CI Intel osx machines, only a few test did not pass by the time of the run.

Apart from having XCode tools and first time homebrew dependencies installation, you don't have to do anything different from linux build: `make postgres` and `cargo build --all` are enough for regular development.

Alas, I'm not entirely sure which are needed to be installed via homebrew, here's a starting set you might want to install: https://github.com/neondatabase/neon/pull/1454/files#diff-7b74d73de878e0e53f6768bbf3a3d4b50c3c6f1f16f9b64518690028b8206b1cR52
You might need more, check out the linux dependencies list in the [readme](https://github.com/neondatabase/neon#running-local-installation), there are slightly differently counterparts in homebrew.
A PR with such list for osx is very much appreciated.

**Comment by phoenix24** [comment]
@SomeoneToIgnore thank you for the details - I just completed building neon (from `main`) on `osx monterey 12.3.1`, cpu spiked but build just zoomed through, no issues at all. no new dependencies other than `xcode`. 

concluding this, I'm thinking of raising a pull-request adding minor documentation updates for building on osx.
