### ISSUE TITLE
restart dead threads after error/panic

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1623]
Needs to be applied to per tenant threads, such as GC and compactor threads.

Changes should go to `thread_mgr.rs`

Options: 
1. Try to change FnOnce to Fn or FnMut
2. Implement something like a factory trait

**Comment by zxcjhg** [comment]
Hey, is it still relevant? I want to give it a go. Looking at the code, I was thinking to write another function to spawn a thread but with restart_on_error flag instead shutdown_process_on_error. What do you think?

**Comment by LizardWizzard** [comment]
Hi! Thank you for your interest! The problem is likely to be fixed with either #1794 or #1933 TLDR we're planning to switch to a threadpool because when the number of tenants is high so is the number of threads which already affected us because of the limit on a number of threads in some of the `tracing` dependencies
