### ISSUE TITLE
pageserver --enabled-features options doesn't list 'profiling'

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1627]
Commit 2f9b17b9e5 added --enabled-features CLI option to pageserver binary, but it doesn't list the 'profiling' feature. Both are listed in the '--version' option.

**Comment by phoenix24** [comment]
Hey @hlinnaka - I tried to reproduce the issue by building from the `main` branch, but couldn't reproduce the issue. Do let me know, if there's anything that I'm missing?

![CleanShot 2022-05-12 at 04 14 06](https://user-images.githubusercontent.com/86035/167959835-5e07d064-138f-404d-ba1a-77e0a2318e48.png)

**Comment by hlinnaka** [comment]
For example:
```
$ ./target/release/pageserver --version
Zenith page server git:d63b204e8a5ffb58e810daff351ed8f124a1fea2-modified profiling:true failpoints:true
$ ./target/release/pageserver --enabled-features
{"features": ["failpoints"] }
```
The `pageserver --version` output shows that the binary was built with features `profiling` and `failpoints`, but the `pageserver --enabled-features' command only lists `failpoints`.
