### ISSUE TITLE
Parallel, lower granularity and time-based upload functionality

### ISSUE THREAD

**Issue by antons-antons** [neondatabase/neon#1636]
Implement advanced features of WAL upload in SK:
1. Integrate SK WAL cleanup with 
2. Parallel upload (avoid blocking rapid write bursts by uploading multiple segments at a time)
3. Time based upload - bundle keep-alive with sub-segment granularity uploads to reduce non-backed-up tail for low write clients
4. Increase frequency of control file updates by SK (currently bundled with the persistence of commit lsn)
5. Eagerly upload WAL on timeline removal (in case of failover)
6. Update WAL backup restore tooling and playbook with fine granularity WAL support

**Comment by arssher** [comment]
integrated this into  updated https://github.com/neondatabase/cloud/issues/1925
