### ISSUE TITLE
Replace per-tenant GC threads with a thread pool or async

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1646]
Currently, we launch a thread for each tenant, which wakes up every now and then to GC. That's not great, because:

- with a lot of tenants, you get a lot of threads. Number of threads can cause trouble, e.g. we ran into limit on number of threads from the `sharded_slab` (https://github.com/neondatabase/neon/issues/1609).
- if a lot of tenants need to perform GC at the same time, you get a CPU and I/O storm. Better to queue up the work and use a small number of concurrent threads.

Let's change the thread model so that there is a fixed-size pool of GC threads that handle all the tenants. Possibly use tokio async to implement that pooling.

**Comment by bojanserafimov** [comment]
I'll give it a try
