### ISSUE TITLE
public slack or discord channel

### ISSUE THREAD

**Issue by phoenix24** [neondatabase/neon#1678]
Hey 👋 - 

I'm new to neon database, and was wondering what's the best way to hangout with neondb engineers.

if there's a public slack or discord channel - where one might be able to ask and get help with questions.

**Comment by SomeoneToIgnore** [comment]
Hey.

I believe, the current plan is to use https://github.com/neondatabase/neon/discussions

Can you post/create anything there?

**Comment by phoenix24** [comment]
@SomeoneToIgnore thank you, it works!  just posted a [question](https://github.com/neondatabase/neon/discussions/1698).
