### ISSUE TITLE
Huge difference between logical and physical data size.

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1708]
I have a cluster on staging that is used to run pgbench against it daily. Console shows that the cluster is using 1.5G of space. This is a logical size. But on the pageserver disk, data occupies almost 200G:

```
199G	/storage/pageserver/data/tenants/ef5774ec9e5ca65b071a6da18713f91a
```

There are a few action points. 
- [ ] The reason for such a big difference is probably the absence of vacuum on computes while they're not running. As far as I'm aware, repeated pgbench runs create a lot of stale data that needs to be cleaned up by a vacuum. The question: What vacuum settings should we use for computes? IMO the most realistic option is to periodically wake up computes so the vacuum can work for some time.
- [ ] We need more observability for such kinds of issues. We need to keep track of physical data size, add metrics, alert when a certain threshold is reached, etc.

Thoughts? @ololobus @hlinnaka

**Comment by hlinnaka** [comment]
Hmm, there's some shenanigans going on here:
```
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 16:52 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05CCA19
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 17:02 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05CD389
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 18:10 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05CDD31
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 18:44 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05CE749
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 18:49 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05CF921
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 18:50 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05D2099
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 19:15 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05D4C81
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 19:35 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05D6599
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 20:10 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05D7F09
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 21:19 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05D99F1
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 23:21 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05DB631
-rw-r--r-- 1 pageserver pageserver 268460032 May  2 23:24 000000067F000040010000600E0000000006-000000067F00004001000060230000007C5D__0000000001696070-00000002D05DD3D1
```
Note how all these layers have the same key range, and same LSN start point, but different LSN end point. That's just one example, there's similar overlap for many other layers.

The pageserver on staging is currently in a nasty restart loop until I pushed commit 51ea9c3053c9ab5d2be837c2eeb0dd149b038229 this morning. I think there's something wrong with what happens after restart, that causes it to create these duplicate layer files. Perhaps we fail to correctly detect and remove files that are "in the future".

**Comment by ololobus** [comment]
> The question: What vacuum settings should we use for computes?

I'm not quite aware of the current storage implementation specifics, but in vanilla Postgres 'just' `VACUUM` (and autovaccuum) doesn't directly free disk space, it just marks some disk space / pages as free to write new data. `VACUUM FULL` does a heap / data files rewrite and it does free disk space usually, but it's not recommended to be used on running production systems, AFAIK.

So I assumed that vacuum / autovaccuum doesn't help with freeing pageserver disk space as well. Or it does help, @hlinnaka?

**Comment by hlinnaka** [comment]
> So I assumed that vacuum / autovaccuum doesn't help with freeing pageserver disk space as well. Or it does help, @hlinnaka?

Agreed, vacuum won't help freeing space in the pageserver.

The pageserver keeps all the history. Even if you remove some data completely from Postgres, it's still stored in the pageserver until it gets old enough to be garbage collected. The default `pitr_interval` is 30 days, so the pageserver will keep all the data for 30 days.

**Comment by LizardWizzard** [comment]
The above issue regarding restarts and resulting small layers was resolved
