### ISSUE TITLE
Manage storage_broker in Python tests better

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#1717]
See https://github.com/neondatabase/neon/pull/1648#issuecomment-1127446184 and related for context

Current etcd is run 
*  [multiple times](https://github.com/neondatabase/neon/pull/1648#issuecomment-1128131911), yet could be run once for all tests
* could pass a `broker_prefix` env var into both pageserver and safekeeper, to ensure the test data does not interfere.

**Comment by petuhovskiy** [comment]
We don't use etcd anymore, but it may still be relevant for broker configuration. Someone needs to verify.

**Comment by LizardWizzard** [comment]
For sure it should be possible to run one broker instance for all tests. neon_local spins up new one for every test

**Comment by arssher** [comment]
But that's hardly a perf issue, right? So moving to backlog.

**Comment by LizardWizzard** [comment]
Its waste of time/other resources. Both locally and in CI. It makes tests slower and restricts ability to run more parallel test workers

**Comment by petuhovskiy** [comment]
Would be nice to share a single setup of (1broker, 1pageserver, 3safekeepers) across most of our python tests, but that may be not an easy task.

**Comment by LizardWizzard** [comment]
Currently broker can be always reused. Pageservers/safekeepers are trickier because tests can restart them. (probably we should have tests that shut down broker as well?)

Shouldnt be hard. Needs cleanup on Env fixture side
