### ISSUE TITLE
Fail test on pageserver / safekeeper panic

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1721]
Currently, if a thread panics in the pageserver, the python tests will still pass if the panic didn't cause other trouble. Let's add a check to the python fixtures to cause a test failure on any panic. And possibly on other, non-panic, errors too.

I ran into this when i was writing a test case to reproduce https://github.com/neondatabase/neon/issues/1719. My test case reproduced the panic, but the test still passed, despite the panic in the storage sync thread.

**Comment by LizardWizzard** [comment]
It may be even better to analyze logs after test run and fail a test if there were unexpected errors

**Comment by shanyp** [comment]
> It may be even better to analyze logs after test run and fail a test if there were unexpected errors


 @LizardWizzard isn't this already done in the current validation of logs in tests ?

**Comment by LizardWizzard** [comment]
Yep, with `tracing_panic_hook` work by @koivunej we should emit error log lines which will be caught by our `NeonPageserver.assert_no_errors` on the python level
