### ISSUE TITLE
Timeout in test_parallel_copy

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1742]
https://app.circleci.com/pipelines/github/neondatabase/neon/6462/workflows/f21c2d5b-a61d-436f-8244-ee4d496a2c49/jobs/65126

I suspect we need to just increase the statement timeout. IIRC I've seen this on my laptop a few times too.

**Comment by shanyp** [comment]
haven't seen this timeout/fail in the last period , closing
