### ISSUE TITLE
Coverage reports upload conflict with each other

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1749]
See e.g. our today's `main` fails: https://app.circleci.com/pipelines/github/neondatabase/neon/6504/workflows/349a4ccc-9db2-4f98-9a4e-bb755bec17f2/jobs/65683 and https://app.circleci.com/pipelines/github/neondatabase/neon/6502/workflows/7ddadc16-74be-4776-b51f-6b01ead753ca/jobs/65671

It does try to `git rebase`, but the committer is not specified.

**Comment by hlinnaka** [comment]
What if we just included the coverage HTML report as an artifact in CI, so that you could view it from CircleCI or github actions tab? That way, we wouldn't need a separate git repository to hold them.

**Comment by yeputons** [comment]
CircleCI only stores artifacts up to 30 days: https://circleci.com/docs/2.0/artifacts/#artifacts-and-self-hosted-runner

> By default, artifact storage duration is set to 30 days.... Currently, 30 days is also the maximum storage duration you can set.

@funbringer What that the reason you decided to go with a separate repository in #959?

**Comment by funbringer** [comment]
@yeputons We discussed that with @kelvich and came to the conclusion that a standalone repo will do for a little while. Even at that moment there was an understanding that we'll be moving from CircleCI, so I didn't want to lock-in. The transition has been delayed, though. Ultimately, I think that git repo is a poor fit here, we could upload those html pages elsewhere ([e.g. s3](https://blog.balthazar-rouberol.com/measuring-the-coverage-of-a-rust-program-in-github-actions)). The uploads are 90% administrative and 10% coding problem.

**Comment by hlinnaka** [comment]
Do we need to upload them anywhere? If they were included as CI artifacts, would that be enough?

**Comment by funbringer** [comment]
@hlinnaka Wouldn't that mean that we'd have to use circleci artifacts infra, which contradicts the idea that we should move from circleci?

**Comment by hlinnaka** [comment]
I'm pretty sure github actions have a similar mechanism

**Comment by hlinnaka** [comment]
> I'm pretty sure github actions have a similar mechanism

see https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

**Comment by funbringer** [comment]
@hlinnaka to me "reuse CI infra" is a special case of "upload anywhere", which is to say that I see no problem with that solution. It wasn't obvious whether you're arguing with my rationale or suggesting another option.

**Comment by LizardWizzard** [comment]
Let me answer this, because originally this repo-based schema was used for perf test results storage. And it still is. So the answer is simple :) At that time it was the simplest solution. Perf test results needed to be kept for longer than 30 days so using artifacts was not an option, so it was just the shortest path to reuse the repo upload wrappers. Also at that time capacity for the task of enabling coverage was limited.

> I'm pretty sure github actions have a similar mechanism

But that incurs setting it up two times. First, you have to set it up for circle, and then move it to actions. Its not too much work, but anyway. I do not see any problems with using CI agnostic solution like s3, only benefits, and better flexibility. For sure repo approach has its limitations.

**Comment by hlinnaka** [comment]
> Let me answer this, because originally this repo-based schema was used for perf test results storage. And it still is. So the answer is simple :) At that time it was the simplest solution. Perf test results needed to be kept for longer than 30 days so using artifacts was not an option, so it was just the shortest path to reuse the repo upload wrappers. Also at that time capacity for the task of enabling coverage was limited.

Ok, makes sense.

> > I'm pretty sure github actions have a similar mechanism
> 
> But that incurs setting it up two times. First, you have to set it up for circle, and then move it to actions. Its not too much work, but anyway.

Or we could let it be as it is until we switch to github actions.

> I do not see any problems with using CI agnostic solution like s3, only benefits, and better flexibility. For sure repo approach has its limitations.

A couple of downsides:

- the upload can fail for various reasons, like the one fixed here, or a network outage
- the upload doesn't work for PRs opened from forked repositories. See e.g. https://app.circleci.com/pipelines/github/neondatabase/neon/6404/workflows/fa580a3e-2b17-4e94-8473-96f2897b232b/jobs/64350.
