### ISSUE TITLE
pg-wire: Is current pg-wire handle extended query mode?

### ISSUE THREAD

**Issue by BowenXiao1999** [neondatabase/neon#1759]
I think it's not, but the code and comment seems claims to, even for non-prepared unnamed sql. 

https://github.com/neondatabase/neon/blob/a4aef5d8dc9666183e3968031952cb511cf918ec/libs/utils/src/postgres_backend.rs#L456-L459

When receiving DESCRIBE, we should write RowDescription for query that might have query results instead of NoData.

Anyone explain this a bit? Thanks very much!

**Comment by hlinnaka** [comment]
It does not, but we only use that server code for the "control commands" in the pageserver, not for the actual user connections. The user connections are served by Postgres itself, which supports extended query protocol and all other features.

**Comment by BowenXiao1999** [comment]
Got it. Thanks for the answer!
