### ISSUE TITLE
`WARN could not remove ephemeral file ... No such file or directory (os error 2)` on detach_timeline

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1775]
There are a lot of `WARN could not remove ephemeral file ... No such file or directory (os error 2)` on staging, but it's probably a different issue, because they always happen right after detach call. [Link to logs](https://observer.zenith.tech/goto/PZwWX_unk?orgId=1)

_Originally posted by @petuhovskiy in https://github.com/neondatabase/neon/issues/1751#issuecomment-1134400931_

**Comment by LizardWizzard** [comment]
Detach waits for all other threads associated with the timeline to finish, but something is clearly wrong. Maybe that does not work with per tenant threads like gc or compaction. So if they are still writing to files it might result in this error. Since it happens for detach it shouldn't lead to any data loss. I'll try to dig into this

**Comment by SomeoneToIgnore** [comment]
Note that now wal_receiver code has similar issues with timeline detach: https://github.com/neondatabase/neon/pull/1619#discussion_r881694400

Should not be a problem, but worth fixing.

**Comment by LizardWizzard** [comment]
So there are two problems. 
* Detach is not synchronized with compaction/gc. This reproduces every time when gc + detach are issued concurrently. Looking at compaction now.
* Detach does not wait for walreceiver shutdown. Is next on the list

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/neon/pull/1794 changes things around compaction/gc. I don't think it fixes this issue directly, but maybe the fix can be implemented easier with that. Not sure..

**Comment by LizardWizzard** [comment]
I checked logs on staging and clearly see these messages coming from page request threads and wall receiver. #1890 makes it possible to join specific page service threads so existing code in detach handler will wait for them to finish. Next PR will handle proper wal_receiver joining.

**Comment by LizardWizzard** [comment]
I started fixing it. Then for some time, I thought that per tenant detach will simplify things (no need to take gc/compaction locks), but as it turns out we still need to be able to delete separate branches, so I'll return to it. #1936 handles wal_receiver joining

**Comment by LizardWizzard** [comment]
After #1936 I do not see this in logs anymore. test_tenant_detach was also created to test detach behavior
