### ISSUE TITLE
Create `LSN` datatype for Python tests

### ISSUE THREAD

**Issue by aome510** [neondatabase/neon#1796]
This reveals another bug in the test, BTW: the error message says that it's trying to compare 'str' with None. We shouldn't be dong string comparison in the first place here, we should convert the LSNs to integers and do an integer comparsion (see `lsn_from_hex`). I've made this mistake a few times myself in the last few weeks; its subtle. Perhaps we should create a Python Lsn datatype for our tests, and register that with psycopg2 so that LSN fields would be automatically converted to the Lsn type (see https://www.psycopg.org/docs/advanced.html#type-casting-of-sql-types-into-python-objects)...

_Originally posted by @hlinnaka in https://github.com/neondatabase/neon/issues/1768#issuecomment-1133752122_

Creating a new datatype can help us reduce the amount of boilerplate such as `            current_lsn = lsn_from_hex(cur.fetchone()[0])` and make it more robust as we can avoid potential comparison between two hex LSNs as mentioned in the original comment.

**Comment by hlinnaka** [comment]
We added an Lsn datatype in commit 47bd307cb8c2941bf66405b4580a11099f4dfe3f. We haven't registered it with psycopg2, but I think what we have is enough to fix this trap.
