### ISSUE TITLE
Proxy is lenient with the *.cloud.neon.tech SNI

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1805]
This works:
```
$ psql postgres://hlinnaka@winter-truth-478633.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.cloud.neon.tech/main
Password for user hlinnaka: 
psql (13.7 (Debian 13.7-0+deb11u1), server 14.2)
WARNING: psql major version 13, server major version 14.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.
```
Maybe harmless, but doesn't feel right.

**Comment by KlimentSerafimov** [comment]
Could you please provide me a little bit more guidance here?  Is it the fact that you can have a.a.a.... in the SNI?
Could you please tell me where is the entry point in the code that I need to be looking at? @hlinnaka @kelvich

**Comment by cicdteam** [comment]
it's related how CF (our DNS provider) do resolving. I created necessary records (I mean `*.cloud.neon.tech` for prod and `*.cloud.stage.neon.tech` for staging) pointing to AWS ALB, but seems CF recognize `*` as simple hostname and as anything as hostname:

```console
% dig +short  try.cloud.neon.tech      
k8s-default-neonprox-ed98ef9efa-551c6ea545df635c.elb.us-west-2.amazonaws.com.
52.35.3.79
```

and

```console
% dig +short  try.no.matter.what.you.specify.here.it.will.work.cloud.neon.tech      
k8s-default-neonprox-ed98ef9efa-551c6ea545df635c.elb.us-west-2.amazonaws.com.
52.35.3.79
```

So, solution is - get hostname in proxy (via SNI) and ensure it fit the mask like `[:alnum:].cloud.neon.tech`

**Comment by kelvich** [comment]
> Is it the fact that you can have a.a.a.... in the SNI?

Right.

So far staging uses `*.cloud.stage.neon.tech`
prod is using `*.cloud.neon.tech`
localhost is using `*.localtest.me`.

And proxy doesn't know on what domain it is listening. I suggest adding this prefix as a CLI parameter so that the current check is used when this parameter isn't set (to have backward compatibility) and a stricter one is used if the param is set; deploy it and change deployments to use the exact domain name.

Another idea is that we can look up `common name` in the provided certificate. If this works out it will be a way simpler to deploy.

**Comment by KlimentSerafimov** [comment]
I see. 
Few questions:
For the first approach:
1. What CLI parameter name do you suggest using? Would 'domain' be fine?
2. So would a user specify like "...&domain='cloud.stage.neon.tech'..."?
3. Would the domain name become part of the project name (so like <project name>.<domain name>)?
4. How to change the deployments? 

For the second approach: 
5. how do I look up the common name in the provided certificate? Is this also something that can be inferred from the SNI?

**Comment by cicdteam** [comment]
> Another idea is that we can look up `common name` in the provided certificate. If this works out it will be a way simpler to deploy.

not sure how it could helps, as certificate CN is also wildcarded (`depth=0 CN = *.cloud.stage.neon.tech`).

```console
$ openssl s_client -connect wow-it-works.cloud.stage.neon.tech:5432 -starttls postgres | head -10
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.cloud.stage.neon.tech
verify return:1
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = *.cloud.stage.neon.tech
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
^C
```

**Comment by cicdteam** [comment]
> I suggest adding this prefix as a CLI parameter so that the current check is used when this parameter isn't set 

btw, I suggest to use env variables everywhere (it simplifier deployment for different environments, as env variables could be propagated from k8s secrets/configmaps)

something like `PROXY_BASE_DOMAIN=cloud.stage.neon.tech`

then proxy retrieves FQDN (if it possible) from request and ensure it fits regexp like `[:alnum:]+\.${PROXY_BASE_DOMAIN}`

**Comment by KlimentSerafimov** [comment]
And how do I access this information from within the code?

**Comment by kelvich** [comment]
> not sure how it could help

well, it tells you a domain that you you are listening on so that you can ensure that a proper cluster domain is `cluster-name-n-dots` + `common-name-without-star`. 

I think this will work and https://docs.rs/x509-parser/latest/x509_parser/pem/struct.Pem.html will do the thing

**Comment by KlimentSerafimov** [comment]
do we want to support project names like "my-cluster-123"? (with hyphens) which are not fully [:alnum:]?

**Comment by kelvich** [comment]
Currently, project names are alphanum and "-"
