### ISSUE TITLE
Lock file is held open after pageserver process has exited

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1814]
See `test_pageserver_recovery` failure here: https://app.circleci.com/pipelines/github/neondatabase/neon/6768/workflows/f6d20ab2-c4a2-4d0c-9354-8c96b9085cdf/jobs/68997/tests. (There's another failing test in that run, which is an unrelated issue)

```
2022-05-27 10:22:57.139 INFO [test_recovery.py:57] Wait before server restart
2022-05-27 10:22:57.139 INFO [zenith_fixtures.py:1072] Stopping pageserver with ['pageserver', 'stop']
2022-05-27 10:22:57.139 INFO [zenith_fixtures.py:1180] Running command "/tmp/zenith/bin/neon_local pageserver stop"
2022-05-27 10:22:57.139 INFO [zenith_fixtures.py:1181] Running in "/tmp/test_output/test_pageserver_recovery/repo"
2022-05-27 10:22:57.166 INFO [zenith_fixtures.py:1205] Run success: Stopping pageserver gracefully..Pageserver with pid 7428 does not exist, but a PID file was found

2022-05-27 10:22:57.166 INFO [zenith_fixtures.py:1180] Running command "/tmp/zenith/bin/neon_local pageserver start --pageserver-config-override=tenant_config={checkpoint_distance = 1048576}"
2022-05-27 10:22:57.167 INFO [zenith_fixtures.py:1181] Running in "/tmp/test_output/test_pageserver_recovery/repo"
2022-05-27 10:22:57.355 INFO [zenith_fixtures.py:1213]             Run failed: Command '['/tmp/zenith/bin/neon_local', 'pageserver', 'start', '--pageserver-config-override=tenant_config={checkpoint_distance = 1048576}']' returned non-zero exit status 1.
              stdout: Starting pageserver at 'localhost:15053' in '/tmp/test_output/test_pageserver_recovery/repo'
              stderr: Error: Failed to start pageserver

Caused by:
    unable to lock pid file. could not daemonize. bailing.
```

The test kills the pageserver, using a failpoint. Then it calls `neon_local pg stop` to wait the process to terminate. Then it immediately restarts it. Here's my interpretation of what happened:

1. When the pageserver process is terminated when it hits the fail point. However, the flock() on the pidfile is kept open a little longer. (Why? See theory below.)
2. `neon_local pg stop` reads the PID file, and tries to send SIGTERM signal to it. If the process with that PID has already exited, the kill() function returns error. We detect that, and conclude that the server is already stopped
3. The pageserver is restarted. It successfully binds to the HTTP and libpq sockets, but fails to lock the PID file because it's still locked.

So why is the PID file still locked after the process terminated? Turns out, when we fork and launch the wal-redo process, it inherits the file descriptor for the lock file. See:
```
$ lsof .zenith/pageserver.pid 
COMMAND       PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
pageserve 4078334 heikki    8w   REG  253,1        7 28634485 .zenith/pageserver.pid
postgres  4078774 heikki    8w   REG  253,1        7 28634485 .zenith/pageserver.pid
```

We have to close() the file descriptor the WAL redo process after forking. That will fix this issue, but it's also important from a security point of view. If a WAL redo process is compromised, we don't want it to be able to read/write the PID file. There isn't anything security sensitive there, but you could wreak havoc by overwriting the PID stored in the PID file. We should check if the WAL redo process holds any other file descriptors open and close everything except the stdin/stdout/stderr, which are used to communicate with the parent process.

**Comment by bojanserafimov** [comment]
The safe rust libraries open file descriptors with `FD_CLOEXEC`, but the daemonize crate calls `open` directly, and doesn't pass that flag.

[This fix](https://github.com/knsd/daemonize/blob/master/daemonize/src/lib.rs#L401) is on `master` branch of `daemonize`, but not released yet. [No signs](https://github.com/knsd/daemonize/issues/46) of a release happening soon.

**Comment by hlinnaka** [comment]
> [This fix](https://github.com/knsd/daemonize/blob/master/daemonize/src/lib.rs#L401) is on `master` branch of `daemonize`, but not released yet. [No signs](https://github.com/knsd/daemonize/issues/46) of a release happening soon.

Ah, cool! I guess we need to change Cargo.lock to use a known-good commit SHA instead of tagged version until then. I think we should also add a check to the wal-redo process, to check for any unexpected file descriptors, and close them or error out. Just in case something like this happens again.

**Comment by bojanserafimov** [comment]
Another possible cause:
1. Stop command sends sigterm to pageserver
2. Pageserver starts killing threads
3. Tcp server thread dies, but other thread hangs
4. neon_local can't connect to tcp and thinks pageserver is dead

Yet another possible cause: sigterm handler panics somewhere, so the thread dies but other threads continue.
