### ISSUE TITLE
Incorrect .pgpass instructions

### ISSUE THREAD

**Issue by joelonsql** [neondatabase/neon#1825]
When resetting the password, it is suggested to run this command to add a line to .pgpass:

    echo 'cloud.zenith.tech:USERNAME:PASSWORD' > ~/.pgpass

Problems:

1. The command would overwrite the .pgpass file, which is probably not what most people want. Should probably change `>` to `>>` to append to the file instead.

2. The hostname "cloud.zenith.tech" doesn't exist. I think the hostname for the project should be used instead, like "tiny-wave-734986.cloud.neon.tech" for my project.

3. The port and database name is missing. The format according to the manual is "hostname:port:database:username:password", so I think the command should be changed to:

    echo 'tiny-wave-734986.cloud.neon.tech:5432:main:USERNAME:PASSWORD' >> ~/.pgpass

Which the line above in my .pgpass file, the psql command then works OK:

    $ psql postgres://joelonsql@tiny-wave-734986.cloud.neon.tech/main
    psql (14.3, server 14.2)
    SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
    Type "help" for help.
    main=> \q

**Comment by grav** [comment]
+1 to using `>>` instead of `>`!

Wrt the other points this seems to be fixed.

**Comment by bojanserafimov** [comment]
Thanks for reporting! It has been fixed inside our webapp repo and will be visible on next release.
