### ISSUE TITLE
Failed to connect to the compute node

### ISSUE THREAD

**Issue by volfco** [neondatabase/neon#1827]
First connection to a idle database results in a flurry of `psycopg.OperationalError: connection failed: ERROR:  Failed to connect to the compute node` errors. 

It looks like there is no delay or wait when the proxy connects to the compute node https://github.com/neondatabase/neon/blob/b3ec6e0661e1f08beb1cd08b265cc64af0cd4035/proxy/src/compute.rs#L49. A connection is attempted, and if it fails then just propagate the error up to the user. 

It makes sense (to me) to have some sort of back-off delay to allow for the compute node to ready up, instead of just fast failing and have the user deal with non-ready compute on the application side. 

It would be double-ly cool if this could be configured by the user on a per-database level.

**Comment by hlinnaka** [comment]
I was able to reproduce this with this self-contained test:
```
import asyncio
import psycopg

async def run_one(worker_id: int):
    async with await psycopg.AsyncConnection.connect(
        dbname="main",
        user="<username>",
        password="<password>",
        host="<project_id>",
        sslmode="require"
    ) as aconn:
        async with aconn.cursor() as acur:
            # Execute a command: this creates a new table
            await acur.execute(f"INSERT INTO test VALUES ('foo{worker_id}')")
            await aconn.commit()

async def runtest(n_parallel: int):
    workers = []
    for worker_id in range(n_parallel):
        worker = run_one(worker_id)
        workers.append(asyncio.create_task(worker))

    # await all workers
    await asyncio.gather(*workers)

asyncio.run(runtest(10))
```
The trick is to try to open multiple connections to the same database, at the same time, when it is idle. The proxy does wait for the server to be started up, but apparently that mechanism gets confused if there are multiple simultaneous connections.
