### ISSUE TITLE
Remove daemonize dependency

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#1841]
The library is not maintained anymore https://github.com/knsd/daemonize/issues/46

And there are other reasons to do daemonization differently, I'll let @funbringer elaborate (feel free to edit).

_Originally posted by @funbringer in https://github.com/neondatabase/neon/pull/1834#issuecomment-1142398481_

**Comment by LizardWizzard** [comment]
Causing troubles again. Having quite a lot of `unable to lock pid file. could not daemonize. bailing.` errors here https://github.com/neondatabase/neon/runs/7690981632?check_suite_focus=true

**Comment by bojanserafimov** [comment]
https://github.com/neondatabase/neon/runs/7786990204?check_suite_focus=true

failed on ci 3 times in a row

**Comment by hlinnaka** [comment]
Yeah, the failures are annoying and we need to fix them.

Let's track the failures, and fixing them one way or another, in https://github.com/neondatabase/neon/issues/2247. And keep this issue to track removing daemonize altogether.
