### ISSUE TITLE
Pageserver may be missing auth checks?

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1858]
For example, `pagestream `'s command handler [calls for `check_permissions`](https://github.com/neondatabase/neon/blob/de7eda2dc6a6dbad3c3ec96e71673c5a8a48bb79/pageserver/src/page_service.rs#L692), same as `basebackup`, but all others do not: e.g. `failpoints` (should require managemental token?), `show`, `do_gc`, `compact`, `checkpoint`, `get_lsn_by_timestamp`...

Note that we do not trust the compute node.

**Comment by yeputons** [comment]
Discussed with @kelvich : yes, all these commands are only for tests and manual triggers, so there should be no consistency issues like "I use bot HTTP/PG connections and assume that they're perfectly are in sync". Let's move them to HTTP API.

**Comment by LizardWizzard** [comment]
The only one that is not for tests is get_lsn_by_timestamp. Should be no problem to move it to HTTP API as well

**Comment by hlinnaka** [comment]
opened https://github.com/neondatabase/neon/issues/2422 to move these to the HTTP API.
