### ISSUE TITLE
Unable to upload coverage report in a PR from a fork; missing `$VIP_VAP_ACCESS_TOKEN`?

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1859]
First seen in #1849, see logs [here](https://app.circleci.com/pipelines/github/neondatabase/neon/6896/workflows/905c1776-8c97-418c-9a37-7b420cab4e5f/jobs/70550). To compare, [here is a successful run](https://app.circleci.com/pipelines/github/neondatabase/neon/6891/workflows/66432833-0c48-416b-89db-8d878846e8ca/jobs/70471).

A good upload step starts like this:

```
Cloning into '/tmp/tmpl2fucvud'...
remote: Enumerating objects: 285976, done.        
remote: Counting objects: 100% (1523/1523), done.        
remote: Compressing objects: 100% (354/354), done.        
```

A bad one starts like this:

```
Cloning into '/tmp/tmpducdsii0'...
warning: redirecting to https://github.com/neondatabase/zenith-coverage-data.git/
remote: Enumerating objects: 286848, done.        
remote: Counting objects: 100% (2395/2395), done.        
remote: Compressing objects: 100% (557/557), done.  
```

So it looks like the bad one decided to strip out auth token from the URL altogether, so the following `git push`es are waiting for credentials and fail.

My current suspicion is that `$VIP_VAP_ACCESS_TOKEN` was not specified for some reason, which turned the `https://$VIP_VAP_ACCESS_TOKEN@github.com/neondatabase/zenith-coverage-data.git` URL [from the CI script](https://github.com/neondatabase/neon/blob/de7eda2dc6a6dbad3c3ec96e71673c5a8a48bb79/.circleci/config.yml#L406) into `https://@github.com/neondatabase/zenith-coverage-data.git` (mind the `@` symbol), which is then redirected as above. At least, the exact same message is printed on my system under those circumstances.

Few questions/suggestions here:

1. We should probably check that `$VIP_VAP_ACCESS_TOKEN` is not empty in the script and fail loud if it is. If it's of `username:token` format, we should also check that the variable contains a colon.
2. Why was `VIP_VAP_ACCESS_TOKEN` not provided in the first place?
3. Why did the `git-upload` script fail `git push` fast first two times (`Username for 'https://github.com': fatal: could not read Username for 'https://github.com': Success`) and then got stuck for ten minutes on the third attempt which started just like the previous two?

**Comment by yeputons** [comment]
Answer to no. 2: the original PR is from another repository. CircleCI does not share secrets (including `VIP_VAP_ACCESS_TOKEN`) [with arbitrary PRs](https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests) for a good reason: otherwise a malicious actor could easily extract them by crafting a special script, altering `config.yml` and sending us a PR.

So, the immediate mitigation is to avoid PRs from forks.

However, that leaves us with another question: how do we receive PRs from external contributors in the future?

**Comment by yeputons** [comment]
Splitted this issue: #1860 (and also found #1861), #1863, and #1862.

**Comment by hlinnaka** [comment]
I think we should stop uploading the coverage reports to a git repository. Publish them as an artifact in the CI, instead, just like e.g. log files. We're not trying to build a database of old coverage reports for historical analysis, we just want to see the coverage report for a particular commit or CI run. Historical analysis would be cool too, but not urgent, and if we wanted to do that we could collect the results for that from the CI artifacts too.

But we should probably finish https://github.com/neondatabase/neon/pull/1647 first. If we're switching away from CircleCI anyway, it doesn't seem worth it to tweak the CircleCI configs now, just to have it be rewritten again.
