### ISSUE TITLE
Spurious test_zenith_regress failure

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1868]
Here is a spurious `test_zenith_regress` failure: https://app.circleci.com/pipelines/github/neondatabase/neon/6925/workflows/6a0dcae5-a777-4504-96e3-c7ca92713eb2/jobs/70910/tests

`regression.diffs` is:

```
diff -U3 /home/circleci/project/test_runner/zenith_regress/expected/zenith-vacuum-full.out /tmp/test_output/test_zenith_regress/regress/results/zenith-vacuum-full.out
--- /home/circleci/project/test_runner/zenith_regress/expected/zenith-vacuum-full.out	2022-06-02 16:04:52.654443452 +0000
+++ /tmp/test_output/test_zenith_regress/regress/results/zenith-vacuum-full.out	2022-06-02 16:08:09.947609044 +0000
@@ -1,5 +1,9 @@
 create table foo(a int primary key, b int, c int);
 insert into foo values (generate_series(1,10000), generate_series(1,10000), generate_series(1,10000));
+ERROR:  could not read block 0 in rel 1663/16384/2691.0 from page server at lsn 0/04B99E60
+LINE 1: insert into foo values (generate_series(1,10000), generate_s...
+                                ^
+DETAIL:  page server returned error: Timed out while waiting for WAL record at LSN 0/4B99E60 to arrive, last_record_lsn 0/49CFA68 disk consistent LSN=0/1696628
 create index concurrently on foo(b);
 create index concurrently on foo(c);
 vacuum full foo;
```

Corresponding logs are:
[pageserver.log](https://github.com/neondatabase/neon/files/8825776/pageserver.log)
[safekeeper.log](https://github.com/neondatabase/neon/files/8825781/safekeeper.log)
[pg.log](https://github.com/neondatabase/neon/files/8825777/pg.log)
[etcd.log](https://github.com/neondatabase/neon/files/8825775/etcd.log) (`etcd_datadir_17001`)

I was unable to quickly reproduce this locally.

**Comment by SomeoneToIgnore** [comment]
Could be the same as https://github.com/neondatabase/neon/issues/1815#issuecomment-1145281135

**Comment by LizardWizzard** [comment]
Do not see recent comments. Some of the bugs were fixed by @SomeoneToIgnore. So closing for now. Feel free to reopen in case it pops up again
