### ISSUE TITLE
Spurious test_normal_work failure

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1869]
First observed here: https://app.circleci.com/pipelines/github/neondatabase/neon/6925/workflows/6a0dcae5-a777-4504-96e3-c7ca92713eb2/jobs/70904/tests

Logs:

```
test_runner/fixtures/zenith_fixtures.py:785: in verbose_error
    res.raise_for_status()
../.cache/pypoetry/virtualenvs/zenith-3aSsmiER-py3.9/lib/python3.9/site-packages/requests/models.py:960: in raise_for_status
    raise HTTPError(http_error_msg, response=self)
E   requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:16038/v1/tenant/673ed51a6f194f8a99caa82ad810981c/timeline/7b1baff01b9f495cb7d22d8b21fdff51/detach

The above exception was the direct cause of the following exception:
test_runner/batch_others/test_normal_work.py:47: in test_normal_work
    check_tenant(env, pageserver_http)
test_runner/batch_others/test_normal_work.py:26: in check_tenant
    pageserver_http.timeline_detach(tenant_id, timeline_id)
test_runner/fixtures/zenith_fixtures.py:806: in timeline_detach
    self.verbose_error(res)
test_runner/fixtures/zenith_fixtures.py:791: in verbose_error
    raise ZenithPageserverApiException(msg) from e
E   fixtures.zenith_fixtures.ZenithPageserverApiException: Failed to remove local timeline directory '/tmp/test_output/test_normal_work/repo/tenants/673ed51a6f194f8a99caa82ad810981c/timelines/7b1baff01b9f495cb7d22d8b21fdff51'
```
[pg1.log](https://github.com/neondatabase/neon/files/8826007/pg1.log)
[pg2.log](https://github.com/neondatabase/neon/files/8826008/pg2.log)
[pg3.log](https://github.com/neondatabase/neon/files/8826009/pg3.log)
[safekeeper.log](https://github.com/neondatabase/neon/files/8826011/safekeeper.log)
[pageserver.log](https://github.com/neondatabase/neon/files/8826005/pageserver.log)

**Comment by LizardWizzard** [comment]
Can be somehow related to #1775

**Comment by yeputons** [comment]
It probably is. I suspect there is a race between the ephemeral file deletion and the `std::fs::remove_dir_all` call, so if the ephemeral file is deleted right when `remove_dir_all` tries to do the same, the former breaks.

However, if it's the other way around, we only emit a warning.

**Comment by stepashka** [comment]
@yeputons mantioned today that maybe this is not reproducing anymore

**Comment by LizardWizzard** [comment]
Closing as it does not appear anymore
