### ISSUE TITLE
Add snapshot test for storage format

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#1896]
Run pageserver with small checkpoint distance, generate and store some tenant data inside the github repo (< 100KB zipped). Then write test that loads the data and answers some queries. The goal is to notice backwards-incompatible changes.

If there's a need for larger datasets we can think about external storage. But for now 100KB is not that much. `layered_repository.rs` is about 100KB, and so is `Cargo.lock`.

**Comment by hlinnaka** [comment]
See also issue #1607, cc @MMeent

**Comment by shanyp** [comment]
closing as a dup of https://github.com/neondatabase/neon/issues/1607 , added @bojanserafimov comments
