### ISSUE TITLE
Epic: fix the attach/detach and add python tests for branching

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1898]
attach and detach commands are implemented per timeline
this is flexible, because we can have different timelines served on different pageservers
OTOH to properly handle a branch on a pageserver, pageserver needs to be aware of the other timelines, e.g. for GC to not mess things up

shall we attach/detach the whole tenant on pageserver?

does this depend on the on-demand download from s3?

**Comment by LizardWizzard** [comment]
#1936 is now merged, attach and detach now handle tenant as a whole

gc tests for branching are tracked in #1899. @stepashka  should we close this?

**Comment by hlinnaka** [comment]
> #1936 is now merged, attach and detach now handle tenant as a whole
> 
> gc tests for branching are tracked in #1899. @stepashka should we close this?

Yeah, let's close this
