### ISSUE TITLE
Epic: expand tests that use branching

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1900]

**Comment by kelvich** [comment]
I don't think that e2e tests are the right place for expanded tests for branches. At first, those tests already exist https://github.com/neondatabase/cloud/blob/main/tests_e2e/tests/test_project.py#L400 At second, I think e2e tests are to test integrations and basic error-out scenarios, not to test feature corner cases. IMO it is better to expand branching tests suite around the pageserver itself -- tests would be fester and they'll have more access to the internal state (files, sizes, manual GC runs, etc).

Let's rename this epic? =)

**Comment by kelvich** [comment]
killed in favor of https://github.com/neondatabase/neon/issues/1899
