### ISSUE TITLE
Index corruption after compute crash and restart

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1915]
Compute crashed while restoring a large schema (somewhere around 1000-2000 tables). After restart:
```
main=# set enable_sort=off;
SET
main=# select * from pg_depend order by refclassid, refobjid, refobjsubid;
ERROR:  index "pg_depend_reference_index" contains unexpected zero page at block 3
HINT:  Please REINDEX it.
main=# 
```

**Comment by hlinnaka** [comment]
This happened on the production env

**Comment by knizhnik** [comment]
I just try to load  backup on the latest sources and got the multiple errors likes this:
```
pg_restore: error: could not execute query: ERROR:  right sibling's left-link doesn't match: block 2 links to 42 instead of expected 38 in index "pg_constraint_conrelid_contypid_conname_index"
```

**Comment by knizhnik** [comment]
I do not using some noticeable memory consumption while pg_restore and later when compute is restarting and querying data. Maximal size of postgres backend doesn't exceed  170Mb (most of them are shared memory with shared_buffer_size=128MB). It it possible to assume that even i this case we can get OOM if total memory size of VM is limited by 256Mb and multiple parallel workers are started (I see 6 running parallel workers). But s far as I understand t even 1Gb of VM memory is not enough and only after 5Gb og_restore is able to complete. It is really strange.

Actually Ketteq schema is not so large:
```
postgres=# select count(*) from pg_class;
 count 
-------
 49952
(1 row)

postgres=# select pg_relation_size('pg_class');
 pg_relation_size 
------------------
         13697024
(1 row)

postgres=# select pg_relation_size('pg_attribute');
 pg_relation_size 
------------------
         33857536
(1 row)
```
