### ISSUE TITLE
On-demand download of S3-offloaded WAL

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#1920]
Recently we started offloading WAL from safekeepers to S3, and removing WAL segments from the disk after a successful upload. That means that `send_wal` (START REPLICATION [LSN]) is no longer able to stream WAL from the beginning of the timeline once we trimmed the WAL. 

We can fix this by downloading WAL segment from S3 once we need to read WAL at some LSN, and we don't have a corresponding segment on the disk.

A good test for that will be:
- create a fresh timeline on the pageserver
- generate some WAL, verify it's offloaded to S3
- reset pageserver to the fresh state, so it should receive (from safekeepers) and replay all WAL
- verify queries return expected results once pageserver has caught up

**Comment by hlinnaka** [comment]
I thought we only remove the WAL from the safekeeper, after the pageserver has uploaded the corresponding layer files to S3. In other words, the pageserver should never call START REPLICATION with an LSN that has already been removed from the safekeeper.

**Comment by petuhovskiy** [comment]
> I thought we only remove the WAL from the safekeeper, after the pageserver has uploaded the corresponding layer files to S3

That's correct, but there are still some corner cases:
- if pageserver is lagging and we've replaced one safekeeper, that safekeeper can miss required WAL locally
- when we do pageserver migration, we have several consumers, and we need to track that carefully

We can fix these cases separately, but this S3-download patch is easy to do and should simplify things in general. Also if we just want to download WAL from the beginning (maybe not even for pageserver), requesting any safekeeper with START REPLICATION for that sounds like a nice feature.

**Comment by LizardWizzard** [comment]
> if pageserver is lagging and we've replaced one safekeeper, that safekeeper can miss required WAL locally

But how is that possible? In my understanding of the current implementation, safekeeper cannot remove WAL that was not acknowledged by the pageserver. So S3 offloading duplicates local WAL and there is no mechanism to delete unacknowledged WAL if it overflows the local disk.

+1 for the feature. It can simplify things a bit

For pageserver migration I imagined a solution that will have a loop that will try to start replication and download latest data from pageserver's s3 part if wal was deleted on the safekeeper side
