### ISSUE TITLE
Perf regression with commit f2881bbd8a90bc4b04fb1693ad3a684b260a0f98

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#1956]
![ff](https://user-images.githubusercontent.com/8680233/174345772-445d8e3c-5857-4d88-aee0-e12714b241ab.png)

@LizardWizzard is investigating

**Comment by LizardWizzard** [comment]
Initially, I compared two commits: https://github.com/neondatabase/neon/commit/f2881bbd and https://github.com/neondatabase/neon/commit/bea84150. The first one increases the duration of test_bulk_insert from 7 seconds to 16. This range contains [commit](https://github.com/neondatabase/neon/commit/9a0fed0880dd1d1f482763b8de7c3a2c219fcf43) that enables at least one safekeeper in each test. **Including performance ones**. Probably we shouldn't have been using setup without safekeepers for performance tests in the first place. Though that might be reasonable to test pageserver with less moving parts. 

So I think there is no big problem introduced here. WDYT @bojanserafimov?

**Comment by bojanserafimov** [comment]
Good to know there's no actual regression.

The captest environment is a better place for whole system tests. For example, now I'm not sure if the safekeeper is the bottleneck (because fsync?) or if safekeeper and pageserver are competing for disk. Also postgres is running with `'synchronous_commit=off'`, which is more comparable with `num_safekeepers=0`.
