### ISSUE TITLE
Manually set timeline_start_lsn in safekeepers for old timelines

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#1965]
Look at https://github.com/neondatabase/neon/issues/1963#issuecomment-1160671271 for more info

After `timeline_start_lsn` will be set everywhere, then we can enable checks that were disabled in https://github.com/neondatabase/neon/pull/1964

**Comment by arssher** [comment]
done

**Comment by petuhovskiy** [comment]
There are still 9 timelines with timeline_start_lsn=1, AFAIR they are very old and first WAL segment is missing.
