### ISSUE TITLE
Epic: internal/developer docs

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1979]
In one of the discussions I raised a question regarding documentation. For storage we have quite a few places and sometimes it becomes pretty difficult to navigate. 

We have now:
1. Readme's for pageserver/safekeeper
2. neon/docs
3. https://neon.tech/docs/storage-engine/architecture-overview/

This way the knowledge is a bit scattered around different places. 

Another problem is that we do not have the procedure for checking that the docs are up to date. Any ideas on how to implements this?

Also I remember that @kelvich said that he has some ideas regarding README structure for the whole repo. This is probably related.  Lets discuss ideas here.

Documentation should fulfill the needs of the following types of target audience:
1. People outside of neon who interested in the internals
2. New contributors
3. Sleepy on-call colleague who needs to debug the outage

**Comment by kelvich** [comment]
Related: https://github.com/neondatabase/neon/issues/1557

**Comment by hlinnaka** [comment]
The docs are in mdbook format now, collected mostly in the docs/ directory rather than as scattered READMEs. There's a lot more documentation that we could and should write, but that's a different issue.
