### ISSUE TITLE
Epic: improve error handling in the pageserver

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2030]
We are a bit clumsy with our error handling right now: we print unnecessary backtraces, sometimes we check error type by matching an error message, we don't classify errors by types, etc.

At the minimum we need:
* distinguish errors by severity
* distinguish between errors caused by panic catch and all other error

@funbringer did a good job with https://docs.rs/thiserror/latest/thiserror/ crate in proxy (https://github.com/neondatabase/neon/blob/main/proxy/src/auth/backend/console.rs#L20) -- pageserver can follow the same approach.

Thinking about Sentry integration when designing error handling would also be good.

[] Silence errors and warnings coming from disconnections (move it to info or debug level)

**Comment by vadim2404** [comment]
RFC:  #neondatabase/neon2681
PR: #neondatabase/neon2653
