### ISSUE TITLE
Epic: create per-service unit tests for pageserver services

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2031]
We have a bunch of `lazy_static` variables in the pageserver that make it quite hard to spin up one or more of the pageserver services (like page service, wal service, etc). We did a good job in the safekeeper to allow such tests: https://github.com/neondatabase/neon/blob/main/safekeeper/src/safekeeper.rs#L968-L975 Such test are most quick to run, so we can programmatically generate a lot of edge cases, use more fuzzing, etc.

There are a few blockers in the pageserver codebase for that tests like:
* avoid `lazy_static` global state, as it hard to spin them up in unit tests
* talk with disk and S3 via an intermediary object that could be mocked in tests

Good candidates for such tests:
* branching and GC interaction
* on-demand S3 load
* rebalancing

While this epic is really wide in its scope I suggest writing such tests for one of the suggested topics (e.g. only for rebalancing) to consider this epic as done.

**Comment by jcsp** [comment]
Testing is good, but I don't think this epic is tracking anything specific enough to make the ticket useful
