### ISSUE TITLE
Create an RFC/docs about tenant state management

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2035]
And clean up state machine.

**Comment by hlinnaka** [comment]
Is this done?

**Comment by SomeoneToIgnore** [comment]
RFC is not present, states are but would require more refactoring if we somehow work on https://github.com/neondatabase/neon/pull/2595#discussion_r993518016 and then an RFC would be beneficial.

**Comment by vadim2404** [comment]
I'm closing this one in favour of #2736
