### ISSUE TITLE
Branch creation waits for compaction to finish

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2054]
Then I tried to understand why GC takes so long time, although it is expected to be cheap operation (reading only layers metadata, do not read or write layer file content - just delete deteriorated layers).  And the reason is compaction_cs which is obtained not only by compaction but also by GC. And compaction can really take very long time. Is it acceptabe to delay creation of new branches and GC until compaction is complete?

_Originally posted by @knizhnik in https://github.com/neondatabase/neon/issues/2053#issuecomment-1178958247_

**Comment by knizhnik** [comment]
Actually compaction is performed for L0 layers. And we can just prohibit GC of L0 layers. In this case not synchronization between GC and compaction is needed. But, from the other side, if GC horizon (LSN and time) is small enough, then there is a chance that L0 layer can be deleted before compaction is triggered. In this case we void doing redundant work, which is good.
But if we really want to support long enough PITR interval (days), then there is no chance that L0 layer will be deleted by GC before compaction. 

Compaction thread is also generating image layers (which IMHO is wrong). And GC checks for presence of successor image layers. But this dependency between GC and compaction thread can be resolved using layer_map lock.

@hlinnaka what do you think?
