### ISSUE TITLE
Give access to the public schema to db owner

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#2058]
Some users report that db owner cannot drop the public schema. Indeed:
```sql
main=> drop schema public cascade;
ERROR:  must be owner of schema public
```

```sql
main=> SELECT nspname, nspowner::regrole::text FROM pg_catalog.pg_namespace;
      nspname       |  nspowner   
--------------------+-------------
 pg_toast           | cloud_admin
 pg_catalog         | cloud_admin
 public             | cloud_admin
 information_schema | cloud_admin
 mypublic           | web_access
```

The workaround could be to grant permissions to `public` to db owner
```sql
ALTER SCHEMA public OWNER TO <db_owner>;
```

Let's try it.

**Comment by zomars** [comment]
Thanks for the follow up @ololobus I suspect that I cannot run this myself right? Trying to run `ALTER SCHEMA public OWNER TO <db_owner>;` returns the same error: 

```
SQL Error [42501]: ERROR: must be owner of schema public
```

**Comment by ololobus** [comment]
Yeah, we need to adjust our compute node code. Just tried with the local Postgres instance, worked well. Not sure how it'll play with our roles management, though, will try

**Comment by ololobus** [comment]
@zomars just bumped the compute image version on prod. Database owner now should have a full control of the scheme `public`. So you can drop and create it again. Can you try to restore your dump again?

**Comment by stepashka** [comment]
feel free to reopen if this doesn't work for you, @zomars

**Comment by zomars** [comment]
Are these changes live? I'm afraid I'm seeing the same issue:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/3504472/180882752-a28863ba-9269-44b5-951e-b6a7eb3a34c7.png">

**Comment by ololobus** [comment]
> Are these changes live?

Yes, it is public. Just tried with a new project and database owner is owner of schema public, so I can drop and create it again:
```
ololobus@main=> SELECT nspname, nspowner::regrole::text FROM pg_catalog.pg_namespace;
      nspname       |  nspowner   
--------------------+-------------
 pg_toast           | cloud_admin
 pg_catalog         | cloud_admin
 information_schema | cloud_admin
 public             | ololobus
(4 rows)

ololobus@main=> drop schema public cascade;
DROP SCHEMA
```

> I'm afraid I'm seeing the same issue

@zomars I see that error references schema `mypublic`, not `public`. Could it be that you created it from a different user? You can check schema ownership with `SELECT nspname, nspowner::regrole::text FROM pg_catalog.pg_namespace;`

**Comment by zomars** [comment]
I've tried with a new DB and new user and indeed the schema is now being dropped correctly. But I'm getting new permission errors 😬

<img width="652" alt="image" src="https://user-images.githubusercontent.com/3504472/181081285-ba5f7cda-7c1d-4ea8-90c4-a4e89bc789b6.png">

**Comment by ololobus** [comment]
Ugh, unfortunately, setting the `session_replication_role` requires [superuser privileges in Postgres](https://www.postgresql.org/docs/current/runtime-config-client.html), which we were not going to provide any time soon :(

It's postponed at least till the point when secure runtime is adopted and we implemented this RFC https://github.com/neondatabase/neon/pull/2104.

And I'm not aware of any workaround for that, excepting the removing the `SET session_replication_role` from the script / cli tool you use. If there will be one, I'll let you know.

@stepashka I'm closing this issue as an access to `public` is given and it apparently works. Having a superuser-like privileges is a whole new story
