### ISSUE TITLE
is_shutdown_requested() called in an unexpected thread

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#2070]
As people noted this log message started to pop up: 
`WARN gc iteration{tenant=5e01a4aae8ba2e15baf43c0ca5a4338d timeline=None}: is_shutdown_requested() called in an unexpected thread` 

It appears because we switched to tenant tasks thread pool that is managed by tokio, and thus threads are not managed by our `thread_mgr.rs`. this can be fixed by registering tokio threads in our thread manager through on_thread_start, on_thread_stop functions of [runtime builder](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.on_thread_start)

**Comment by aome510** [comment]
Thanks for creating this issue. I also saw this message in https://github.com/neondatabase/neon/pull/1569#issuecomment-1179363345
