### ISSUE TITLE
Timeout in test_wal_acceptor::test_unavailability

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2112]
https://app.circleci.com/pipelines/github/neondatabase/neon/8150/workflows/ef2c3e04-1585-40c3-802b-7ebe7611c673/jobs/83441/steps

```
=================================== FAILURES ===================================
_____________________________ test_unavailability ______________________________
[gw2] linux -- Python 3.9.2 /home/runner/.cache/pypoetry/virtualenvs/zenith-TcEEkJmQ-py3.9/bin/python
test_runner/batch_others/test_wal_acceptor.py:253: in test_unavailability
    proc.join()
../.pyenv/versions/3.9.2/lib/python3.9/multiprocessing/process.py:149: in join
    res = self._popen.wait(timeout)
../.pyenv/versions/3.9.2/lib/python3.9/multiprocessing/popen_fork.py:43: in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
../.pyenv/versions/3.9.2/lib/python3.9/multiprocessing/popen_fork.py:27: in poll
    pid, sts = os.waitpid(self.pid, flag)
E   Failed: Timeout >300.0s
------------------------------ Captured log setup ------------------------------
2022-07-18 10:48:57.266 INFO [neon_fixtures.py:2047] get_test_output_dir is /tmp/test_output/test_unavailability
2022-07-18 10:48:57.266 INFO [neon_fixtures.py:2068] test_output_dir is /tmp/test_output/test_unavailability
----------------------------- Captured stderr call -----------------------------
```

**Comment by hlinnaka** [comment]
@arssher can you take a look at this one, please?

Looks like it got stuck while trying to start the safekeeper. The test performs the safekeeper-startup in a separate process. Looking at sk2/safekeeper.log, it succeeds, though, so not sure what's going on. The background process that launches the safekeeper doesn't seem to print anything about in the pytest log. Is that a pytest thing? Maybe using async instead of a background process would give more diagnostics?

**Comment by petuhovskiy** [comment]
I once had an issue with python Process on macOS. It was not timeout, but python3.8+Process+macOS behaved strange, global variables were not initialized in a child process. It was also hard to debug, because background process swallows all the output.

> Maybe using async instead of a background process would give more diagnostics?
Sure, async will be better than Process and can also fix the issue. I'll create a PR to replace Process with async.
