### ISSUE TITLE
Track tokio tasks in thread_mgr

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#2137]
We can rename thread_mgr to task_mgr then :)

Originally raised by @hlinnaka here: https://github.com/neondatabase/neon/pull/2078#issuecomment-1185383111

**Comment by hlinnaka** [comment]
This was done in commit 40c845e57d7060b1946e3a9e9d6bf076a8847e52. We have more issues with making sure a Tenant/Timeline isn't removed while there are Tasks operating on it, but there are separate issues for those.
