### ISSUE TITLE
Neon API requests handling error

### ISSUE THREAD

**Issue by kislerdm** [neondatabase/neon#2159]
## Problem description

Some Neon API end-points return incorrect responses. The are not in line with [the documentation](https://console.neon.tech/api-docs/v1), neither are they correct from the logical point of view.

## How to reproduce

Please find the examples illustrating API calls to retrieve data for the project which does not exist.

```sh
curl -I -X GET -H "Authorization: Bearer ${NEON_API_KEY}" "https://console.neon.tech/api/v1/projects/foo"
HTTP/2 200 
date: Tue, 26 Jul 2022 10:19:14 GMT
content-length: 0

curl -I -X GET -H "Authorization: Bearer ${NEON_API_KEY}" "https://console.neon.tech/api/v1/projects/foo/query/saved"    
HTTP/2 201 
date: Tue, 26 Jul 2022 10:21:35 GMT
content-type: application/json; charset=utf-8
content-length: 2

 curl -I -X GET -H "Authorization: Bearer ${NEON_API_KEY}" "https://console.neon.tech/api/v1/projects/foo/operations"
HTTP/2 200 
date: Tue, 26 Jul 2022 10:23:16 GMT
content-type: application/json; charset=utf-8
content-length: 2
```

## Expected behaviour

The following response is expected to be in line with the API documentation if requested resource is missing.

Status code: `404`.
Content format:
```json
{
  "code": "string",
  "message": "string"
}
```

**Comment by antonyc** [comment]
In API v2 we are not 100% protected from returning 200 on error. If there is a bug in handling an error in the controller code, we will get the same result in API v2. On the other hand, it's highly unlikely to have such an error in API v2 if we're always handling the error in the form of 
```
if err != nil {
  return err
}
```
and do not try to handle errors in any other way.

In API v2 we're 100% protected from returning unexpected status codes on successful handling, we're 100% compliant with the spec here.

Specifically tested these endpoints. Only the `GET ../projects/foo/query/saved` still suffers from this rather strange behavior, and it happened to be compliant with the spec (!). Will fix.

```
➜  cloud git:(main) ✗ curl -I -X GET -H "Authorization: Bearer ${NEON_API_KEY}" "https://console.neon.tech/api/v1/projects/foo"
HTTP/2 404
date: Wed, 02 Nov 2022 12:36:59 GMT
content-type: application/json; charset=utf-8
content-length: 33

➜  cloud git:(main) ✗ curl -I -X GET -H "Authorization: Bearer ${NEON_API_KEY}" "https://console.neon.tech/api/v1/projects/foo/query/saved"
HTTP/2 201
date: Wed, 02 Nov 2022 12:37:26 GMT
content-type: application/json; charset=utf-8
content-length: 2

➜  cloud git:(main) ✗ curl -I -X GET -H "Authorization: Bearer ${NEON_API_KEY}" "https://console.neon.tech/api/v1/projects/foo/operations"
HTTP/2 404
date: Wed, 02 Nov 2022 12:37:44 GMT
content-type: application/json; charset=utf-8
content-length: 33
```
