### ISSUE TITLE
Allow `logical_size` to be lazy initialized when loading a branch

### ISSUE THREAD

**Issue by aome510** [neondatabase/neon#2167]
Currently, `logical_size` is initialized when loading a branch. This can be an expensive operation for large DB, as it needs to scan through many relations for size calculation.

It's possible to make this step lazy, as "there's no strong reason we couldn't allow the user to use the branch, before the logical timeline size has been calculated". (https://github.com/neondatabase/neon/pull/2154#discussion_r930359465)

**Comment by hlinnaka** [comment]
Implemented by commit f78a542cbad53d3cb12b2655ec71abfb51ebc22a. cc @SomeoneToIgnore
