### ISSUE TITLE
Test walreceiver failure cases

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#2171]
Part of https://github.com/neondatabase/neon/pull/2168 and https://github.com/neondatabase/neon/issues/2160

We track [connection attempts](https://github.com/neondatabase/neon/blob/d6f12cff8e1dd858a961369d6caf1e8ea8345759/pageserver/src/walreceiver/connection_manager.rs#L258) in walreceiver logic, but have no test for that.
We would need to ensure that we're able to recover after temporary network issues and continue reconnecting for WAL streaming.

**Comment by LizardWizzard** [comment]
cc https://github.com/neondatabase/neon/issues/3667
