### ISSUE TITLE
Unable to install/build on MacOs

### ISSUE THREAD

**Issue by erenerdemli** [neondatabase/neon#2177]
Unable to install on mac os due to lib crypto issue

<img width="1151" alt="Screenshot 2022-07-28 at 13 38 01" src="https://user-images.githubusercontent.com/23046690/181486031-0e50d08f-a40c-449e-8da4-c03c2fdef059.png">

**Comment by erenerdemli** [comment]
<img width="1602" alt="Screenshot 2022-07-28 at 13 40 35" src="https://user-images.githubusercontent.com/23046690/181486463-25217fc5-d6ed-4237-85a9-41ffbbc68d85.png">

**Comment by SomeoneToIgnore** [comment]
My setup seems to be very similar:

```
~ ❯ uname -a
Darwin alaptop.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

~ ❯ brew search openssl
==> Formulae
glib-openssl                                          openslp                                               opensc                                                opencsg
openssl@1.1 ✔                                         openssh                                               open-sp ✔                                             openmsx
openssl@3 ✔                                           opensaml                                              openfst                                               homebrew/portable-ruby/portable-openssl
```

yet when I run the build, I see this:

```
~/Downloads/neon main:origin/main ❯ make -j`nproc`
Configuring postgres build
mkdir -p /Users/someonetoignore/Downloads/neon//tmp_install/build
(cd /Users/someonetoignore/Downloads/neon//tmp_install/build && \
	/Users/someonetoignore/Downloads/neon//vendor/postgres/configure CFLAGS='-O0 -g3 ' \
		--enable-debug --with-openssl --enable-cassert --enable-depend --with-includes=/opt/homebrew/opt/openssl/include --with-libraries=/opt/homebrew/opt/openssl/lib \
		 \
		--prefix=/Users/someonetoignore/Downloads/neon/tmp_install > configure.log)
Installing PostgreSQL headers
```

`--with-includes=/opt/homebrew/opt/openssl/include` is used in the config while you have the `--with-includes=/opt/openssl/include` one.

That comes from this line in the makefile:
https://github.com/neondatabase/neon/blob/61cc562822eaf5f8f51c231d6c65dcbd42a6f44d/Makefile#L34

and I see that I have not set up this prefix myself, yet it's present in my system:
```
~ ❯ echo $HOMEBREW_PREFIX
/opt/homebrew
```

and I see it is officially documented: https://docs.brew.sh/Formula-Cookbook#variables-for-directory-locations

Could you check your homebrew values? One could add a fallback value, but we need to know what to fall back to for that, AFAIK, Apple Silicon and Intel macs have different default directory under `$HOMEBREW_PREFIX`

**Comment by bayandin** [comment]
Hey @erenerdemli, could you pull new changes and try to build it again? The issues should have been fixed, I believe.

**Comment by erenerdemli** [comment]
Hi All,

The settings are of a default base of homebrew with no custom changes, homebrew prefix is not set.

<img width="252" alt="Screenshot 2022-07-28 at 21 47 35" src="https://user-images.githubusercontent.com/23046690/181614726-4341fc09-a44e-4af1-b557-76ba96c14798.png">

**Comment by erenerdemli** [comment]
> Hey @erenerdemli, could you pull new changes and try to build it again? The issues should have been fixed, I believe.

Thanks @bayandin 

changes seems to have fixed the issue, waiting for build to  now.

**Comment by bayandin** [comment]
Great!

Most likely,  HOMEBREW_PREFIX is unset because you haven't set up brew shellenv for your zsh profile: https://docs.brew.sh/Manpage#shellenv
