### ISSUE TITLE
golang basic example not working. Error: Malformed password message: invalid payload

### ISSUE THREAD

**Issue by xmlking** [neondatabase/neon#2193]
```golang
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	NEON_HOST := "XYZ.cloud.neon.tech"
	NEON_DB := "main"
	NEON_USER := "XYZ"
	NEON_PASS := "XYZ"
	NEON_PORT := 5432

	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=require", 
	NEON_HOST, NEON_PORT, NEON_USER, NEON_PASS, NEON_DB)
	//fmt.Println(psqlInfo)
	
    db, err := sql.Open("postgres", psqlInfo)
    if err != nil {
        log.Fatal(err)
    }
    defer db.Close()

    rows, err := db.Query("select version()")
    if err != nil {
        log.Fatal(err)
    }
    defer rows.Close()

    var version string
    for rows.Next() {
        err := rows.Scan(&version)
        if err != nil {
            log.Fatal(err)
        }
    }
    fmt.Printf("version=%s\n", version)
}
```

when ` sslmode=require"` is not added or with ` sslmode=disable`  
Error: ` pq: connection is insecure (try using `sslmode=require`)`

after supplying `sslmode=require` now I am getting following error 
Error: `pq: Malformed password message: invalid payload`

**Comment by pabloesm** [comment]
I'm having exactly the same issue with Python and `sqlalchemy`. In my case I'm using the snippet provided in the *Code samples*:
```python
from sqlalchemy import create_engine

CONNSTR = "postgresql://my_user:my_pass@XYZ.cloud.neon.tech:5432/my_db_name"

engine = create_engine(CONNSTR)
```

The above code produces the following error:
```sh
psycopg2.OperationalError: ERROR:  Malformed password message: invalid payload
ERROR:  connection is insecure (try using `sslmode=require`)
```
which can be fixed, as suggested, by using `sslmode=require`:
```python
engine = create_engine(CONNSTR, connect_args={"sslmode": "require"})
```
And then I'm receiving the malformed password error:
```sh
psycopg2.OperationalError: ERROR:  Malformed password message: invalid payload
```

**Comment by bayandin** [comment]
Hey @xmlking, setting `sslmode=verify-full` should help with it.

**Comment by bayandin** [comment]
Hey @pabloesm, I can't reproduce the issue you've mentioned; it works for me even without explicitly setting `sslmode`. I've tried it with python 3.9.13, psycopg2==2.9.3, SQLAlchemy==1.4.39. 
Could you please double-check the project id in the connection string (`XYZ` in your example matches the project id in https://console.neon.tech)

**Comment by pabloesm** [comment]
Hi @bayandin and thanks for the quick reply. In my case the `engine` is created correctly, but I am not able to use it in any query (my example in the previous post was incomplete, sorry, my fault).

```python
from sqlalchemy import create_engine

CONNSTR = "postgresql://my_user:my_pass@XYZ.cloud.neon.tech:5432/my_db_name"

engine = create_engine(CONNSTR, connect_args={"sslmode": "require"})

with engine.connect() as con:
    # Returns psycopg2.OperationalError: ERROR:  Malformed password message: invalid payload
    con.execute("SELECT version()")
```

Tested with Python 3.10.4, psycopg2==2.9.3, sqlalchemy==1.4.39.

Could you reproduce this example? Thanks!

**Comment by xmlking** [comment]
> verify-full

yes, this worked. please document to help other devs.

**Comment by bayandin** [comment]
Hey @pabloesm, if the error still occurs for you, could you please email us at support@neon.tech with your project id (and a reference to this issue)? We'll debug it there. Thanks!

@xmlking, thanks for the suggestion. Updated examples will be rolled out on the next release!

Feel free to reach out at https://community.neon.tech/
