### ISSUE TITLE
Can Neon build or run on redhat/centos operating system

### ISSUE THREAD

**Issue by aqktjcm** [neondatabase/neon#2207]

**Comment by LizardWizzard** [comment]
Hi! I'm developing Neon on Fedora Workstation without any problems. To build Neon some system packages are required to be present. See [this](https://github.com/neondatabase/neon#installing-dependencies-on-linux) section in our readme and "On Fedora, these packages are needed" in particular. Please let us know if you face any problems with the setup. Thanks!

**Comment by ansrivas** [comment]
I can also confirm, I am also on Fedora 36, the `README` instructions worked perfectly on the first try.

**Comment by aqktjcm** [comment]
Ok, I try it on ubuntu 20.04, and it works.
