### ISSUE TITLE
pq suggests using `sslmode=require`, but that gives a `pq: Malformed password message: invalid payload` error

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#2208]
So, pq suggests using `sslmode=require`, but that gives a `pq: Malformed password message: invalid payload` error. It comes from [here](https://github.com/neondatabase/neon/blob/main/proxy/src/auth/flow.rs#L84)

_Originally posted by @bojanserafimov in https://github.com/neondatabase/cloud/pull/1954#pullrequestreview-1058602887_

**Comment by bayandin** [comment]
Users keep seeing it and it's confusing:
- https://github.com/neondatabase/neon/issues/2193
- https://community.neon.tech/t/error-trying-to-add-as-destination-in-segment-com/100

@funbringer could you please have a look once you have a moment?

**Comment by ololobus** [comment]
A couple of similar reports more:
- https://community.neon.tech/t/malformed-password-message-invalid-payload/119
- https://community.neon.tech/t/hasura-connection-error/105/2
