### ISSUE TITLE
Fix CI for external contributors

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#2222]
"Tests fail because they rely on infra you have no access to. Sorry about that, we'll work around it somehow to merge this PR and solve the issue for the next external contributor. Thanks for contributing."

_Originally posted by @bojanserafimov in https://github.com/neondatabase/neon/pull/2195#pullrequestreview-1063218757_

**Comment by bojanserafimov** [comment]
cc @LizardWizzard @zoete @bayandin

**Comment by LizardWizzard** [comment]
Related https://github.com/neondatabase/neon/issues/1863

**Comment by KlimentSerafimov** [comment]
Any follow up on this?

**Comment by koivunej** [comment]
I vaguely remember a bot/workflow script a bit like bors which allowed triggering a workflow run with full permissions with some comment-based commands (post-review for example). This problem affects any repo using secrets so there should be a number of workarounds... Will edit if I can find it.

**Comment by zoete** [comment]
It seems any job that isn't assuming roles (from the AWS instance it runs on) fails due to secrets not being available

**Comment by SomeoneToIgnore** [comment]
Yes, that's the reason for the most of it.

If we won't be implementing a solution to the creds soon, we can meanwhile detect if that's an external PR and skip all Docker, coverage, e2e and allure steps: then it's a matter of fixing a few Python tests to make the CI look green for external contributors.

**Comment by bayandin** [comment]
Recently, one of the contributors has shared this link: https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci

We could use [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) to make PR from external contributors work, but it has huge warnings message (which is kinda expected):

> Warning: For workflows that are triggered by the pull_request_target event, the GITHUB_TOKEN is granted read/write repository permission unless the permissions key is specified and the workflow can access secrets, even when it is triggered from a fork. Although the workflow runs in the context of the base of the pull request, you should make sure that you do not check out, build, or run untrusted code from the pull request with this event. Additionally, any caches share the same scope as the base branch. To help prevent cache poisoning, you should not save the cache if there is a possibility that the cache contents were altered. For more information, see "[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)" on the GitHub Security Lab website.

Ref https://github.com/neondatabase/neon/pull/4188#issuecomment-1543940685

**Comment by bojanserafimov** [comment]
Another PR to test this workflow on https://github.com/neondatabase/neon/pull/5120

I clicked the "Approve and run tests" button but they're failing on permissions
