### ISSUE TITLE
test_tenants_many[RemoteStorageKind.REAL_S3] is flaky

### ISSUE THREAD

**Issue by aome510** [neondatabase/neon#2245]
Example failed runs:

https://github.com/neondatabase/neon/runs/7740424684?check_suite_focus=true
https://github.com/neondatabase/neon/runs/7740121190?check_suite_focus=true
https://github.com/neondatabase/neon/runs/7739496537?check_suite_focus=true
https://github.com/neondatabase/neon/runs/7758820107?check_suite_focus=true

**Comment by hlinnaka** [comment]
Some of these failures seem to be duplicates of issue #2247.

Assigning to @LizardWizzard since you opened a PR for this already

**Comment by LizardWizzard** [comment]
#2248 is the PR that increases the timeout for waiting until checkpoint is uploaded. This should help because previously we used only local flavours of remote storage (either local fs or mock server running locally) and now we use truly remote s3.

Please reopen if you see this again
