### ISSUE TITLE
flaky tests because of "unable to lock pid file. could not daemonize. bailing."

### ISSUE THREAD

**Issue by aome510** [neondatabase/neon#2247]
Example failed runs:

test_tenant_config:
https://github.com/neondatabase/neon/runs/7740489518?check_suite_focus=true
https://github.com/neondatabase/neon/runs/7740120513?check_suite_focus=true

test_pageserver_restart:
https://github.com/neondatabase/neon/runs/7740425335?check_suite_focus=true
https://github.com/neondatabase/neon/runs/7740118966?check_suite_focus=true
https://github.com/neondatabase/neon/runs/7781089364?check_suite_focus=true

Related: 
- https://github.com/neondatabase/neon/pull/2210#issuecomment-1205029496
- https://github.com/neondatabase/neon/issues/1814
- https://github.com/neondatabase/neon/pull/1834
- https://github.com/neondatabase/neon/pull/2060

**Comment by bojanserafimov** [comment]
Wrote a [test](https://github.com/neondatabase/neon/compare/fixture-restart?expand=1) to quickly + reliably reproduce the issue.

Probably the root cause is that we send kill signal without waiting for pageserver to die. I'll look into it.

**Comment by knizhnik** [comment]
There are two obvious but ugly workarounds:
1. Insert some sleep between server restart
2. Make several attempts to lock fie before give up
