### ISSUE TITLE
Prometheus metrics are left behind when a tenant is detached

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2271]
When a tenant is detached or a timeline is deleted, we don't remove the corresponding prometheus metric. Should call https://docs.rs/prometheus/latest/prometheus/core/struct.MetricVec.html#method.remove_label_values somewhere

**Comment by rhzs** [comment]
@hlinnaka is it possible to call it in inside `Drop` trait ?

**Comment by hlinnaka** [comment]
> @hlinnaka is it possible to call it in inside `Drop` trait ?

Makes sense. After https://github.com/neondatabase/neon/pull/2278, you could do it in `Drop` implementation of `TimelineMetrics`.

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/neon/pull/2328 fixed this, closing.
