### ISSUE TITLE
Docker image size of the compute node is very large

### ISSUE THREAD

**Issue by MMeent** [neondatabase/neon#2345]
## Steps to reproduce
Check size of docker image neondatabase/compute-node:latest

## Expected result
A value much less than 500 MB

## Actual result
500+ MB

## Environment
Any

**Comment by hlinnaka** [comment]
Stripping the useless  .debug_pubnames and .debug_pubtypes sections from the rust binaries would help a little, see https://github.com/neondatabase/neon/pull/2514. That PR doesn't change the docker build, but we could add a similar step in there.

```
$ ls -lh target/release/compute_ctl
-rwxr-xr-x 2 heikki heikki 114M Sep 30 22:52 target/release/compute_ctl
$ objcopy -R .debug_pubnames -R .debug_pubtypes -p target/release/compute_ctl
$ ls -lh target/release/compute_ctl
-rwxr-xr-x 2 heikki heikki 88M Sep 30 22:52 target/release/compute_ctl
```
