### ISSUE TITLE
Support channel binding

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2350]
We're missing support for channel binding in the proxy:

```
~$ psql "postgres://hlinnaka@rough-snowflake-340245.cloud.neon.tech:5432/main?channel_binding=require"
psql: error: connection to server at "rough-snowflake-340245.cloud.neon.tech" (52.35.3.79), port 5432 failed: channel binding is required, but server did not offer an authentication method that supports channel binding
```
Channel binding would make client connections more secure, by preventing MITM attacks. Using `sslmode=verify-full` provides the same level of security, but it's more cumbersome to set up as you need to install the SSL certificate in the client.

**Comment by vadim2404** [comment]
it will be merged this week
