### ISSUE TITLE
`plv8` extension creation crashes postgres sometimes

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2361]
I've managed to do this two times. The rough algorithm is following:

1. Create a new staging project
2. Run `create extension postgis;`
3. Run `create extension plv8;`

With some probability step 3 will result in a crash.

My try 1, late-surf-318322: 

https://observer.zenith.tech/d/IJSLHBOnk/neon-logs-compute-nodes?orgId=1&var-environment=staging&var-region=virginia&var-project=compute-node-late-surf-318322&var-search=&var-exclude=substing%20to%20exclude&from=1661776289601&to=1661777410709

My try 2, silent-union-873343: 

https://observer.zenith.tech/d/IJSLHBOnk/neon-logs-compute-nodes?orgId=1&var-environment=staging&var-region=virginia&var-project=compute-node-silent-union-873343&var-search=&var-exclude=substing%20to%20exclude&from=1661806532323&to=1661806628863

In both cases it was with the following log messages:
```
	
2022-08-29 23:56:05	
compute-node-silent-union-873343	2022-08-29 20:56:05.502 GMT [14] LOG:  server process (PID 33) was terminated by signal 7: Bus error
	
2022-08-29 23:56:05	
compute-node-silent-union-873343	2022-08-29 20:56:05.502 GMT [14] DETAIL:  Failed process was running: create extension plv8;
```

**Comment by kelvich** [comment]
> I've reproduced it with

Locally? Is there a backtrace?

**Comment by hlinnaka** [comment]
Did this really get fixed by PR #2366? I think Github intepreted "this may or may not fix #2361" as just "fix #2361", and closed this issue automatically :-).

**Comment by stepashka** [comment]
are you working on this, @SergeyMelnikov ?

**Comment by stepashka** [comment]
we'll increase the amount of memory, deploy on staging and check if this still fails

**Comment by klink** [comment]
are we still working on this?

**Comment by ololobus** [comment]
- [ ] update docs (@lubennikovaav is working on it)
- [ ] add release notes (cc @danieltprice )
