### ISSUE TITLE
web page "Or you can add it to the .pgpass:" double the '.pgpass'

### ISSUE THREAD

**Issue by usrtax** [neondatabase/neon#2379]
should use '> ~/.pgpass' , not '>> ~/.pgpass'

<img width="870" alt="image" src="https://user-images.githubusercontent.com/110233389/188070599-68386176-75ca-40c3-ab7a-206ae74fd4ac.png">

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/110233389/188070835-4ace5c0c-c70a-4f7c-8b67-96a6f6e12f3e.png">

**Comment by danieltprice** [comment]
It looks like https://github.com/neondatabase/cloud/pull/2056 was supposed to address this issue. I will look into it.

**Comment by danieltprice** [comment]
To just append rather than duplicate and append, this might be what we're looking for:
echo -e "<project_id>.cloud.stage.neon.tech:5432:main:<user>:<password>\n" >> ~/.pgpass

**Comment by danieltprice** [comment]
The following PRs were created to address this issue:
https://github.com/neondatabase/cloud/pull/2410
https://github.com/neondatabase/website/pull/207
