### ISSUE TITLE
Pageserver Python tests should not fail if the server is built with no `testing` feature

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#2531]
`testing` feature is disabled by default and some people use `make` and then run tests, which fails.

We could use pageserver's version string to determine which features are enabled and expect those tests to fail/skip them.

**Comment by sharnoff** [comment]
I think this is a good idea. Separately, I wonder if we should have `make` by default use `testing`, and something like `make release` to build without it - just so that the default path runs more of the tests.

**Comment by andresrsanchez** [comment]
Hi! So before doing any PR's i would like to know ur take on [this](https://github.com/neondatabase/neon/compare/main...andresrsanchez:neon:pytest-error-features-enabled)

Please take a look if u have time at the `session` scope in `is_testing_supported` and `is_profiling_supported`, i have done it this way to "cache" the result of the current pageserver's features for all the pytest session, if this is dangerous or not interesting i would go with a simple `skipif(is_testing_supported, "blabla")` or something else.
Also, the fixture go at first in the python signature test's to skip (or not) fast, without doing anything with `NeonEnv`.

Thanks!!!

**Comment by SomeoneToIgnore** [comment]
I am a bit sceptical about the approach, since it requires a person, writing the test, to place two things independently: a failpoint and a marker on the test, it's easy to overlook.

I wonder, if `NeonPageserverHttpClient::configure_failpoints` method could run the same `pytest.skip("pageserver was built without 'testing' feature")`? 
Then we could inject the feature knowledge about pageserver into the HTTP client and disallow all the maintenance HTTP calls.
That requires knowledge about which rust methods are dependent on `feature` call, but it only requires hardcoding in the client, so should be fine?

Also, I think rather than creating a lot of `is_**_supported` methods with `scope="session"`, I would create a single `scope="session"` method that returns a `NeonEnv` object with pageserver version inside, and a few methods on it, `def is_testing_enabled`.
This way, we're writing more customisable code, if we decide to change the way service versions are handled.

Otherwise, thanks for the effort and thinking on this: I am now aware of important `pytest.skip` bit and we can think more on the implementation.

**Comment by andresrsanchez** [comment]
So if we want to check the features inside `configure_failpoints` to skip and also we want to maintain the pageserver's features under a `scope="session"` then i think that we would need something similar to [this](https://github.com/neondatabase/neon/blob/main/test_runner/fixtures/neon_fixtures.py#L249), because we cannot call the fixture directly we need to inject it somewhere, in this case would be `_shared_simple_env` or `neon_env_builder` to store the features inside `NeonEnv` otherwise we would need to pass the fixture from the executing test deep down to `configure_failpoints` and the spot now would be similar to before.

Why do you want a sessionize `NeonEnv`? In that case we would need a different fixture and specify it in each test that we want to use the `configure_failpoints` and i think we don't want that.
So something like:

```
@pytest.fixture(scope="session")
def pageserver_features:
    yield PageServerFeatures()

class PageServerFeatures:
    def __init__(self):
        # get the features from pageserver --version
    def is_testing_enabled():
        # do things

Then inject PageServerFeatures inside NeonEnv with pageserver_features
```
WDYT? Sounds too complicated

**Comment by SomeoneToIgnore** [comment]
I imagined, we need to do things:
* write a code to parse pageserver version string, at least on the level of "is testing feature is enabled"
* `NeonPageserverHttpClient` is instantiated via `NeonPageserver` Python class, that has access to whole `env`
* we can call `pagesever --version` using that `env` (might require code adjustments), parse the version, add this knowledge to `NeonPageserverHttpClient`
* when `configure_failpoints`, `timeline_gc` or whatever else "service" HTTP method is called, do `pytest.skip` with a warning log or smth.

We could add more checks on top of that, I guess, such as "always be sure that CI regress tests are run with these tests enabled", but it's optional.
To me, seems simple and portable (no pytest scopes involved) enough, am I missing something?

**Comment by andresrsanchez** [comment]
Oh if we can check the pageserver's version each time the `NeonEnv` is created and forget the fixture/session-scopes thing then yeah, that sounds promising!!! My take was about the same idea of `NeonEnv` -> `NeonPageserver` -> `NeonPageserverHttpClient` but with a sessionize fixture so we would need the fixture builders.

Thanks! I'm on it
