### ISSUE TITLE
Creating databases through api creates timestamp of '0001-01-01T00:00:00Z'

### ISSUE THREAD

**Issue by dein-ding** [neondatabase/neon#2533]
## Steps to reproduce
1. Grab a beer and some popcorn because this is a funny one
2. Send a request to the api endpoint `POST https://console.neon.tech/api/v1/projects/<your_project_id>/databases` 
with a body of `{
  "database": {
    "name": "test_db",
    "owner_id": <your_owner_id>
  }
}`
<details>
    <summary>Send directly with curl</summary>
    <pre>curl -X 'POST' \
  'https://console.neon.tech/api/v1/projects/&lt;your_project_id>/databases' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer &lt;your_api_key>' \
  -H 'Content-Type: application/json' \
  -d '{
  "database": {
    "name": "test_db",
    "owner_id": &lt;your_owner_id>
  }
}'</pre>
</details>

## Expected result (api response)
```json
{
    "id": "<database_id>",
    "created_at": "2022-09-29T17:09:29.751Z",
    "updated_at": "2022-09-29T17:09:29.751Z",
    "project_id": "<your_project_id>",
    "owner_id": "<your_owner_id>",
    "name": "test_db"
}
```

## Actual result (api response)
```json
{
    "id": "<database_id>",
    "created_at": "0001-01-01T00:00:00Z", // this should not be off by 2021 years
    "updated_at": "0001-01-01T00:00:00Z",
    "project_id": "<your_project_id>",
    "owner_id": "<your_owner_id>",
    "name": "test_db"
}
```

There is nothing wrong with the actual database created, but the timestamp should not be off by 2021 years. It is just the response that is messed up.

**Comment by nikitakalyanov** [comment]
@dein-ding This is fixed now, thanks for the report!
