### ISSUE TITLE
Make get_lsn_by_timestamp available in mgmt API

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2536]
The pageserver has an API call, 'get_lsn_by_timestamp', as part of the libpq API. For example when creating a branch, the user specifies a timestamp, but internally the branch is created at a particular LSN. The API call can be used to convert the convert the user-supplied timestamp into an LSN.

However, the console cannot easily call into the libpq API, which makes it inconvenient to use fro the console. Let's move the functionality into the HTTP management API instead.

The current code to handle it is in `pageserver/src/page_service.rs`. It should be moved into pageserver/src/http/routes.rs. The URL could be something like "/v1/tenant/:tenant_id/timeline/:timeline_id/get_lsn_by_timestamp?timestamp=:timestamp".

get_lsn_by_timestamp isn't used by anything yet, so we are still free to change it as we wish without breaking things. It will be used by the console in the future.

**Comment by andresrsanchez** [comment]
Hey @hlinnaka i think i can do this!

**Comment by andresrsanchez** [comment]
Done, that's the correct branch

**Comment by SomeoneToIgnore** [comment]
Closed with https://github.com/neondatabase/neon/pull/2560
