### ISSUE TITLE
Safekeepers panic and don't respond to HTTP

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#2545]
## Steps to reproduce

Have a latest version of safekeepers running for some time.

## Expected result

Everything works without issues.

## Actual result

We have panics in the logs, starting from this line: https://github.com/neondatabase/neon/blob/main/safekeeper/src/wal_service.rs#L39
These panics say something about exceeding the thread limit of 4096 threads.

HTTP queries to safekeeper server don't work. This triggers `delete_tenant` alert in our SLO monitoring and also disables safekeepers metrics.

## Environment

Staging

## Logs, links

Logs were already rotated, it happened on Sep 28. We can see that metrics from some safekeepers are unavailable in the Explore section of the Grafana.

**Comment by hlinnaka** [comment]
Same issue we had in pageserver: https://github.com/neondatabase/neon/issues/1609. It's coming from the `sharded-slab`, which is used by `tracing-subscriber`.

**Comment by hlinnaka** [comment]
Not sure why the safekeeper had so many threads in the first place, though.
