### ISSUE TITLE
Treat every non-empty tenant and timeline directory existing on local pageserver FS

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#2552]
See https://github.com/neondatabase/neon/pull/2546#discussion_r986704751 for more context on tenants

Now, we completely ignore a `tenants/{tenant_id}/` directory, if it has no `timelines/` directory, due to error being popped in `fn collect_timelines_for_tenant` function.
We log that error, but otherwise not showing such tenants anywhere, including management HTTP tenant list command.
This results in special effects, such as odd errors during an attempt to crate the timeline with the same id (which console usually does in a loop for the tenant creations that failed for some reason).

Instead, we should load such tenants as `Broken` and return them in the management API.

Timelines would require the same treatment, but as a first step, first PR could be about tenants only, as it's a simpler task.

**Comment by andresrsanchez** [comment]
hey @SomeoneToIgnore can i try to do this?

**Comment by SomeoneToIgnore** [comment]
Sure! 
Ask away here, if something's unclear.

**Comment by SomeoneToIgnore** [comment]
Closed via https://github.com/neondatabase/neon/pull/2575

@andresrsanchez , feel free to reach out in DM or issues for any dev questions related.
