### ISSUE TITLE
Pageserver HTTP handlers return incorrect response codes when Tenant/Timeline not found

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/neon#2574]
Currently some of the Tenant/Timeline methods do not provide a way to distinguish between errors from a Tenant/Timeline not being found and other internal errors, because they return `anyhow::Error`.

Possible solutions:
* Use a more expressive return type -- e.g., `Result<Option<T>, anyhow::Error>`
* Reorganize methods so that the "get tenant/timeline" and "do operation" steps are decoupled, and both must be called by the handler, giving it the necessary context to turn the errors into the correct `ApiError`
* Resurrect #2487 (more expressive error types)

**Comment by shanyp** [comment]
@sharnoff note that now that the timeline/tenant "get" methods return ApiError::NotFound for non active/non existent objects

let me know if I can close this one
