### ISSUE TITLE
`make` ignores compile errors

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#2577]
## Steps to reproduce
Add compile error in `pgxn`, run `make`

## Expected result
The last few lines of the output indicate that there's some error. Ideally the error is visible there too.

## Actual result
Output looks indistinguishable from successful compilation

## Environment
Local

**Comment by hlinnaka** [comment]
This is what I get:
```
gcc -O0 -g3   -fPIC -I/home/heikki/git-sandbox/neon/pg_install/v14/include -I. -I/home/heikki/git-sandbox/neon//pgxn/neon/ -I/home/heikki/git-sandbox/neon/pg_install/v14/include/postgresql/server -I/home/heikki/git-sandbox/neon/pg_install/v14/include/postgresql/internal  -D_GNU_SOURCE   -c -o pagestore_smgr.o /home/heikki/git-sandbox/neon//pgxn/neon/pagestore_smgr.c -MMD -MP -MF .deps/pagestore_smgr.Po
/home/heikki/git-sandbox/neon//pgxn/neon/pagestore_smgr.c:1:2: error: expected ‘;’ before ‘typedef’
    1 | s/*-------------------------------------------------------------------------
      |  ^
      |  ;
make[1]: *** [/home/heikki/git-sandbox/neon/pg_install/v14/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:940: pagestore_smgr.o] Error 1
make[1]: Leaving directory '/home/heikki/git-sandbox/neon/pg_install/build/neon-v14'
make: *** [Makefile:151: neon-pg-ext-v14] Error 2
```
It might be less visible if you use "make -j". I always use "make -j4 -s", to reduce the noise, and that also makes it quite visible. I don't think there's much we can do here, this is just how "make" behaves. (Could switch to a different build system I guess, but sees like overkill to introduce yet another one, in addition to "make" that's used by Postgres and cargo)

**Comment by bojanserafimov** [comment]
Sometimes the last line I see is `make[1]: Leaving directory`, and I have to scroll way up to find the error. A solution is to maybe look at the exit code and print an extra line at the end that says "Error". If it doesn't seem like a problem we can close the issue and I'll just alias the command locally for myself.
