### ISSUE TITLE
race condition for creating a branch from head

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#2579]
when you create a branch for 'now', with emtly LSN value in the pageserver API ('Head' in the console terms), it is created from the LSN that pageserver has (the last_record_lsn), but not necessarily the most recent LSN on the safekeepers that the user may assume to be saved already
this could affect the automated scnarios of creating a branch: e.g. we run a scrip that created & poopulates tables, then we create a branch and assume it will have all of this data, but it doesn't)

**Comment by stepashka** [comment]
@ololobus , @kelvich , @hlinnaka , could you please review the description?

**Comment by stepashka** [comment]
where do we need to fix this? on the storage side or on the control plane?

**Comment by ololobus** [comment]
> could you please review the description?

In overall, that sounds exactly as I imagined the problem. Yet, the exact LSN name -- `last_record_lsn` -- should be confirmed by someone from the storage, I always mix the lsn values.

> where do we need to fix this? on the storage side or on the control plane?

I'd say that it's tricky to solve on the storage side. Basically, pageserver will need to do sync safekeepers to get the lsn value, which doesn't sound great, as compute is responsible for doing that and it could be running during branch creation.

From the control-plane there are different paths:
- if compute is running, we can just call `select pg_current_wal_insert_lsn()` as all current branching tests do and create branch with this LSN. This will be a correct definition of HEAD, IMO
- if it isn't, then we can start compute first and do the same. Nothing difficult, but will complicate branch creation logic a bit

**Comment by kelvich** [comment]
In theory, we can save the last LSN during the shutdown in the database --  to avoid creating compute to query it.

**Comment by stepashka** [comment]
closing in favor of neondatabase/neon#1371
