### ISSUE TITLE
add the history size to the pageserver API

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#2599]
report the history size from the pageserver in the pageserver APi to make it available for the console
1. WAL size
2. the amount of days it's configured for

this should be reported per tenant & timeline

**Comment by koivunej** [comment]
It might make sense to integrate this to some existing query. Problem will be, what to do if the values haven't yet been calculated, unsure what to do in that case, but perhaps that will clarify itself when querying console team.

**Comment by koivunej** [comment]
Initially implemented in #2714 as a separate route. The `history_size: u64` could eventually be added into `GET /v1/tenant/{tenant_id}` using a similar filtering as with `GET /v1/tenant/{tenant_id}/timeline?include-non-incremental-logical-size=true&include-non-incremental-physical-size=true` but it was not considered now.
