### ISSUE TITLE
Consider initializing timelines via temporary directory

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#2670]
Timelines are now created using uninit marks, introduced in https://github.com/neondatabase/neon/pull/2489
While tenants are created, using a temporary directory.

Timelines have a very special case, that makes such tmp_dir approach harder to implement: `bootstrap_timeline` that happens for timelines, created from scratch, creates two directories:
* initdb directory, where a `pg_init` process is run into, creating temporary postgres files
* real timeline directory, where temporary postgres files are imported via pageserver logic

Our code uses a somewhat detached way to get the timeline path to write into (when importing temporary postgres files) and that path is hard to change to some temporary directory.
https://github.com/neondatabase/neon/pull/2489#discussion_r998570376

We need to find a way to do that, if possible, this making both directories temporary and eliminating the need for more complex logic around the uninit mark file

**Comment by shanyp** [comment]
@LizardWizzard is this still relevant ?

**Comment by LizardWizzard** [comment]
I would close it as wontfix. Using tempdirs for timeline creation is trickier, so I think we wont be moving from that any time soon
