### ISSUE TITLE
it will be nice if could drop a architecture.md at Architecture overview section

### ISSUE THREAD

**Issue by ben1009** [neondatabase/neon#2695]
as the title, it would be nice if could find an architecture description like in https://neon.tech/blog/architecture-decisions-in-neon/, when go through the codebase. BTW, is there only one writer computer node, multiple reader computer node, since we support multi-tenancy, is there multi-writer according, thanks

**Comment by hlinnaka** [comment]
(sorry for the slow response, didn't notice this until now!)

> as the title, it would be nice if could find an architecture description like in https://neon.tech/blog/architecture-decisions-in-neon/, when go through the codebase.

I opened [PR](https://github.com/neondatabase/neon/pull/2992) that adds a link to that, along with some other minor updates. What you think, is that helpful?

> BTW, is there only one writer computer node, multiple reader computer node, since we support multi-tenancy, is there multi-writer according, thanks

There is only one writer compute node for each Postgres database cluster. We have no plans for multi-writer at the moment. Multi-writer opens a big can of worms on doing 2-phase commit and synchronous replication across the writers, or dealing with inevitable conflicts, which by nature needs application-specific logic.

**Comment by ben1009** [comment]
> (sorry for the slow response, didn't notice this until now!)
> 
> > as the title, it would be nice if could find an architecture description like in [neon.tech/blog/architecture-decisions-in-neon](https://neon.tech/blog/architecture-decisions-in-neon/), when go through the codebase.
> 
> I opened [PR](https://github.com/neondatabase/neon/pull/2992) that adds a link to that, along with some other minor updates. What you think, is that helpful?
> 
> > BTW, is there only one writer computer node, multiple reader computer node, since we support multi-tenancy, is there multi-writer according, thanks
> 
> There is only one writer compute node for each Postgres database cluster. We have no plans for multi-writer at the moment. Multi-writer opens a big can of worms on doing 2-phase commit and synchronous replication across the writers, or dealing with inevitable conflicts, which by nature needs application-specific logic.

thanks for the replay. have one more question, so if need more read resource could pull up more reader nodes, since we already support serverless, that should be fast enough. but what if need more write resource, scale up is the only way ? what is the process, since only one writer could exist per cluster, thanks

**Comment by hlinnaka** [comment]
> thanks for the replay. have one more question, so if need more read resource could pull up more reader nodes, since we already support serverless, that should be fast enough. but what if need more write resource, scale up is the only way ? what is the process, since only one writer could exist per cluster, thanks

Basically, you shut down the writer node, and start a new writer on a larger VM. That terminates all in-progress transactions, but other than that it's a pretty fast operation, thanks to the separation of compute and storage. To do better than that, we're working on VM migration and autoscaling. That will allow moving the writer node to a bigger physical instance when needed, but it's still in early development.
