### ISSUE TITLE
Flaky `test_compatibility::test_prepare_snapshot`

### ISSUE THREAD

**Issue by alexstanovoy** [neondatabase/neon#2706]
## Steps to reproduce

Run the test several times.

`while ./scripts/pytest test_runner/regress/test_compatibility.py::test_prepare_snapshot; do done`

## Expected result

Test passes.

## Actual result

Test fails with the error `Exception: timed out while waiting for remote_consistent_lsn to reach 0/A330000, was 0/A32FFD0`

## Environment

Same as in the CI.

## Logs, links

Example from the CI:
https://github.com/neondatabase/neon/actions/runs/3337116531/jobs/5524284198

CI logs:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2686/release/3337116531/index.html#testresult/3df818a5a22a1644
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2686/debug/3337116531/index.html#testresult/f76ea31dc6783c12

**Comment by bayandin** [comment]
Fixed by https://github.com/neondatabase/neon/pull/2719
