### ISSUE TITLE
Race condition in `set_state`

### ISSUE THREAD

**Issue by alexstanovoy** [neondatabase/neon#2727]
[Code link](https://github.com/neondatabase/neon/blob/main/pageserver/src/tenant.rs#L636)

Let's imagine we have not only `Active` and `Paused` states, but also some valid `Active2` state. Steps to reproduce:

1. `self.current_state()` returns `Active` for the first thread.
2. `self.current_state()` returns `Active` for the second thread.
3. The first thread changes the state to `Paused` according to the `match`.
4. The second thread changes the state to `Active2` according to the `match`.

Without the `Active2` state, it's currently impossible to reproduce. But it could be a problem when the new state appears.

**Comment by LizardWizzard** [comment]
Related WIP PR: https://github.com/neondatabase/neon/pull/2665. TLDR: we can use `send_if_modified` to perform the match under `watch`s internal `RWLock`

**Comment by hlinnaka** [comment]
Is this the same as https://github.com/neondatabase/neon/issues/2003 ?

**Comment by koivunej** [comment]
Noted that this issue no longer points to any sensible location in code. The `Sender::send_modify` is now being used through out.

**Comment by hlinnaka** [comment]
The code has changed a lot since this issue was created. Closing.
