### ISSUE TITLE
Create a test for gc that detects lost history when gc misses info about certain timelines

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#2729]
## Steps to reproduce

See https://github.com/neondatabase/neon/pull/2726
We need a test that can detect this

## Expected result

Tests passed

## Actual result

Tests should fail on such changes

## Logs, links
-

**Comment by andresrsanchez** [comment]
Hi @LizardWizzard i was looking to do this test but i have one question with these steps i did:

- Create one branch and request to pageserver the details about it, receiving a `state: Active`.
- Stop the compute to trigger `on_compute_disconnect` setting the timeline state to `active=false` in SK
- Wait a little bit and again request to pageserver the details about it, receiving again a `state: Active` 

Why is that? Is it correct? 

I was looking to set a few timelines non active and then trigger a gc to test the not deletion of data needed by a child timeline.
Thanks!

**Comment by LizardWizzard** [comment]
Hi! @andresrsanchez 

> Wait a little bit and again request to pageserver the details about it, receiving again a state: Active

Yeah, this indeed feels wrong. There is an option in pageserver called `checkpoint_timeout`. Checkpoints are performed by wal receiver either when enough size gets accumulated (`checkpoint_distance` option) or when `checkpoint_timeout` is reached. And currently state is not changed when we reach this timeout which is by default 10 minutes. I think it is a separate issue. Thought about opening a new one, but it turns out there is an existing one: https://github.com/neondatabase/neon/issues/2027

For this issue I think it may be simpler to create a unit test, but it may require additional glue code for setting up gc stuff there
