### ISSUE TITLE
Epic: pageserver s3 coordination

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#2739]
## Motivation

We need this in order to resolve issues for tenant relocation and possible read scalability feature which will allow connecting single compute to multiple pageservers

## DoD

Implement the [RFC](https://github.com/neondatabase/neon/pull/2676)

## Implementation ideas

See linked RFC

## Tasks
- [ ] Change index file structure to contain log of changes instead of just the file list
- [ ] Implement pinging/elections for pageservers

## Other related tasks and Epics
- https://github.com/neondatabase/neon/issues/1556
- https://github.com/neondatabase/neon/issues/886

**Comment by stepashka** [comment]
as of @shanyp this is not super relevant anymore, closing
