### ISSUE TITLE
Post initial `tenant_size` issues

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#2748]
Initial PR: #2714, condensing the review comments and remaining TODO's, observations here.

- Incremental size update ideas for both:
    - `libs/tenant_size_model`
    - `pageserver::tenant::size::calculate_logical_size`
    - in discussions: might not be a blocker for production usage

- #2962
- #2809 -- test failure blocking

#2817 will change a lot, but while that rewrite has been in progress, many of the issues are now handled.

----------------------------------------------------------------

Done or irrelevant now given all of the post-initial changes:

- Current panicking vs. fallible operations in `libs/tenant_size_model` (#3410)
- Behaviour below tenant's `gc_horizon` (currently just zero)
    - #2781
    - overhauled in #3377 to be non-zero (about initdb_lsn)
- Behaviour with regards to `next_gc_cutoff` being on the ancestor_timeline (currently filtered out)
    - This seems ok
- Added and removed test in which timeline is attempted to be broken by deleting it's layer file start and stop raised questions
    - Size remained the same, but data was lost in postgres
    - Timeline was not broken in pageserver's view, because of degenerate local only test case
- Interaction with on-demand downloads ([comment](https://github.com/neondatabase/neon/issues/2748#issuecomment-1302066120), #2029)
    - Related find: #3387 which has not been reproduced, unlikely to be caused by tenant_size
- Wrongly calculated and poorly tested `retention_period` parameter
    - altered in #2817, assuming it's now handled

**Comment by LizardWizzard** [comment]
Another related point tied to on-demand download. In current on-demand model we need to download significant amount of layers to calculate size. Would be good if we can make incremental calculation reliable through restarts, and if not we'll probably need some tweaking to place sizes in one layer (or metadata) so it is cheaper to obtain it on startup

**Comment by koivunej** [comment]
On the #2755 my selection of `next_gc_cutoff` to represent the non-disk_consistent_lsn oldest retained Lsn raised questions, also the `_cutoff` name. Originally Heikki proposed `last_retain_lsn` for this, but I went with `next_gc_cutoff` because it's calculated so much similarly. My interpretation of how it should be calculated could be equally wrong.
