### ISSUE TITLE
Proxy does not forward all server-reported settings to client

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2752]
Proxy does not forward all the settings reported by the server to the client. For example, `standard_conforming_strings`, as reported here: https://community.neon.tech/t/error-while-using-pgx-and-gorm-v2-but-the-error-not-present-in-the-database/221.

Here's a capture of the ParameterStatus packets received after authentication, from PostgreSQL:
> R...6....v=X8kpY5g++ZbNjC8FG6A2BTrBaNgj2x7PuY7U31Gu8U4=R........S....application_name.psql.S....client_encoding.UTF8.S....DateStyle.ISO, DMY.S...&default_transaction_read_only.off.S....in_hot_standby.off.S....integer_datetimes.on.S....IntervalStyle.postgres.S....is_superuser.on.S....server_encoding.UTF8.S....server_version.14.3.S...!session_authorization.heikki.S...#standard_conforming_strings.on.S....TimeZone.Europe/Helsinki.K....../}.4.4Z....I

And here's what I got from our proxy:

> R...6....v=TTZHCsZ2uviTVtrVzwmYuYlcncCv8s+WPGnqGcCG0ys=R........S....client_encoding.UTF8.S....server_version.15.0.K..........$.Z....I

(this capture was from a v15 database, but it's the same with v14).

We need to pass through all the settings that the Postgres sends. Ideally, the proxy would switch to the "pass-through" mode immediately after AuthenticationOK message, so that it wouldn't need to even parse the ParameterStatus messages. That would be most robust if there are changes in Postgres in this area.

**Comment by hlinnaka** [comment]
This also shows up when you try to tun the pgx driver's test suite against a database in neon:

```
$ git clone https://github.com/jackc/pgx
Cloning into 'pgx'...
$ cd pgx
$ PGX_TEST_DATABASE=postgres://heikki:<password>@old-pond-174454.eu-central-1.aws.neon.tech/main go test
...
    --- FAIL: TestUnregisteredTypeUsableAsStringArgumentAndBaseResult/simple_protocol (0.51s)
        conn_test.go:821: simple protocol queries must be run with standard_conforming_strings=on
```

**Comment by hlinnaka** [comment]
This is kind of the reverse of https://github.com/neondatabase/neon/issues/1287. In #1287, the problem is that when the client provides extra parameters in the startup message, we don't forward them to the Postgres server. And this issue is that when the server sends ParameterStatus messages, we don't forward them to the client. cc @funbringer

**Comment by hlinnaka** [comment]
Bumped into another problem that this causes:

Connect to a neon database, with psql. Try tab-completion with:
```
select * from pg_stat_acti<TAB>
```

Expected: auto-complete to `pg_stat_activity`

Actual result: doesn't autocomplete.

It doesn't work, because psql thinks that standard_conforming_strings is off, and escapes the '_' in the tab-completion query incorrectly. If you do a `SET standard_conforming_strings=off; SET standard_conforming_strings=on;`, the client gets the ParameterStatus update, and it starts working.

**Comment by lakhansamani** [comment]
I am also facing a similar issue while adding neon-db integration with https://github.com/authorizerdev/authorizer (open-source authentication and authorization service). Trying to use this with [gorm](https://gorm.io/)

It would be great to have this fixed and let people adopt this auth system.

**Comment by hlinnaka** [comment]
Was this fixed by https://github.com/neondatabase/neon/pull/3122? @funbringer

**Comment by funbringer** [comment]
Yes, this should be fixed now.

**Comment by meetzaveri** [comment]
Any idea if this is fixed or not ? thanks !

**Comment by meetzaveri** [comment]
Thanks @funbringer for the update.

So @lakhansamani , will this unblock [295](https://github.com/authorizerdev/authorizer/issues/295) ?

**Comment by lakhansamani** [comment]
Yes I will soon work on tht issue
Thanks for the update
