### ISSUE TITLE
pg_version and walredo

### ISSUE THREAD

**Issue by knizhnik** [neondatabase/neon#2770]
Right now we have one walredo process for all timelines of one tenant.
But looks like it is assumed that it is possible to change postgres version for newly created timeline.
At least  Tenant::create_timeline_data extracts pg_version  from new metadada and pass it to Timeline::new
Which in turn pass this value to walredo_mgr.request_redo
But one PostgresRedoManager will not be able to server requests from different postgres version. It launches PostgresRedoProcess  at first invocation of apply_batch_postgres  and use pg_version specified at this moment. 
So if we upgrade postgres version then walredo will fail.

Do we plan to support different postgres versions for one tenant?
How it can be done, taken in account that page reconstruction may require walredo records from more than one timeline (i case of branching)?

Are we going to support to choose new postgres version only for new root (main) timelines?
But is it possible for one tenant to have multiple main timelines?

If we are going to support multiple Postgres versions for the same client, then  we should be ready to spawn multiple wal-redo processes with different postgres versions.
If we are not going to support it, then may be it will be better to refactor our API and specify `pg_version` in `create_tenant`?
It will make logic of version choice more clear and simplify implementation of buffered walredo.

**Comment by lubennikovaav** [comment]
We now use one pg_version per tenant and all child branches inherit parent's pg_version.

I added pg_version to `create_timeline` API, because initially we were going to have different versions withing a tenant.
And `create_tenant` doesn't do anything that needs knowledge of pg_version anyway.

Does your PR need this to change?

**Comment by hlinnaka** [comment]
This will become topical again when we implement pg_upgrade. But let's track it as part of that project when we get there, I'll close this old issue.
