### ISSUE TITLE
`test_tenant_relocation` is sometimes flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#2773]
## Steps to reproduce

This has happened few times over the last weeks. I fixed the easier issue in #2743 but the test still comes up as the only flaky. Find example in: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2769/release/3418739591/index.html#categories/d05291d2dd8eef8f0fffa57aa3ed82cc/d4c4456911ca2d0b/

From the logs it seems that pageserver is started in two places using the same configuration:

```
2022-11-08T11:49:07.723773Z  INFO Starting pageserver http handler on localhost:18143
...
2022-11-08T11:49:08.832796Z  INFO Starting pageserver http handler on localhost:18143
```

But I haven't looked if the first pageserver was stopped already at that point. Might be that it was already stopped, and it works usually to reuse the port but not always.

## Expected result

Use distinct ports for launches and always succeed?

## Actual result

Test fails.

## Environment

CI.

**Comment by LizardWizzard** [comment]
To clarify, is it always `test_tenant_relocation[with_load-major]` or other ones fail too? major/minor ones are quite different. Major uses fullbackup/import and minor uses s3

**Comment by bojanserafimov** [comment]
Both pageservers should run at the same time, so we definitely need separate ports

**Comment by hlinnaka** [comment]
related issue: https://github.com/neondatabase/neon/issues/2495. Not sure it's the exact same one, so I'm leaving both issues open for now

**Comment by shanyp** [comment]
@koivunej do we have a place for the history of this kind of test failure? is this one still reproducing?

**Comment by koivunej** [comment]
Whatever flakyness there may have been, looking at the test report, it happened at the starting of initial env building, so we had not yet gotten to the launching of a second pageserver, which has always used new reserved ports.

**Comment by koivunej** [comment]
According to the flaky test db this is not flaky now, closing.
