### ISSUE TITLE
Epic: checksums for s3 data from pageservers (DRAFT)

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#2784]
## Motivation

Reflect current state of open issues in s3 side of things. Replaces #1556 

## DoD

Tasks done.

## Implementation ideas

```[tasklist]
### Tasks
- [ ] #987 Cannot be done on the s3 side because of the missing support in the sdk. Found a way around - use our index file to store this. Ref: We plan to have support for page level checksums as a partial protection from corruption #1185
```

See corresponding issues

## Other related tasks and Epics
- https://github.com/neondatabase/neon/issues/2739
- On-demand Epic is closely related: https://github.com/neondatabase/neon/issues/2476
- https://github.com/neondatabase/neon/issues/2606
- https://github.com/neondatabase/neon/issues/987
- https://github.com/neondatabase/neon/issues/1083

**Comment by shanyp** [comment]
@SomeoneToIgnore @LizardWizzard  how is this one different from #2606

**Comment by SomeoneToIgnore** [comment]
I see https://github.com/neondatabase/neon/issues/2606 as a base for building some set of background tasks to check the timelines across the entire storage.

This one seems like a good base for pageserver internal consistency checks: checksums could be added for layers and pages and need a good design to fit them into current metadata.

**Comment by shanyp** [comment]
@stepashka this can be closed , no work planned here
