### ISSUE TITLE
Epic: OLAP perf tests

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2789]
## Motivation

Separation of storage and compute increases latency of page reads which is mostly visible of big scan queries. Set up infra to run them ans grafana dashboard with results.

We can start with TPC-H; database can be pre-filled manually; panels on dashboard can show time of each query.

**Comment by knizhnik** [comment]
Should we emulate network latency in this tests?
`tc qdisc add dev lo root handle 1:0 netem delay 1msec`
