### ISSUE TITLE
Deploy neon_broker

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#2805]
Deploy in k8s neon_broker replacing etcd from
https://github.com/neondatabase/neon/pull/2733

Features:
- it is stateless
- if failed, pod should be automatically recreated 
- it should be accessible from storage nodes, and only from them
- metrics should be collected
- logs should be collected

overall, expected to resemble
https://github.com/neondatabase/helm-charts/blob/main/charts/neon-proxy/templates/deployment.yaml

**Comment by zoete** [comment]
Can you elaborate on the following point?
`it should be accessible from storage nodes, and only from them`

**Comment by zoete** [comment]
Would there be a methods of accomplishing that not strictly on an infra level? Our approach wouldn't really be elegant or scalable.
