### ISSUE TITLE
run immediate compaction in task_mgr task // fix flaky `test_get_tenant_size_with_multiple_branches`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#2860]
Test failure from CI: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2854/release/3495948350/index.html#suites/d70040d097c5c7c438e421e0416d69ce/5314d4642ad7c0d/ from ` test_get_tenant_size_with_multiple_branches`:

```
AssertionError: assert not ['2022-11-18T10:19:33.924123Z ERROR compaction_loop{tenant_id=2aefe4bc42fa96fa849b620ce4d1faee}: Compaction failed, retrying in 2s: No such file or directory (os error 2)\n']
```
This looks like another instance of the race condition between GC and tenant detach, not this PR's fault. I restarted it.

_Originally posted by @hlinnaka in https://github.com/neondatabase/neon/issues/2854#issuecomment-1320081277_

**Comment by yeputons** [comment]
Another flaky run: https://github.com/neondatabase/neon/actions/runs/3499938636/jobs/5862189280
The only thing changed in the commit is documentation.

**Comment by arssher** [comment]
Likely same here
https://github.com/neondatabase/neon/actions/runs/3532459142/jobs/5927127195

**Comment by koivunej** [comment]
Has test_get_tenant_size_with_multiple_branches flakyness been triaged to be caused by this?

**Comment by petuhovskiy** [comment]
Another flaky run: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6530/8539801725/index.html#suites/d70040d097c5c7c438e421e0416d69ce/33205a89af7b4f40/

It looks like the test is flaky, but just a bit – it fails only several times per year.

**Comment by jcsp** [comment]
Issue described in OP is unlikely to still be an issue, since this code has changed a lot.
