### ISSUE TITLE
VIsualize performance tests run

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#2887]
I want a dashboard that shows how we're improving the performance.

Currently, only @knizhnik knows how to run a query that our customers provided with their sample data.

Why do I need this? Our goal is based on this predefined set and query.

**Comment by bayandin** [comment]
The ticket itself is about adding more perf test cases. And they will be automatically visualized in Grafana.

@vadim2404 do we want to compare Neon results with some other platforms or just collect them regularly to see a trend?

I haven't checked the data sample yet, but I guess it will look like https://github.com/neondatabase/neon/pull/2855

**Comment by vadim2404** [comment]
it's nice-to-have a reference number, but still, at this point we know this value — 4.5 seconds.
