### ISSUE TITLE
Automate RDS provisioning for testing

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#2900]
In the current setup of Nightly Benchmarks, we use preconfigured databases for Aurora Postgres and RDS Postgres. This scales neither horizontally (for running the same tests in parallel) nor vertically (for changing instance type).

I suggest we switch to auto-provisioning databases for testing with AWS CLI. And create a database in GitHub Actions.

**Comment by bayandin** [comment]
Last week:
- We have a terraform setup
- A script for fill-up the databases

This week:
- Merge PR: https://github.com/neondatabase/neon/pull/8682
- Restore projects

**Comment by Bodobolero** [comment]
We have now
- TF for RDS instances
- automatic restore for all reuse projects in _benchmarking_preparation.yml workflow (neon repo)
- all databases use pg16

Todo: delete remaining AWS aurora cluster in EU-West-1 - I am currently still using this to prepare another test (unrelated)

**Comment by Bodobolero** [comment]
Added neonvm controller bench in Azure region, findings

https://github.com/neondatabase/cloud/issues/16589
https://github.com/neondatabase/cloud/issues/16587
https://github.com/neondatabase/cloud/issues/16586

**Comment by bayandin** [comment]
All nightly benchmarks have been switched to auto-provisioned instanced. 
This issue is open because we still use the old Aurora setup for Ramp test preparation.

**Comment by bayandin** [comment]
The setup is automated.
Still using the old Aurora instance for different purposes.
