### ISSUE TITLE
Race conditions in timeline_delete

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2914]
Wouldn't we need to shut down the tasks of the timeline _after_ we transition it to `::Paused` state?

For example, the `"initial size calculation"` task doesn't use `task_mgr::is_shutdown_requested`, it just reacts to timeline state changes.

_Originally posted by @problame in https://github.com/neondatabase/neon/pull/2910#discussion_r1031457110_

**Comment by shanyp** [comment]
@problame did @LizardWizzard work handle this issue ?

**Comment by problame** [comment]
There is no `Paused` state anymore.
