### ISSUE TITLE
In `storage_sync2`: failed deletions because object doesn't exist should be considered success

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#2934]

**Comment by shanyp** [comment]
@LizardWizzard per your recent PR , this is not relevant as s3 API delete doesn't indicate when trying to delete a nonexistent object. @problame is it worth "ls the file" prior?

**Comment by LizardWizzard** [comment]
> per your recent PR , this is not relevant as s3 API delete doesn't indicate when trying to delete a nonexistent object

Correct

**Comment by arpad-m** [comment]
Hmm the [comment in delete_layer](https://github.com/neondatabase/neon/blob/1f151d03d8410f6fe87622ff0bb8901dbaf7875d/pageserver/src/tenant/remote_timeline_client/delete.rs#L24) still references this issue. I wonder if it made sense to change the comment with the information that S3 does not error when trying to delete nonexistent files already (and if the backing storage is not s3 but the file system, i suppose one can live with the error).

**Comment by shanyp** [comment]
yes this comment should be removed, the alternative is to always try to. "list" the object before is just a waist of resources

**Comment by LizardWizzard** [comment]
Note that our local fs storage has other behavior that is not consistent with real s3. For example it keeps empty "directories" while with real s3 you wont see prefixes that dont have objects in them
