### ISSUE TITLE
Blocking throughout `pageserver` in async contexts

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#2975]
During #2875 I hit an interesting deadlock, which is reproduced at [this branch](https://github.com/koivunej/neon/tree/deadlock-repro). I managed to find multiple "waker woken, but deadlock". The most interesting was:

A thread of `task_mgr::BACKGROUND_RUNTIME` was executing periodic compaction from [`pageserver::tenant_tasks`](https://github.com/koivunej/neon/blob/2211451461eb3dff3675fc39e2f9c9b5ab27649d/pageserver/src/tenant_tasks.rs#L72) while the same thread had previously executed the async walredo task. The thread became deadlocked on blocking [`flume::Receiver::recv`](https://github.com/koivunej/neon/blob/2211451461eb3dff3675fc39e2f9c9b5ab27649d/pageserver/src/walredo.rs#L1137) because the [async walredo task](https://github.com/koivunej/neon/blob/2211451461eb3dff3675fc39e2f9c9b5ab27649d/pageserver/src/walredo.rs#L762) was blocked on the same runtime worker thread, on its [LIFO slot](https://github.com/tokio-rs/tokio/blob/dea1cd49955ab5e9d041e9f1ed0c5f28e18246de/tokio/src/runtime/scheduler/multi_thread/worker.rs#L97). The async walredo task would have been the one to process the `Timeline::get` eventually.

I think the repro commit does have other deadlocks, but I failed to really understand them. Originally I suspected a thread being blocked on locking `Timeline::layer_removal_cs` have the async walredo task on it's LIFO slot, but haven't seen it now in `rr` at least.

<details><summary>More reproduction info</summary>

- branch has the `NEON_LOCAL_RECORD_COMMANDS="pageserver"` support if you want to try your hand at `rr` (closed #2958)
- used dev builds, `cargo build_testing`
- `./scripts/pytest --capture=no test_runner/regress/test_branch_and_gc.py::test_branch_and_gc`
    - I think this was already fixed but on the branch compaction runs nonstop

</details>

I don't think this is an issue of `tokio`, though they are working on making this LIFO slot stealable in the future. I think it's the issue of blocking the codebase. More precisely I think it's the many paths that are called from async context which forbid using async, like in the `deadlock-repro` branch.

Straight forward solution to this is to never block on tokio runtime threads. That is however difficult to implement and will likely come with some performance loss at least with the current tokio version we use. A "test case" I've used in the past to keep the blocking in check is to run the whole app within one `current_thread` runtime instead of multiple runtimes with multiple threads. We should be able to do this with the regression tests. I think it should be a long-term goal.

During #2875 I tried sprinkling `tokio::task::block_in_place` and `tokio::task::spawn_blocking` around. The use of `tokio::task::block_in_place` has the downside of making it impossible to aim for the `current_thread` flavored executor. Eventually tests passed, but it's difficult to estimate how complete a solution this is. In the course of the sprinkling, I used a [very rough tool](https://github.com/koivunej/strident-mutex) to help guide the process, but it's a prolonged process, didn't complete it.

**Comment by koivunej** [comment]
The `tokio::task::block_in_place` is basically not a solution or alternative because of https://github.com/tokio-rs/tokio/issues/5239 for `spawn_blocking`, at least until we get [capabilities](https://tmandry.gitlab.io/blog/posts/2021-12-21-context-capabilities/) but the proper support for those might come in sooner.

Still I think there's benefit to consider a single runtime with very few threads (1-2) and using for example 8 threads for blocking pool. We most likely don't need that much async code going on in the first place. Blocking pool will be utilized regardless with `block_in_place` so it might be used explicitly.

**Comment by jcsp** [comment]
This week:
- Async write operations 
- Avoid using spawn_blocking(block_on) because of the overhead of churning io_uring runtimes (while keeping it for prod until we cut over io_uring)

**Comment by problame** [comment]
A lot has happened since opening this issue.

Closing it as duplicate in favor of the two currently known remaining sources of executor stalling:

- https://github.com/neondatabase/neon/issues/4744
- https://github.com/neondatabase/neon/issues/6628
