### ISSUE TITLE
CI failure, when upload to S3 failed at first, but succeeded on retry

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2990]
Occasional failures to upload to S3 are expected, network issues happen. But our CI is very picky, and any failure to upload a file cause a test failure, even if the upload succeeds on retry. Here's one such instance:

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2987/debug/3595510051/index.html#suites/f9eba3cfdb71aa6e2b54f6466222829b/5ea80421bae22996/

```
AssertionError: assert not ["2022-12-01T19:20:54.791436Z ERROR remote_upload{tenant=2bf89cd16111e86ec4b036083b9fd99f timeline=16dd3647c7badea9756... (attempt 0): Failed to upload index part for '2bf89cd16111e86ec4b036083b9fd99f / 16dd3647c7badea9756fe1475b7f89b6'\n"]
```

Let's tone down the ERROR to INFO or DEBUG level for the first few retries, and only ERROR or WARN if it keeps failing for more than N times.

**Comment by arssher** [comment]
https://pipelines.actions.githubusercontent.com/serviceHosts/c6812ed7-bc42-44ce-8956-2c7f871e1175/_apis/pipelines/1/runs/18718/signedlogcontent/101?urlExpires=2022-12-03T05%3A13%3A44.1662417Z&urlSigningMethod=HMACV1&urlSignature=ASvp8qPkY2hm4m4H8npe6VkPeLpZSU4Fc4d6UVT0d5M%3D
one more time

**Comment by arssher** [comment]
and one more
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2733/debug/3604095026/index.html#suites/f9eba3cfdb71aa6e2b54f6466222829b/cde1b0a4146419d/
