### ISSUE TITLE
Timeout error during credentials request for s3 request

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3006]
## Steps to reproduce

No clear idea

## Expected result

No errors

## Actual result

```
022-12-03T13:17:32.391191Z ERROR remote_upload{tenant=X timeline=Y upload_task_id=2630}: failed to perform remote task UploadMetadata(lsn: 0/170E678), will retry (attempt 0): Failed to upload index part for 'X / Y'
Caused by:
    0: Failed to upload from '/storage/pageserver/data/tenants/X/timelines/Y/index_part.json' to storage path '"XXXtenants/X/timelines/Y/index_part.json"'
    1: failed to construct request: Failed to load credentials from the credentials provider: An error occurred while loading credentials: An IO error occurred communicating with IMDS: timeout: HTTP read timeout occurred after 10s
    2: Failed to load credentials from the credentials provider: An error occurred while loading credentials: An IO error occurred communicating with IMDS: timeout: HTTP read timeout occurred after 10s
```

## Environment

Staging PS4

## Logs, links
- 

Seen some errors in stress env. Note that the machine this errors comes from is about to be decomissioned.

cc @SomeoneToIgnore Likely originates from recent s3 library change

**Comment by LizardWizzard** [comment]
More context:

```
Failed to load credentials from the credentials provider: An error occurred while loading credentials: An IO error occurred communicating with IMDS: io error: connection error: Connection reset by peer (os error 104)
```

For some reason retries on our side do not help. It my be because client keeps old connection and doesnt try to reestablish it. We can try to reinitialize client on such errors.

Also there is a feature for configuring retry policy for auth requests, but it is not released yet

**Comment by LizardWizzard** [comment]
Happened on production.

**Comment by SomeoneToIgnore** [comment]
Yes, I'm generally not sure whether we should dig down to the roots of the issue, since IAM presumably has to go, since that will allows us more than x10 concurrent requests per second, which should be good for both on-demand downloads and regular work.

**Comment by SomeoneToIgnore** [comment]
Will be fixed with https://github.com/neondatabase/neon/issues/3118, let's close this?

**Comment by LizardWizzard** [comment]
Lets continue in #3118

**Comment by koivunej** [comment]
I had no idea of these issues before looking at the outage report. Would had linked this as well from the https://github.com/neondatabase/neon/pull/3128.
