### ISSUE TITLE
Pg version in safekeeper logs looks incorrect (140005)

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3016]
## Steps to reproduce

Found in logs

## Expected result

14 or 15

## Actual result

`INFO load_timeline{timeline=efd7bc147000bd5b9ae64ed843d09fd0}: setting pg_version to 140005`

## Environment

staging-sk-4

## Logs, links
-

**Comment by LizardWizzard** [comment]
I'm not sure, maybe this is just internal representation of the version number 14.5

**Comment by arssher** [comment]
Right, see `PG_VERSION_NUM` macro in `pg_config.h`.
