### ISSUE TITLE
Properly retry errors when connection from compute when tenant is Loading.

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3018]
We shouldn't wait in get_tenant

**Comment by hlinnaka** [comment]
I don't understand this issue. Where do we wait that we shouldn't? @problame do you remember the context?

**Comment by LizardWizzard** [comment]
> during tenant / timeline delete.

Also it was the case when we restarted pageserver and compute request came earlier than tenant finished loading. And it didnt retry the request/reconnect after failure
