### ISSUE TITLE
ERROR:  column "datlastsysoid" does not exist

### ISSUE THREAD

**Issue by dimitrios1988** [neondatabase/neon#3021]
## Steps to reproduce
Connect to postgresql database using Navicat

## Expected result
See the list of tables

## Actual result
A popup appears with the following message

ERROR:  column "datlastsysoid" does not exist
LINE 1: SELECT DISTINCT datlastsysoid FROM pg_database
                        ^

## Environment
Database Manager: Navicat Premium 15.0.30
OS: Linux Manjaro

## Logs, links
-

**Comment by hlinnaka** [comment]
The `datlastsysoid` field was removed in PostgreSQL 15. Looks like navicat needs to be updated to not use that column anymore.

(see upstream commit [ab4fd4f868edb4a59302db52857f4fe7c8d81f42](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=ab4fd4f868edb4a59302db52857f4fe7c8d81f42)).
