### ISSUE TITLE
unexpected layer filename in remote storage: A-B__C.0.old

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3024]
## Steps to reproduce

Found for old project created on staging in May 2022

## Expected result

No error during reconcile with remote, and probably no such files in remote storage

## Actual result
```
2022-12-07T11:58:49.445040Z ERROR could not load tenant 46eb16d232d1e747af7b59e64b4b39a8: load local timeline 35765cf4546bea869078c6f1082f8ed9
Caused by:
    0: failed to reconcile with remote
    1: unexpected layer filename in remote storage: 000000067F000040020000C0AE0000014000-030000000000000000000000000000000002__0000001145498F20.0.old
```

And indeed this file (and a bunch of others with similar `.old` suffix are included in the index file and exist as files

## Environment

staging

## Logs, links
- 

First we should check that we dont upload such files anymore. For dealing with existing files I think we have two options. Skip such files during sync (which can be ok if thats really old thing) or completely fix it with some migration that removes such files from index and from the storage. Will inspect how many of those we have in other places  

cc @hlinnaka @problame

**Comment by problame** [comment]
Is this `.old` file referenced from the `IndexPart` ?

**Comment by SomeoneToIgnore** [comment]
I think, that could be a combination of https://github.com/neondatabase/neon/blob/a46a81b5cbb0f4b9022152c609428247e288804d/pageserver/src/tenant/timeline.rs#L2757-L2759, some abrupt restart and a logic in remote storage that considered every file around as layer on start and attempted to upload it.

**Comment by LizardWizzard** [comment]
> For the long-term solution, what if we attempt to fix this with https://github.com/neondatabase/neon/pull/2993#issuecomment-1337126725 ?

Looks good to me.

> Is this .old file referenced from the IndexPart ?

Yes

**Comment by problame** [comment]
Here's code from before `storage_sync2` that caused the `.old` files to be uploaded & become part of `IndexPart`

https://github.com/neondatabase/neon/blob/c7093545794e5a1072fa358d1aa38c87031bce7e/pageserver/src/storage_sync.rs#L1467-L1489

During download, these files would be downloaded as well, but the code that loads the layer map would then ignore it.

:+1: if you agree with this root-cause analysis.

**Comment by koivunej** [comment]
Re: root-cause analysis, happened to look since that was one of the first commit I wrote here. I don't think I managed to create a bug there, but it would appear to be that we never filtered out the rotated files when collecting timeline files: https://github.com/neondatabase/neon/blob/c7093545794e5a1072fa358d1aa38c87031bce7e/pageserver/src/tenant_mgr.rs#L693-L699

Now filtering is done first by `Timeline::load_layer_map` which is now used as a basis for "local files" in `Timeline::reconcile_with_remote`. `Timeline::load_layer_map` knows about the `.{nth_backup}.old` naming strategy so the files are just ignored. I am unsure how were those kind of files produced in the first place.

**Comment by LizardWizzard** [comment]
>  don't think I managed to create a bug there

Yep, I agree, I think we always had this problem and it originated from decoupling we had previously. I mean the strategy that sync module lives separately and treats layers as opaque files

**Comment by LizardWizzard** [comment]
Yes we do

**Comment by LizardWizzard** [comment]
Leaving this open until we clean up the files in remote storage for existing environments

**Comment by shanyp** [comment]
Done by the older layer removal
