### ISSUE TITLE
Epic: Restore from back-up

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3063]
## Motivation
The user must be able to restore the database to some state in the past. For instance, several minutes ago or a week ago. 

## Tasks
- [ ]

## Other related tasks and Epics
-

**Comment by koivunej** [comment]
How is this different from PITR in #3064?

**Comment by vadim2404** [comment]
It can be the same, finally. In my thoughts, we need to provide such mechanics to our customers.

Talking about the horizon, I think that window in 2-3 days will cover all our needs. Usually, if an emergency occurs, we need to take the last successful back-up before destructive action.

**Comment by shanyp** [comment]
Merging this one with #3064

**Comment by stepashka** [comment]
will delete in favor of having this in the roadmap
there we will define the specific things we need from the storage and log them as Epics
