### ISSUE TITLE
Epic: Read-only replicas

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3065]
## Motivation
Users must be able to start reading replicas on top of existing storage to execute such queries. 

## Tasks
- [ ]

## Other related tasks and Epics
- https://github.com/neondatabase/neon/issues/1952
- https://github.com/neondatabase/neon/issues/769

**Comment by LizardWizzard** [comment]
Added a bunch of related issues. It may be a dup of #769

**Comment by vadim2404** [comment]
Duplicates #769
