### ISSUE TITLE
Epic: history and size limits per branch

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3067]
## Motivation
As a user, I want to disable history for some branches
As a user, I want to set up a size limits for the history per branch

## Tasks
- [ ]

## Other related tasks and Epics
-

**Comment by koivunej** [comment]
> Disable history

I don't think it's feasible to try not to have *any* history. Perhaps this as a user story would be `As a user I want branch $X to cost me zero for the history`...?

Was thinking that we already have `gc_horizon` and `pitr_interval` but we don't even have a concept of per-timeline configuration settings so now I understand this issue.

**Comment by vadim2404** [comment]
You're right. If we need to keep a small bunch of history for our internal, we will keep it. From customers' perspective, it should look like, they don't care about it and don't overpay for that stuff.

**Comment by stepashka** [comment]
this will be closed in favor of roadmap item that we have nearly shipped: https://github.com/neondatabase/neon_roadmap/issues/41
(storage part is done already, the UI part is awaiting release ATM of writing)
