### ISSUE TITLE
Merge the ways to handle with layer formats

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#3072]
We have [`IndexLayerMetadata`](https://github.com/neondatabase/neon/blob/d1edc8aa00eeebbc20a5839c614c7f4c541f4b97/pageserver/src/storage_sync2/index.rs#L139) and `IndexPart` to manage similar things: remote storage file format.

We need to think of a unified, versioned way to handle this format.

See https://github.com/neondatabase/neon/pull/3026#discussion_r1046105083 for the context

**Comment by LizardWizzard** [comment]
I would clarify. Its is only aboit index file format. Not the format for files themselves. Format for data files is the same as local one (since these are the same file essentially)
