### ISSUE TITLE
Epic: Support pg_graphql extension

### ISSUE THREAD

**Issue by seymourisdead** [neondatabase/neon#3096]
## Motivation
The extension allows using graphql without third-party services.
Documentation can be found [here](https://supabase.github.io/pg_graphql/)

## DoD
Users can use pg_graphql with Neon

## Tasks
- [ ] support pg_graphql extension

## Other related tasks, Epics, conversations
- https://neondb.slack.com/archives/C036U0GRMRB/p1670944938064859

**Comment by nicksrandall** [comment]
This extension has reached 1.0 status and is considered stable. It would be great to see support for it with neon!

**Comment by nicksrandall** [comment]
Would maintainers be open to a PR that added this extension? I’m willing to give it a shot.

**Comment by vadim2404** [comment]
@nicksrandall 

The extension is available on production!
