### ISSUE TITLE
[NEON_SMGR] failed to send page request 

### ISSUE THREAD

**Issue by commandodev** [neondatabase/neon#3097]
## Steps to reproduce

My neon instance has just started failing with the above error. I can't select or insert into the database and I also see
![image](https://user-images.githubusercontent.com/87764/207632819-759150e5-9115-481d-a39f-08bb196c7748.png)

In the console

Project is `jolly-hill-931589`

**Comment by kelvich** [comment]
Hey! There was an issue with our pageserver -- we've fixed it already. Sorry for the inconvenience.

P.S.

It is better to use support form about issues with our service -- we have a better reaction time over there. We use Github mostly for development tasks.
