### ISSUE TITLE
gc_loop starting on 0 timelines is wrong

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3107]
## Steps to reproduce

the tenant was in broken state and I `ignore` -> `load` it. And this appeared

## Expected result

starting on 1 timeline

## Actual result

```
INFO gc_loop{tenant_id=59b8194a8b0c4021e1e68792dcde69c7}: starting on 0 timelines
INFO compaction_loop{tenant_id=59b8194a8b0c4021e1e68792dcde69c7}:compact_timeline{timeline=ac40625fd35bff607a1c5ad95984fce0}: starting op: Barrier
INFO compaction_loop{tenant_id=59b8194a8b0c4021e1e68792dcde69c7}:compact_timeline{timeline=ac40625fd35bff607a1c5ad95984fce0}: waiting for upload ops to complete
INFO compaction_loop{tenant_id=59b8194a8b0c4021e1e68792dcde69c7}:compact_timeline{timeline=ac40625fd35bff607a1c5ad95984fce0}: starting op: UploadMetadata(lsn: 0/1AAE150) 
INFO wal_connection_manager{tenant=59b8194a8b0c4021e1e68792dcde69c7 timeline=ac40625fd35bff607a1c5ad95984fce0}: Subscribed for broker timeline updates
```

It says `starting on 0 timelines` while there is a timeline

## Environment

Prod

## Logs, links
-

**Comment by problame** [comment]
Why are you expecting `1`? If `refresh_gc_info_internal` returns an empty vec, we log 0.
Would you want a different log message in that case?

Or were you expecting that at least one timeline needs GC?

**Comment by LizardWizzard** [comment]
I expected that it logs number of all timelines, if we log only number of timelines that need gc then lets just change the message. If there are no timelines I would expect "Nothing to gc", or "X timelines need gc, starting" or something similar
