### ISSUE TITLE
Add broker metrics, healthchecks, alerts, log browser and dashboards

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#3117]
Broker is vital for WAL streaming, it is important to know that it has enough memory and CPU to operate, same as the other important metrics that it exposes

**Comment by arssher** [comment]
https://neonprod.grafana.net/d/e15c3948-831f-4bd2-a475-3ca3b3e5b02e/storage-broker-metrics?orgId=1
