### ISSUE TITLE
The connection string option `&search_path=custom` doesn't work

### ISSUE THREAD

**Issue by frederikhors** [neondatabase/neon#3148]
I'm trying neon for the first time today. Congratulations for the amazing idea!

I created a new DB and a new owner user.

With these credentials I connect to it and create a new schema called "`custom`".

I launch my two apps, the first uses "`public`" schema and the other one the "`custom`" one.

First connection string:

`DB_CONNECTION_STRING_PUBLIC` = `postgres://<USER_NAME>:<USER_PASS>@ep-project-name-012345.eu-central-1.aws.neon.tech/<DB_NAME>?sslmode=verify-full`

Second connection string (for the `custom` schema) (note the `&search_path=custom`):

`DB_CONNECTION_STRING_PUBLIC` = `postgres://<USER_NAME>:<USER_PASS>@ep-project-name-012345.eu-central-1.aws.neon.tech/<DB_NAME>?sslmode=verify-full&search_path=custom`

The first works good. **The second one nope!**

It seems that with or without `search_path=custom` it's the same: it always uses the `public` schema.

Obviously I'm using EXACTLY the same DB schema, the same apps, ALL THE SAME on other DBs too (and it works).

Maybe neon has some problem with schemas?

**Comment by funbringer** [comment]
Hi! Thanks for reporting this. This is actually a duplicate for https://github.com/neondatabase/neon/issues/1287. Long story short, due to current implementation our proxy service doesn't forward all parameters. This is being reworked at the moment.

**Comment by funbringer** [comment]
Sure! I'll close that issue once the fix is available in prod environment.
