### ISSUE TITLE
Prisma docs: creating a second account for a shadow db, instead of just creating a second db.

### ISSUE THREAD

**Issue by samhwang** [neondatabase/neon#3196]
Hi Neon team,

First of all, sorry for not following the template. This is not a software bug, but more like docs issue, and I didn't see a template for it 😅 .

In the Shadow Database section of the Prisma connection docs, it says:

> To configure a shadow database:
>
> 1. Create a second Neon project and make sure to copy the connection string.

This is a problem because:

- The current Free Tier only allows 1 project per account, so a dev following this doc cannot go on.
  ![Screen Shot 2022-12-23 at 3 33 31 pm](https://user-images.githubusercontent.com/4188758/209271435-76795c2d-f778-48f3-a8aa-6ba19e5bbbf6.png)
- A project can host multiple databases. Surely this can be done with just creating a new database inside the same project. I just did on mine and Prisma doesn't complain about a shadow DB anymore. 

## Links
- [Prisma connection docs](https://neon.tech/docs/guides/prisma/#configure-a-shadow-database-for-prisma-migrate)

**Comment by danieltprice** [comment]
Thank you for reporting this issue @samhwang. The documentation has been updated.
