### ISSUE TITLE
test_ondemand_download_timetravel is flaky

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#3209]
```
2022-12-27T12:57:59.9556663Z =================================== FAILURES ===================================
2022-12-27T12:57:59.9557129Z __________________ test_ondemand_download_timetravel[real_s3] __________________
2022-12-27T12:57:59.9558063Z [gw3] linux -- Python 3.9.2 /github/home/.cache/pypoetry/virtualenvs/neon-_pxWMzVK-py3.9/bin/python
2022-12-27T12:57:59.9558626Z test_runner/regress/test_ondemand_download.py:231: in test_ondemand_download_timetravel
2022-12-27T12:57:59.9559324Z     assert filled_current_physical == get_api_current_physical_size()
2022-12-27T12:57:59.9559726Z E   assert 161538048 == 152928256
2022-12-27T12:57:59.9560028Z E     +161538048
2022-12-27T12:57:59.9560432Z E     -152928256
```

https://github.com/neondatabase/neon/actions/runs/3787456343/jobs/6439377970

**Comment by yeputons** [comment]
Another one: https://github.com/neondatabase/neon/actions/runs/3797187823/jobs/6457976754

**Comment by koivunej** [comment]
Another: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3377/debug/3967060688/index.html#suites/b97efae3a617afb71cb8142f5afa5224/f7f29803cab5953d/

**Comment by arssher** [comment]
One more like in the last comment:
```
Exception: timed out while waiting for remote_consistent_lsn to reach 0/4307970, was 0/4307938
```

**Comment by koivunej** [comment]
https://neon-github-public-dev.s3.amazonaws.com/reports/main/release/4231954076/index.html#suites/b97efae3a617afb71cb8142f5afa5224/98a3664506a883/ was not fixed by #3616.

**Comment by hlinnaka** [comment]
> https://neon-github-public-dev.s3.amazonaws.com/reports/main/release/4231954076/index.html#suites/b97efae3a617afb71cb8142f5afa5224/98a3664506a883/ was not fixed by #3616:
> 
> ```
> Exception: timed out while waiting for remote_consistent_lsn to reach 0/42F03E0, was 0/42F03A8
> ```
> 
> It is quite curious, how could 20s timeout not be enough. Looking at pageserver log it is just standing idle.
> 
> Does this mean that the lsn used here is just wrong:
> 
> ```
> def wait_for_sk_commit_lsn_to_reach_remote_storage(
>     tenant_id: TenantId,
>     timeline_id: TimelineId,
>     safekeepers: List[Safekeeper],
>     pageserver: NeonPageserver,
> ):
>     lsn = wait_for_sk_commit_lsn_to_arrive_at_pageserver_last_record_lsn(
>         tenant_id, timeline_id, safekeepers, pageserver
>     )
> ```
> 
> Why is it waited like this at all, instead of using the wait_for_last_flush_lsn?

The test stops postgres before calling `wait_for_sk_commit_lsn_to_arrive_at_pageserver_last_record_lsn`. `wait_for_last_flush_lsn` runs a query on postgres to get the last flush LSN, so it doesn't work if postgres has already been stopped.

> Before calling this wait method (reproduced above) there is checkpointing ... This sounds a bit like the fix from #3629 could help here (shutting down pg before last checkpoint). Though, this is very complex test and I guess many aren't interested in touching it.
> 
> @hlinnaka any ideas?

Hmm, the test already stops postgres, before calling wait_for_sk_commit_lsn_to_arrive_at_pageserver_last_record_lsn(). No new WAL can be generated after postgres has been stopped. I don't understand why it's flaky.

**Comment by koivunej** [comment]
> Hmm, the test already stops postgres, before calling wait_for_sk_commit_lsn_to_arrive_at_pageserver_last_record_lsn(). No new WAL can be generated after postgres has been stopped. I don't understand why it's flaky.

Ok, I completely missed this. Well, I think my idea (even though flawed as a question) is still valid, lets see a few PR runs for this. Demonstrating my idea on https://github.com/neondatabase/neon/pull/3695/commits/e723a8690aec7c4c55473bd4d8db9c6fb6ce3ab5 about stopping pg before last checkpoint, running tests a few times.

**Comment by koivunej** [comment]
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3696/release/4253557268/index.html#suites/b97efae3a617afb71cb8142f5afa5224/f947fbf5dd488147/

```
Exception: timed out while waiting for remote_consistent_lsn to reach 0/42F4498, was 0/42F4460
```

**Comment by hlinnaka** [comment]
Hit this again: https://github.com/neondatabase/neon/pull/3886.

Here's a theory: The test does this:

1. write a bunch of data
2. stop endpoint
3. call wait_for_sk_commit_lsn_to_reach_remote_storage

I think it's possible that when the endpoint is stopped, the last piece of WAL has only been flushed to 2 out of the 3 safekeepers. One safekeeper has not received it yet, and after the endpoint is stopped, it never will. If that happens to be the safekeeper that the pageserver is connected to, the pageserver will not receive the WAL either.

There is logic in the pageserver to switch to a different safekeeper, if the safekeeper it's connected to lags behind the others. But it's not instant, there are some delays in the walreceiver connection manager before it reacts. wait_for_sk_commit_lsn_to_reach_remote_storage() only waits for 10 seconds, which might not be enough.

So perhaps this flakiness would go away if we just make wait_for_sk_commit_lsn_to_reach_remote_storage wait longer. Or perform "sync safekeepers" operation before stopping the compute.

@SomeoneToIgnore, you're more familiar with the walreceiver loop, does that theory sounds plausible to you?

**Comment by arssher** [comment]
There is single safekeeper in this test, so it is not plausible (also, default switch to another safekeeper timeout is 3s). Taking a closer look, `wait_for_sk_commit_lsn_to_reach_remote_storage` usage is probably broken in another sense: commit_lsn is updated at safekeepers asynchronously -- compute can commit something and get terminated before communicating updated commit_lsn to safekeepers, so likely this function doesn't do what authors expected.

However, this is not an issue here, as due to previous `wait_for_last_record_lsn` data definitely reached the safekeeper. I think the reason is different: in the short window between `client.timeline_checkpoint(tenant_id, timeline_id)` on pageserver and `env.endpoints.stop_all()` terminating the compute something slips into WAL (e.g. xl_running_xacts which postgres writes each 15 seconds) and manages to get committed. It is then streamed to pageserver, but since it is farther than the manual checkpoint position, it won't get checkpointed/uploaded to s3 until next checkpoint -- there is timeout for that, but it is large (10m AFAIR). We should instead wait only for `pg_current_wal_flush_lsn` value which existed in pageserver before the manual checkpoint started. I'll make a patch.

**Comment by arssher** [comment]
Hm, I overlooked that `wait_for_sk_commit_lsn_to_reach_remote_storage` also makes checkpoint. It makes issue less probable, however in theory still possible.

**Comment by koivunej** [comment]
Now it's consistently failing on manual checkpoint: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4062/debug/4794578284/index.html#suites/b97efae3a617afb71cb8142f5afa5224/98b4532b0b7bfa49/

I'll be looking into this, as it has now happened 4-5 times in row.

**Comment by koivunej** [comment]
Unless this was dropped from the latest release, it just reproduced:

- https://neon-github-public-dev.s3.amazonaws.com/reports/release/debug/4832365688/index.html#suites/b97efae3a617afb71cb8142f5afa5224/c6021b7503b788a0/
- https://neon-github-public-dev.s3.amazonaws.com/reports/release/release/4832365688/index.html#suites/b97efae3a617afb71cb8142f5afa5224/310f152ec857473e/

Both hit the assert on the same line:

```
test_runner/regress/test_ondemand_download.py:246: in test_ondemand_download_timetravel
    assert filled_current_physical == get_api_current_physical_size()
E   assert 195174400 == 195665920
E     +195174400
E     -195665920
```

**Comment by koivunej** [comment]
The assert has changed, so I created a new issue instead.
