### ISSUE TITLE
Epic: Improve page server logging story

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3218]
## Motivation

Per this discussion started by [@lassizci](https://neondb.slack.com/archives/C033RQ5SPDH/p1672234941320819)  and [@kelvich ](https://neondb.slack.com/archives/C033RQ5SPDH/p1672239384427269?thread_ts=1672234941.320819&cid=C033RQ5SPDH) 
Pageserver creates ~7.5M lines of log at INFO level every hour. Size wise talking about 1.45GB/hour

## DoD
A concise log story for pageserver providing necessary breadcrumbs for actual issues and less verbose in normal operation

## Implementation ideas
https://docs.google.com/document/d/1i4yb102lrZgnKOU7sjKAf4zWXQxdUbU4OrkIDZSHj7M/edit

- Observability of remote storage - metrics
- Request context - missing  (management operations are ok for adding, might be costly for non user operations)
- Many issues arise with string formatting, need to come up with a solution (maybe ETW way)
- Move to collect bread crumbs, and only log them in case of an error
- Add the ability to change log level, per component dynamically, 
- Llvm xray, dynamic instrumentation framework, enable/disable  (https://internals.rust-lang.org/t/pre-rfc-xray-instrumentation-support/17473) 
- support dynamically per Timeline tracing on/off 
- Go over lassi’s noisy messages grafana and flash out the ones that cause most of the noise 
- In the future alert for over quota logs /' alerts over exceeding Errors/Warns  
- Deduplication of trace messages. 
- Use variables for log messages, and not string formatting 

## Tasks

- [x] https://github.com/neondatabase/neon/issues/3114
- [x] https://github.com/neondatabase/neon/pull/3227
- [x] #3253 
- [x] #3314 
- [x] #3337 
- [x] #3338 
- [x] #3339
- [x] #3340 
- [x] #3341 
- [x] #3342 
- [x] #3343 
- [x] #3344 
- [x] #3346 
- [x] #3347 
- [x] #3372 

## Other related tasks and Epics
-

**Comment by kelvich** [comment]
Would also super useful to have:
* per-module tags on logs and ability to change it enforce log level per module in a runtime, e.g. though http api.
* ability to show all logs for specific tenant in runtime

depending on complexity that could be done now or later

**Comment by shanyp** [comment]
the per module logging was moved to epic : #3547
