### ISSUE TITLE
DROP ROLE statements are rolled back at startup

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#3279]
Spotted while reading the code:

In `handle_role_deletions` (https://github.com/neondatabase/neon/blob/main/compute_tools/src/spec.rs#L213), we create a transaction and run `DROP ROLE IF EXISTS` statements, but but the transaction is never committed. Which means that it is always implicitly rolled back.

**Comment by ololobus** [comment]
Fixed by https://github.com/neondatabase/neon/commit/df42213dbb5958a50cb6a80743b69d9b50836507
