### ISSUE TITLE
On demand download storage release

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3287]
- [x]  Re test in Staging of detach/attach of a Page server
 - [x] Prepare script to force all layer download @problame 
   - of all attached tenants
   - of a single tenant
   - of a single timeline
 - [x]  Create a release candidate (merging into release branch) @problame 
   - https://github.com/neondatabase/neon/pull/3301
 - [x]  Release into one small region (Singapore) and test detach/attach (*)
    - In case of failure, trigger the "download all layers" endpoint 
    - Restore to previous version
    - @SergeyMelnikov will implement Approval stage in GH actions release workflow for this
 - [ ] Validating in small region
   - [ ] The on demand download relevant metrics , 
   - [ ] Verify the logs were toned down (https://github.com/neondatabase/neon/pull/3227) 
 - [ ] Let console run some additional `check_availability` ops 
 - [ ]  Release to ROW

**Comment by hlinnaka** [comment]
>  Release to ROW

What is ROW?

**Comment by shanyp** [comment]
Rest of the world

**Comment by shanyp** [comment]
done
