### ISSUE TITLE
Follow up on un expected on demand download action after release 

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3314]
#3440

## Steps to reproduce
https://gist.github.com/problame/4599b7aeaa305729120685509cd8342a

See https://neondb.slack.com/archives/C03H1K0PGKH/p1673384612371789?thread_ts=1673258419.437079&cid=C03H1K0PGKH

## Logs, links
-

**Comment by problame** [comment]
Proper write-up with root cause analysis in https://github.com/neondatabase/neon/issues/3369
