### ISSUE TITLE
walreceiver: lifecycle traced events without any context

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3330]
Noted while watching the production logs on `zenith-1-ps-2`, because of an ongoing cleanup we now find randomly spaced plain `timestamp INFO Connection cancelled` which cannot be directly correlated to any timeline from https://github.com/neondatabase/neon/blob/16baa91b2b817eea20a0672ef237c11276b01973/pageserver/src/walreceiver/walreceiver_connection.rs#L121

Right above previous callsite is similar `timestamp INFO Walreceiver db connection closed`, which also appears in logs: https://github.com/neondatabase/neon/blob/16baa91b2b817eea20a0672ef237c11276b01973/pageserver/src/walreceiver/walreceiver_connection.rs#L113

Not saying these cannot be useful, but they need more context, but perhaps their overall usefulness should be considered.

Looking around however, in the same scope of `handle_walreceiver_connection` we have access to `timeline` and `wal_source_connconf`, so we should be able to add context by using `#[instrument(...)]` and propagating that at to the `task_mgr::spawn`'d future which will run both `connection` and be the context for the two lifecycle events.

It might be this is on already someone's list so this issue can be closed.

Cc: #3218

**Comment by shanyp** [comment]
@koivunej was this addressed by wal_reciever PR that you merged?

**Comment by SomeoneToIgnore** [comment]
https://github.com/neondatabase/neon/pull/4090 was not supposed to address this issue, unless done accidentally.

**Comment by koivunej** [comment]
Agreed, it was not supposed to be closed.
