### ISSUE TITLE
Image layer files with LSNs from the future

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3369]
When we rolled out on-demand download last week, we did not expect any on-demand downloads to happen after deployment.
The reason is that we don't have layer eviction yet, so for all layer files in existence, we assumed that precisely one
of the following cases is true:

* layer file exists just on pageserver
* layer file exists on pageserver and in remote
    * "existence in remote" := layer file object exists, and is referenced by remote's `index_part.json`

That assumption holds, but there can still be on-demand downloads if we ~~delete~~ rename-to-backup a layer file because its LSN is greater than disk_consistent_lsn.
We hit that situation during the deployment, and the following is the result of investigating it:

## What Happened - Reconstructed From Logs

The line that struck us was

```
pageserver-1.ap-southeast-1.aws.neon.tech 2023-01-10T17:02:11.502053Z  INFO download complete: /storage/pageserver/data/tenants/5f168efb076945599798deed108a41f2/timelines/dad195ba03db90056b7e392dbfa58212/000000000000000000000000000000000000-030000000000000000000000000000000002__0000000003D26910
```

What caused this layer download?
Checking for the tenant UUID in the console reveals that the tenant was created on Nov 05.
Going through Grafana logs since then (painful, since max query range is 720h) and filtering for tenant's ID and the layer file name reveals the following log lines (larger query: https://neonprod.grafana.net/goto/LmcsV124k?orgId=1 ):

```
2022-12-30T10:21:49.043055Z  INFO compaction_loop{tenant_id=5f168efb076945599798deed108a41f2}:compact_timeline{timeline=dad195ba03db90056b7e392dbfa58212}: new image layer /storage/pageserver/data/tenants/5f168efb076945599798deed108a41f2/timelines/dad195ba03db90056b7e392dbfa58212/000000000000000000000000000000000000-030000000000000000000000000000000002__0000000003D26910.ZTyocmur.___temp
2022-12-30T10:21:50.246940Z  INFO compaction_loop{tenant_id=5f168efb076945599798deed108a41f2}:compact_timeline{timeline=dad195ba03db90056b7e392dbfa58212}: scheduled layer file upload 000000000000000000000000000000000000-030000000000000000000000000000000002__0000000003D26910
...
2022-12-30T11:55:41.939132Z  INFO version: git-env:125381eae7802d487eb0c8b616ee5de97091478e failpoints: true, features: []
...
2022-12-30T11:55:43.214167Z  WARN load{tenant_id=5f168efb076945599798deed108a41f2}:load_local_timeline{timeline_id=dad195ba03db90056b7e392dbfa58212}: found future image layer 000000000000000000000000000000000000-030000000000000000000000000000000002__0000000003D26910 on timeline dad195ba03db90056b7e392dbfa58212 disk_consistent_lsn is 0/3D267F0
2022-12-30T11:55:43.239250Z  INFO load{tenant_id=5f168efb076945599798deed108a41f2}:load_local_timeline{timeline_id=dad195ba03db90056b7e392dbfa58212}:reconcile_with_remote: remote layer does not exist locally, downloading it now: 000000000000000000000000000000000000-030000000000000000000000000000000002__0000000003D26910
2022-12-30T11:55:43.239263Z  WARN load{tenant_id=5f168efb076945599798deed108a41f2}:load_local_timeline{timeline_id=dad195ba03db90056b7e392dbfa58212}:reconcile_with_remote: found future image layer 000000000000000000000000000000000000-030000000000000000000000000000000002__0000000003D26910 on timeline dad195ba03db90056b7e392dbfa58212 remote_consistent_lsn is 0/3D267F0
```

What do these log lines mean?

- The image layer file was written by compaction at `2022-12-30T10:21:49.043055Z`
- One second after, it was scheduled for upload.
- Pageserver was restarted at `2022-12-30T11:55:41.939132Z` with a new software version (storage_sync2)
- As part of startup, pageserver ignores the local image layer file (`found future image layer`)
- The image layer is present in the `index_part.json`, so, `load_local_timeline` ~~downloads it as part of `reconcile_with_remote`~~ it skips in `download_missing` (`reconcile_with_remote: found future image layer`)
- So, the image layer wasn't part of the LayerMap after the restart.
- But it's still in the `index_part.json`.

So, when we upgraded pageserver to on-demand download on `2023-01-10 17:01:38`, the image layer was still in the `index_part.json`.
We didn't skip it this time because disk_consistent_lsn moved forward since the last pageserver restart on 2022-12-30.
Then compaction on-demand downloaded the layer because it was in the layer map.

Logs from on-demand download deployment that prove this: https://neonprod.grafana.net/goto/RNdK4WT4k?orgId=1

## The Root Cause: Why Did This Image Layer From The Future Exist In The First Place?

Above, we've reconstructed what happened.

But we have not yet answered **why** that image layer with LSN greater than `disk_consistent_lsn` existed in the first place.
Is there a bug here?

The following is the summary of this ([internal Slack thread](https://neondb.slack.com/archives/C03H1K0PGKH/p1673384612371789?thread_ts=1673258419.437079&cid=C03H1K0PGKH)).

The image layer file was uploaded, but the `disk_consistent_lsn` was not updated, neither on the pageserver's local disk nor in S3.
How did that happen?

Look at the code as it was on 2022-12-30 after the restart (commit d8b5e3b88d).
The following happened:

* `Timeline::compact` calls `create_image_layers`, with `self.get_last_record_lsn`. That LSN can be larger than `disk_consistent_lsn`.
* It then calls `schedule_layer_file_upload` for any newly created image layers.
* Let's assume that our image layer was created like this and that its LSN is greater than `disk_consistent_lsn`.
* `Timeline::compact` proceeds with `compact_level0`. It doesn't have any work to do, if there are no level0 files to compact. But in any case, it calls `schedule_layer_file_deletion`, with an empty set of files,
* `schedule_layer_file_deletion` uploads an updated index file. The disk_consistent_lsn in the uploaded index file **is not updated**, only the list of files.

Note **what does not happen** here: there are no calls to flush the in-memory layers or to update the disk_consistent_lsn.
So now we have an image file present locally, in S3, and in index_part.json, that is higher than the disk_consistent_lsn in the local or remote metadata file.

Note that we cannot simply update the disk_consistent_lsn value just because we wrote out an image layer.
The reason is that the new image layer does not necessarily cover the entire key range of the in-memory and/or frozen delta layers.

## What To Do About This?

The situation is generally harmless.

The only semi-accute problem is that we're renaming-to-backup the image layer file on every pageserver restart and then re-download it in compaction. The renamed-to-backup layer files will consume more and more disk space. All of this stops as soon as disk_consistent_lsn covers the image layer's LSN.

However, the situation is weird and unexpected, so we should fix it.
Thoughts from the slack thread:

- Perhaps we should call `flush_frozen_layers_and_wait` in `Timeline::compact` if we created any image layers.
  At first I (Heikki) thought that this behavior was changed in https://github.com/neondatabase/neon/pull/3149, but nope, we still don't force a flush and don't update disk_consistent_lsn as part of compaction.

- The "level 0 compaction" of delta layers operates on historic layers (i.e., layers up to `disk_consistent_lsn`).
  But image layer creation uses `last_record_lsn`.
  Both operations happen as part of `Timeline::compact`.
  But really, they are independent of each other.

## Action Items:

TBD

**Comment by hlinnaka** [comment]
I ran into this in the CI: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4310/5058734799/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/b937019b302dcfa/
