### ISSUE TITLE
`timeline_details_handler` and friends fail with `NotFound` during pageserver restart

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3373]
During pageserver restart, there is a window in which we already opened the management API for business, but the tenant / the timeline is still in `Loading` state.
See these logs from the latest us-east-2 deploy as an example: https://neonprod.grafana.net/goto/-1AiZnoVz?orgId=1

In practice, this results in a bunch of `NotFound` errors whenever we restart the pageserver.

There are two problems with this:

1. we don't want ERROR log messages simply because we're restarting the pageserver. `Loading` is an expected state, it shouldn't cause ERROR log messages.
2. clients, e.g., a future control plane, that automatically migrates tenants might do stupid things when it gets the NotFound error, e.g., assume that the tenant is truly not present on the pageserver, and attach the tenant to a different pageserver. 

Adding this as part of the pageserver logging story epic, but cc'ing @LizardWizzard as well since he's involved with migration.

**Comment by koivunej** [comment]
Noted that these are logged with full stacktrace whenever before a tenant is created as well. Made me think of adding an "intention" to the request, as in "this is just a sanity check to make sure the generated uuid is good", so we'd know to not log at least those as error level messages.

**Comment by LizardWizzard** [comment]
Hmm, detail should return what is available without errors. If we have a tenant/timeline we must return something other than NotFound. 

Theoretically pageserver may not know about certain timelines if they exist only on remote, but this is a legitimate NotFound case

**Comment by jcsp** [comment]
Timeline detail requests now do a wait-for-active, so I think it's likely this issue is gone.
