### ISSUE TITLE
Couldn't start compute

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3405]
## Steps to reproduce
Try to connect to our largest tenant on staging

## Expected result
The compute is started

## Actual result
```    {
      "id": "a94cfb85-d6f5-45ec-b74f-e5965270dfa9",
      "project_id": "calm-unit-272325",
      "branch_id": "br-little-math-565362",
      "endpoint_id": "ep-fragrant-glade-840764",
      "action": "start_compute",
      "status": "failed",
      "error": "could not execute operation: could not start the compute node: failed to get basebackup@47/27F4E7D8 from pageserver host=pageserver-2.us-east-2.aws.neon.build port=6400\n\nCaused by:\n    0: db error: ERROR: Timed out while waiting for WAL record at LSN 47/27F4E7D8 to arrive, last_record_lsn 47/208936D8 disk consistent LSN=47/19086BD8\n    1: ERROR: Timed out while waiting for WAL record at LSN 47/27F4E7D8 to arrive, last_record_lsn 47/208936D8 disk consistent LSN=47/19086BD8",
      "failures_count": 6,
      "retry_at": "2023-01-23T12:36:29Z",
      "created_at": "2023-01-23T12:25:10Z",
      "updated_at": "2023-01-23T12:33:59Z"
    },
```

## Environment
staging

## Logs, links
I got the same error while vacuuming this database
the task is related to #3404

**Comment by vadim2404** [comment]
I've run such queries, that can affect the disc size:

```sql
CREATE TABLE x (x INT);
INSERT INTO x SELECT * FROM generate_series(1, 100000);
SELECT SUM(x) FROM x;
DROP TABLE x;
VACUUM;
```

And I received the error while `vacuuming` the databsae

**Comment by problame** [comment]
Yeah, that'd be expected. Just in case it's not obvious: even though the SQL is _freeing_ up logical space, this doesn't free up any space on the pageserver, in fact, it consumes more space. Until PITR is over and compaction comes around to generate image layers. But even that needs more space before it can delete the delta layers.

**Comment by shanyp** [comment]
This is by design and known behavior
