### ISSUE TITLE
ERROR synthetic_size_worker: failed to calculate synthetic size for tenant ... no end_size on latest segment for 

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#3412]
Synthetic size calculation fails for some projects on staging with error:

```
ERROR synthetic_size_worker: failed to calculate synthetic size for tenant 82d8a4983d362a9e90483907f9bad355: no end_size on latest segment for Some(5b7cf251f121e7c24f15d51869bbcd1f)
```

This happens, because such projects branch a new timeline from an LSN which is greater than ancestors last_record_lsn. As model inputs, this looks like:

```json
[
    {
      "lsn": "0/0",
      "command": { "branch_from": null },
      "timeline_id": "9084c1a0376db01e4601be5a31bf9f07"
    },
    {
      "lsn": "0/149F0F0",
      "command": "end_of_branch",
      "timeline_id": "9084c1a0376db01e4601be5a31bf9f07"
    },
    {
      "lsn": "0/1E48ED8",
      "command": { "update": 22208512 },
      "timeline_id": "9084c1a0376db01e4601be5a31bf9f07"
    },
    {
      "lsn": "0/1E48ED8",
      "command": { "branch_from": "9084c1a0376db01e4601be5a31bf9f07" },
      "timeline_id": "36fd37f252e3f7d0e81eb6553d8b9d7a"
    }
]
```

## Environment

staging

## Links
https://neondb.slack.com/archives/C033RQ5SPDH/p1674492860548339

CC: @koivunej

**Comment by koivunej** [comment]
Looking at the logs of this tenant, an attempt was made to detach it, but something happened. It was retried once and on the next deploy it was loaded in as an existing tenant.

**Comment by koivunej** [comment]
Hmm makes sense, I think we are good to close this. A lot of silly bugs introduced by me related to synthetic size calculation were fixed later on and tests added for different situation, then a rewrite so this might not be fixable anymore at all.
