### ISSUE TITLE
test_download_remote_layers_api[local_fs] failed on unrelated PR

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#3422]
```
AssertionError: current_physical_size is sum of loaded layer sizes, independent of whether local or remote
assert 29818880 == 29343744
  +29818880
  -29343744
```

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3419/debug/3994869837/index.html#suites/b97efae3a617afb71cb8142f5afa5224/e0e1298fe94293ae/

**Comment by jcsp** [comment]
Closing in favor of identical https://github.com/neondatabase/neon/issues/3831
