### ISSUE TITLE
Epic: pg_jsonschema extension

### ISSUE THREAD

**Issue by nileshtrivedi** [neondatabase/neon#3429]
## Motivation

[pg_jsonschema](https://supabase.com/blog/pg-jsonschema-a-postgres-extension-for-json-validation) is an extension built by Supabase. [Github repo](https://github.com/supabase/pg_jsonschema).

It provides the ability to validate the integrity of json columns with deep structure.

## Tasks
- [ ]

## Other related tasks and Epics
-

**Comment by vadim2404** [comment]
Created a bug tcdi/pgx#1032

**Comment by vadim2404** [comment]
@nileshtrivedi. The extension is available in all regions

**Comment by nileshtrivedi** [comment]
Thank you @vadim2404 for driving this to closure. I can see that it was not an easy fix because of hardcoded Postgres ABI in PGX etc. 👏
