### ISSUE TITLE
Unable to build Compute Docker image

### ISSUE THREAD

**Issue by mingfang** [neondatabase/neon#3436]
## Steps to reproduce
run `docker build -f Dockerfile.compute-node-v15 .

## Expected result
finish building docker image

## Actual result
I see this error
```
Step 28/43 : FROM 369495373322.dkr.ecr.eu-central-1.amazonaws.com/rust:$TAG AS compute-tools
Get "http://369495373322.dkr.ecr.eu-central-1.amazonaws.com/v2/": dial tcp 3.121.166.70:80: i/o timeout
```

## Environment
Ubuntu

**Comment by mingfang** [comment]
The problem appears to be that `369495373322.dkr.ecr.eu-central-1.amazonaws.com` is not private and not publicly accessible.  

It turns out the same image is available on Dockerhub.
I am now able to using using these parameters...
```
-f Dockerfile.compute-node --build-arg REPOSITORY=neondatabase --build-arg PG_VERSION=v15
```

Should `REPOSITORY=neondatabase` be the default?

**Comment by hlinnaka** [comment]
Hi! It works for me now, I tested with this command:

```
docker build -f Dockerfile.compute-node --build-arg PG_VERSION=v16
```
It's been a long time since this issue was opened, so I assume it got fixed at some point. I'll close this, but please re-open if it still doesn't work for you.
