### ISSUE TITLE
Add a facility to evict layer files manually

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#3439]
Part of https://github.com/neondatabase/neon/issues/2476

The implementation will use HTTP management API to do that.

We need to:

* be able to return layers via the HTTP API

     - There's currently no layer concept in the HTTP API at all, need to add one and have some unique layer ID there (local FS layer file name is good enough)
API.

     - Layer map dumping mechanism has to be called via that HTTP API and the result converted to the new API object

* be able to evict layers via the HTTP API

Using the IDs produced from the new API handle described above, we can remove the local FS file and replace it with the "Remote" variant of this layer to not to loose it and be able to redownload it again, if needed

Given that the previous API step is implemented, the HTTP API <-> layer map access interface is already there and it's relatively trivial to add the reverse operation code-wise, but there's one potential caveat: we need to hold a lock during layer replacement, and do layer map rebuilds during that. 
It might be slow, according to https://github.com/neondatabase/neon/issues/3394

Most probably, it's not an issue, but should be considered during the impl.

* synchronize with the upload_queue and forbid evicting the layers that are not uploaded

Something similar may happen with GC/compaction that deletes the layer that's not yet uploaded: we can remove that along the way too.
https://github.com/neondatabase/neon/blob/aabca55d7e7e020a30f6afd286c850af88063f28/pageserver/src/tenant/timeline.rs#L2592-L2598

**Comment by SomeoneToIgnore** [comment]
Additional notes:

* we should care about atomic removals: we can be dropped any time, and should 
    * assert that there's no local file in memory when actually removing the file
    * do file removal after the layers in memory are adjusted to have the remote layer

**Comment by shanyp** [comment]
>we can consider soft-deletion and rename the layers files into some layer_name.deleted instead of directly removing them

If we do , there should be a scavenger of some type to delete those upon page server restart
