### ISSUE TITLE
walredo: find a design that uses Rust typesystem to child stdio file descriptor lifetimes [P:2] [S:2]

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3459]
# Problem Statement

As of https://github.com/neondatabase/neon/pull/3368 , when we kill the walredo child process, we keep its  ChildStdout and ChildStderr alive. This keeps the file descriptors that we receive from the OS open so that, when we spawn a new walredo child, we will have different file descriptors for the new child's stdout & stderr.
`apply_wal_records` uses this behavior to detect that we spawned a new walredo child process.

I believe this **file descriptor dance is currently correct but very brittle** (see [my comments in the code](https://github.com/neondatabase/neon/pull/3389/files)).
I fear it will be glossed over or not properly understood in a future change to walredo.rs.
The worst-case outcome is that another tenant's walredo process's stdio file descriptors get used, resulting in a potential cross-tenant information leak.

# Propsoal

Introduce a new struct `WalRedoProcess` and move the `apply_wal_records` method there.
When we launch the walredo process, we heap-allocate the `WalRedoProcess` struct using `Arc`.
`PostgresRedoManager` stores the current walredo process in a `Mutex<Option<Arc<WalRedoProcess>>>`.
`apply_batch_postgres` grabs that mutex _briefly_ to check whether there is already a walredo process.
If there is, `Arc::clone` it, drop mutex, call `apply_wal_records`.
If `apply_wal_records` comes back with an error:
1. re-acquire the mutex 
2. if it's still the same WalRedoProcess, `.take()` it out, drop mutex, and `kill_and_wait` it

```
pub struct PostgresRedoManager {
    tenant_id: TenantId,
    conf: &'static PageServerConf,
    redo_process: Mutex<Option<Arc<WalRedoProcess>>>,
}

struct WalRedoProcess {
    child: NoLeakChild,

    // stderr is used by both tx and rx. Rule is: must hold either tx or rx mutex before this one.
    stderr: Mutex<ChildSterr>

    tx_mutex: Mutex<ChildStdin>,

    rx_mutex: Mutex<struct {
      stdout: ChildStdout,
      pending_responses: VecDeque<Option<Bytes>>,
      n_processed_responses: usize,
    }>
}

impl WalRedoProcess {
    fn apply_wal_records(&self, ...) -> ... {
        let borrowed_child_stdin_fd: BorrowedFd<'_> = self.tx_mutex.lock().unwrap().as_fd();
        // The BorrowedFd type limits the lifetime to the scope of this function.
        // https://doc.rust-lang.org/stable/std/os/fd/struct.BorrowedFd.html
    }
}

```

With this design, the lifetimes of file descriptors are tracked through Rust's type system at all times.
That makes it _much_ harder to accidentally use a file descriptor after closing it or, worse, after it is reused by another walredo process.

Further, the code will be much more idiomatic and straightforward.

# FAQ

> Won't there be contention around the mutex `redo_process: Mutex<Option<Arc<WalRedoProcess>>>`

Definitely, but we hold it only briefly on the hot path, so the futex code will likely remain in userspace.
We could also use `RwLock` or do tricks with atomic pointer swaps if it ever becomes a severe bottleneck.

---

Also, the complete discussion that followed my original proposal to implement this as part of 
https://github.com/neondatabase/neon/pull/3368#pullrequestreview-1263240030

**Comment by koivunej** [comment]
I am surprised we haven't yet seen fd confusion with the restart pr landing #3739, because it should trigger the issue easily locally. Perhaps we have no tests for this, and #3739 didn't add those.
