### ISSUE TITLE
pageserver management API should log start of request handling [P:3] [S:3]

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3479]
The current management API only has middleware for logging the result of a request (status code + URL).

When looking at logs, it would be helpful to log the beginning of request processing as well, so that it becomes easier to attribute log messages from various subsystems to the request.

Adding a request ID to the tracing span while we're at it would futher simplify log analysis.

Example where it would have been useful to get a log line for start of request processing:

Logs: https://neonprod.grafana.net/goto/Z5tSjW0Vz?orgId=1
Associated discussion on Slack: https://neondb.slack.com/archives/C03H1K0PGKH/p1675072015829369
Resulting issue: #3478 
Summary:
> So, what happens in hyper when the client hangs up? Is the future still polled to completion?
> If it is not polled to completion, I have the hypothesis that the first API call polled the future far enough  to transition the future into Stopping state, but then stopped polling.

If we had logged the start of request processing, it would have been immediately obvious that the request handler didn't finish.

But even if we fix #3478 , I think there's still value in logging the start of request processing, especially if we add a request ID to the `tracing::Span`

**Comment by shanyp** [comment]
this was done with both #3708 and #3755
