### ISSUE TITLE
send cached metric values from pageserver from time to time

### ISSUE THREAD

**Issue by antonyc** [neondatabase/neon#3485]
That is needed to have a workaround for the consumption tracking when the month changes. I suggest having a configurable amount of seconds to provide an interval in which to update the cached values because the actual value is still needs to be discovered.

for https://github.com/neondatabase/neon/issues/2941

**Comment by lubennikovaav** [comment]
Reopen the issue, because metrircs don't show up in Orb as expected

**Comment by antonyc** [comment]
| metric                   | coordinates  | comments  | ok   |  
| ------------------------ | --------- | --------- | ---- |
| `synthetic_storage_size`, `remote_storage_size`, `resident_size` | `"tenant_id": "bf82e8c03544b2cbc7b6ddb9b523ee46",` | * Feb 17 1:57:05.0000<br> * Feb 17 3:07:04.0000 <br> * Feb 17 4:17:05.0000 <br> * Feb 17 5:27:05.0000 <br> no events at 6,7,8,9 o'clock. no errors sending/receiving those metrics for 6 hours on the dashboard. No errors I see in [pageserver logs](https://gist.github.com/2f8397b94f172d0be44c10d09ddf460f). I see other synthetic_storage_size and other metrics at 7,8,9 o'clock for other projects of my [user](https://console.stage.neon.tech/admin/projects?user_id=36b70845-ec35-4fc9-b588-b9b701304c83&sort=created_at&order=desc) | ⛔️ |
