### ISSUE TITLE
Racy startup causes unnecessary ERROR events

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3501]
Error event:

```
timestamp ERROR gc_loop{tenant_id=X}: Failed to get a tenant X: Tenant X not found in the local state
```

During startup, this can be caused when the initial `pageserver::tenant::mgr::init_tenant_mgr` takes a long time to write switch the `TenantMap::Initialized` to `TenantMap::Open` in https://github.com/neondatabase/neon/blob/895f929bcef6078683073d4088452df1691eeff3/pageserver/src/tenant/mgr.rs#L144-L146

This error is irrelevant anytime in the lifecycle of the tenant or pageserver deployment -- this may happen during shutdown as well.

Also notice that there is 3 formattings of tenant_id on the same message!

**Comment by koivunej** [comment]
Reliance on the global tenants map in this case seems pointless, as the `Tenant::activate(&self)` could also be `fn activate(self: &Arc<Tenant>) -> _` and just give the correct `Arc<Tenant>` to the background tasks without the background tasks ever needing to fetch it from anywhere.

**Comment by problame** [comment]
I have such a change in my WIP changes for RequestContext phase 2, assigning to myself.
