### ISSUE TITLE
LSN and ids `Serialize` impls force unnecessary copy-paste

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3511]
Repeated:

```rust
#[serde_with::serde_as]
#[derive(serde::Serialize)]
struct Foo {
  #[serde_as(as = "DisplayFromStr")]
  lsn_start: Lsn,
}
```

This could be just:

```rust
#[deride(serde::Serialize)]
struct Foo {
  lsn_start: Lsn,
}
```

If we'd query the serializer for https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable in the `serde::Serialize` impl for LSN, id and then decide to use stringified (for json) or u64 (for bincode).

This has been a bigger issue with ids by default serializing to array of bytes.

Deserialize impls should handle strings and u64 or string and array of bytes (haven't checked if they already do).

(I haven't yet implemented this so there might be some issues.)

**Comment by SomeoneToIgnore** [comment]
> Deserialize impls should handle strings and u64 or string and array of bytes (haven't checked if they already do).

AFAIK, this was the issue last time I've tried to implement this: I failed to distinguish "bytes of a json string" from "bytes of a bincode serialization", causing obscure bugs in tests.

**Comment by koivunej** [comment]
There is `#[serde(with = "hex")]` as well in safekeeper code.

**Comment by koivunej** [comment]
Marking this as good_first_issue.

First thing which needs to be done here is to add image tests for both bincode AND serde-json serialized types which have LSN, TenantId or TimelineId within them. Tests should be something like:

```rust
#[test]
fn ensure_type_roundtrips() {
  let type = /* creation omitted */.
  
  let expected = b"....";  // for serde-json
  let expected = [...] or hex; // for bincode, whichever you find more aesthetic
  
  assert_eq!(&serialize(&type), expected);
  assert_eq!(deserialize(expected), type);
}
```

After that in the Serialize implementation my plan was to use https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable to query which type of value it is, and in the Deserializer implementation, support both.

**Comment by koivunej** [comment]
Alternatively a new test type with all (Lsn, TenantId, TimelineId) could be created as two variants, one for bincode and other for serde_json. Then tests could be created for that type and the different formats roundtripping.

However, it would still be better to find the two examples and show that the really used serialization format does not change. We only have "image based" testing for `index_part.json`, which is not much.
