### ISSUE TITLE
documentation how to start locally is not clear

### ISSUE THREAD

**Issue by vadimtk** [neondatabase/neon#3518]
## Steps to reproduce
I am looking at
https://github.com/neondatabase/neon#running-local-installation

it says

> ./target/debug/neon_local init
Starting pageserver at '127.0.0.1:64000' in '.neon'.

## Expected result
I expect the script or binary neon_local is available somewhere

## Actual result

I can't find it anywhere

## Logs, links
-

**Comment by LizardWizzard** [comment]
Hi @vadimtk! 

This part of the instruction assumes that you've followed build instructions as well, e g see [building on linux](https://github.com/neondatabase/neon#building-on-linux) section (or corresponding one for MacOS just below). They're just above [this](https://github.com/neondatabase/neon#running-neon-database) paragraph. There are also some dependencies required for build to succeed. See list of required dependencies one more [paragraph up](https://github.com/neondatabase/neon#installing-dependencies-on-linux) 

Let me know if there are any problems with that!

**Comment by koivunej** [comment]
Did a clean `git clone --recursive` like above (now at f383b4d5401bd8ddb4e96a683af4d72496967d0a) followed by `make -j8 -s`. This does compile the `neon_local` for me under `target/debug/neon_local` as expected.

(The pysync script is not necessary to run to compile the rust side of the repository.)

After succesful compilation (skipping directories):

```shell
$ find ./ -name 'neon_*' -type f
./test_runner/fixtures/neon_fixtures.py
./.github/workflows/neon_extra_builds.yml
./control_plane/src/bin/neon_local.rs
./target/debug/deps/neon_local-6e46e508fd9339b9
./target/debug/deps/neon_local-6e46e508fd9339b9.d
./target/debug/neon_local
./target/debug/neon_local.d
./pg_install/build/neon-walredo-v14/neon_walredo.so
./pg_install/build/neon-test-utils-v15/neon_test_utils.so
./pg_install/build/neon-test-utils-v14/neon_test_utils.so
./pg_install/build/neon-walredo-v15/neon_walredo.so
./pg_install/v15/share/postgresql/extension/neon_test_utils--1.0.sql
./pg_install/v15/share/postgresql/extension/neon_test_utils.control
./pg_install/v15/lib/postgresql/neon_walredo.so
./pg_install/v15/lib/postgresql/neon_test_utils.so
./pg_install/v14/share/postgresql/extension/neon_test_utils--1.0.sql
./pg_install/v14/share/postgresql/extension/neon_test_utils.control
./pg_install/v14/lib/postgresql/neon_walredo.so
./pg_install/v14/lib/postgresql/neon_test_utils.so
./pgxn/neon_test_utils/neon_test_utils--1.0.sql
./pgxn/neon_test_utils/neon_test_utils.control
./pgxn/neon_walredo/neon_seccomp.h
```

So @vadimtk your output makes me think that the `make` failed for you. Note that our `make` by default runs for example `cargo build ... --verbose` which creates a ton of output, you might have better luck to catch the error by:
- leaving out the `-j` flag for sequential build
- using the `-s` to supress most of the output

Exit value of `make` will of course always denote an error or success.

**Comment by vadimtk** [comment]
yes it seems my build failed and I did not see it with `make -j` command

my build failed because cargo was not in $PATH and actually rust installation says what needs to be done:

`source "$HOME/.cargo/env"`

but I think it might be helpful if you add this tip to the documentation

**Comment by SomeoneToIgnore** [comment]
I have added a `-s` recommendation in https://github.com/neondatabase/neon/pull/3624 , but not sure that we have to explain all `rustup` installation moments in our docs, it is rustup's task and it does that already (random picture from the internet):

![image](https://user-images.githubusercontent.com/2690773/219358895-7c8f0ffe-d3e7-48b5-8434-a31abd14ac31.png)
