### ISSUE TITLE
release builds have unknown git-rev

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3619]
From Slack: https://neondb.slack.com/archives/C033RQ5SPDH/p1676469556982139
@koivunej :

> the git commits we print on prod startup are not commits really in our repository
>
> note that the logs have from recent 3h:
> - version: git-env:001260be6d74e1eda7a2f16f30881668384e88eb
https://github.com/neondatabase/neon/commit/001260be6d74e1eda7a2f16f30881668384e88eb
> - version: git-env:40bb4633695d711a87e3608493e9c96baa2b6664
> https://github.com/neondatabase/neon/commit/40bb4633695d711a87e3608493e9c96baa2b6664
>
> github has them, but they don't belong to any branch. these are probably some MERGE_REF's or whatever they were called.

**Comment by koivunej** [comment]
I think this is an effect of using the PR flow to build releases instead of just tagging. It is very good that we use these "merge refs" in testing PRs to avoid merge skew, but we don't want them for releases binaries.

Unsure what is "merge ref" really, unable to find it from our `.github/workflows/build_and_test.yml` right now.

**Comment by SomeoneToIgnore** [comment]
GH actions do the following:

> When a workflow is triggered by pull request event, the github.ref will be refs/pull/<id>/merge

https://github.com/neondatabase/neon/blob/5082d84f5ba099025e6a1ddd51051e6565b16d17/.github/workflows/build_and_test.yml#L492-L497

See https://github.com/orgs/community/discussions/25191 for more details

**Comment by problame** [comment]
>     When a workflow is triggered by pull request event, the github.ref will be refs/pull//merge

@SomeoneToIgnore so, a post-merge run is also a "pull request event", or what does that mean?

**Comment by SomeoneToIgnore** [comment]
I'm not sure what's happening in this case, actually, just wanted to note how things work for our PR CI runs: the `GITHUB_SHA` in that case gets to point to the fake merge commit and then this could slip as an argument to other CI steps.

**Comment by koivunej** [comment]
Evidence from todays release:

```
2023-07-05T15:20:15.898280Z  INFO version: git-env:353d915fcf81a40482981202fcca55c433688168 failpoints: true, features: [] launch_timestamp: 2023-07-05 15:20:15.895661231 UTC
```

353d915fcf81a40482981202fcca55c433688168 is a merge commit on `release`. On staging:

```
2023-07-05T14:14:01.356221Z  INFO version: git-env:505aa242ace380fe7641935cc3ce98fd6b4c3411 failpoints: true, features: [] launch_timestamp: 2023-07-05 14:14:01.352375883 UTC
```

505aa242ace380fe7641935cc3ce98fd6b4c3411 is on `main`.

**Comment by koivunej** [comment]
Well, it seems it was not really #4545 after all, Alexander traced it to when we got rid of the deploy scripts :) Happy coincidents.

A fix could still be done for PR branches, so reopening this.
