### ISSUE TITLE
test_compaction_downloads_on_demand_with_image_creation flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3627]
The added test fails on merge commit for the first time (non-locally):

https://neon-github-public-dev.s3.amazonaws.com/reports/main/debug/4194510385/index.html#suites/b97efae3a617afb71cb8142f5afa5224/ab71fb4c33a6daaa/

Added a wait timeout for this which took the amount of failures to zero locally and didn't think about this after but it seems that something new might come up after the last checkpoint, had not noticed. Perhaps the last checkpoint should be done only after pg is stopped, or just ignore the inmemory layer.

_Originally posted by @koivunej in https://github.com/neondatabase/neon/issues/3598#issuecomment-1433182815_

**Comment by arssher** [comment]
One more:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3576/debug/4199226575/index.html#suites/b97efae3a617afb71cb8142f5afa5224/176df9f06b1c58c5/
the error (for the record/search) is 
```
AssertionError: no inmemory layers expected after post-commit checkpoint
```
