### ISSUE TITLE
pg_regress failures after bitmap prefetch patch

### ISSUE THREAD

**Issue by MMeent** [neondatabase/neon#3637]
## Steps to reproduce

PG15 with 96126171 fails, but without it doesn't.

## Expected result

pg_regress doesn't fail.

## Actual result

There is an off-by-one in the bitmap scan results:

```diff
 insert into bmscantest select r, 'fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo' FROM generate_series(1,100000) r;
 create index i_bmtest ON bmscantest(a);
 select count(*) from bmscantest where a>1;
- count 
--------
- 99999
+ count  
+--------
+ 100000
 (1 row)
 
 -- test accumulation of stats for parallel nodes
```

## Environment

Postgres 15, Postgres 14.

## Logs, links
-

**Comment by kelvich** [comment]
Fixed in https://github.com/neondatabase/postgres/pull/260 and https://github.com/neondatabase/postgres/pull/261
