### ISSUE TITLE
pageserver_remote_timeline_client_calls_unfinished metric never reaches 0 for layer downloads

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3657]
https://neonprod.grafana.net/d/Z31XmM24k/ondemand-download?orgId=1&from=1676972533778&to=1676978234151&viewPanel=8

![Image](https://user-images.githubusercontent.com/956573/220354468-21b2cf3e-9d32-44db-8e10-c4fbaa14d105.png)

**Comment by hlinnaka** [comment]
Do I get it right that the tokio's IO workers use the same thread pool as spawn_blocking? So if you spawn two many tasks with spawn_blocking, the IO is starved and no IO happens?

**Comment by problame** [comment]
Yes.

**Comment by problame** [comment]
Here's the tokio code:

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/956573/220426312-bd678309-ba70-432d-bdde-3896708c5445.png">

`spawn_blocking` and `<File as AsyncWrite>>::poll_write` both end up using the same `blocking_spawner`.

**Comment by koivunej** [comment]
Testing ideas: Was thinking that this would had reproduced with current_thread runtime but I've rarely thought about limiting the number of spawn_blocking threads to one.
