### ISSUE TITLE
Pageserver downloads a significant amount of layers on every restart

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3658]
Here's a screenshot from staging metrics (most tenants are completely idle):

![Image](https://user-images.githubusercontent.com/956573/220352184-55581df7-8fcf-4aab-8f67-017a30be0cd2.png)

The configured eviction task period is 20 minutes, with a 20 minute eviction threshold.
Annotations (red) indicate a pageserver restart.

We see a clear correlation between restart and a bump in resident size.

The cause is clearly on-demand downloads:

![Image](https://user-images.githubusercontent.com/956573/220352726-bad86cd6-be5e-41cb-9010-7df96d51a252.png)

Grafana Link for this range: https://neonprod.grafana.net/d/Z31XmM24k/ondemand-download?orgId=1&from=1676910417731&to=1676934463526

The likely candidate for these bumps:

- initial logical size computation, possibly triggered by synthetic size calculation
  - it's not cached after pageserver restart, so, it needs to run for each tenant

NB: subsequent synthetic size calculations also cause on-demand download, but, significantly smaller ones:

![Image](https://user-images.githubusercontent.com/956573/220353604-c37693c9-7bd5-4818-993f-c8338a3cab4c.png)

**Comment by koivunej** [comment]
After "yesterdays fixes" there's now a larger continious spike, but also the ratelimit behaviour was changed (#3663) so unsure if the magnitude has changed. Interestingly it has seemed to "diminish" in size in later deploys to staging, but is it more than an effect of less time to evict..? Unsure.

![image](https://user-images.githubusercontent.com/1081634/220690848-9b9ab9ca-4e2e-4cdd-a4ad-3351e321e917.png)

**Comment by problame** [comment]
We added the "imitate accesses" (  #3867  #3871  #3885   ).
Data from prod shows these solved the issue.

There's one remaining edge-case which needs to be investigated, we track that in #4040
