### ISSUE TITLE
be smarter about re-calculation 'initial logical size' upon pageserver restart

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3726]
Timeline tracks the `current_logical_size` as follows:
* upon first access, it kicks off its computation for the current LSN, let's call it `lsn_t1` in the background and answers with an approximate value
* every new change that causes a logical size change is tracked as a delta `logical_size_delta_since_t1` to the still-being-computed logical size 
* once the precise value `logical_size_t1` for the logical size at LSN `lsn_t1` has arrived, the answer for "current logical size" of a timeline is `logical_size_t1 + logical_size_delta_since_t1`

Pageserver reports the value to Safekeepers via the walreceiver status, and Safekeepers report it to Proxy.
Proxy is then responsible for enforcing the logical size limit.

The pros & cons of this:
1. **Con**: Every pageserver restart wastes CPU time to recalculate the logical size.
2. **Con**: If the logical size didn't change, we might have evicted the layer that holds the logical size data. On restart, we re-download it, which causes a spike in on-demand downloads. => #3658
3. **Pro**: If there is an error in the delta tracking (it's not as straightforward as one would hope), a pageserver restart fixes it as the new `logical_size_t1` will be based on whatever the disk_consistent_lsn is after the restart.

The proposal from the team meeting earlier today (2023-03-01)

1. Cache `logical_size_t1` value in `index_part.json`, along with the LSN at which it was computed and a wall-clock timestamp.
2. Add an API to invalidate the cache via mgmt API.
3. Re-compute the value from time to time and
  3.1. replace the cached value
  3.2. alert if the value was off by more than X bytes

Open question:

- when is an opportune point in time to re-compute the value?
  - Ideally, it shouldn't on-demand-download layers, but if so, it's ok.
  - However, re-computation for different tenants should spread out evenly in time and not self-synchronize.

**Comment by problame** [comment]
Also, an idea by @LizardWizzard from today's meeting:

> spread out the spike by persisting set of tenants with active walreceivers, and prioritize those after restart

**Comment by koivunej** [comment]
@problame found this issue of yours, maybe close it with your recent work?

**Comment by shanyp** [comment]
closing it
