### ISSUE TITLE
pageserver disk-usage based eviction

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3728]
On-demand download currently assumes that disk capacity is infinite.
However, if we overcommit the pageserver, it will run out of capacity.
*Overcommit* means that the `sum of its tenant's remote layers` exceeds the `disk space - walredo dirs - filesystem overhead - temp files - ...`).
If all layer files were to be downloaded simultaneously on an overcommitted pageserver, we would run out of disk space.
That is not acceptable.
Pageserver must be able to self-heal from such a situation, **if they are transient**.
For the scope of this ticket, Pageserver need not be able to self-heal if the workload has changed and its tenants permanently need more resident layers than before.
But, Pageserver must provide metrics to understand that this is the case, enabling humans to provision more Pageservers and relocate tenants to spread the load.

## Design

Basic idea:
- additional background loop/data structure that monitors disk usage
- have  a target disk utilization (% of total space and absolute value)
- have some `max guaranteed resident size` per tenant (e.g., 10 GiB)
- policy: if we're above target utilization, we LRU-evict layers above the per-tenant `max guaranteed resident size` until we've reached target utilization
- Best to think about it visually:
  - each tenant has a bar in a bar chart
  - each bar is the stack of resident layers: the bottom of the stack is the most recently used, and the top is the least frequently used layer
  - every $interval, we perform the following:
    - cut off the lowest 10 GiB of each tenant. If a tenant has less than 10 GiB, still do it.
    - throw all the remaining upper pieces of each bar into a list and sort it from least to most recently used
    - evict from least-recently-used until we're below the disk usage threshold
      - maintain the metric that tracks the last eviction date, labeled per tenant id.
- Advantage of per-tenant
  - prevents noisy neighbor problems (tenants < 10GiB won't see any evictions)
  - can enhance this in the future to account for biz aspects, e.g., paid tenants should get a larger `max guaranteed resident size`.
- NB: the case where `max guaranteed resident size` is `0` for all tenants is equivalent to a global LRU policy

Observability / what to monitor:

- add metric that tracks `max(most_recent_access_timestamp_of_evicted_layers)` per tenant
  - if `(now - that_metric)` becomes too small, then we know we need to provision more pageservers -> alert on that
  - it's also our goal metric: we want it to be around 48h
    -  while we're above it (> 48h): add more tenants to the pageserver
    - if we're below it: add a pageserver and relocate tenants

## Alternative Ideas (Rejected)

- only a global LRU list:
  - pro: simple to implement
  - pro: solves the immediate problem sufficiently & intuitively because the disk is also a global resource
  - con: doesn't solve noisy-neighbor

- respond to disk pressure by detaching tenants until we have "enough" free space
  - pro: maintains better performance for remaining tenants
  - con: it seems more complicated as it would likely need to coordinate with the control plane

**Comment by vadim2404** [comment]
I was on the call with one of our users. And they mentioned that they will be happy to have such limit

cc @acervantes23

**Comment by LizardWizzard** [comment]
> Pageserver need not be able to self-heal if the workload has changed and its tenants permanently need more resident layers than before.

Can you elaborate? Looks like:

> evict from least-recently-used until we're below the disk usage threshold

Should solve that too, or I'm misunderstanding it?

**Comment by koivunej** [comment]
Should we refuse create tenant if we don't have 10GB?
- No, control plane should be wiser

Should we avoid disk full, instead of trying to fix it now?
- No need to try to fix it now
- Ballast file?
- There's also the root area on the fs

Dod for christian:
- Have the background loop, which evicts?

Testing ideas which are separate:
- Testing that the scheme avoids disk space
- Testing that we recover from disk full

Only trigger from "disk full seems close" instead of handling ENOSPC. Staying below artificial limit vs. poll how much we are using.
- I want 10% head room, via fs
  - No issue for prod
  - For testing loopback
  - Filesystem delays for updating the 
- Configurable limit idea
  - Use internal counter for disk usage
  - Easier to test, more pure
