### ISSUE TITLE
`pageserver_remote_physical_size` metric lags behind

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3738]
While implementing https://github.com/neondatabase/neon/pull/3729 I noticed that the `pageserver_remote_physical_size` lags behind.

So, I commented out that part of the test.

But we need to get to the bottom of this.

**Comment by koivunej** [comment]
Will be interesting to see if these tests become flaky, since layermap is more consistent than the relaxed counters/gauges which could have whatever value even on amd64.
