### ISSUE TITLE
add a prometheus counter for number of layers & sum of bytes on-demand downloaded

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3745]
Watching the pageserver's network RX metric is insufficient because it intermingles safekeeper RX traffic and S3 on-demand download traffic.

The only other way to compute it is to analyze the layer scrapes database.
But it would be more ergonomic & efficient to use Prometheus for this.

---

Ideally also with a label to disambiguate the following categories of on-demand downloads:
- unavoidable: the first download after attach
- avoidable: download of a layer that we evicted after the tenant was attached

Without durable residence history, we can't make above disambiguation.

**Comment by koivunej** [comment]
I think this is supposed to be per tenant metrics, or just a global one?

**Comment by koivunej** [comment]
> I think this is supposed to be per tenant metrics, or just a global one?

I think these should be global as this originates from global network traffic.

Then add the two variants of the global total metrics for "unavoidable". One could get the "avoidable" by total - "unavoidable". Unavoidable by above logic in https://github.com/neondatabase/neon/issues/3745#issuecomment-1462075372.

**Comment by problame** [comment]
Hmm, good thinking wrt initial logical size calculation, but, compaction and gc would also count as 'avoidable' for me, as per my initial definition

> avoidable: download of a layer that we evicted after the tenant was attached

I'll close this issue and create a follow-up for the avoidable vs unavoidable.

**Comment by problame** [comment]
Created https://github.com/neondatabase/neon/issues/3797
