### ISSUE TITLE
root-cause `task iteration took longer than the configured period` messages afer ap-southeast-1 restart on 2023-03-03

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3746]
Before the restart, we enabled eviction for an additional 600 tenants in that region.

After the restart, we observed a slew of the following type of log messages (the only abnormal log message!):

```
task iteration took longer than the configured period elapsed=59.22373848s period=20s task="compaction"
```

Link to Grafana: https://neonprod.grafana.net/goto/oGvPSyx4z?orgId=1
Link to Slack thread: https://neondb.slack.com/archives/C03H1K0PGKH/p1677869730028649

---

I expect that these are due to on-demand downloads after pageserver restart, or, general load during pageserver restart.

Let's make sure this is the case.

**Comment by koivunej** [comment]
Only now found the ready list :) Looked a few, looked like on-demand downloads, will look more tomorrow.

**Comment by koivunej** [comment]
Should probably look into tweaking that message ... But unsure how. Feels like a lost cause hunt for logs for something we should just include in the message (summary of downloads/uploads time).

**Comment by koivunej** [comment]
Adding those non-prometheus metrics on task context seems sensible forward, so this ties in a bit with the #3745 "(un)avoidable" subset, which will need further task context propagation to `Timeline::download_remote_layer`. Return value is of course most straightforward but that wouldn't catch image creation on-demand downloaded, including all future thoughts of moving remote downloading under Delta/ImageLayer.

**Comment by koivunej** [comment]
Going through few of the first. It seems image creation downloads and races against initial logical size calculation downloading the same layers. I don't want to post the tenant ids publicly because it will hard for us to change those but perhaps it's not that interesting either.

Would make sense that these two would race for the same layers because they are recent-ish non-L0, deltas or images. I wonder if it ever pays to evict L0 layers, or if they should have a higher threshold because they will be compacted come restart unless the tenant is completly dormant.

**Comment by problame** [comment]
> Going through few of the first. It seems image creation downloads and races against initial logical size calculation downloading the same layers. I don't want to post the tenant ids publicly because it will hard for us to change those but perhaps it's not that interesting either.

NB: "image creation" is part of compaction.

If there hadn't been initial logical size calculation, compaction would have done the on-demand download.

So, this confirms the hypothesis that compaction was waiting for an on-demand download.

> Would make sense that these two would race for the same layers because they are recent-ish non-L0, deltas or images. I wonder if it ever pays to evict L0 layers, or if they should have a higher threshold because they will be compacted come restart unless the tenant is completly dormant.

Let's figure out the effect of completely excluding L0 from threshold-based eviction.
Maybe combined with forcing image layer creation at $current_lsn if all L0's are older than the eviction threshold?
