### ISSUE TITLE
Discuss HA strategies for pageservers - Active/Standby 

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3749]
https://neondb.slack.com/archives/C033RQ5SPDH/p1678007277320459

**Comment by vadim2404** [comment]
I want to raise the priority for this ticket. Ultimately, we want to have read replicas in different regions. In order to reduce the latency, we want to have “Standy” pageserver nearby

**Comment by shanyp** [comment]
Don't we want the replica to be of a specific tenant?

**Comment by vadim2404** [comment]
yes, we need to replicate data per tenant

**Comment by shanyp** [comment]
@LizardWizzard @hlinnaka before starting the deep dive discussion here, do we have this already partially covered for the read-only state for tenant relocation?

**Comment by LizardWizzard** [comment]
It depends on what is meant by HA. What are the requirements?
