### ISSUE TITLE
`test_remote_timeline_client_calls_started_metric` is flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3765]
`assert 0 > 0` in
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3762/release/4359645106/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/ef597a896e400b6b/
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3763/debug/4359653494/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/4f7cbce429e4f6cd/

**Comment by hlinnaka** [comment]
Like https://github.com/neondatabase/neon/issues/3766, this was also not flaky on 'main', only in PR #3762. I fixed the PR.
