### ISSUE TITLE
`test_remote_storage_upload_queue_retries` is flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3766]
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3762/release/4359645106/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/109b26307be1766c/
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3763/debug/4359653494/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/149c8151d841099d/

`assert 0 > 0`

Related:
- #3051 
- #3042

**Comment by hlinnaka** [comment]
Those two failures were from https://github.com/neondatabase/neon/pull/3762, and from https://github.com/neondatabase/neon/pull/3763 which is on top of #3762. It's not flaky, the fix from #3762 is consistently making it fail. 

I'll dig into that.

**Comment by hlinnaka** [comment]
Fixed that in https://github.com/neondatabase/neon/pull/3762/commits/cada09d0e4155ed858c3302ce94812cce71acb88
