### ISSUE TITLE
automated performance testing: visualize

### ISSUE THREAD

**Issue by mklgallegos** [neondatabase/neon#377]
edit 22 Dec 2021 by @kelvich :

We have now https://zenithdb.github.io/zenith-perf-data/reports/local.html

Let's define scope of that issue as adding grafana dashboard to show results of per-commit and periodical perf tests.

**Comment by kelvich** [comment]
We can create dashboard with both usual on-commit perf tests and daily ones

**Comment by jcsp** [comment]
There are grafana dashboards for things like nightly pgbench these days.
