### ISSUE TITLE
Epic: Prefetch for pgvector

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3803]
## Motivation
Improve the performance of pgvector extension in neon

## Implementation ideas
Implement the prefetch mechanics that we added in other places

pgvector/pgvector#86

**Comment by knizhnik** [comment]
I wonder how we are going to support our own fork of pgvector extension?
I looks how @vadim2404 has added support of other extensions (for example #3785 tiktoken) - it is just change of generated docker file: down load extension, add one line to control file and include it in docker image.
But in case of pgvector much more changes are required. So we need to create fork of pgvector.
Where? Add it to our postgres v14/v15 repositoroy (contrib/pgvector)?
Or neon/pgxn/pgvector?
Ot separate repository under neandatabase?

**Comment by hlinnaka** [comment]
Separate repository, and submit all the changes to upstream. We don't want to maintain a fork

**Comment by knizhnik** [comment]
> Separate repository, and submit all the changes to upstream. We don't want to maintain a fork

My prefetch implementation for pgvector is using Neon  `enable_indexscan_prefetch` GUC.
So it can not be built with Vanilla Postgres.

**Comment by knizhnik** [comment]
I created repository https://github.com/neondatabase/pgvector
for the version of pgvector with prefetch

**Comment by vadim2404** [comment]
@hlinnaka I don't think that it's an option to avoid supporting it from our side.

**Comment by arssher** [comment]
A user bumped into slow pgvector index creation, we should ship our patched version. Context:
https://neondb.slack.com/archives/C04BLQ4LW7K/p1690294328268679
