### ISSUE TITLE
Need for a top-down architectural overview doc

### ISSUE THREAD

**Issue by petergeoghegan** [neondatabase/neon#382]
The Zenith team discussed documentation in person recently. It was agreed that we really ought to have a top-down architectural overview of the entire system, with links to related documentation. @kelvich volunteered to do this at some point. Ideally this will make it easy to drill down, by linking to more specialized docs for each of the major subsystems.

Personally, I think that this should become our top-level README.md, at least for now. At the very least it should be located in the top level directory for discoverability. It doesn't have to be perfect or comprehensive at first. Just something that gives the source code/design some amount of structure would be a big improvement IMV.

**Comment by stepashka** [comment]
will keep this in favor of #909

**Comment by SomeoneToIgnore** [comment]
While dedicated to another topic, I've found this useful as a top level description of the topic: https://github.com/zenithdb/zenith/pull/1364

**Comment by stepashka** [comment]
we've started this in blog and docs, will keep improving
