### ISSUE TITLE
Allow detaching ignored tenant

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#3828]
Required for automating the ad-hoc tenant migration in the control-plane

See
- https://github.com/neondatabase/cloud/wiki/Cloud:-Ad-hoc-tenant-relocation
- https://github.com/neondatabase/cloud/issues/3113

Currently it's done by manual `mv` in step 12

**Comment by ololobus** [comment]
cc @shanyp

**Comment by shanyp** [comment]
@ololobus Done
