### ISSUE TITLE
With disabled gc/compaction period logs get polluted

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3830]
_Originally posted by @knizhnik in https://github.com/neondatabase/neon/pull/3673#discussion_r1129719189_
            
I would just remove the logging in tests, make it more rare or make it once. We very rarely need set period to zero in production, but at the same time, should we forget either to zero in production that would be bad.

Ideas on how to make it more rare or make it once:
- `#[cfg(feature = "testing")]`

Places of logging:
- https://github.com/neondatabase/neon/blob/48936d44f8cc991f2888f580ad7894887b701a75/pageserver/src/tenant/tasks.rs#L109-L111
- https://github.com/neondatabase/neon/blob/48936d44f8cc991f2888f580ad7894887b701a75/pageserver/src/tenant/tasks.rs#L180-L182

**Comment by shanyp** [comment]
@koivunej as this is a good first issue, please add the necessary steps so a first time contributor would easily pick this up

**Comment by koivunej** [comment]
Updated ... I guess we'll have to have a discussion about "is it ever useful to have it repeated in production". Having thought about it now, I cannot really see it.

**Comment by duguorong009** [comment]
@koivunej 
I would like to take this issue!

Can you review the PR #5188?
