### ISSUE TITLE
[PROXY] proxy should respect SAN field in certificate

### ISSUE THREAD

**Issue by cicdteam** [neondatabase/neon#3846]
## Steps to reproduce

Staging region `us-east-2` (EKS cluster name `dev-us-east-2-beta` has wildcard certificate `wildcard-us-east-2-aws-neon-build-tls` with:

```
Subject: CN=*.us-east-2.aws.neon.build

X509v3 extensions:
     X509v3 Subject Alternative Name: 
         DNS:*.us-east-2.aws.neon.build, DNS:*.us-east-2.internal.aws.neon.build
 ```

when I trying connect to `ep-gentle-queen-266236.us-east-2.aws.neon.build` everything foes well, but
when I trying connect tp `ep-gentle-queen-266236.us-east-2.internal.aws.neon.build` I got error:

```
ERROR:  SNI ('ep-gentle-queen-266236.us-east-2.internal.aws.neon.build') inconsistently formatted with respect to common name ('us-east-2.aws.neon.build'). SNI should be formatted as '<project-name>.us-east-2.aws.neon.build'.
```

## Expected result

scram proxy (and may be others) should use both CN and SAN fields in certificate when checking hostname format.

## Actual result

proxy respect only CN filed in certificate

**Comment by stradig** [comment]
We are not sure if this is needed anymore. Please comment or close. If this is still necessary, they consider updating the priority.
