### ISSUE TITLE
 test_ondemand_download_large_rel[local_fs] is flacky

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#3864]
Started to see it failing recently, logs: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3857/release/4488339959/index.html#suites/b97efae3a617afb71cb8142f5afa5224/76bb6e827af6cd74/

**Comment by koivunej** [comment]
There is already: https://github.com/neondatabase/neon/issues/3666

The solution (discussed on the PR) is non-trivial -- at least how I see it. I think this should be closed, the error is similar.

**Comment by koivunej** [comment]
Oh there's even https://github.com/neondatabase/neon/issues/3234 I had missed :facepalm:
