### ISSUE TITLE
add prometheus metrics for page cache hits vs misses

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3888]
At the very least for page reconstruction.

Global metrics would likely be sufficient, as it's a global resource, and we're not interested in fairness of cache resources.

**Comment by xinlifoobar** [comment]
Hi @problame, I would like to take this as the first issue. Is this like adding metrics when `lookup_materialized_page` and `memorize_materialized_page` return ok or none? Is there any code link for metrics I could follow, like naming or dimension definitions?

https://github.com/neondatabase/neon/blob/main/pageserver/src/page_cache.rs#L309-L370

**Comment by problame** [comment]
Hi @xinlifoobar , sorry for not replying here.

The goal with this issue is to have metrics so we can evaluate the page cache's actual effectiveness. The current page cache size in prod is quite small, to the extent that it's most likely not effective at all. We want to verify this, then experiment with sizes `0` and `X% of physical memory`. For this, we need the metrics.

For each type of page in the page cache, we want two counters: an access counter, and a hit counter.

I think the `lock_for_read` function may be a good place for this, since it's used for all three page types.

The page types are:

* for ephemeral files
* for immutable files (= layer files)
* for cached page materializations


Are you still interested in working on this?

**Comment by koivunej** [comment]
@problame I wonder if you already merged this in?

**Comment by problame** [comment]
Yeah, this is done.
