### ISSUE TITLE
pageserver::http::routes::State should be constructed at main, with builders

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#3894]
Currently it has a constructor, arguments of which are duplicated at `make_router` needlessly. Unsure about what to do about the paths, perhaps they could be added in `make_router` instead..?

_Originally posted by @koivunej in https://github.com/neondatabase/neon/pull/3887#discussion_r1150225944_

Good first issue:
- refactor the creation away from https://github.com/neondatabase/neon/blob/48936d44f8cc991f2888f580ad7894887b701a75/pageserver/src/http/routes.rs#L1333-L1342
- to be created in `main()` or `start_pageserver()` in `pageserver/src/bin/pageserver.rs`
- passed as a parameter to https://github.com/neondatabase/neon/blob/48936d44f8cc991f2888f580ad7894887b701a75/pageserver/src/bin/pageserver.rs#L481

**Comment by duguorong009** [comment]
@koivunej 
I would like to take this issue!
Can you review the PR #5165?
This is a simple, straightforward refactoring PR.
