### ISSUE TITLE
Epic: Mirrored pageserver

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#3939]
## Motivation
To reduce latencies for read replicas in different regions, we need to send requests to the nearby pageserver. For this sake, we have to mirror the data somehow.

## Tasks
- [ ] Prepare an RFC

## Other related tasks and Epics
-

**Comment by ololobus** [comment]
Closing in favor of https://github.com/neondatabase/neon/issues/4439 and because of the lack of any details. Also, cross-region replication is not going to be worked on in Q4 and not on the current roadmap. I think we should also design all such projects with storage team
