### ISSUE TITLE
`test_partial_evict_tenant` is flaky

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3978]
See https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3975/release/4631307967/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/86bde5a71b3be727/

```
AssertionError: the other tenant should be evicted to is min_resident_size, i.e., max layer file size
assert 10813440 < (2 * 5242880)
 +  where 5242880 = EvictionEnv(timelines=[(`TenantId("a7cdffb428510c7e804d76eb26cfa11e"), TimelineId("01d2589e75a4adeb9920ceda13fa26f7"))...a7cdffb428510c7e804d76eb26cfa11e"): Lsn("0/4AA79E0"), `TenantId("9952fa59f9ad4d531fdd720dc88aebd1"): Lsn("0/6464048")}).layer_size
```

Triggered in #3975

**Comment by arssher** [comment]
One more:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4063/release/4795319978/index.html#categories/f27b9e9af1d5ea50d8f228e20929c31f/35f8ed9ecd4158d/

**Comment by shanyp** [comment]
@bayandin is this still flaky ? (where can we see the list of the flaky tests anyway )

**Comment by bayandin** [comment]
> @bayandin is this still flaky ? (where can we see the list of the flaky tests anyway )

I use `scripts/flaky_tests.py --days 10 <connstr>` (with  "Regression tests result" connstr from [notion page](https://www.notion.so/neondatabase/72beeaabcdde4380b9c6bc318810c983?v=2fae34ede0e24c91bf882fcbecade90e))

The last 10 days don't mention `test_partial_evict_tenant`
```
	test_runner/regress/test_ondemand_download.py::test_ondemand_download_large_rel[local_fs]
	test_runner/regress/test_ondemand_download.py::test_ondemand_download_large_rel[real_s3]
	test_runner/regress/test_proxy.py::test_close_on_connections_exit
	test_runner/regress/test_tenant_size.py::test_get_tenant_size_with_multiple_branches
	test_runner/regress/test_threshold_based_eviction.py::test_threshold_based_eviction
```

But the last 20 are:
```
	test_runner/performance/test_branch_creation.py::test_branch_creation_heavy_write[20]
	test_runner/performance/test_wal_backpressure.py::test_pgbench_intensive_init_workload[vanilla-1000]
	test_runner/regress/test_disk_usage_eviction.py::test_partial_evict_tenant
	test_runner/regress/test_ondemand_download.py::test_ondemand_download_large_rel[local_fs]
	test_runner/regress/test_ondemand_download.py::test_ondemand_download_large_rel[mock_s3]
	test_runner/regress/test_ondemand_download.py::test_ondemand_download_large_rel[real_s3]
	test_runner/regress/test_ondemand_download.py::test_ondemand_download_timetravel[real_s3]
	test_runner/regress/test_pageserver_restart.py::test_pageserver_chaos
	test_runner/regress/test_proxy.py::test_close_on_connections_exit
	test_runner/regress/test_tenant_detach.py::test_detach_while_attaching[real_s3]
	test_runner/regress/test_tenant_detach.py::test_tenant_reattach[real_s3]
	test_runner/regress/test_tenant_size.py::test_get_tenant_size_with_multiple_branches
	test_runner/regress/test_tenants.py::test_pageserver_with_empty_tenants[real_s3]
	test_runner/regress/test_tenants_with_remote_storage.py::test_tenants_many[real_s3]
	test_runner/regress/test_threshold_based_eviction.py::test_threshold_based_eviction
	test_runner/regress/test_wal_acceptor.py::test_s3_wal_replay[real_s3]
	test_runner/regress/test_wal_acceptor.py::test_wal_backup[real_s3]
```

**Comment by shanyp** [comment]
@problame does this make sense with your changes time line ?

**Comment by koivunej** [comment]
From @bayandin's gist:

```
test_runner/regress/test_disk_usage_eviction.py:404: in test_partial_evict_tenant
    assert (
E   AssertionError: the other tenant should be evicted to is min_resident_size, i.e., max layer file size
E   assert 10813440 < (2 * 5242880)
E    +  where 5242880 = EvictionEnv(timelines=[(`TenantId("c7e4c7ab15acb88542b4dab042b67ade"), TimelineId("2aab1324c55877a45f89bf2d900cf57e"))...c7e4c7ab15acb88542b4dab042b67ade"): Lsn("0/4AA3940"), `TenantId("2daf96411ba1ab91a410b538b899da1f"): Lsn("0/6464048")}).layer_size
```

- [test_partial_evict_tenant[debug-pg14]](https://neon-github-public-dev.s3.amazonaws.com/reports/main/4991705948/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/4952bb4fddc29fb8/)
- [test_partial_evict_tenant[release-pg14]](https://neon-github-public-dev.s3.amazonaws.com/reports/main/4983948954/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/6deaeec432f5a74c/)

**Comment by koivunej** [comment]
Again: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4415/5176204789/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/911c08c027754388 (while fixing another flaky :D)

**Comment by bayandin** [comment]
And again https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4646/5473410503/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/b52c08610e4674f8

**Comment by koivunej** [comment]
Two test runs on same PR, unrelated to PR, pg14 and pg15:
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4938/5968885987/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/1523cd4a484b34ee/
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4938/5968885987/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/d1aa54feb69530e2/

While looking at this, I noticed the env.layer_size is off by 16kB. Not a big thing.

Both tests manage to free up layers as far as I can eyeball the outputs. Both definitely freed up more space than what was asked.

Maybe the problem is that we insist on asserting by bytes when we could look at layers counts? That would be more forgiving towards different shaped layers being done.

**Comment by jcsp** [comment]
Recent failure: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5207/6311482564/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/dd6d989bc4583cae/

**Comment by koivunej** [comment]
Interesting:
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5198/6311728531/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/cb5381d334697d75
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5198/6311728531/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/9daeac88a7328995/retries

(debug and release or release and debug runs).

Messages:

```
AssertionError: the other tenant should be evicted to is min_resident_size, i.e., max layer file size
assert 12615680 < (2 * 5242880)
 +  where 5242880 = EvictionEnv(timelines=[(`TenantId("8f59ff83aa35cb932291d413d08888f6"), TimelineId("b6bf7a5373cef9450f436bc87203120a")), (`TenantId("fe5aa14efc939f5cda53601c4252bbee"), TimelineId("4ac9ba7dfa1440c6fd20ec66f4bd10e1"))], neon_env=<fixtures.neon_fixtures.NeonEnv object at 0x7f9d6f82e2e0>, pg_bin=<fixtures.neon_fixtures.PgBin object at 0x7f9d6f82e670>, pageserver_http=<fixtures.pageserver.http.PageserverHttpClient object at 0x7f9d6f8a1e80>, layer_size=5242880, pgbench_init_lsns={`TenantId("8f59ff83aa35cb932291d413d08888f6"): Lsn("0/7A515B8"), `TenantId("fe5aa14efc939f5cda53601c4252bbee"): Lsn("0/ACC2EC8")}).layer_size
```

```
AssertionError: the other tenant should be evicted to is min_resident_size, i.e., max layer file size
assert 12607488 < (2 * 5242880)
 +  where 5242880 = EvictionEnv(timelines=[(`TenantId("7938da0f418db29172d0006c46e85981"), TimelineId("d0482b82818338b7e4052a16f9674104")), (`TenantId("5652dd761d6674b6d3cf1d8b1b4a0539"), TimelineId("db8294cb8566853b9e9d6a87949247e3"))], neon_env=<fixtures.neon_fixtures.NeonEnv object at 0x7f4786f081c0>, pg_bin=<fixtures.neon_fixtures.PgBin object at 0x7f47870fcc10>, pageserver_http=<fixtures.pageserver.http.PageserverHttpClient object at 0x7f4786f08dc0>, layer_size=5242880, pgbench_init_lsns={`TenantId("7938da0f418db29172d0006c46e85981"): Lsn("0/7A515B8"), `TenantId("5652dd761d6674b6d3cf1d8b1b4a0539"): Lsn("0/ACC0E78")}).layer_size
```

Where:
- `2 * 5242880` would had been `10485760` or the familiar 10MiB
- 12607488 = 5259264 + 5259264 + 2088960

warmed up tenant `7938da0f418db29172d0006c46e85981/d0482b82818338b7e4052a16f9674104` went from 125MiB (132055040) to 70MiB (74260480).

other tenant `5652dd761d6674b6d3cf1d8b1b4a0539/db8294cb8566853b9e9d6a87949247e3` went from  177MiB (186023936) to 12MiB (12607488).

Report formatted:

```
2023-09-26T11:15:03.126956Z  INFO request{method=PUT path=/v1/disk_usage_eviction/run request_id=3345cb95-466e-4139-9470-2dedd659b55c}: disk_usage_eviction_task_iteration_impl finished res=Ok(Finished(IterationOutcomeFinished {
before: Usage { config: Config { evict_bytes: 231079936 }, freed_bytes: 0 },
planned: PlannedUsage {
  respecting_tenant_min_resident_size: Usage {
    config: Config { evict_bytes: 231079936 },
    freed_bytes: 231211008
  },
  fallback_to_global_lru: None
},
assumed: AssumedUsage { projected_after: Usage {
  config: Config { evict_bytes: 231079936 },
  freed_bytes: 231211008
},
failed: LayerCount { file_sizes: 0, count: 0 } } }))
```

I think this run completed successfully but for the passing runs the size of small layers on the smaller timeline is different:
- 655360
- 647168

Interesetingly enough, the larger tenant has exactly the same sized layers on both runs.
