### ISSUE TITLE
Measure time to apply several kinds of WAL records to the page

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#399]

**Comment by stepashka** [comment]
have we done this already? @knizhnik @bojanserafimov

**Comment by knizhnik** [comment]
We have told many times that we should measure speed of our WAL redo process. It is possible to monitor it now using Prometheus metrics, but I was not sure if precision is enough and also want to measure speed of individual operations. 
So my results with release Rust version on our pgbench tests with -N are the following:

1. Prometheus 
pageserver_wal_redo_time_sum 2.556758943000012
pageserver_wal_redo_time_count 15964

2. Time of update operation (1000 iterations in loop): 400usec for vector with 61 updates

So in first case average WAL redo time is 160usec, in the second - 400usec.
It corresponds to maximum 2500 get_page_at_lsn requests per second (not including network roundtrip). Actual TPS for one client is about 1000. Taken in account that pgbench script with -N option access just one random tuple(which requires reading ~pages: index and heap), this times are compatible and wal-redo postgres can really be a bottleneck.

**Comment by knizhnik** [comment]
Apply one insert record by wal-redo postgres (eliminating all communication and xlog decoding overhead) is about 2usec. If we multiple it by 61, then get about 100 usec for applying all wal records needed to reconstruct one page. Others 300 usecs seems to be used by  communication.

**Comment by knizhnik** [comment]
I did more investigation of  what is limiting now wal-redo speed.
So applying one INSERT record in Rust takes about 5usec.
When we apply multiples records (i.e. in case of table population), then per-record time is decreased to 3usec.

With our wal-redo process, reconstruction of page takes 230usec. And it almost not depends on whether one wal record is applied or many.
So looks like the most limiting factor is messages roundtrip through the pipe. But I have modeled communication between rust and C process through the pipe (using exactly the same code) and it is 42usec. It is still 10 times larger than applying one record in-place in Rust. But for applying multiple records the difference will not be so large.

**Comment by knizhnik** [comment]
Related PRs:
[https://github.com/zenithdb/zenith/pull/1362](url)

**Comment by shanyp** [comment]
@knizhnik should this be closed ?

**Comment by jcsp** [comment]
Stale ticket.
