### ISSUE TITLE
Error Running create tenant

### ISSUE THREAD

**Issue by Lolly1150** [neondatabase/neon#3992]
## Steps to reproduce
Normal install when you run ./target/debug/neon_local tenant create --set-default return error

## Expected result
tenant 9ef87a5bf0d92544f6fafeeb3239695c successfully created on the pageserver
Created an initial timeline 'de200bd42b49cc1814412c7e592dd6e9' at Lsn 0/16B5A50 for tenant: 9ef87a5bf0d92544f6fafeeb3239695c
Setting tenant 9ef87a5bf0d92544f6fafeeb3239695c as a default one

## Actual result
tenant f92d7c997bc760aa5620022fe37f8566 successfully created on the pageserver
command failed: Error: Error: initdb failed: 'initdb: error: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.

## Logs, links
-

**Comment by kelvich** [comment]
> Error: Error: initdb failed: 'initdb: error: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.

Yes that is a postgres behavior -- it requires non-root user to run. You can create user named, e.g. neon and run the same commands

**Comment by Lolly1150** [comment]
I had try this but don't work.

**Comment by Rucchao** [comment]
encounter the same issue...
