### ISSUE TITLE
remote_storage::s3_bucket: replace concurrency_limilt semaphore with proper requests-per-second rate limiter

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#3997]
@koivunej

> since the suggestion from Christian to raise s3 concurrency semaphore permits, i haven't been able to not think of a performant 3500 requests per second limiter.
> I didn't want to do the limit rising because you can trivially go past the 3500 rps limit with even 100 concurrent requests because those are unrelated.
> has someone already looked into this rps limiter topic? I can think of quite pessimistic using tokio_util::...::DelayQueue but this would require mutex locking from rps_limit+1 requests, and I am unsure how to stay fair (semaphore is fair) without requiring each request after rps_limit to lock.. I think we might need fairness for across timeline operations..
> Well, perhaps a single task to "unpack" or return the permits from the delayqueue would give fairness and lack of locks. The same task would have to receive "used permits" after request has been processed (drop) over a channel.

**Comment by koivunej** [comment]
Prior art: #3698, closing as duplicate.
