### ISSUE TITLE
RemoteTimelineClientMetrics: investigate using `parking_lot` upgradable RwLock guards

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4001]
This is follow-up from review comment https://github.com/neondatabase/neon/pull/3951#discussion_r1161635303 .

---

The `RemoteTimelineClientMetrics` has comments like

```
        // XXX would be nice to have an upgradable RwLock
        let mut guard = self.remote_operation_time.lock().unwrap();
```

The `parking_lot` crate provides upgradable RwLock guards: https://docs.rs/parking_lot/0.12.1/parking_lot/struct.RawRwLock.html#method.upgrade

Presumably, we could use them here, but, `parking_lot` usage seems quite sparse around the code base, and I don't have experience with it.

**Comment by shanyp** [comment]
@problame I remember that there was an argue not to use it, so is this still relevant ?

**Comment by LizardWizzard** [comment]
Close by removing the comment
