### ISSUE TITLE
Fix frequent reconnections due to choosing sk in the same AZ

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#4022]
There is definitely something going wrong:
https://neonprod.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_env%3D%5C%22prod%5C%22,%20neon_region%3D%5C%22us-east-2%5C%22,%20neon_service%3D%5C%22pageserver%5C%22%7D%20%7C%3D%20%5C%22f3a8a629a040be387db0af9dd07e0c5b%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221681288999000%22,%22to%22:%221681289075000%22%7D%7D

It continued for ~minute after pageserver start and self healed.
Also, in any case we shouldn't log ERROR and print backtrace when walreceiver itself kills the connection due to switch to another candidate.

CC @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
Backtraces due to "connection closed" reason do not look normal either — we should remove them.

**Comment by petuhovskiy** [comment]
Duplicate of https://github.com/neondatabase/neon/issues/3972

**Comment by arssher** [comment]
indeed
