### ISSUE TITLE
Postgres 15 doesn't enter standby mode in some cases

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#4032]
## Steps to reproduce

An unrelated test caught the problem in https://github.com/neondatabase/neon/pull/2809, so don't be surprised that we run the test that doesn't mention standby mode

```sh
git checkout bayandin/default-to-15
BUILD_TYPE=debug CARGO_BUILD_FLAGS="--features=testing" make -s -j`nproc`
git revert 162ffb53ed1ee7bfe006ecc3269940fc00897c48 # Revert commit with a workaround
./scripts/pytest -s -k test_partial_evict_tenant # https://github.com/neondatabase/neon/blob/98d5ca0ba45d561f93be257b708610a132435487/test_runner/regress/test_disk_usage_eviction.py#L357
```

## Expected result

Test passes (you can run it on the main branch with Postgres 14)

## Actual result

Test gets stuck on vacuuming the DB (during the `pgbench -S`):
```
2023-04-14 16:32:19.47  INFO [neon_fixtures.py:1781] Running command '/Users/bayandin/work/neon/pg_install/v15/bin/pgbench -S host=localhost port=15008 user=cloud_admin dbname=postgres options='-cstatement_timeout=120s ''
pgbench (15.2)
starting vacuum...
```

## Environment
Local

## Logs, links
- https://neondb.slack.com/archives/C04DGM6SMTM/p1681482282502569

Part of pg.log from Postgres 14:
```
...
2023-04-14 14:09:09.975 GMT [53671] LOG:  database system is ready to accept read-only connections
...
``` 
Part of  pg.log from Postgres 15:
```
...
2023-04-14 14:11:43.970 GMT [58996] LOG:  database system is ready to accept connections
...
```

**Comment by lubennikovaav** [comment]
probably, this is the commit to blame
https://github.com/neondatabase/postgres/commit/00c68fe85024834af855b3e98a0acadf60940133

I can't remember why exactly we decided to do that...

**Comment by bayandin** [comment]
> probably, this is the commit to blame [neondatabase/postgres@00c68fe](https://github.com/neondatabase/postgres/commit/00c68fe85024834af855b3e98a0acadf60940133)
> 
> I can't remember why exactly we decided to do that...

Given this commit doesn't have linked PR, I guess this could have been done for Postgres 15.2 rebase.
There're a couple of lines that mention standby mode in the release notes also https://www.postgresql.org/docs/release/15.2/

**Comment by knizhnik** [comment]
This is the original discussion of the problem:
https://neondb.slack.com/archives/C033RQ5SPDH/p1663698370041899

Looks like not setting `ArchiveRecoveryReqested` is not correct
But with my original patch (disarming assert):
```
@@ -1703,7 +1705,10 @@ PerformWalRecovery(void)
        else
        {
                /* just have to read next record after CheckPoint */
-               Assert(xlogreader->ReadRecPtr == CheckPointLoc);
+               if (ZenithRecoveryRequested)
+                       xlogreader->ReadRecPtr = CheckPointLoc;
+               else
+                       Assert(xlogreader->ReadRecPtr == CheckPointLoc);
                replayTLI = CheckPointTLI;
                record = ReadRecord(xlogprefetcher, LOG, false, replayTLI);
        }
```

the test is passed. 
It seems to be the smallest possible patch and compatible with PG14.
Can somebody propose better fix?

But I wonder about two things:

1. Now old way of running tests with PG15 doesn't work:
```
   DEFAULT_PG_VERSION=15 ./scripts/pytest -s -k test_partial_evict_tenant
```
pg_ctl fails to start server and pg.log contains errors that database was initialized by different version of Postgres (1.5)i

2. Why test_timetravel.py disappears?
