### ISSUE TITLE
`check_availability` op from console causes on-demand downloads

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4061]
Not urgent for now, but, creating an issue to keep track of this design deficiency:

`check_availability` does checks at widending intervals, but capped at 72h 15m, 30m, 60m, 120m, ..., MAX(72h)
  - this means, we on-demand download a small set of layers that's required for  `check_writability` ([source code](https://github.com/neondatabase/neon/blob/e5cc2f92c4f611f1bebba3e6c1151b0c4f36c5bd/compute_tools/src/checker.rs#L26)) every 72h, even if the project is completely unused
  - https://github.com/neondatabase/cloud/blob/a772defc5b31a2eadbf1e0bdbb748d5a99611cc0/goapp/internal/consoleliveconfig/declaration.go#L41
  - https://github.com/neondatabase/cloud/blob/0b3bdb4efd6d4c7d6c5c3760379215c75dfae826/helm/zenith-console/templates/api-configmap.yaml#L81-L83

Grafana dashboard that showcase the problem:
https://neonprod.grafana.net/d/-KOr2qAVq/basic-layer-map-info?orgId=1&from=1676570636316&to=1676573425813

**Comment by LizardWizzard** [comment]
Closing until it becomes an issue
