### ISSUE TITLE
test_ondemand_download_timetravel is still flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#4112]
Previous failure modes, see #3209.

Unless this was dropped from the latest release, it just reproduced:

- https://neon-github-public-dev.s3.amazonaws.com/reports/release/debug/4832365688/index.html#suites/b97efae3a617afb71cb8142f5afa5224/c6021b7503b788a0/
- https://neon-github-public-dev.s3.amazonaws.com/reports/release/release/4832365688/index.html#suites/b97efae3a617afb71cb8142f5afa5224/310f152ec857473e/

Both hit the assert on the same line, but with different values:

```
test_runner/regress/test_ondemand_download.py:246: in test_ondemand_download_timetravel
    assert filled_current_physical == get_api_current_physical_size()
E   assert 195174400 == 195665920
E     +195174400
E     -195665920
```

Moved from the original issue as the assert is no longer the same.

**Comment by koivunej** [comment]
Third for the evening, this time on PR after release: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-4111/debug/4832246267/index.html#suites/b97efae3a617afb71cb8142f5afa5224/c6edf44258a55c5f

**Comment by koivunej** [comment]
From @bayandin's gist:

```
test_runner/regress/test_ondemand_download.py:246: in test_ondemand_download_timetravel
    assert filled_current_physical == get_api_current_physical_size()
E   assert 195190784 == 195682304
E     +195190784
E     -195682304
```

[test_ondemand_download_timetravel[debug-pg14-real_s3]](https://neon-github-public-dev.s3.amazonaws.com/reports/main/4984908321/index.html#suites/b97efae3a617afb71cb8142f5afa5224/b71f5043f3712227/)

**Comment by arssher** [comment]
One more time
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5205/6211540919/index.html#categories/29b11e07325dfc5f3c38df3ff8d4a427/37cacf770aa1d249/

**Comment by koivunej** [comment]
> * `test_ondemand_download_timetravel[mock_s3]`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5108/6960529018/index.html#suites/b97efae3a617afb71cb8142f5afa5224/fc254918a12636cb)

**Comment by koivunej** [comment]
And still: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6081/7143280709/index.html#suites/b97efae3a617afb71cb8142f5afa5224/82c0c806400abb4d

**Comment by jcsp** [comment]
This is a top-3 flaky test over last 48h

**Comment by problame** [comment]
Possible fix: https://github.com/neondatabase/neon/pull/6687

**Comment by jcsp** [comment]
14 flaky failures in last 7d

**Comment by jcsp** [comment]
No failures since 17th.
