### ISSUE TITLE
pageserver: prohibit branching from LSNs that are not yet remote consistent

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4218]
> I don't think there isn't anything wrong with the current approach per se either, but I agree it would feel less surprising.
> 
> It means that we need to wait for the remote storage uploads on the parent timeline to finish before the timeline creation can complete, but I guess that's acceptable.
> 
> We'd still need the "wait for ancestor timeline to become active" part of this PR anyway. Most of the code changes here were needed for that, the wait_for_lsn call is just a one-liner on top of that. So I'd suggest committing this PR as it is, and open a follow-up issue/PR to change timeline_create to wait for parent's remote uploads. What do you think?

Sure, we can take this PR now and fix branch creation later, although, as part of that later fix, IMO we should stop `wait_lsn` for ancestors and instead bail out if we don't have it, in the spirit of

>> The argument I'd make is that, detach+attach should be a pageserver-internal affair. SKs >> availability should not impact ability to successfully detach+attach+access existing data.

I'll create an issue for that.

---

On a side note, I'm now wondering whether we can currently branch in the future? Couldn't spot a check while skimming through `Tenant::branch_timeline` .

---

_Originally posted by @problame in https://github.com/neondatabase/neon/issues/4170#issuecomment-1545381441_

**Comment by LizardWizzard** [comment]
Waiting period for LSN becoming remote consistent can be up to 10 minutes (flush timeout), so if we return an error we can do so for up to 10 minutes which is not acceptable.
