### ISSUE TITLE
clean up resurrected timelines from before #3560 was fixed

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4263]
Before https://github.com/neondatabase/neon/issues/3560 was fixed (releasing it this week), deleted timelines would be resurrected by attach.

One of the affected tenants is `39fa0a33ca08f1948bd01b5f1e4ae898` (posting tenant id because it's already [in the original issue](https://github.com/neondatabase/neon/issues/3560#issuecomment-1433364946)).

Those affected tenants need to be cleaned up in some way.
Suggested procedure (feel free to improve):

* Find list of deleted timelines for active projects. 
* Check pageservers to gather list of deleted timelines that are attached to pageservers. (This should be the case only for migrated tenants).
* Use https://github.com/neondatabase/s3-scrubber to clean up deleted branches.

This is possible because timelines shouldnt be in broken state. If they're in broken state then the following sequence makes sense:

* Get list of deleted timelines from console
* Get affected tenant's tenant config
* Detach affected tenants
* Idempotently set `deleted_at` flag in IndexPart
* Attach affected tenant with tenant's tenant config
* Assert that the deleted timeline is not present in the attached tenant

NB we need to take care of tenant config now because console sets PITR for one of our partner integrations (and actually it also sets another explicit value for any other project as well, see https://github.com/neondatabase/cloud/pull/4740#pullrequestreview-1427046402 ).

Proceeding with the first approach. If broken timelines will be observed, the plan will be adjusted.

***

Merging with #4251

**Comment by LizardWizzard** [comment]
See the attached gist for script I'd like to run, and SQL query to run against console db to find deleted branches for non deleted projects: https://gist.github.com/LizardWizzard/7f9d47ce87f40f12af25d222a6a9a3f7

On staging I dont see any such projects so I tried to create one manually. I created a project, created second branch, deleted it, then removed "deleted_at" from index part on s3, and clicked "reattach pageserver". 

Timeline appeared on pageserver and script found it. It was in active state and deleting it via an API worked as expected. 

Would be good to have second pair of eyes on the script (I think thats for @neondatabase/storage and query (@ololobus could you please take a look?)

**Comment by ololobus** [comment]
> query (@ololobus could you please take a look?)

So query fetches all deleted branches in all non-deleted projects, LGTM

**Comment by shanyp** [comment]
@LizardWizzard is this done already ?

**Comment by LizardWizzard** [comment]
I havent finished all the regions yet, will finish this week

**Comment by LizardWizzard** [comment]
Done
