### ISSUE TITLE
storage_broker has not started yet

### ISSUE THREAD

**Issue by yaoyinnan** [neondatabase/neon#4278]
## Steps to reproduce

When I start neon, I have a problem at the start step.

```
cargo neon init
cargo neon start
```

## Actual result

The error is as follows:

```
    Finished dev [optimized + debuginfo] target(s) in 0.39s
     Running `target/debug/neon_local start`
Starting neon broker at 127.0.0.1:50051.....
storage_broker has not started yet, continuing to wait.........................
command failed: Failed to spawn storage_broker subprocess

Caused by:
    storage_broker did not start in 30 seconds
```

`.neon/storage_broker.log`:

```
2023-05-19T09:58:12.632348Z  INFO version: git:b391c94440de63a05d4f97e5e9d2a2ed18d74559-modified
2023-05-19T09:58:12.634991Z  INFO listening on 127.0.0.1:50051
```

I modified the timeout time to 30s, but still can't start. Please tell me how to troubleshoot and suggest to me how to fix it.

And I confirmed that there are no processes occupying ports (such as 50051) (I feel that I can improve the feature that the cleaning of processes after startup failures).

## Logs, links
-

**Comment by kysshsy** [comment]
How do you solve this problem ? I meet the same problem. It about proxy or ?

**Comment by kysshsy** [comment]
> How do you solve this problem ? I meet the same problem. It about proxy or ?

It's seems that I have not exited processes like pageserver ...
