### ISSUE TITLE
stop accepting empty body in /attach API

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4282]
PR https://github.com/neondatabase/neon/pull/4255 adds the attach-time tenant config capability, but continues to accept the default tenant config for backwards-comaptibility reasons.

Once the corresponding `cloud.git` work to use attach-time tenant config is done, we should error out if the request body is empty and instead require a correct `TenantAttachRequest` object in the body.

Required work (in correct order)

* [ ] Adjust test cases that currently use plain detach + attach (if they don't care, they can continue to use an empty `config={}`
  * Consider requiring the config as an argument to make callers aware that they need to think about this.
* [ ] Make the change
  * ... in `tenant_attach_handler`
  * ... adjust openapi yaml 
  * ... and adjust the `test_empty_body` added in #4255 to expect failure (=> use `NegativeEnv`)
  * remove now-unused `json_request_or_empty_body`

**Comment by problame** [comment]
This will be obsoleted by the move to the upsert location endpoint.

**Comment by hlinnaka** [comment]
If I understand correctly, https://github.com/neondatabase/cloud/pull/10927 removed the last calls of the `/attach` endpoint from the control plane. Can we remove it from the pageserver now?

I think the python tests are still using it though (tenant_attach in test_runner/fixtures/pageserver/http.py). Should they be changed to use the new API? What exactly is the corresponding new API?

**Comment by problame** [comment]
> If I understand correctly, https://github.com/neondatabase/cloud/pull/10927 removed the last calls of the /attach endpoint from the control plane. Can we remove it from the pageserver now?

Yeah, my understanding also is that there shouldn't be any more production users of `/attach`.

> I think the python tests are still using it though (tenant_attach in test_runner/fixtures/pageserver/http.py). Should they be changed to use the new API? What exactly is the corresponding new API?

`.../location_config` is the new API.

Let's take this conversation into the team channel.
