### ISSUE TITLE
Move to use batch operations to delete files from S3

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#4325]
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/4461
- [ ] Batch DeleteOp's from UploadQueue
```

**Comment by jcsp** [comment]
Working on this - wip branch that aggregates deletions into a pageserver-wide queue that can generate nice efficient DeleteObjects is here
https://github.com/jcsp/neon/tree/jcsp/deletion-queue

**Comment by jcsp** [comment]
Complete with merge of deletion queue
