### ISSUE TITLE
Report attach failures in pageserver API

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#4344]
Based on conversation here: https://neondb.slack.com/archives/C033A2WE6BZ/p1684854161739799

TLDR: we need to return Failed status instead of `Attached` if tenant is in broken state

**Comment by problame** [comment]
Cross-posting @koivunej 's comment on this from PR review #4321  (would be good to base this work on top of that PR)

https://github.com/neondatabase/neon/pull/4321#discussion_r1205393759

> So right now "not found from s3" tenant on attach will yield broken and is assumed to *stay* broken, as in we will not get rid of the tenant in memory? Confirmed we don't.
> 
> For me the answer seems to be quite simple; just forget everything about the tenant if we never had any possibility of attaching it? Problem will probably be then crash-safety, because we will have the files on disk. It seems even the attach marker was left, so until a manual detach comes we can't make progress even across restarts. This is most likely current design.
> 
> I am unsure if we *need* to focus on solving the "tried to attach tenant from different region" issue.

**Comment by koivunej** [comment]
Note this is already causing rare flakyness on #4321 so I am thinking we cannot yet release this: https://github.com/neondatabase/neon/pull/4321#issuecomment-1566729898.

**Comment by koivunej** [comment]
Solution in #4321 ended up as [d6d0c74](https://github.com/neondatabase/neon/pull/4321/commits/d6d0c74c0699a3ff0c7c977a4c46c29754c589f0) which was:
- use the `attachment_status` of the state from which we transitioned to `Activating` (loading or attaching)

**Comment by LizardWizzard** [comment]
I'll pick this up once #4321 is merged
