### ISSUE TITLE
`pageserver_tenant_synthetic_size` not available in metrics

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#4347]
## Steps to reproduce

In a default setup of page server using `cargo neon`, this metric is not reported. Probably the background job is not triggered frequently enough.

(But this data is available in the production / staging Grafana cloud)

## Logs, links
-

**Comment by koivunej** [comment]
You need to configure a metric collection endpoint. It does not have to be an actual metric collection endpoint, basically any hopefully not used port will do. By configuring it, then the on the metric collection interval synthetic size will get calculated and metrics published: https://github.com/neondatabase/neon/blob/2b25f0dfa08ec1f6d6f73fd08481571f406c437d/pageserver/src/bin/pageserver.rs#L392

**Comment by skyzh** [comment]
Thanks! Then I should enable this by default in benchmarks...
