### ISSUE TITLE
IO under TENANTS.write() lock in attach_tenant

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#4357]
## Steps to reproduce

In [attach_tenant](https://github.com/zenithdb/zenith/blob/e5617021a7b08000733c122fa487c22fde85c026/pageserver/src/tenant/mgr.rs#L501) closure passed to tenant_map_insert does a lot of IO, and tenant_map_insert is holding TENANTS.write() while executing the closure, which is not good.

TENANTS map is used to retrieve a tenant to establish page_service connection. Latency spike in this scenario is undesirable. 

## Expected result

No IO under write lock

**Comment by shanyp** [comment]
P3 S2
