### ISSUE TITLE
SNI Issue in Elixir

### ISSUE THREAD

**Issue by datduyng** [neondatabase/neon#4367]
## Steps to reproduce
<div dir="auto"><br><br>Hi team,<br><br>I couldn't get my Elixir app working with Neon tech.&nbsp;<br><br><span style="color:#c6c9cd;font-family:Inter, -apple-system, system-ui, Segoe UI, sans-serif;font-size: 14px"></span><span style="font-size: 14px"><br></span><span style="font-size: 14px"><br></span><span style="font-size: 14px"><br></span>I have found several resources below<br><a href="https://neon.tech/docs/connect/connectivity-issues" target="_blank">https://neon.tech/docs/connect/connectivity-issues</a><br>

Postgrex | Elixir | ✓ (configure ssl_opts with server_name_indication)
-- | -- | --

<br>But the option doesn't work for me. I have tried<br></div><ul><li>postgres://&lt;USERNAME&gt;:&lt;PASSWORD&gt;@ep-plain-262670.us-east-2.aws.neon.tech/neondb?sslmode=require</li><li>postgres://&lt;USERNAME&gt;:&lt;PASSWORD&gt;@ep-plain-262670.us-east-2.aws.neon.tech/neondb</li><li>postgres://&lt;USERNAME&gt;:&lt;PASSWORD&gt;@ep-plain-262670.us-east-2.aws.neon.tech/neondb?sslmode=require&amp;options=endpoint%3Dep-plain-262670</li><li>postgres://&lt;USERNAME&gt;:&lt;PASSWORD&gt;@ep-plain-262670.us-east-2.aws.neon.tech/neondb?sslmode=verify-full&amp;options=endpoint%3Dep-plain-262670</li></ul><div dir="auto"><br><br>But I saw the same result<br><br><br><br></div>
## Error saw

```
11:10:38.916 [error] GenServer #PID&lt;0.317.0&gt; terminating ** (Postgrex.Error) ERROR XX000 (internal_error) Endpoint ID is not specified. Either please upgrade the postgres client library (libpq) for SNI support or pass the endpoint ID (first part of the domain name) as a parameter: '?options=endpoint%3D&lt;endpoint-id&gt;'. See more at https://neon.tech/sni (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2 (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5 (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3 Last message: nil State: Postgrex.Protocol
```

```
11:19:16.854 [error] GenServer #PID&lt;0.1887.0&gt; terminating ** (DBConnection.ConnectionError) tcp connect (ep-plain-262670.us-east-2.aws.neon.tech:5432): non-existing domain - :nxdomain (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2 (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5 (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3 Last message: nil State: Postgrex.Protocol
```

## Environment

- `MacOS M1`
- 
```
elixir -v 
Erlang/OTP 23 [erts-11.2.2.17] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
```

-   `"postgrex": {:hex, :postgrex, "0.15.5",`

## Logs, links
-

**Comment by danieltprice** [comment]
@datduyng I hope you got it working. We have a new Elixir guide, here:
https://neon.tech/docs/guides/elixir-ecto
Also, there are a couple of posts in the Community forum on Elixir/Ecto.
https://community.neon.tech/t/elixir-phoenix-connection-failed/596
https://community.neon.tech/t/guide-on-connecting-via-ecto/75
