### ISSUE TITLE
Implement dynamic extension loading in compute_ctl

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#4420]
Based on [RFC](https://github.com/neondatabase/neon/pull/4158)

1. Download control files from `s3-bucket/public/*.control` to `SHAREDIR/extension`

SHAREDIR path can be found with `pg_config --sharedir`

We can do this step even before we have spec, because public extensions are common for all projects.

2. After we have spec, before project start

Download control files from `s3-bucket/[tenant-id]/*.control` to `SHAREDIR/extension`

3. After we have spec, before postgres start

Download preload_shared_libraries from 
`s3-bucket/public/[library-name].control` and `s3-bucket/public/[library-name].control` into  `LIBDIR/`

LIBDIR path can be found with `pg_config --libdir`

4. After postgres start
TBD

**Comment by awestover** [comment]
question: do we actually want the extensions to be separated by postgres version?

**Comment by ololobus** [comment]
Closing as it's marked as done
