### ISSUE TITLE
re-enable the relocation e2e tests that we disabled in https://github.com/neondatabase/neon/pull/4371#discussion_r1219826402

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4434]
https://github.com/neondatabase/cloud/pull/5321 disabled e2e tests so we can merge breaking change https://github.com/neondatabase/neon/pull/4371

Re-enable the tests after it is merged and cloud.git updated (probably int the same PR)

Slack: https://neondb.slack.com/archives/C057TSC1VJP/p1686064375484949?thread_ts=1686058586.099679&cid=C057TSC1VJP

**Comment by NanoBjorn** [comment]
btw already enabled in https://github.com/neondatabase/cloud/commit/e204022fb0d9bba1b9cf2370901fb7064ae726f7#diff-69c1cdfce8d8c87576780f0b1c80fffa979cbe397137d85ce877530d42d1588f
