### ISSUE TITLE
flush loop not running during bootstrap / basebackup (?)

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#4507]
> But the flush loop isn't running yet in these cases.
> 
> So, I'm wondering, what actually happens at runtime if the bootstrap / basebackup import fills up the first open layer. What turns it frozen? Is anything flushing?

Hmm, I guess nothing is flushing during those operations. That's fine when the imports are small, but we'll need to fix that when we expose the import functionality to end users...

_Originally posted in https://github.com/neondatabase/neon/issues/4474#issuecomment-1588144406_

**Comment by koivunej** [comment]
The flush loop is running and causing double retry attempt during bootstrap: https://github.com/neondatabase/neon/blob/682dfb3a31ad13fd70b1d05fb099e4f54f93bf4e/pageserver/src/tenant.rs#L2676

For branched timelines this is not easy to find. Surely we are starting it? :) I'll test this, seems critical enough.
