### ISSUE TITLE
authenticate the remaining storage interactions

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#451]
In #323 not all interactions were covered with authentication support because of ongoing refactoring of walproposer/walacceptor networking. So authentication was added to the following interactions:
* zenith cli <-> pageserver
* compute postgres <-> pageserver

The remaining parts are:
* compute postgres <-> safekeeper
* safekeeper <-> pageserver

Now safekeerer <-> pageserver part uses "hardcoded" token in passed to safekeeper via environment variable. Safekeeper should validate the token against distributed public key and pass it to pageserver in connections. 

Should be done after #117

**Comment by stepashka** [comment]
closing this as dup of https://github.com/neondatabase/neon/issues/1854
please reopen if you think something else is missing
