### ISSUE TITLE
Replication consistency issues

### ISSUE THREAD

**Issue by MMeent** [neondatabase/neon#4516]
## Steps to reproduce
See https://community.neon.tech/t/are-read-replicas-available-in-tech-preview/218/5

## Expected result
No consistency issues

## Actual result
consistency issues

## Logs, links
- 

## hints

We might be seeing issues because of our manual XLOG_CHECKPOINT_SHUTDOWN record. 
On hot standby nodes, we might instead need to use XLOG_CHECKPOINT_ONLINE records; because XLOG_CHECKPOINT_SHUTDOWN means there are no running transactions, even if the primary has running transactions. I'm not sure about that, though - it wouldn't explain the 2x larger count(*).

**Comment by vadim2404** [comment]
closed with #4579
