### ISSUE TITLE
Enable pg_bouncer for Zenith users 

### ISSUE THREAD

**Issue by mklgallegos** [neondatabase/neon#457]
Context

While discussing enabling postgREST during a staff meeting on 2021-08-23 (https://www.notion.so/zenithtech/Staff-Meeting-2021-08-23-2e4c4e76c53f4ea692c05d5715b01d8d) in the context of Cloudflare (https://www.notion.so/zenithtech/Initial-Cloudflare-integration-discussion-with-Greg-McKeon-on-2021-08-17-7ef7748349a34dac84e698994ee7407a) Heikki mentioned we'll probably also need a way for users to enable pg_bouncer.

I'm creating this issue as a placeholder for discussing how to enable pg_bouncer for Zenith users

CC: @hlinnaka , @kelvich , @nikitashamgunov

**Comment by x4m** [comment]
BTW, consider [Odyssey](https://github.com/yandex/odyssey) - scalable connection pooler for PostgreSQL. PgBouncer is single threaded.

**Comment by kelvich** [comment]
The discussion moved to https://github.com/neondatabase/cloud/issues/1604

(for @x4m: most likely we'll use Odyssey, tried using pgbouncer and immediately stepped on a few issues)

**Comment by x4m** [comment]
Cool! Just in case - I'd be happy to sprinckle some commit bits.

**Comment by x4m** [comment]
JFYI https://github.com/neondatabase/cloud/issues/1604 is closed from me.
