### ISSUE TITLE
Ability to unload inactive tenants from memory (no layer map, etc)

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#4575]
The problem is that we can have tens of thousands of tenants on pageservers. Keeping everything in memory seems wasteful.

From the graphs I see that memory usage grows continuously from the time of restart:

![Image](https://github.com/neondatabase/neon/assets/19991702/9d8f96eb-892d-42fa-a264-295f93b38beb)

Pageserver on the graph has ~18k tenants.

So the suggestion is to unload inactive tenants. Maybe put them to some "low energy" mode when layer map is unloaded for example. We can look at active compute connections and replication lag. 

Note that we still have background tasks, such as compaction, gc, consumption reporting. We can either shut them down too, or schedule some sort of wakeups so the work is still done, but much less frequently.

- [ ] Verify where this usage comes from
- [ ] Implement the fix

related #4576

**Comment by jcsp** [comment]
This was achieved by detaching tenants from pageservers entirely
