### ISSUE TITLE
Do not require compute restart to change pageserver connection string

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#4578]
Most of the relocation time is spent to stop/start compute endpoints. Lets avoid that.

We can still detach tenant from pageserver compute is being connected to. (I think this is fine, need to discuss it).

At this point reconnections on smgr side should hide the disconnects from user.

When attach is completed we change the connection string and restart compute.

For that we need to add support in postgres to allow changing this config variable with SIGHUP.

Context:  https://neondb.slack.com/archives/C03H1K0PGKH/p1687866020116189

**Comment by jcsp** [comment]
Unassigning self: we think it makes sense for the compute team to do this work, pending @vadim2404 confirming.

**Comment by knizhnik** [comment]
Pageserver connection string is defined now as PGC_POSTMASTER GUC "neon.pageserver_connstring".
To be able to change it with `alter system` `pg_reload_conf` it is necessary to change it to PGC_SIGHUP.
Is it the only thing which should be done in this ticket?
If so, why it was not addressed in 3 month?
I can create online PR...

**Comment by stepashka** [comment]
notes from Nov 6th 2023:
this is worked by Sasha in compute team, but for visibility putting 'in progress' in Storage team project too.

**Comment by vadim2404** [comment]
@save-buffer has already merged these changes

**Comment by jcsp** [comment]
A change landed, but it doesn't fully work yet -- keeping this ticket open to track that.

https://github.com/neondatabase/neon/pull/5693

**Comment by jcsp** [comment]
completed in https://github.com/neondatabase/neon/pull/5693
