### ISSUE TITLE
Optimize postgres startup

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#4609]
Part of https://github.com/neondatabase/cloud/issues/5315

Postgres startup takes 180ms on average in prod, but 20-30ms on my laptop (emulating latency changes nothing). So we can do a lot better.

Evidence that postgres startup is 180ms: Currently on the free tier the `config_ms` metric shows about 180ms p50. This metric effectively measures startup time of postgres itself (see https://github.com/neondatabase/neon/pull/4608 for why it's called `config_ms`). I'm looking at p50, not p90 because p90 is skewed by first starts of projects, where the actual config time takes a lot.

So what could be the difference between my fast laptop and the slow prod startups? My first theory was about difference in allocated CPUs, so I ran an experiment with different vCPU configs on staging and measured the time spent on postgres startup during cold start. Results are strange:
```
1/4 vCPU: 187ms
1/2 vCPU: 184ms
1 vCPU: 55ms
2 vCPU: 78ms
3 vCPU: 102ms
```

It's not surprising to see 1 vCPU is faster than 1/2 vCPU, but why is it faster than 3 vCPU? Maybe postgres notices and starts more threads, which takes time? I don't know. These numbers make no sense to me so I ran each test a few times to confirm, but there isn't much noise.

So I guess we can win 130ms of startup time by giving the pod 1vCPU for the first 100ms, regardless of compute budget. But maybe this is worth investigating? And still, my laptop starts postgres in 20-30ms, so there's room for something better.

cc @hlinnaka @sharnoff is there an obvious explanation I'm missing?

**Comment by knizhnik** [comment]
> but why is it faster than 3 vCPU?
Is there the same amount of memory or it is proportional to number of CPUs?
Postgres doesn't somehow take in account number of available core  and do not start threads at all (only backends).
And number of spawned process is the same. May be spawned processes compete with each other and it cause larger time on host with more vCPUs, but I do not think that it can explain such difference.

In any case 20msec or 180msec are much smaller than total time of spawning new compute. As fas as I understand even with all this VM pools and other optimisations is it still seconds and not milliseconds.

**Comment by bojanserafimov** [comment]
> As fas as I understand even with all this VM pools and other optimisations is it still seconds and not milliseconds

Non-first starts are about [800ms](https://neondb.slack.com/archives/C04BLQ4LW7K/p1686961212850849) with pools if you ignore the bug with sni routher (or maybe it's something else).

**Comment by bojanserafimov** [comment]
Some logs with ms timestamps:
```
2023-07-05 01:17:39.371 GMT [18] LOG:  [NEON_SMGR] using storage auth token from NEON_AUTH_TOKEN environment variable
2023-07-05 01:17:39.562 GMT [18] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-07-05 01:17:39.562 GMT [18] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-05 01:17:39.562 GMT [18] LOG:  listening on IPv6 address "::", port 5432
2023-07-05 01:17:39.563 GMT [18] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-05 01:17:39.564 GMT [22] LOG:  [ZENITH] found 'zenith.signal' file. setting prev LSN to 0/3F4C760
```

**Comment by hlinnaka** [comment]
> It's not surprising to see 1 vCPU is faster than 1/2 vCPU, but why is it faster than 3 vCPU? Maybe postgres notices and starts more threads, which takes time? I don't know. These numbers make no sense to me so I ran each test a few times to confirm, but there isn't much noise.

Weird. There are no per-CPU structures in PostgreSQL, it doesn't even know how many CPUs you have.

**Comment by bojanserafimov** [comment]
Btw basebackup time also drops from 100ms to 50ms when I increase CPUs from 0.25 to 1

**Comment by bojanserafimov** [comment]
Yeah I'd guess it's either one of the extensions, or just memory allocation.

@hlinnaka I'm not sure what's our process for patching postgres.. would it be feasible to add [these](https://github.com/neondatabase/postgres/compare/startup-logging?expand=1) logs to staging for a week so we can collect some data? I think they'd be enough since they cover everything that looks important between the two log lines that currently have a 200ms gap.

Also, turns out that as a side effect of the interaction of pooling and vms, we'll get 1 vCPU during startup for all pods, so runtime will drop to 55ms. But still, it can probably be even lower, and p90 might still be large so it's worth investigating.

**Comment by hlinnaka** [comment]
> @hlinnaka I'm not sure what's our process for patching postgres.. would it be feasible to add [these](https://github.com/neondatabase/postgres/compare/startup-logging?expand=1) logs to staging for a week so we can collect some data? I think they'd be enough since they cover everything that looks important between the two log lines that currently have a 200ms gap.

Sure.

> If yes, which branch should I send to?

1. Open a PR in [neondatabase/postgres](https://github.com/neondatabase/postgres/) against `REL_15_STABLE_neon` branch
2. Open another PR in [neondatabase/neon](https://github.com/neondatabase/neon/) against `main` branch, for the submodule update.
3. Merge both PRs.
