### ISSUE TITLE
Does PageServer support sharding and distribution?

### ISSUE THREAD

**Issue by yaoyinnan** [neondatabase/neon#4650]
Hello, I am very interested in Neon and I have some questions to ask.

Does PageServer support sharding and distribution? Is it possible to put a user's cached data on multiple PageServers, configure one Compute as a write node for a user, and multiple Computes as read-only nodes, and distribute the read and write pressure on different PageServers? And whether PageServer can achieve IO isolation and resource control among multiple users?

**Comment by shanyp** [comment]
Yes these are on our roadmap

**Comment by yaoyinnan** [comment]
Oh, this is very important.
Is there a roadmap/future planning document that I can look into?

**Comment by shanyp** [comment]
not at the moment, once we will have such will let you know

**Comment by yaoyinnan** [comment]
@shanyp Hello, I have a question to ask, does Neon currently support one master and multiple slaves of Pageserver?

After the Safkeepers persist the WAL, they send the Safekeeper metadata information and Timeline information to the Storage Broker. After the Pageserver obtains the metadata information and Timeline information from the Storage Broker, it pulls the WAL data from the corresponding Safekeeper and persists it. Then I can configure two Pageserver nodes to correspond to a Compute node, and one of the Pageserver nodes only caches data after local persistence, and does not back up data to S3. This node is used to relieve the pressure of multiple computing nodes accessing the Pageserver. Is this scenario reasonable? Does Neon currently support this scenario? Is there a way to test configuration deployment for my reference?

Thank you very much.

**Comment by shanyp** [comment]
@yaoyinnan This is something that we have on our backlog will let you know when and if we execute on it

**Comment by jcsp** [comment]
Tenant sharding across pageservers is/was these epics:
- https://github.com/neondatabase/neon/issues/5507
- https://github.com/neondatabase/neon/issues/6288
- https://github.com/neondatabase/neon/issues/6278
- https://github.com/neondatabase/neon/issues/6342
