### ISSUE TITLE
timeline compaction kmerge_by not necessarily ascending

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#4666]
## Steps to reproduce

https://github.com/neondatabase/neon/blob/20137d9588c78b8b119087dcab2b4f00099f9463/pageserver/src/tenant/timeline.rs#L3639

We are applying some manual rules about Ok and Err, and this might lead to incoming data not ascending, causing problems for the merge process. For example,

```
iter 1: 1, 2, 4, Err, 5
iter 2: 3, 6, 7, 8
```

If the implementation of k_merge is using the binary heap, then Err will always be the top element, and we might be safe to do so. Otherwise, there might be some issues.

Probably we should just implement our own merge iterator.

## Logs, links
-

**Comment by skyzh** [comment]
should already be fixed by @arpad-m in one of the PRs? could you please link the PR, thanks!

**Comment by arpad-m** [comment]
The PR that did this was #4839, although it sorts by only the key, which might not be great either. I've filed #4918 to get back the old behaviour (without Ok/Err processing).
