### ISSUE TITLE
proxy: memory leak

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#4672]
Summarizing discussion after #4612 @conradludgate noticed that Peak RSS grows up to gigabytes during the lifetime of proxy sessions. While our metrics are very coarse (no anon pages metric on proxies) it was noticed that in [`proxy_pass`](https://github.com/neondatabase/neon/blob/76b1cdc17e2e5f212f30de3515585ff78028678f/proxy/src/proxy.rs#L476) we never clear the metrics, contributing or causing the memory leak.

We use the collected metrics as part of billing, so we cannot immediatedly drop them, we need some grace period, or change how they are read as part of consumption metrics.

Slack thread: https://neondb.slack.com/archives/C04DGM6SMTM/p1688391989363929

**Comment by koivunej** [comment]
My solution idea:

> once the proxy_pass complete/cancel, throw the metric labels into a `tokio::sync::mpsc::channel`, receiver maintains a tokio_util::DelayQueue and removes them from the metrics globals after 15min or so.

15min here is a Harrison-Stetson constant, it should be enough to witness the last values for at minimum once for metric collection.

**Comment by LizardWizzard** [comment]
Will this solution work if we have a new connection after previous one is closed but before expiration of the timeout? Makes sense to have such a test
