### ISSUE TITLE
Replace PathBufs with camino

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#4689]
We shouldn't in general have non-utf8 paths anywhere, like with `RemotePath::object_name` they scare me because it's not that the object has no name, it could also be that it fails to convert to str. See https://github.com/neondatabase/neon/blob/92aee7e07f347a0cc125462705811963ab5c78e9/libs/remote_storage/src/lib.rs#L66-L68

Instead of directly using `std::path::PathBuf`, we should use https://docs.rs/camino/latest/camino/. It's not like we could ever even read a non-utf8 path from a config file; we could only read them from command line arguments or environment (`std::env::var_os` -- luckily only used in `neon_local` and `postgres_ffi`) .

This is a rather large change, yielding hopefully tiny amount of touching everything in pageserver as we use a plenty of PathBufs or otherwise preformatted path names for things which have structured names and `libs/remote_storage`, and it's users (at least safekeeper).

Most likely there is a path to fix this in multiple separate PRs.

**Comment by koivunej** [comment]
Good first issue: while large, it's straightforward; the camino transformation should not add new errors to be handled, but it might move them from "deep within" to "parsing."

**Comment by ameya-deshmukh** [comment]
@koivunej would love to pick this up as my first contribution to Neon!

**Comment by Reminiscent** [comment]
@ameya-deshmukh Hi, just wondering do you still working on this issue?

**Comment by ameya-deshmukh** [comment]
Hey, yes I am! Would you like to collaborate? I'm @/ameya on Discord

**Comment by koivunej** [comment]
Apologies, I had not seen the interest expressed here. Are you able to make progress, did you hit a stumbling block? @Reminiscent @ameya-deshmukh

**Comment by duguorong009** [comment]
I am also interested in taking this issue!

**Comment by koivunej** [comment]
I would start the work on `libs/remote_storage`, then it's callsites should be the easiest step forward. It might be this work already falls naturally into two separate PRs, but a larger is fine. I don't expect any problems there, but it does not mean there cannot be any :) Even finding those problems would be very useful.

**Comment by duguorong009** [comment]
@koivunej 
I started working on this issue.
Can you review the PR & give feedback?
If the first commit is looking good, I will keep working on other crates.(in fact, most of codebase)
