### ISSUE TITLE
proxy: more connection metrics and dashboards

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#4702]
1) Connection latency histogram

From the start of connect_to_compute to the end, measure the duration and add that to a prometheus histogram. This should be the connection time between proxy and compute, no client latencies.

2) Connection error counter

For all unique sets of connection errors (as well as no error), maintain a counter.
Do the same for wake_compute

**Comment by skyzh** [comment]
the first item seems already here in the codebase: https://github.com/neondatabase/neon/commit/2ebd2ce2b6dbc143d2ec4715d3d4caa2cfb5d640

for connections failure, we already have `NUM_CONNECTION_FAILURES` for wake computes; I'll add a new counter that breaks down error reason.

**Comment by conradludgate** [comment]
https://github.com/neondatabase/neon/pull/5464

**Comment by conradludgate** [comment]
Todo: add a cache-miss label to compute latency metrics so we can differentiate.
