### ISSUE TITLE
Data is missing after restarting docker using docker compose?

### ISSUE THREAD

**Issue by xiaocode** [neondatabase/neon#4717]
## Steps to reproduce
my docker compose yaml is:

version: '3'

services:
  minio:
    restart: always
    image: quay.io/minio/minio:RELEASE.2022-10-20T00-55-09Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./data:/data
    command: server /data --address :9000 --console-address ":9001"

## Expected result
data persistence

## Actual result
data missing after restart

## Environment
ubuntu 22.04

## Logs, links
-

**Comment by skyzh** [comment]
This looks more like a minio issue instead of an issue on the Neon side? Feel free to reopen if it is related to Neon.

**Comment by xiaocode** [comment]
I confirm that the minio is working fine.I try to restart each service in docker compose, finally I figured out it is the "compute" service would make data missing after restarting.
I read relate docs, the compute_node would try to create new tenentID and timelineID everytime, how can I select specific tenentID and timelimeID, so I can retrieve the saved data?

**Comment by skyzh** [comment]
IIRC we generally provide compute_node with a spec so that it can retrieve history data from safekeeper + pageserver.
