### ISSUE TITLE
Have separate TCP port in safekeeper for compute and pageserver connections 

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#4730]
## Motivation

A separate port will make it easier to limit access at network level, with e.g. k8s network policies.

## DoD

- you can only use the APIs needed by compute on the compute port
- you can only use per-tenant JWT tokens on the compute port

**Comment by arssher** [comment]
> you can only use the APIs needed by compute on the compute port

The main API is 1) push WAL 2) fetch WAL. First is required by computes, the second by replicas, so this doesn't make much sense... but JWT token separation is ok.

**Comment by arssher** [comment]
done
