### ISSUE TITLE
Don't panic on WAL decoding issues

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#474]
Panicking in the page server is bad, because it's a multi-tenant service. We don't want to bring down the whole server, if there's trouble with one tenant. And even within one tenant, it would be nice if other timelines could continue to work even if we have trouble decoding the WAL on one timeline.

Replace assertions in the page server code with some other kind of errors. Or, make sure that we handle panics gracefully, without bringing down the whole server.

see https://github.com/zenithdb/zenith/pull/473/files#r696018750 for one example.

**Comment by stepashka** [comment]
this is either solved or backlog
