### ISSUE TITLE
Epic: /metrics thinning out

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#4797]
## Motivation

We have too many timeline specific metrics which are straining the infrastructure already.

## DoD

Lower the number of metrics we collect.

## Tasks
- #4768
- #4769
- #4796
  - #4800

### More ideas

- `pageserver_smgr_query_seconds` is still per timeline histogram, possibly the only

Related: #4816

**Comment by shanyp** [comment]
@koivunej can this one be closed ?
