### ISSUE TITLE
Web-driver latencies

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#4851]

**Comment by skyzh** [comment]
The dashboard is ready to view and we can follow up on Slack.

https://neonprod.grafana.net/d/d6f5b99f-2e0f-4c5d-b93d-dbbd3cd9fa0b/websocket-latency?orgId=1
https://neondb.slack.com/archives/C04DGM6SMTM/p1690922228117729

**Comment by skyzh** [comment]
... and the data is from Arthur's neon-lights app.
