### ISSUE TITLE
tests: wait until pageserver is ready in NeonPageserver.start

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#4864]
Context: https://github.com/neondatabase/neon/pull/4856#discussion_r1280496437

TLDR: In tests we sometimes start some operations immediately after calling pageserver.start which leads to flakiness because sometimes pageserver startup sequence is not fully completed quick enough to be invisible for the test. Most often this is the case when real_s3 remote storage backend is used.

The expected solution is to add to pageserver http endpoint that waits for `init_done_rx`. See things around `InitializationOrder`.

Http endpoint can just block, or polling needs to be implemented on python side.

Initially discussed with @koivunej

**Comment by koivunej** [comment]
#5580 already implemented this.
