### ISSUE TITLE
Ideas to ensure comments stay up to date

### ISSUE THREAD

**Issue by patins** [neondatabase/neon#490]
Maybe we can enforce `rustdoc::broken_intra_doc_links` errors in CI to ensure that symbols in docs are valid.

Example of the lint in action when running `cargo doc`:
```
warning: unresolved link to `fasfjdis`
  --> zenith_utils/src/postgres_backend.rs:83:67
   |
83 | /// May not be readable. See [`PostgresBackend::take_stream_in`] [`fasfjdis`]
   |                                                                   ^^^^^^^^^^ no item named `fasfjdis` in scope
   |
```

**Comment by sharnoff** [comment]
This seems like a good idea - AFAIK there's no way to get this to trigger without running `cargo doc`, but we can run with `--no-deps` to avoid some of the extra work. (Still have to 'check' every dependency, but this means we don't *also* generate the documentation)

For the general case of ensuring comments stay up to date (not just doc comments, but arbitrary logical links between the words in a comment and locations in code), I made a tool a while back to handle this, but... it's probably a bit overkill here. It essentially does the equivalent of grepping the codebase for some strings that are expected to match. Happy to discuss more if there's interest, but again... probably overkill. My experience is that it's best suited to large(-ish) projects with very few contributors.
