### ISSUE TITLE
Remove tenant/timeline labels from pageserver metrics

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#4906]
The problem is that it creates >100k different timeseries, and grafana/prometheus isn't fast enough to even add them up to look at the total. So there's no way to look at per-pageserver or just total metrics.

Alternatively, if we really need these, add a fake tenant/timeline called "all" and aggregate there

**Comment by bojanserafimov** [comment]
Check that the metrics aren't used for data pipelines first!

**Comment by koivunej** [comment]
You mean the #4797 -- only one left is `pageserver_smgr_query_seconds`.

**Comment by bojanserafimov** [comment]
> only one left is pageserver_smgr_query_seconds

Yes that's the important one :)

**Comment by koivunej** [comment]
I did not remove it because last I removed a lot #4796, and this is like the last lifeline to debugging production per-timeline issues. I don't think we *need* to remove it. We could close this issue anyways and use the other one.

**Comment by bojanserafimov** [comment]
> I don't think this is a performance issue in any case; the streaming /metrics response should take care of that

This is something that's required for **monitoring** performance in prod. Without it I can't even visualize "average get_page latency per pageserver"

> and this is like the last lifeline to debugging production per-timeline issues. I don't think we need to remove it. 

Can we add a separate metric for per-pageserver get_page latency, which doesn't include per-tenant label? My end goal is just to make the "average get_page latency per pageserver" panel

> We could close this issue anyways and use the other one.

The other one is about the size of metrics. It might involve more work

**Comment by bojanserafimov** [comment]
Update: I have screenshots of this consistently timing out and not working earlier, but works now. I'll reopen if needed
