### ISSUE TITLE
Fix files_created/bytes_written metrics

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#4907]
We [only](https://github.com/neondatabase/neon/blob/d811f1b34ad5352cfe12f7566811f47af715d5df/pageserver/src/tenant/timeline.rs#L2838) update them on flush, and forget to update them on compaction, reimaging, etc

**Comment by Reminiscent** [comment]
Hi, I'd like to fix this issue. Just wondering how to add a test to check the metrics. Are there any test cases I can reference?
