### ISSUE TITLE
Investigate 10x perf difference among pageservers

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#4908]
Some are [10x](https://neonprod.grafana.net/explore?left=%7B%22datasource%22:%22ZNX49CDVz%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22ZNX49CDVz%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28pageserver_smgr_query_seconds_sum%7Binstance%3D%5C%22pageserver-2.eu-central-1.aws.neon.tech%5C%22,%20smgr_query_type%3D%5C%22get_page_at_lsn%5C%22%7D%5B$__rate_interval%5D%29%29%20%2F%5Cnsum%28rate%28pageserver_smgr_query_seconds_count%7Binstance%3D%5C%22pageserver-2.eu-central-1.aws.neon.tech%5C%22,%20smgr_query_type%3D%5C%22get_page_at_lsn%5C%22%7D%5B$__rate_interval%5D%29%29%22,%22range%22:true,%22refId%22:%22A%22,%22interval%22:%22%22%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22ZNX49CDVz%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28pageserver_smgr_query_seconds_sum%7Binstance%3D%5C%22pageserver-0.us-east-2.aws.neon.tech%5C%22,%20smgr_query_type%3D%5C%22get_page_at_lsn%5C%22%7D%5B$__rate_interval%5D%29%29%20%2F%5Cnsum%28rate%28pageserver_smgr_query_seconds_count%7Binstance%3D%5C%22pageserver-0.us-east-2.aws.neon.tech%5C%22,%20smgr_query_type%3D%5C%22get_page_at_lsn%5C%22%7D%5B$__rate_interval%5D%29%29%22,%22hide%22:false,%22range%22:true,%22refId%22:%22B%22,%22interval%22:%22%22%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22ZNX49CDVz%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28pageserver_smgr_query_seconds_sum%7Binstance%3D%5C%22pageserver-2.us-west-2.aws.neon.tech%5C%22,%20smgr_query_type%3D%5C%22get_page_at_lsn%5C%22%7D%5B$__rate_interval%5D%29%29%20%2F%5Cnsum%28rate%28pageserver_smgr_query_seconds_count%7Binstance%3D%5C%22pageserver-2.us-west-2.aws.neon.tech%5C%22,%20smgr_query_type%3D%5C%22get_page_at_lsn%5C%22%7D%5B$__rate_interval%5D%29%29%22,%22hide%22:false,%22range%22:true,%22refId%22:%22C%22,%22interval%22:%22%22%7D%5D,%22range%22:%7B%22from%22:%221691144428035%22,%22to%22:%221691163625379%22%7D%7D&orgId=1) faster than others during some moments, and perf over time fluctuates. Could be due to overload, or there could be something to improve in the pageserver. Not clear yet.

There's no strict dependency, but would be nice to get https://github.com/neondatabase/neon/issues/4906 done first

**Comment by vadim2404** [comment]
cc @shanyp. It impacts computes start-up time.

**Comment by bojanserafimov** [comment]
>It impacts computes start-up time.

This is more about overall get_page perf. If one pageserver is 10x faster than another, then we have 10x optimization opportunity.

Startup time also depends on pageserver (uncorrelated with overall pageserver perf), but it's unclear if that will still be the case after https://github.com/neondatabase/neon/pull/4912

**Comment by shanyp** [comment]
@problame do we already have the get_page slo ?

**Comment by bojanserafimov** [comment]
I made a new [dashboard](https://neonprod.grafana.net/d/f9acf46f-fe3e-4b1d-a3a6-02cd51c3d7f3/ps-perf?orgId=1) using the new metrics that @problame added. Average get page latency ranges from 15us to 500us, depending on pageserver. It's possible that it's caused by difference in workloads, but the gap is stable over time, so probably not. Also there's no obvious correlation with number of requests.

**Comment by problame** [comment]
Closing this because
* staleness
* we have established the per-instance SLOs
* improvements from https://github.com/neondatabase/neon/pull/6574
  * although it likely wasn't an issue when Bojan created this issue
