### ISSUE TITLE
failed to run custom build command for `storage_broker v0.1.0 (/root/neon/storage_broker)`

### ISSUE THREAD

**Issue by thestackdev** [neondatabase/neon#4911]
## Failed to install neon postgres
BUILD_TYPE=release make -j`nproc` -s

## Full error
     Running `/root/neon/target/release/build/storage_broker-f3d2f8aacdfc3644/build-script-build`
error: failed to run custom build command for `storage_broker v0.1.0 (/root/neon/storage_broker)`

Caused by:
  process didn't exit successfully: `/root/neon/target/release/build/storage_broker-f3d2f8aacdfc3644/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto/broker.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'failed to compile protos Custom { kind: Other, error: "protoc failed: broker.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }', storage_broker/build.rs:9:29
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:66: neon] Error 101

## Environment
AWS EC2 AMD64 running ubuntu 22.04

![Screenshot from 2023-08-05 20-51-08](https://github.com/neondatabase/neon/assets/49651332/99928df4-a66c-4212-8e01-4e22dc6f23b9)

**Comment by petuhovskiy** [comment]
```
protoc failed: broker.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set
```

That feature is availabile in protoc 3.15+, so you may need to update protoc to compile neon repo without errors. Some distro repos have only old version of protoc, so you may need to install it manually. Here a command for that:

```
export PROTOC_VERSION=22.2
curl -fsSL "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-$(uname -m | sed 's/aarch64/aarch_64/g').zip" -o "protoc.zip" \
    && unzip -q protoc.zip -d protoc \
    && mv protoc/bin/protoc /usr/local/bin/protoc \
    && mv protoc/include/google /usr/local/include/google \
    && rm -rf protoc.zip protoc
```

**Comment by koivunej** [comment]
Assuming this is good to close, feel free to comment if your issue was not cleared. I am pretty sure the protoc version is on README.md.

**Comment by thestackdev** [comment]
How do I connect a self hosted version in edge runtime
