### ISSUE TITLE
remote_storage metrics: remove deprecated, migrate dashboards

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#4942]
Follow-up to #4892, from PR desc:

- [x] remove the old metrics #4957 
- [ ] migrate dashboards

Removal and migration instructions:

https://github.com/neondatabase/neon/blob/4ce7aa9ffe5524e69187d7d13026d67da07e0e45/libs/remote_storage/src/s3_bucket/metrics.rs#L128-L133

> `sum by (result) (remote_storage_s3_requests_count)` 

This migration suggestion is wrong; the old one included all (succeeded, failed, cancelled) requests, so it would just be sum over all `remote_storage_s3_requests_count` per instance or whatever we want to filter for.

**Comment by jcsp** [comment]
@koivunej is this issue still relevant?

**Comment by koivunej** [comment]
Probably not, the new dashy has been in use for a long time.
