### ISSUE TITLE
Epic: add possibility to warm up tenant after attach [draft]

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#4968]
## Motivation

When migrating huge tenants destination will be initially empty and it can take a lot of time to download the whole working set. It would be way easier if we had some handle to load all last data from S3.

## DoD

[To be discussed]

Pageserver API endpoint and admin UI button to warm up tenant on pageserver

## Tasks
- [ ]

## Other related tasks and Epics
- #4969

**Comment by koivunej** [comment]
Assuming we manage to fix that `create_image_layers` no longer update source layer access times, then it should make layer access stats much more useful and a possibility for this.

**Comment by kelvich** [comment]
```
Dmitry Rodionov
  [1 hour ago](https://neondb.slack.com/archives/C03F5SM1N02/p1691756611235859?thread_ts=1691724821.764719&cid=C03F5SM1N02)
Note that we have a script that downloads everything from s3. Though it can be used only after migration. https://github.com/neondatabase/neon/blob/main/scripts/force_layer_download.py
```

**Comment by LizardWizzard** [comment]
Idea: What if before migration we fetch set of resident layers from pageserver and after migration we pass this list to attach so new pageserver can spawn a task to fetch exactly these layers?

To my mind when we're able to migrate without downtime the mechanism needs no changes

**Comment by jcsp** [comment]
The general approach to this will be https://github.com/neondatabase/neon/issues/5199 -- either put the new pageserver into warm secondary mode before doing the migration, or just go ahead with the migration and let the control plane wait for the new pageserver to catch up with latest LSNs before cutting over.

In that context, I'm not sure we'll need a specific API for warming up.

**Comment by jcsp** [comment]
This is covered with secondary mode now: any time we want to warm up a server before migrating to it, we can just put it into secondary mode
