### ISSUE TITLE
pageserver: use read cursors for faster image generation

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#4979]
**Like all performance work, this needs profiling before prioritizing!**

Currently, the heart of `Timeline::create_image_layers` is a loop over calls to `Timeline::get` -- each of those calls is independently walking the LayerMap, and walking the btree index of each layer to find the data relevant to the key.

This is wasteful in CPU time & memory bandwidth, and may also be generating smaller/slower disk I/O, as currently the approach is fully reliant on the kernel page cache and prefetching to avoid just issuing 8k I/Os and then waiting between each one.

All this can be avoided, since we are walking the key space sequentially, and contents of layers are already sorted by key.

For a tree that is already covered by historical image layers, a rough approach for image generation would be:
- Find the historical image layer that will be the basis for our next range of keys.
- Find all delta layers which have >LSN and overlap in the keyspace with that base image layer
- Open read cursors to the 1 image layer and N delta layers from the last steps
- Iterate: for reach step, pick the layer with the lowest "next" key, and then look forward in LSN order through the "next" keys of upper layers to find the elements needed for wal redo.
- When we reach the end of the base image layer, go back to start and pick, the next base image layer.

All the reads during one phase of that loop just become peeks at the next key in each cursor, rather than index lookups, and we may issue large sequential read I/Os to each layer, buffering data on the cursor.

**Comment by jcsp** [comment]
Since this issue was created, we added vectored gets.

@VladLazar are we already using vectored gets in the image generation path?

**Comment by VladLazar** [comment]
> are we already using vectored gets in the image generation path?

Yes we are, although it could probably do with a bit of tuning https://github.com/neondatabase/neon/blob/63b2060aef39da8e9eb00cda72ff1e99eed2a74d/pageserver/src/tenant/timeline.rs#L3624

Tail latencies for vectored gets done by compaction have improved somewhat in ap-southeast-2, but it's a bit soon to tell: https://neonprod.grafana.net/d/adh0sbkd9hkowc/tmp-vec-get-ap-2?orgId=1

**Comment by jcsp** [comment]
I'm going to close this ticket: it was mainly inspired by the gratuitous inefficiency of doing page-by-page reads.  We might still make this more efficient in future with true streaming here, but I don't think we need to track it.
