### ISSUE TITLE
pageserver: abort compactions in progress when timeline is deleted

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#4998]
This showed up in https://github.com/neondatabase/neon/pull/4992 as a test timing issue, but really the test was reasonable to expect deletion to be fast: the problem is that compaction isn't checking the tenant status enough to drop out promptly.

For example, in that test, the compaction was busy in the `compact_level0_phase1` function's big loop over keys: that loop needs to check if the timeline is still active (or check some CancellationToken)

Note that we _do_ already stop background tasks, but:
- Compactions aren't only started in those tasks, they can also be started via management API
- Background tasks are stopped gracefully and join()'d, so if inner compaction loops aren't doing some explicit check to drop out if the timeline is inactive, it doesn't help us.

**Comment by LizardWizzard** [comment]
I think this applies not only to deletions but to the whole shutdown thing. Deletion uses Tenant::shutdown. So by fixing shutdown deletion will be fixed too.

**Comment by jcsp** [comment]
This is probably fixed now, we added a bunch of cancellation token checks.
