### ISSUE TITLE
Get rid of EphemeralFile::ephemeral_files_id

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5038]
Do we need a separate ephemeral file ID and page cache file ID, or could they be the same?

_Originally posted by @hlinnaka in https://github.com/neondatabase/neon/pull/4994#discussion_r1295806972_

**Comment by Reminiscent** [comment]
Hi, I'd like to try this issue.

**Comment by hlinnaka** [comment]
@problame commented at https://github.com/neondatabase/neon/pull/4994#discussion_r1297392911:

> This PR maintains the separate IDs for the sole purpose of file names: https://github.com/neondatabase/neon/commit/e0b8785f72f9dd9a588e203b556fc97f23eaadf2
>
> I'd prefer if we don't intermingle these.

Hmm, looking at the code as it is in 'main' now, I don't see a separate "ephemeral file id" anymore. I guess that you renamed it `NEXT_FILENAME` counter. I think that helped to reduce the confusion already.

We could replace NEXT_FILENAME with the page cache file ID. Might be handy during debugging that you could see the file ID directly in the filename. But doesn't really matter much.

**Comment by Reminiscent** [comment]
@hlinnaka Thanks for your explanation. I think you are right. I'll try other issues.

**Comment by koivunej** [comment]
@problame could you update this to reflect current state and perhaps restore good_first_issue, or close?
