### ISSUE TITLE
pageserver: clean up backoff::retry calls without cancellation tokens

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5066]
Everywhere we are waiting on the wall clock, we should be carrying a CancellationToken to enable prompt shutdown.

In https://github.com/neondatabase/neon/pull/5065, there are placeholders for call sites that did not currently have a CancellationToken handy -- all these should get a real CancellationToken.

**Comment by koivunej** [comment]
I have a related PR on semaphore waiting.
