### ISSUE TITLE
Epic: provide pg_partman extension

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#5116]
## Motivation
users requested this

## DoD
pg_partman is available on neon

```[tasklist]
### Tasks
- [ ] Add a task or an issue reference here
```

## Other related tasks and Epics
-

**Comment by meaweaw** [comment]
I can't find pg_partman in extensions.

**Comment by acervantes23** [comment]
@meaweaw https://github.com/pgpartman/pg_partman

**Comment by meaweaw** [comment]
> @meaweaw https://github.com/pgpartman/pg_partman

@acervantes23 Sorry. I mean not found in neon.
[https://neon.tech/docs/extensions/pg-extensions](url)

**Comment by vadim2404** [comment]
@lubennikovaav to enable it

**Comment by vadim2404** [comment]
to move this extension to our docker image

**Comment by andreasscherbaum** [comment]
Still needs to be added to the Docker image

**Comment by andreasscherbaum** [comment]
Not in the old compute image which is currently pinned, we need to roll out new compute first.

**Comment by andreasscherbaum** [comment]
@save-buffer Please confirm that this is available now, and what other work is still required.

**Comment by save-buffer** [comment]
It merged so it should be available with the next compute release
