### ISSUE TITLE
Epic: [Proxy] Removal of opt-in from JSON endpoint

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#5123]
## Motivation
We need to make our endpoint GA.

## Tasks
- [x] #4698
- [x] #4699
- [x] #4709
- [x] #4703
- [x] #4735
- [ ] roll out it region-by-region

**Comment by vadim2404** [comment]
@conradludgate 
to add flag this week

Roll out will start on the week after the off-site

**Comment by vadim2404** [comment]
not done yet

**Comment by conradludgate** [comment]
https://github.com/neondatabase/aws/pull/843 removing opt-in flag in a couple of regions

**Comment by vadim2404** [comment]
it will be released at the same time with this issue #5705

**Comment by vadim2404** [comment]
@conradludgate to merge AWS PR
we can close the issue when the proxy will be deployed (next week release)
