### ISSUE TITLE
test_wal_lagging is flaky on Postgres 16

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#5305]
Test `test_wal_lagging` is flaky on Postgres 16 exclusively.
```
Failed: Timeout >300.0s
```

- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5301/6172082327/index.html#/testresult/c48772cfc6967aec
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/6164926317/index.html#/testresult/cab3f89489f79109

**Comment by bayandin** [comment]
https://neon-github-public-dev.s3.amazonaws.com/reports/main/6226128309/index.html#/testresult/3acbb2257e5c4ca9

**Comment by koivunej** [comment]
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5919/6982388865/index.html#suites/6e36553ef86e9ad135df2bdcdce89d33/db99f877bea4b86b

Nothing else is suspicious in the logs, except that the logged term history grows -- probably this has some limit.. It is unclear what the execution was waiting for.

**Comment by alexanderlaw** [comment]
I could reproduce this (slow test execution for release-pg16) on 831fad46d. For example, I'm observing the following timings (which can be easily increased when running tests concurrently):
```
DEFAULT_PG_VERSION=16 BUILD_TYPE=release poetry run pytest test_runner/regress/test_wal_acceptor_async.py::test_wal_lagging
======================== 1 passed in 161.63s (0:02:41) =========================

DEFAULT_PG_VERSION=15 BUILD_TYPE=release poetry run pytest test_runner/regress/test_wal_acceptor_async.py::test_wal_lagging
============================== 1 passed in 39.95s ==============================
```

The last commit I see such a difference on is b701394d7~1. Starting from b701394d7, v16 performs as fast as v15:
```
DEFAULT_PG_VERSION=16 BUILD_TYPE=release poetry run pytest test_runner/regress/test_wal_acceptor_async.py::test_wal_lagging
============================== 1 passed in 26.14s ==============================

DEFAULT_PG_VERSION=15 BUILD_TYPE=release poetry run pytest test_runner/regress/test_wal_acceptor_async.py::test_wal_lagging
============================== 1 passed in 20.06s ==============================
```

So maybe this issue should be closed as resolved by https://github.com/neondatabase/neon/pull/6179.

**Comment by bayandin** [comment]
Nice, thanks for digging into it @alexanderlaw!
