### ISSUE TITLE
Add build_tag to set_build_info_metric

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#5306]
Currently, we return only revision of a service in `libmetrics_build_info`:
https://github.com/neondatabase/neon/blob/ffd146c3e519ace5f14b619ca63f00ca9dda4b56/libs/metrics/src/lib.rs#L92-L100

See a grafana dashboard (with deployed revisions):
https://neonprod.grafana.net/goto/EQUiO5iSg?orgId=1

To make it more useful, let's add a build_tag to the metric, then it'll easier to find a corresponding release in https://github.com/neondatabase/neon/releases

Required changes:
- Add BUILD_TAG env var support to all services
- Add  build_tag to libmetrics_build_info

**Comment by problame** [comment]
For Rust at least, I think the BUILD_TAG should be baked into the binary, not supplied via env var to the process.

**Comment by bayandin** [comment]
> I think the BUILD_TAG should be baked into the binary, not supplied via env var to the process.

It is baked into the binary.
Env var is used to supply the version on the build stage.

**Comment by duguorong009** [comment]
I would like to pick this task!

@bayandin 
Can you review the draft PR #5576?
Thanks in advance!

**Comment by duguorong009** [comment]
@bayandin 
Can you take some time to review the PR #5576?
