### ISSUE TITLE
test_gc_cutoff: VirtualFile::crashsafe_overwrite fails in tests

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5329]
Example: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5327/6208533255/index.html#/testresult/13cedbbb13de601c

```
2023-09-16T17:09:12.499700Z ERROR gc_loop{tenant_id=1fca66b1f4aee8af9024b011721d05ce}: Gc failed, retrying in 2s: save_metadata

Caused by:
    0: write metadata
    1: rename tempfile to final path: No such file or directory (os error 2)
    2: No such file or directory (os error 2)
```

VirtualFile::crashsafe_overwrite was introduced in #5186.

**Comment by koivunej** [comment]
Looking at #5186 the implementation is good. In the log there's an above inmemory layer flush happening at the same time. So we have an actual race to update metadata file, since we use a fixed tempfile suffix, and a concurrent `save_metadata` is first removed before an update. Perhaps this has always been the behaviour but recent changes just made this possible to notice.

Probably does not need anything, since I am soon looking to remove local metadata in #5172.

**Comment by problame** [comment]
> Probably does not need anything, since I am soon looking to remove local metadata in https://github.com/neondatabase/neon/issues/5172.

+1 , let's just 🔥  it
