### ISSUE TITLE
View to view local file cache contents doesn't work

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#5347]
## Steps to reproduce

```
postgres=# create extension neon;
CREATE EXTENSION
postgres=# select * from local_cache;
ERROR:  no hash_seq_search scan for hash table "lfc_hash"
```

**Comment by hlinnaka** [comment]
Per comments on `hash_seq_term`:
```
 * hash_seq_term should be called if and only if the scan is abandoned before
 * completion; if hash_seq_search returns NULL then it has already done the
 * end-of-scan cleanup.
```
Looking at `local_cache_pages`, it's incorrectly calling `hash_seq_term` also when end-of-scan is reached.

And looking at `lfc_disable`, it has the same bug. So the "disable" mechanism seems broken in a dangerous way

**Comment by knizhnik** [comment]
Sorry, just recently added calls of `hash_seq_term` - didn't notice the comment:(

**Comment by tristan957** [comment]
I actually had this same bug in some code I wrote too, and had to figure it out. Solidarity in not reading :+1:

**Comment by hlinnaka** [comment]
This has been fixed.
