### ISSUE TITLE
Improve CrashsafeOverwriteError source printing

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#5366]
Currently, the `CrashsafeOverwriteError` enum looks like this:

https://github.com/neondatabase/neon/blob/d8977d519972331016fa1a516f1ca3e3766bacde/pageserver/src/virtual_file.rs#L177-L194

@koivunej [has pointed out](https://github.com/neondatabase/neon/pull/5186#discussion_r1314761053) that we do duplicate work here: we both format the error and also add the source. Ideally, only one of the two things is done.

**Comment by rmodpur** [comment]
I tested removing `{0}` but keeping the `#[source]` it doesn't result in duplication when using `{:#}` but on using `{}` it will only print `remove tempfile` for `RemovePreviousTempfile` not the associated `std::io::Error` which may make debugging difficult. Should i instead remove `#[source]` and keep `{0}` (this will not give caused by when using `{:?}`  because of removal of `#[source]`)

**Comment by arpad-m** [comment]
This is an example of the errors we have: #5329

**Comment by koivunej** [comment]
The example duplication happens when using either:
- `anyhow::Error` as "reporter" like we sadly do in many places, while capturing a stacktrace at the error conversion
- `utils::error::report_compact_sources`

Example of the first:

```
2023-09-27T11:50:48.852455Z ERROR request{method=GET path=/v1/tenant/X/timeline/Y request_id=acde6d1f-ada5-417e-ac4d-21b055d66cb3}: Error processing HTTP request: InternalServerError(Tenant X is not active
Stack backtrace:
   0: pageserver::http::routes::<impl core::convert::From<pageserver::tenant::mgr::GetTenantError> for utils::http::error::ApiError>::from
             at /home/nonroot/pageserver/src/http/routes.rs:165:47
      <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1961:27
      pageserver::http::routes::timeline_detail_handler::{{closure}}::{{closure}}
             at /home/nonroot/pageserver/src/http/routes.rs:424:22
...
```

**Comment by rmodpur** [comment]
Ok, i will remove `{0}` and keep the `#[source]`

There are other error enums as well with this type of duplication like
https://github.com/neondatabase/neon/blob/090a6443929915ed92924b6ae2077d0b229f118d/pageserver/src/tenant/mgr.rs#L538-L544

Should i fix these in other error enums as well ?
