### ISSUE TITLE
proxy: review why connection limits are being exhausted

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#5370]
related to #5368 - why are we seeing so many of these errors.

For connections originating from TCP and Websockets, it's most likely a user error.
For connections originating from HTTP, it's more likely an internal error.

We should have a dashboard that makes it clear (per endpoint) how many connections are active at a time, and where the connection originated from

# Implementation ideas

We discussed a few ways this could be implemented.

## Prometheus metric

Counter with endpoint_id and connection_type labels.

Pros: Simple to implement and query.
Cons: high cardinality metrics are bad.

## Log lines

Write a log for each connection opened and closed. We can use Loki to filter these logs and get a time series.

## Postgres

Supposedly we can monitor connection counts from postgres. Maybe it's possible to also see the application name for those connection counts?

We can then set an appropriate application name prefix for all connections through proxy

**Comment by stradig** [comment]
Investigation did not really find anything. Closing.
