### ISSUE TITLE
walredo for pg16 logs `registered custom resource manager "neon" with ID 134`

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5399]
We treat all of walredo's logging as ERROR level, it would be best if these were not logged with walredo.

Example from prod:

```
2023-09-27T05:41:47.890384Z ERROR compaction_loop{tenant_id=X}:compact_timeline{timeline_id=Y}:apply_wal_records{tenant_id=X pid=837258}: wal-redo-postgres: 2023-09-27 05:41:47.890 GMT [837258] LOG:  registered custom resource manager "neon" with ID 134
```

**Comment by koivunej** [comment]
Hmm ok. We don't really do any line detection in pageserver for walredo output BUT it would make sense to parse the messages and detect these INFO's. This will however require either a dedicated background task or more shared state.

**Comment by hlinnaka** [comment]
We could do the equivalent of `set log_min_messages='WARNING'` in the walredo process startup routine to prevent that from being printed. I'm a little surprised that there are no other LOG-level messages printed at walredo process startup though. Normal Postgres startup is quite noisy.

**Comment by problame** [comment]
My take on this from https://github.com/neondatabase/neon/pull/5560#discussion_r1363588503

> => make walredo not log this; walredo should stay quiet unless there's a problem

**Comment by problame** [comment]
fixed in https://github.com/neondatabase/neon/pull/5587
