### ISSUE TITLE
local file cache is not restart safe in some edge cases (SIGKILL of `postmaster`)

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5405]
While developing https://github.com/neondatabase/autoscaling/pull/534 , it was discovered that the local file cache free space monitor can remain running after the rest of the postgres processes is gone, e.g., due to OOM kill.
If something then restarts the postgres process (`init` in the case of NeonVM), the old free space monitor process can interfere with the restarted postgres process.

**Option A**: remove free space monitor.

**Option B**: somehow make the file cache restart safe

**Comment by skyzh** [comment]
I assume this issue has been resolved with https://github.com/neondatabase/neon/pull/5406? (Free free to reopen if I'm wrong)

**Comment by andreasscherbaum** [comment]
It's released
