### ISSUE TITLE
pageserver: investigate baseline 10-316 tenants or timelines without fresh enough metrics

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5433]
Earlier investigation with evidence: https://neondb.slack.com/archives/C04ESKALJB1/p1696242392749039

We should have a baseline of 0 tenants or timelines without fresh enough metrics.

Possible causes:
- sampling:
    - we send every 10min and calculate synthetic size every 10min
    - to get on the linked charts by being over 15min late (assumption)

Metric ideas:
- first collection of a new tenant from it's creation (creates, attaches)

**Comment by jcsp** [comment]
Stale
