### ISSUE TITLE
pageserver: simplified tenant+timeline creation API

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5456]
## Problem

Currently, our API for tenant creation is a bit strange:
- There's a tenant_create path (POST /tenants/tenant_id) that does nothing but create a directory
- A Tenant can't be used for anything meaningful without at least one timeline.
- ~Tenant attach only works if a tenant has had at least one timeline created, _and_ that timeline has been written to remote storage.~ (no longer the case since #5580 )
- ~Newly created tenants (before any timelines) are in a weird state where they really only exist locally on that pageserver, and if you tried to detach/attach such a tenant, it would fail.~ (since #5580, you can ask a pageserver to attach any tenant ID, and it will, even if there are no timelines and nothing in remote storage: the caller (control plane) is the authority for which tenants exist)

## Solution

**Edit:** We can _also_ just get rid of timeline creation if we choose to, and auto-create it on page service calls.  The safekeeper apparently already does this.  We would need to think carefully about deletion.

Things would be simpler if we made tenant creation include creating an initial timeline, and implement it as one remote I/O that uploads the index_part.json for that timeline: it would take the initial timeline parameter as an argument, and it would work like this:
- Create temp directory tenant locally
- Create temp directory timeline locally
- Do initdb
- Upload resulting index_part.json to remote storage.
- (optionally, we can then also attach the tenant, but that's just a normal attach operation that the caller could equally do themselves)

Combined with #5080, this would mean that creating & deleting tenants is no longer coupled with attaching/detaching from a particular pageserver.

**Note**: in order to make this fully atomic, we also need a way to accomodate timelines with no  layer files, so that a timeline that has just uploaded an IndexPart is in a valid loadable state.  Currently if an index contains zero layer files, we throw an error during attach.

This is conceptually aligned with https://github.com/neondatabase/neon/issues/5080 -- both creation and deletion primarily operate on remote storage (the pageserver is an ephemeral cache), and that should be reflected in the API.

**Comment by arpad-m** [comment]
Sounds reasonable to me to move tenant creation into timeline creation, basically glorified `mkdir -p`. We should just watch out that we will still error instead of recreating the tenant if the tenant was deleted previously.

**Comment by rmodpur** [comment]
@jcsp i would like to work on this if it's available

**Comment by rmodpur** [comment]
I was thinking of creating a new API `/tenant/bootstrap` which would do the bare minimum things you described in the issue with an option to `attach` it through a query parameter. If that's not preferred I will try to make the changes in non-breaking way by refactoring the existing tenant creation

**Comment by koivunej** [comment]
I'm currently working on #5172 and as part of that, trying to tweak so that we will always have timelines at the remote before returning `200 OK` but also deny branching and compute startup before that. It is not exactly related but I think there might be issues trying to this *right now*. Maybe after my currently not even draft PR (hopefully this week). I'll try to remember to update this issue.

**Comment by jcsp** [comment]
Currently, the storage controller already "creates" tenants by simply attaching them, taking advantage of the knowledge that creation is a no-op.

I suspect eventually we'll add some tenant-wide metadata (e.g. which timelines are active, to enable selectively loading them), and at that point we can re-visit the need for a separate creation API.
