### ISSUE TITLE
safekeeper test: restart safekeepers while postgres is under the load

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#546]
Run bank transfers test in N connections from one thread.
Our system if described by the following state vector: [compute=on/off, sk1=on/off, .. sk3=on/off].
Bank test can handle disconnects and runs all the time.
Each 10 second other thread chooses next state vector out of 16 possibilities (including ones where no progress should be made).
Test ensures that progress is made where it should and that there no progress is made where it shouldn't be.

**Comment by petuhovskiy** [comment]
Implemented bank test with state vectors where progress can be made (there are only 3 of them) in #591

**Comment by petuhovskiy** [comment]
Initial version is merged in #591, what could be done later:
- Add compute restarts, retries in client code
- Test no progress is made where it shouldn't be
- Add a control coroutine to check that rows in bank_log are not decreasing

**Comment by arssher** [comment]
We have such tests, though need more chaotic testing, closing this issue.
