### ISSUE TITLE
Error handling best practices

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#551]
I wanted to gather thoughts on error handling best practices so we can document that as a kind of a guideline.

Personally, I see that we are sticking to anyhow and this is handy at error site, but at the catch site anyhow errors do not provide a way to distinguish between different error causes because anyhow erases the actual error type. 

There are several approaches to this, we can write needed impls manually (in some cases it even not that much boilerplate). Or use another crate, for example thiserror. It is from the same author as anyhow, but serves different purpose. anyhow being for simple application level errors, and thiserror for structured errors, e.g. in libraries. We actually use thiserror in several places: [walredo](https://github.com/zenithdb/zenith/blob/main/pageserver/src/walredo.rs#L158), [pageserver http api](https://github.com/zenithdb/zenith/blob/main/zenith_utils/src/http/error.rs#L8). Also thiserror is used in our dependencies, see for example [prometheus](https://github.com/tikv/rust-prometheus/blob/master/src/errors.rs).

Thiserror requires error modelling, but if we carefully design our error types we will be able to distinguish between recoverable/unrecoverable errors, we can decide to retry some operations (e.g. when we are out of disk space). So any thoughts on that?

cc @sharnoff You'd mentioned this subject on one of the meetings, so maybe you can add something

**Comment by sharnoff** [comment]
After taking a while to think about this, I have a few thoughts.

@LizardWizzard It seems like the direct issue you raised here is wanting to be able to determine how far up to unwind from an error. This is _somewhat_ related to the question of error severity (see @hlinnaka's comment in #585), but I think solutions are going to end up providing orthogonal functionality.

In any case, we can do a significant amount of this with `anyhow`. The [`is`](https://docs.rs/anyhow/1.0.44/anyhow/struct.Error.html#method.is) and [`downcast_ref`](https://docs.rs/anyhow/1.0.44/anyhow/struct.Error.html#method.downcast_ref) methods both check the attached contexts **and** the base error, which gives us a lot of freedom. Naively checking for whether we ran out of space could be written like:

```rs
use anyhow::Error;
use std::io;

fn is_out_of_space(err: Error) -> bool {
    err.downcast_ref::<io::Error>()
        .map(|e| e.kind() == io::ErrorKind::StorageFull)
        .unwrap_or(false)
}
```

We could also write wrapper types to signify different error causes that we might want to look out for higher up. This could look something like:
```rs
use std::error::Error;
use std::fmt::Display;

struct StorageFull(Box<dyn Error>);

impl Display for StorageFull { /* defer to inner value's methods */ }
impl Error for StorageFull { /* defer to inner value's methods */ }

// In this case, we wouldn't even need this as a separate function,
// but I've kept it to highlight that the functionality is still there.
fn is_out_of_space(err: anyhow::Error) -> bool {
    err.is::<StorageFull>()
}
```
We could also write this as a type provided for context (maybe storing an additional, "real" context inside), which `Error::is` also detects.

A couple distinct advantages that these have over creating large error enums is that it becomes easier to check for certain errors (`anyhow` makes it really simple!) and we still get to keep all of the current benefits that `anyhow` gives us.

**Comment by LizardWizzard** [comment]
> In any case, we can do a significant amount of this with `anyhow`

I partly agree with that, but have a few "but".

We have quite a lot of places with just `bail!` or `anyhow!` and this doesn't work well with the first approach. Errors are indistinguishable (you can only match on string message). Second approach involves writing some boilerplate but probably it could be simplified with a macro. 
And what is more important to me, both approaches fail to answer the question: "What errors to expect from this function?" And there we could benefit from exhaustiveness checks provided to us by `match`, which we do not get using the dynamic approaches.

**Comment by LizardWizzard** [comment]
> the type system allows us to receive an ErrorKind;:WriteZero from File::create

I partly agree with that, but still think that this is better than one dynamic type. See for example this http handler in pageserver https://github.com/zenithdb/zenith/blob/main/pageserver/src/http/routes.rs#L95 it calls to branch create which can return an error when branch already exists: https://github.com/zenithdb/zenith/blob/main/pageserver/src/branches.rs#L283 So from the http side it is better to handle this error and respond with 400 (client error). But this particular error is undistinguishable from other ones. So IMO using cleanly modelled enums for errors serves two purposes: allows to distinguish different errors and highlights which type of errors to expect from this module, which may be especially useful when you are not familiar with the module, but can quickly understand what kind of errors to expect.

Another thing is IMO enum based errors preserve more context, it may be a little more verbose to add more context (for example via extra message field in a enum member), but I think this might be mitigated via helper function/macro.

Thoughts?

**Comment by hlinnaka** [comment]
There's now a chapter on error types in the new error handling documentation page: https://github.com/neondatabase/neon/blob/main/docs/error-handling.md#error-types. I'm closing this.

We had a discussion on this as part of that RFC: https://github.com/neondatabase/neon/pull/2681#discussion_r1004328710. The consensus was that we continue to use anyhow in general, but when we need to distinguish between error types, introduce Error types, e.g. using `thistype` . In other words, create error types as needed, and only as needed.

I'm sure we have places where we shoud differentiate between different kinds of errors more, and assign different  error codes to API calls depending on what error happened, for example. Should fix those, but since this issue was about the general approach, individual cases like that are out of scope for this issue.
