### ISSUE TITLE
Convert `internal error` into smth meaningful

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#5510]

**Comment by conradludgate** [comment]
Hard to do analysis on these errors atm. A quick check reveals that most of these internal errors result from receiving an EOF from the client. The code agrees. tentative WONTFIX. I want to change how we report "forwarding error to user" messages so we can run better analysis with the real error side by side

**Comment by vadim2404** [comment]
should we continue tracking this error in our metrics?

**Comment by conradludgate** [comment]
I don't think so.
