### ISSUE TITLE
Use streaming APIs for Azure uploads/downloads

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#5563]
https://github.com/neondatabase/neon/pull/5546 added azure upload/download functionality, but it buffers everything to RAM. This is suboptimal, as we would ideally use the streaming APIs.

The streaming APIs provided by the SDK [also want seek functionality](https://docs.rs/azure_core/0.16.0/azure_core/enum.Body.html) which means we'd have to do some refactors and change the API of RemoteStorage. Ideally this would be done in a way that `azure_core` traits are not part of the cloud agnostic interface (but instead there is some wrapper type local to the azure_blob.rs module).

Part of #5567.

PR #5446 did the upload side, now only the download side is remaining.

**Comment by koivunej** [comment]
Hmm looks like this would be solved instantly by just using stream for downloads as well.

**Comment by koivunej** [comment]
Almost; I don't know what to do with the metadata available only on first request.
