### ISSUE TITLE
test test_real_azure.rs in CI

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#5565]
PR #5546 has added support for azure blob storage, including a `test_real_azure.rs` file with various tests, similar to the `test_real_s3.rs` file. These tests can be run locally but should also be ran in CI.

Part of #5567.

**Comment by arpad-m** [comment]
see also: https://github.com/neondatabase/neon/pull/5546#discussion_r1360700224

**Comment by bayandin** [comment]
What's required to do?
Create secrets for `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_ACCESS_KEY`. 
And set `REMOTE_STORAGE_AZURE_CONTAINER`, `REMOTE_STORAGE_AZURE_REGION`, `ENABLE_REAL_AZURE_REMOTE_STORAGE`?

**Comment by arpad-m** [comment]
Yes, you need to create a storage account (configured for block blobs, IIRC it's not the default) and then you create a container. Then these secrets need to be set via env vars in a github action, similarly to how it's done for `test_real_s3.rs`.
