### ISSUE TITLE
Epic: proxy error classification

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#5599]
## Motivation

Proxy errors should be logged with as much detail as possible, and only once.

Errors should have a responsible party who is to blame for the error:
* User
* Proxy
* Dependency

Errors should have a flakiness factor:
* Transient - Most likely would succeed if attempted again
* Fatal - Will always fail

## Known user errors:

* https://github.com/neondatabase/neon/issues/5569
* https://github.com/neondatabase/neon/issues/5510
* https://github.com/neondatabase/neon/issues/5570
* https://github.com/neondatabase/neon/issues/5800

```[tasklist]
### Tasks
- [x] Proxy: Add error classicifation framework
- [x] Proxy: Implement error classification for TCP/WS flow
```

**Comment by stradig** [comment]
All planned P1 work was done.
