### ISSUE TITLE
pageserver: rogue layer in IndexPart after compaction deletes it

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5635]
Version: 49377abd98fb059ed34c2753970b261f78609a8f

Apparent order of operations is:
- Layer created
- Layer deleted in compaction
- Compaction's updates to RemoteTimelineClient are a no-op, because the layer isn't in the project remote metadata yet
- Somehow the layer then makes it into the remote metadata, so IndexPart has an entry that points to a nonexistent object.

This can lead to a pageserver getting stuck trying to download the nonexistent layer.

Mitigation:
- Identify the offending layer from a log line like download_remote_layer.*failed, will retry.*Failed to download a remote file
- Download the index_part.json for the timeline from S3.
- Remove the offending layer from index_part.json
- `POST v1/tenant/<tenant_id>/detach`
- Upload the edited index_part.json to S3.
- `POST v1/tenant/<tenant_id>/attach`

More detail to come.

**Comment by koivunej** [comment]
IndexPart cleanup was forgotten (my bad) from this: https://github.com/neondatabase/neon/issues/4526
