### ISSUE TITLE
Epic: Use Nginx based gateway (with cache) to load pg extensions

### ISSUE THREAD

**Issue by cicdteam** [neondatabase/neon#5661]
## Motivation

Currently computes able to download custom postgres extension from a specific (per region) S3 bucket. It implemented by using [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) and granting access to AWS S3 directly to pods. But this approach doesn't work for VM based computes (due architecture limitations). Instead of passing AWS credentials to process inside VM I suggest use  caching proxy between computes and AWS S3.

Pros:
- no need provide AWS credentials to compute
- reduce latency of downloading extension data as proxy resides near computes
- reduce AWS costs as proxy has cache and 1000 computes asking the same extension will not generate 1000 downloads from S3
- we can use **only one S3 bucket** to store extensions (and rid of regional buckets which were introduced to reduce latency)

Cons:
- need to re-implement the part that is used when loading pg extensions: instead of `aws s3 cp s3://bucket/file file` use `HTTP GET http://pg-ext-s3-gateway/file`

## Implementation ideas

Proxy gateways already started in both staging clusters and accessible by url http://pg-ext-s3-gateway. See example how to load `/latest/v15/ext_index.json` via proxy instead of using S3 api:

curl command
```console
curl http://pg-ext-s3-gateway/latest/v15/ext_index.json
```
result:

```json
{
  "public_extensions": [
    "anon",
    "postgis"
  ],
  "library_index": {
    "kq_imcx": "kq_imcx",
    "pg_partman_bgw": "pg_partman"
  },
  "extension_data": {
    "kq_imcx": {
      "control_data": {
        "kq_imcx.control": "# This file is generated content from add_postgresql_extension.\n# No point in modifying it, it will be overwritten anyway.\n\n# Default version, always set\ndefault_version = '0.1'\n\n# Module pathname generated from target shared library name. Use\n# MODULE_PATHNAME in script file.\nmodule_pathname = '$libdir/kq_imcx.so'\n\n# Comment for extension. Set using COMMENT option. Can be set in\n# script file as well.\ncomment = 'ketteQ In-Memory Calendar Extension (IMCX)'\n\n# Encoding for script file. Set using ENCODING option.\n#encoding = ''\n\n# Required extensions. Set using REQUIRES option (multi-valued).\n#requires = ''\ntrusted = true\n"
      },
      "archive_path": "latest/v15/extensions/kq_imcx.tar.zst"
    },
    "pg_partman": {
      "control_data": {
        "pg_partman.control": "default_version = '4.7.3'\ncomment = 'Extension to manage partitioned tables by time or ID'\nrelocatable = false\ntrusted = true\n"
      },
      "archive_path": "latest/v15/extensions/pg_partman.tar.zst"
    }
  }
}
```

cc: @lubennikovaav

**Comment by cicdteam** [comment]
cc: @vadim2404

**Comment by lubennikovaav** [comment]
looks good to me, thank you!

one more pros is that we'll simplify compute_ctl config, as there's no need to pass s3 config to it.

do we need to pass any extra credentials for `compute_ctl` to connect to this proxy?

**Comment by cicdteam** [comment]
@lubennikovaav 

Currently proxies hasn't any credentials as the acts as simple caches. You can not delete something in S3 via proxy or upload something, only GET files from there.
