### ISSUE TITLE
Use nextest as a test runner for Rust tests

### ISSUE THREAD

**Issue by bayandin** [neondatabase/neon#5681]
Should we consider switching to something like `cargo nextest` (it has [timeouts](https://nexte.st/book/slow-tests.html#terminating-tests-after-a-timeout) and [junit output](https://nexte.st/book/junit.html))?

_Originally posted by @bayandin in https://github.com/neondatabase/neon/pull/5680#pullrequestreview-1699705220_

**Comment by koivunej** [comment]
I rememember there being an earlier discussion, but nothing of it. I am not able to validate the junit output but unsurprisingly it works with our codebase.

I think the path to testing it would be to build a new rust image, then use a PR in this repo to test it?
