### ISSUE TITLE
tenant deletion fails if timeline creations are still ongoing

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5715]
This happened in prod testing with tenants:
- 755c7dd0e07190efee5c7376d05d3df8 (gw4-aws-us-east-2_test_branch_create_delete)
- b6f1162c35ce2f0e202c7ee37cb297c2 (gw2-aws-us-east-2_test_created_role_login_works)

[Log search](https://neonprod.grafana.net/explore?panes=%7B%2215n%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bneon_service%3D%5C%22pageserver%5C%22,%20neon_region%3D%5C%22us-east-2%5C%22%7D%20%7C~%20%60tenant_id%3D%28755c7dd0e07190efee5c7376d05d3df8%7Cb6f1162c35ce2f0e202c7ee37cb297c2%29%7Cgit-env:%60%22,%22intervalMs%22:1000,%22maxDataPoints%22:43200,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221698650741000%22,%22to%22:%221698672341000%22%7D%7D%7D&schemaVersion=1&orgId=1).

This testing happened near restart (6min after) which probably means there was enough restart-time busyness on the instance to allow deleting to fail with #5712 (which would had failed anyways). Afterwards it looks like even control plane stopped retrying the operations.

Expected behaviour: tenant delete would had prohibited timeline creation or waited for them all to complete.

**Comment by jcsp** [comment]
Two general thoughts:
- Since #5550 the uninit marker may not be necessary any more
- I'm generally not a fan of how brittle the timeline delete code is: once we've delete it in remote storage, I'm inclined to say we should just recursively remove the local directory irrespective of what it contains.

**Comment by koivunej** [comment]
> Kind of interesting that the creation was apparently taking so long, in any case.

Unsure if it did to be honest, but the flushing has traditionally taken a long time but we might now really have slack in our background runtime so this completed in seconds. In relation to that, both timelines have:

```
2023-10-30T11:35:07.418367Z  INFO layer flush task{tenant_id=755c7dd0e07190efee5c7376d05d3df8 timeline_id=2db35673cf73cb541ccec7f0e78ca570}: shutting down layer flush task
2023-10-30T11:35:07.418338Z  INFO layer flush task{tenant_id=755c7dd0e07190efee5c7376d05d3df8 timeline_id=2db35673cf73cb541ccec7f0e78ca570}: started flush loop
2023-10-30T11:35:07.450003Z  INFO layer flush task{tenant_id=b6f1162c35ce2f0e202c7ee37cb297c2 timeline_id=1695a369b0c31b8ce973bf61fa258a90}: shutting down layer flush task
2023-10-30T11:35:07.449977Z  INFO layer flush task{tenant_id=b6f1162c35ce2f0e202c7ee37cb297c2 timeline_id=1695a369b0c31b8ce973bf61fa258a90}: started flush loop
```

I cannot remember what would create these log lines.

**Comment by jcsp** [comment]
This hasn't reocurred in recent history
