### ISSUE TITLE
metric: launched and killed walredo processes

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5722]
In OOM situations, knowing exactly how many walredo processes there were at a time would help afterwards to understand why was pageserver OOM killed.

We need two counters:
- walredo processes started
- walredo processes shutdown

Good first issue:

- pageserver/src/walredo.rs is the walredo implementation
- We could increment the started counter near launching the process
- We could increment the killed counter in the process waiting newtype wrapper
- metric could be `pageserver_walredo_processes`, an IntCounterVec with "operation" key
  - the two concrete counters could be `operation="started"` and `operation="shutdown"`
  - the "shutdown" separate from "killed" if we'd ever want to distinguish on the ones we need to kill in addition to finding them having exited

**Comment by rmodpur** [comment]
@koivunej i would like to work on this

**Comment by stepashka** [comment]
nov 6th notes:
discussed whether this aligns with the team priorities for Q4, considering to postpone and get back to this once other priorities are resolved
did i capture this right, @koivunej @jcsp @shanyp ?

**Comment by koivunej** [comment]
@rmodpur feel free to do so and ping me once you have a draft! This should be more straightforward than the #5310 which I will eventually get to :)
