### ISSUE TITLE
metric: periodic scanning of walredo processes to capture the ram they consume, export it

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5723]
With 16k processes this will be non-insignificant number, like 21GB. Simply summing the RSS is not good enough, because the sum of their RSS will be overcounting a lot because of shared pages. The correct value seems to be obtained through summing their PSS instead, like:

```
for pid in $(pidof postgres); do grep '^Pss:' /proc/$pid/smaps_rollup; done | awk '{ total+=$2; count+=1; } END { print total,count; }'
```

There are considerations on how to implement this:
- grepping for pids is unnecessary, because in pageserver we know all of the pids
- `smaps_rollup` still needs to be looked into and the correct line read
  - unless there's an actual api for this, but probably not

There might be alternative ways of obtaining this, or easier as in starting all of the `postgres --wal-redo` in a separate cgroup which would be `O(1)` monitorable. I am unsure what kind of complications would that cause outside of the obvious and trivial macos incompatibilities.

**Comment by stepashka** [comment]
nov 6th notes:
discussed whether this aligns with the team priorities for Q4, considering to postpone and get back to this once other priorities are resolved
did i capture this right, @koivunej @jcsp @shanyp ?

**Comment by koivunej** [comment]
I caught postponing at least.

I'll just close this because the timer based approach from #5877 works so well in prod.
