### ISSUE TITLE
/attach: `404` code for `Timeline not found` doesn't make sense

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5732]
Above there is a
```yaml
        "404":
          description: Timeline not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
```
which doesn't look as a valid response in this case, right?

I'm not sure that 404 is a valid response for this API handler at all

_Originally posted by @ololobus in https://github.com/neondatabase/neon/pull/5698#discussion_r1376109212_

**Comment by jcsp** [comment]
This part of the swagger no longer exists.
