### ISSUE TITLE
Make connection retries on Compute side exponentially backoff

### ISSUE THREAD

**Issue by save-buffer** [neondatabase/neon#5757]
## Steps to reproduce
Have an unstable connection with the pageserver

## Expected result
Not spinning in a loop trying to reconnect

## Actual result
Spins in a tight loop trying to reconnect

## Logs, links
-

**Comment by vadim2404** [comment]
To talk to @knizhnik this week. To finalize the solution

**Comment by vadim2404** [comment]
#6048
