### ISSUE TITLE
Add retry on fetching basebackup

### ISSUE THREAD

**Issue by save-buffer** [neondatabase/neon#5758]
## Steps to reproduce
Make connection between pageserver and compute unstable, try to start compute

## Expected result
It retries until it works

## Actual result
It errors out saying "failed to fetch basebackup". 

## Logs, links
-

**Comment by save-buffer** [comment]
Made PR: https://github.com/neondatabase/neon/pull/6537

**Comment by save-buffer** [comment]
Merged

**Comment by andreasscherbaum** [comment]
It's released
