### ISSUE TITLE
pageserver: don't log error when shutting down tenant during page_service request

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5784]
test_pageserver_restarts_under_worload has a log allow list entry for this.

This is logged as an error because this class of error is getting converted to `QueryError::Other`, via some implicit anyhow::Error conversion.  It should be converted to `QueryError::Shutdown`

```
E   assert not ["2023-11-03T17:15:59.163010Z ERROR page_service_conn_main{peer_addr=127.0.0.1:43614}: query handler for 'pagestream 72a9e2ea29c835771d0daa845008ad47 31fb40eee3d5c58f08a9bec57c07e48f' failed: Tenant 72a9e2ea29c835771d0daa845008ad47 will not become active. Current state: Stopping\n"]
```

**Comment by duguorong009** [comment]
@jcsp 
I would like pick up this issue!
