### ISSUE TITLE
pageserver: clean up public functions in `mgr.rs`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5796]
`mgr.rs` historically consisted of a collection of functions that operated on the `TENANTS` static variable.  This is awkward compared with defining a type that contains the tenants map and also provides accessors: it's hard to unit test due to the static var, and function prototypes have many arguments because things like the PageServerConf have to be passed in to every function call.

**Comment by duguorong009** [comment]
@jcsp 
Can I work on this issue?
Or anyone working on this task?

**Comment by jcsp** [comment]
@duguorong009 I would suggest avoiding this one for the moment: it will probably conflict with other changes in flight.

**Comment by duguorong009** [comment]
> @duguorong009 I would suggest avoiding this one for the moment: it will probably conflict with other changes in flight.

okay, thanks for info! @jcsp
