### ISSUE TITLE
Server login has been failing, try again later

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#5801]

**Comment by khanova** [comment]
Managed to reproduce bug, filed issue in pgbouncer https://github.com/pgbouncer/pgbouncer/issues/989
Created PR in pgbouncer, which can possibly fix it: https://github.com/pgbouncer/pgbouncer/pull/985

**Comment by vadim2404** [comment]
@knizhnik , can you ping Jelte to look at this PR?

**Comment by knizhnik** [comment]
I already did it. He replied (week ago):
```
Yeah, I got back from my honeymoon yesterday and catching up on lots of things at the moment. Pgbouncer issues reported while I was away are on that list too. I'm hoping to get to this one in the next few days. 

```

**Comment by vadim2404** [comment]
@khanova to work with @bayandin to cherry-pick this fix to our pgbouncer image

**Comment by vadim2404** [comment]
It's fixed
