### ISSUE TITLE
unlogged permanent layer loading error in prod

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5815]
Via the rare counters we can observe permanent layer loading errors in: https://github.com/neondatabase/neon/blob/fc47af156f4d712e04722a3319a24e4c136c1f0b/pageserver/src/tenant/storage_layer/layer.rs#L1214-L1216

Two of these happened with the after deploy before `2023-11-07 11:53:00Z` but there is nothing in the logs. Layer stringifies the error for the caller on access, but it seems we just do not log all errors, so there is no knowing what caused these.

One clear path in which we do not end up logging the error was added in #5660. I have not found any others, but as that was a quickfix, we should fix the PageReconstructError. It even has completely unused variant "NeedsDownload" which has not been used since 2022 if I recall correctly.

If we were to have multiple paths like this, it would mean that our logging related metrics cannot be trusted.

**Comment by koivunej** [comment]
More such events, but still cannot see from the logs the reason: [two minutes of logs](https://neonprod.grafana.net/explore?panes=%7B%22AVh%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_service%3D%5C%22pageserver%5C%22,%20hostname%3D%5C%22pageserver-7.us-east-2.aws.neon.tech%5C%22%7D%20%21~%20%60%28jwt%20auth%20succeeded%20for%20scope%7Ctimelines%20need%20GC%7C:connection%5C%5CS%2B:%20%7Ctask%20iteration%20took%20longer%20than%7CSwitching%20to%20new%20connection%20candidate:%7CGC%20starting%7CNew%20SK%20node%20was%20added%7CSafekeeper%20node%20%5C%5CS%2B%20did%20not%20send%20events%20for%20over%2010s,%20not%20retrying%20the%20connections%29%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221699421220000%22,%22to%22:%221699421340000%22%7D%7D%7D&schemaVersion=1&orgId=1) around the 2 -> 3 eventnoteworthy: this is only happening on ps-7.us-east-2 still.

**Comment by jcsp** [comment]
Looks like https://github.com/neondatabase/neon/pull/5915 resolved this
