### ISSUE TITLE
test_tenant_detach_smoke is flaky: Error processing HTTP request: InternalServerError(cancelled

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#5826]
It was found in https://github.com/neondatabase/neon/pull/5686#issuecomment-1782226432 (comment might have been edited since):

> #### Failures on Postgres 16
> 
> * `test_tenant_detach_smoke`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5686/6782103133/index.html#suites/f9eba3cfdb71aa6e2b54f6466222829b/c57b7b08c7a1853a)
> 
> 
> #### Failures on Postgres 15
> 
> * `test_tenant_detach_smoke`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5686/6782103133/index.html#suites/f9eba3cfdb71aa6e2b54f6466222829b/c9948d0f9e873e37)
> 
> 
> #### Failures on Postgres 14
> 
> * `test_tenant_detach_smoke`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5686/6782103133/index.html#suites/f9eba3cfdb71aa6e2b54f6466222829b/86ffeaedd27d553b)
> 

```
AssertionError: assert not ['2023-11-07T09:15:59.735569Z ERROR request{method=PUT path=/v1/tenant/86a180feb3caa301c60951c80c24f354/timeline/c0d42dcef7e12d879b5b9f15828d7fe3/do_gc request_id=16baa6b3-998c-47e2-843a-d6d76c032991}: Error processing HTTP request: InternalServerError(cancelled\n']
```

**Comment by jcsp** [comment]
I don't think we've seen recent failures of this
