### ISSUE TITLE
add linux arm64 variant of `check-codestyle-rust` and `build-neon` to GitHub Actions

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5829]

**Comment by bayandin** [comment]
For `build-neon`, do we need to build both `debug` and `release` builds?

**Comment by petuhovskiy** [comment]
I think we can start with https://github.com/neondatabase/neon/blob/main/.github/workflows/neon_extra_builds.yml
There we already have checks for macos, it should be easy to add the same checks for aarch64. And it looks like both `check-codestyle-rust` and `build-neon` are already checked for macos
