### ISSUE TITLE
Cancellation fails on different proxy instance

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#5839]
Cancellation doesn't always work. To test, start a slow query in psql, e.g. "select pg_sleep(100);", and hit CTRL-C to cancel it. Sometimes it works, sometimes it doesn't. Often you have to hit CTRL-C 2-5 times before the query is cancelled.

My hypothesis is that we run multiple proxy instances, and the cancellation only works if the cancel request arrives at the same instance as the connection that you are cancelling.

**Comment by khanova** [comment]
Looked at this issue. It looks like you are right: when the cancel request ends up in a different (from original) proxy instance it always end up with `query cancellation key not found` error.
