### ISSUE TITLE
last_flush_lsn_upload stuck waiting for 1 wal record after remote_consistent_lsn

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5853]
> #### Failures on Postgres 16
> 
> * `test_threshold_based_eviction`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5851/6827669260/index.html#suites/3fc871d9ee8127d8501d607e03205abb/cb3e77d5765b4b41)

```
Exception: timed out while waiting for remote_consistent_lsn to reach 0/611B330, was 0/611B2F8
```

56 byte difference. But how could this be?

_Originally posted by @koivunej in https://github.com/neondatabase/neon/issues/5851#issuecomment-1806233512_

**Comment by jcsp** [comment]
This ticket is quite old, and since then we have made changes that cause the LSN to advance more reliably across WAL records that don't generate any ingest work.
