### ISSUE TITLE
test_branching_with_pgbench failure

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5854]
> #### Failures on Postgres 16
> 
> * `test_branching_with_pgbench[flat-1-10]`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5851/6827669260/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/e0da40e7e9c6aeb5)

Unclear what caused this. Problem has been noticed with both `cascade` and `flat`. Merging #5520 made it less frequent on the merges.

Some failure logs show what looks like "rogue primary compute" but we haven't been able to understand which could that be, we might even be missing some logging.

@petuhovskiy had an idea about collapsing all of the logs.

_Originally posted by @koivunej in https://github.com/neondatabase/neon/issues/5851#issuecomment-1806281319_

**Comment by koivunej** [comment]
More instances: https://neon-github-public-dev.s3.amazonaws.com/reports/main/6942621581/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/9a0d540d56f9c375/ -- see also retries.

**Comment by koivunej** [comment]
More: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5902/6959521385/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/7709742b5531b61f

**Comment by lubennikovaav** [comment]
One more instance of this
https://neon-github-public-dev.s3.amazonaws.com/reports/main/7005229440/index.html#testresult/377a59f7390cf70c
with this error in the `repo/endpoints/ep-7/compute.log`
```
2023-11-27 13:10:07.595 GMT [135907] PANIC:  WAL acceptor 127.0.0.1:18369 with term 3 rejected our request, our term 2
```

**Comment by bayandin** [comment]
3 More examples: 
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/7025913425/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/b2ae7cba6931ae47
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/7026248022/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/e493a672d370b3ca
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/7026697234/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/4d3a5be600ffd709

**Comment by problame** [comment]
Slack thread with investigation & some optimistic insights: https://neondb.slack.com/archives/C04KGFVUWUQ/p1701169779613809

**Comment by koivunej** [comment]
It seems merging #5520 may have changed the situation. Upon further inspection it should had not helped, but perhaps it adding a new test case helped which affected the test execution order.

**Comment by koivunej** [comment]
https://neon-github-public-dev.s3.amazonaws.com/reports/main/7050113183/index.html#suites/ffbb7f9930a77115316b58ff32b7c719/c4ad61d05db29119 caused the #6004 PR, but quoting @arssher:

> Figure out what cases initial 5m timeout.

**Comment by jcsp** [comment]
This doesn't appear to have failed in the recent past, based on test database output
