### ISSUE TITLE
initdb image layer optimization is broken (import of large pgdumps doesn't work)

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5863]
Expected: after creating a timeline we have a single image layer.

Actual: we have a single delta layer because of the wal ingestion near the end of import, so the check fails: https://github.com/neondatabase/neon/blob/ea63b43009f2ccac30e447de1095159365d27ad8/pageserver/src/tenant/timeline.rs#L2544

Fix it to allow bulk imports larger than memory.

_Originally posted by @koivunej in https://github.com/neondatabase/neon/issues/5843#issuecomment-1810548967_

**Comment by koivunej** [comment]
@problame mentioned seeing sometimes an image layer being created. It is hard for me to see how could this be the case as we always need to ingest the wal to learn prev_lsn and there must always be some wal logged activity. We should however learn this.

**Comment by jcsp** [comment]
Triage notes:
- A test exists but does not cover the initdb case, it only  covers create empty timeline.
- Impact: the import functionality (vanilla pgdump import) is limited in size it can handle 
- Do we care?  Not super urgent but significant tech debt to carry code that looks like it should do something it doesn't do.
- The right test would be: create a pgdump larger than layer size (or larger than memory size), import it, and assert that the resulting state of the layer map is image layers.

**Comment by jcsp** [comment]
Just realized this is basically the same thing as https://github.com/neondatabase/neon/issues/7197

This ticket was here first, but that one has a slightly fuller description, so closing this one.
