### ISSUE TITLE
Proper support of logical replication and branching

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#5885]
Safekeepers are not aware of branches, so if parent creates logical slot and branches off, branch on start will try to download WAL for it (we always fetch since the start of the segment to fetch page headers) and fail. We should fix this.

**Comment by kelvich** [comment]
discussed with @knizhnik that we could filter out recursive search in parent branches for logrep-related files on the pageserver

**Comment by ololobus** [comment]
IIUC, we now drop logical replication slots in new branches, so we can close this, right? @arssher @knizhnik

**Comment by arssher** [comment]
> IIUC, we now drop logical replication slots in new branches, so we can close this, right?

We do (test_slots_and_branching).
