### ISSUE TITLE
Feature Request: Rebase Main from Branch

### ISSUE THREAD

**Issue by brendan-stephens** [neondatabase/neon#5888]
Since PITR creates a child branch, it can mean that a parent tree is void and no longer required.
While you can promote a branch to primary, you cannot delete a branch that has children.

```mermaid
graph TD;
    MAIN-->BRANCH-1;
    MAIN-->PITR;
    PITR-->BRANCH-3;
    PITR-->BRANCH-4;
```

It may be helpful in many cases to allow a rebase from a child branch, with the caveat that other branches would be deleted.

```mermaid
graph TD;
    PITR-(MAIN)-->BRANCH-3;
    PITR-(MAIN)-->BRANCH-4;
```

Perhaps this could be accomplished by marking the parents as "hidden", such they they are removed from view and selection without an additional API attribute. This also provides an "undo" path, though it may still consume additional storage.

**Comment by jcsp** [comment]
This is broadly similar to #6994
