### ISSUE TITLE
Reverse Postgres <-> Page server connection when running without safekeepers

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#589]
It's currently possible to run a Postgres compute node and a Page server without WAL safekeepers. We do that in the tests. In that configuration, the Page server connects directly to Postgres to receive the WAL.

The normal configuration with WAL safekeepers looks like this:
```
+----------+        +-------------+        +-------------+
| Postgres | -----> | WAL service | <----- | Page Server |
+----------+        +-------------+        +-------------+
```
where the arrow indicates who initiaties the connection.

Without safekeepers, it looks like this:
```
+----------+                               +-------------+
| Postgres | <---------------------------- | Page Server |
+----------+                               +-------------+
```
Some hacks are required to support this. There's a chicken-and-egg problem if the page server isn't fully up-to-date, because when it connects to Postgres, the walsender process needs to do a lookup in pg_authid, to authenticate the connection. But that in turn can require requesting a page from the page server, and if the page server isn't fully caught up, you end up in deadlock. To break that deadlock, there's a hack in the smgr requester code in postgres to request the latest page version without waiting, when it's the WAL sender process making the request. That's not correct, you could read an out-of-date page version and it could cause all sorts of weird issues.

I propose that we solve this chicken-and-egg problem differently, by having the WAL proposer process in Postgres connect directly to the Page Server:
```
+----------+                               +-------------+
| Postgres | ----------------------------> | Page Server |
+----------+                               +-------------+
```
We can have a "light" version of the safekeeper running in Page Server, so that it looks like a safekeeper to the WAL proposer code.

This issue is related to #117

**Comment by hlinnaka** [comment]
@sharnoff, what are you thoughts on this, in light of https://github.com/zenithdb/zenith/issues/117? Will this change happen "for free"? Or should we just forget about this setup and run all our tests with safekeepers?

**Comment by kelvich** [comment]
Right now main focus was to avoid callback connection between safekeeper and pageserver. And the protocol for the new connection is deemed to be an usual postgres replication protocol. So we would have receiving part of setup described in this issue. To connect postgres to the pageserver in this mode we would need corresponding sender in postgres. That can be done as a separate mode for a proposer or as a separate kind of proposer. Latter is better IMO since here we can reuse most of postgres WalSender and hack around connection creation. Also both replication protocol and safekeeper protocol use postgres CopyBoth messages but safekeeper protocol is synchronous, so it would be hard to consider single page server connection as an edge case for usual wal proposer.

**Comment by sharnoff** [comment]
@hlinnaka

> Or should we just forget about this setup and run all our tests with safekeepers?

If it's always the case that users will have safekeepers, then all the code that's only run in the "no safekeepers" tests is essentially dead code, right? 

As @kelvich mentioned, the immediate plan for #117 is to remove the callmemaybe connection from walkeeper -> pageserver, but keep the ones from postgres -> page server. If we always ran tests with safekeepers though, that would actually be all we need to do.

My perspective on this is pretty limited though -- are there other reasons we might want to keep around tests without safekeepers?

**Comment by stepashka** [comment]
#636 #117 #589 all relate to the similar issues and are on hold for now

**Comment by kelvich** [comment]
Resolved in https://github.com/neondatabase/neon/blob/main/docs/rfcs/015-storage-messaging.md / https://github.com/neondatabase/neon/commit/e5cb72757250457a61eeb4bdd7c613527ce7ec98
