### ISSUE TITLE
timeline_create: bootstrapping a timeline can block an executor thread for 1s

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#5895]
It is probably not the cause of long `timeline_create` requests we endure during startup, but it certainly is not helping.

This is in the class of bugs that could had been found with by running with current_thread executor only, but at the same time, this has been known for a long time.

In short, this needs to be async using https://docs.rs/tokio/latest/tokio/process/struct.Command.html instead of what is currently used (`std::process::Command`):

https://github.com/neondatabase/neon/blob/0d10992e463e9377d9791cdb90c5d13c452aa504/pageserver/src/tenant.rs#L3344-L3350

Async opens us up for cancellation, so we need to kill the process in case we are cancelled (which is not expected to be happening).

Concurrency limit: static semaphore of 8 should be plenty, and the same what we had earlier (8 threads for management requests runtime).

**Comment by koivunej** [comment]
good_first_issue: duplication of setup code can be avoided using https://docs.rs/tokio/latest/tokio/process/struct.Command.html#impl-From%3CCommand%3E-for-Command right before spawning and awaiting.

**Comment by problame** [comment]
Part of the impl should be some sort of concurrency limit.

Also I'm wondering whether our `initdb` has fsync disabled.
It should.

**Comment by koivunej** [comment]
> I'm wondering whether our initdb has fsync disabled.

1s does not sound like it but there is at least the `--no-sync`, which is documented to give this.

**Comment by koivunej** [comment]
As far as the next steps go, I was thinking the WalkDir usage together with `tokio::fs` for file accesses might not be healthy, but needle will move when #5446 is merged.

#5390 adds similar WalkDir and `tokio::fs` usage.
