### ISSUE TITLE
pageserver: failed to clean up timeline dir from partial creation

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#5990]
Slack: https://neondb.slack.com/archives/C03F5SM1N02/p1701344019373969

We saw a timeline creation failing.  It had started creating and then pageserver restarted partway through the original creation request.

The remote storage contents of the timeline were the initdb bundle, but no index_part: i.e. the creation is not complete.

Failures were due to the timeline dir existing (check in `create_timeline_uninit_mark`).

This shouldn't happen: on tenant attach, we load remote metadata for timelines, and any local timeline dir that doesn't correspond to one found in remote storage should be removed -- this is done in `Tenant::clean_up_timelines`

We do see log messages purging the timeline's ___unint and ___tmp folders.  But the actual timeline dir also still exists, containing a metadata file and an ephemeral layer file (timestamp from before the restart).

**Why didn't that timeline dir get purged?**

**Comment by problame** [comment]
Please link the Slack thread where we did the investigation.

**Comment by arpad-m** [comment]
closing this in favour of #6007
