### ISSUE TITLE
Safekeeper timeline is deactivated without persisting state

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#5993]
Which means we sometimes lose latest values on restart. This leads to excessive ps -> sk reconnections due to stale remote_consistent_lsn on the latter; more details at
https://github.com/neondatabase/neon/issues/5962

ref https://neondb.slack.com/archives/C033RQ5SPDH/p1701197668789769

**Comment by problame** [comment]
I think this can be closed. Reviewed impact in https://github.com/neondatabase/neon/issues/6062
