### ISSUE TITLE
Synchronous wait in async `gc_timeline` function

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#6045]
`gc_timeline` function is async, but it calls synchronous `RcuWaitList::wait()` function:

https://github.com/neondatabase/neon/blob/483caa22c6e4ba5c8a73526fe24fd5ca275b7c24/pageserver/src/tenant/timeline.rs#L3982

In the worst case, all tokio executor threads could get stuck on that, so that there are no threads available to make progress on the tasks that hold the RcuReadGuard. That would be a deadlock.

I noticed this while searching for an explanation for https://github.com/neondatabase/neon/issues/6006#issuecomment-1841065435. I don't know if this explains it, but maybe?

**Comment by jcsp** [comment]
Closed by #6046
