### ISSUE TITLE
`test_deletion_queue_recovery` is flaky 

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#6092]
> Failures on Postgres 16
> 
> * test_deletion_queue_recovery[validate-keep]: [release](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6060/7142083254/index.html#suites/7538959189f4501983ddd9e167836c8b/480a1a1166b29fcb)

The count can be more after a restart than it was before `pageserver.shutdown(immediate=True)` because of future layers. There is a misused `fail::failpoint!("control-plane-client-validate")` which will need to become `pausable_failpoint!()` as well.

Because of that failpoint used as pause or return, we are probably able to just use wait upload queue empty.

**Comment by jcsp** [comment]
Failed 4x in last three days, may not be the same failure mode as this ticket was originally opened for.

**Comment by jcsp** [comment]
https://github.com/neondatabase/neon/pull/7325 should help with the most common failure mode.  We can check in in ~1wk to see how prevalent other failures modes are.

**Comment by jcsp** [comment]
No failures in past 7d
