### ISSUE TITLE
`pageserver_client::mgmt_api`: use TenantShardId instead of TenantId

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6154]
Noticed that some of the methods should be taking `TenantShardId` instead of `TenantId`, but, none of the callers seem to be sharding-aware. So, leaving that for another time. cc @jcsp

_Originally posted by @problame in https://github.com/neondatabase/neon/issues/6127#issuecomment-1858234890_

**Comment by ScottLinnn** [comment]
I'd like to have a try on this!

**Comment by jcsp** [comment]
@ScottLinnn most of these are updated in https://github.com/neondatabase/neon/pull/6251, but if you would like to open a PR to update them all in one commit, that would be cleaner, so feel free.

**Comment by ScottLinnn** [comment]
Thanks for letting me know! I'd prefer looking at other issues.
