### ISSUE TITLE
[Logical replication] Test for lost connections

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#6182]
from @danieltprice:
> I believe a lost connection to a destination or an abandoned publication could result in a slot accumulating data and eventually hitting storage limits. 

Details in the thread: https://neondb.slack.com/archives/C026T7K2YP9/p1702813041997959

**Comment by vadim2404** [comment]
@knizhnik will create such a test

cc @kelvich

**Comment by kelvich** [comment]
i think we can close this one. thread was about smoke testing, issue name is somewhat not related to the thread. we could have a similar tests in nightly benchmarks, but proper LR testing setup is a different story
