### ISSUE TITLE
postgres: `FailedAssertion("(wp->truncateLsn != InvalidXLogRecPtr)`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6248]
Seen here: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6246/7385000585/index.html#suites/a45a54de0f437467df434b0529cc0b71/ed8d2b4496929aa5

This was a test run on a PR that only touches pageserver code, so should be unrelated to the failure.

```
2024-01-02 11:13:34.878 GMT [32563] LOG:  got VoteResponse from acceptor 127.0.0.1:16152, voteGiven=1, epoch=2, flushLsn=0/1696320, truncateLsn=0/0, timelineStartLsn=0/1696320
TRAP: FailedAssertion("(wp->truncateLsn != InvalidXLogRecPtr) || (wp->config->syncSafekeepers && wp->truncateLsn == wp->propEpochStartLsn)", File: "/__w/neon/neon//pgxn/neon/walproposer.c", Line: 980, PID: 32563)
```

**Comment by arssher** [comment]
Compute here is created and immediately stopped, so no WAL had been sent, but elected message was; assertion is wrong. Will fix.

**Comment by petuhovskiy** [comment]
It's already fixed here: https://github.com/neondatabase/neon/pull/5804/commits/fe1b2f1f9c989762de500ee8a103282c150678d3

But this PR is not merged yet.

**Comment by arssher** [comment]
separate pr:
https://github.com/neondatabase/neon/pull/6396
