### ISSUE TITLE
Compute reconnect appears to be spinning in `test_pageserver_restarts_under_worload`, 

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6260]
In this test failure, postgres is getting "Cannot assign requested address" errors, which may be a test environment issue (run out of ports?).

It appears to be reconnecting more frequently than one would expect with #6048 .  e.g. in [this failure](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6259/7389597696/index.html#suites/542b1248464b42cc5a4560f408115965/78f9475cc5a2da14) look at timestamp 19:26:50.32[789].  There are enough reconnects that one would expect it to have backed off to the max reconnect interval, but that doesn't seem to be happening.

Slack: https://neondb.slack.com/archives/C033RQ5SPDH/p1704266539266389

**Comment by save-buffer** [comment]
This can probably be closed due to #6267
