### ISSUE TITLE
temporary initdb file remains on tenant deletion race with timeline creation

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#6287]
The `initdb.tar.zst.upload-{}.___temp` file, created by timeline creation, is not deleted if there is a tenant deletion request racing it before the initdb upload finishes. The timeline creation then fails but leaves the file around, which then puts the tenant into a broken state.

See [slack discussion](https://neondb.slack.com/archives/C03F5SM1N02/p1704658772669939).

**Comment by jcsp** [comment]
Duplicates https://github.com/neondatabase/neon/issues/6255
