### ISSUE TITLE
Make pull_timeline production-ready

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#6340]
tests:
- [x] - simple
- [x] - under load which creates WAL which should be garbage collected before pull_timeline finishes
- [x] - under load which truncates WAL on donor during pull_timeline

**Comment by petuhovskiy** [comment]
One of the unresolved issues: pull_timeline doesn't work with auth enabled, and we don't have auth enabled in tests.

**Comment by problame** [comment]
This week:
* implement last test from to-do list in issue description

**Comment by arssher** [comment]
Opened draft PR for this. It is almost ready, need to rebase and implement WAL hold off.

**Comment by petuhovskiy** [comment]
Fixed in https://github.com/neondatabase/neon/pull/7944
