### ISSUE TITLE
Restrict safekeeper -> pageserver connection thread lifetime to the lifetime of connection from walproposer

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#636]
Otherwise they breed uncontrollably.

**Comment by sharnoff** [comment]
@arssher Could you elaborate more about the behavior you observed? I would have assumed that it was at least partially handled by the page server only running one walreceiver connection per timeline.

**Comment by stepashka** [comment]
#636 #117 #589 all relate to the similar issues and are on hold for now
