### ISSUE TITLE
Investigate test timeout from nextest 

### ISSUE THREAD

**Issue by abhigets** [neondatabase/neon#6361]
### But for the following run 
https://github.com/neondatabase/neon/actions/runs/7530476784/job/20496964721

```
       SLOW [>7200.000s] pageserver tenant::remote_timeline_client::tests::index_part_download_ordering
        SLOW [>7200.000s] pageserver tenant::tests::test_images
        SLOW [>7200.000s] pageserver tenant::timeline::walreceiver::connection_manager::tests::connection_no_candidate
        SLOW [>7260.000s] pageserver tenant::remote_timeline_client::tests::index_part_download_ordering
        SLOW [>7260.000s] pageserver tenant::tests::test_images
        SLOW [>7260.000s] pageserver tenant::timeline::walreceiver::connection_manager::tests::connection_no_candidate```

It was wasn't terminated by nextest

**Comment by problame** [comment]
This investigation already happened here: https://github.com/neondatabase/neon/pull/6355#issuecomment-1893745763

**Comment by abhigets** [comment]
Sorry for missing the leading title. This issue is to fix the behavior where a test should be terminated if it run longer than 1 min

**Comment by abhigets** [comment]
@problame If you are ok I will repoen this one and change the description slightly to match the above comment. Please let me know what are your thoughts on this

**Comment by problame** [comment]
Yeah, go ahead and re-open after adjusting the titles.

>  Sorry for missing the leading title. This issue is to fix the behavior where a test should be terminated if it run longer than 1 min

1min would actually have been counter-productive in debugging https://github.com/neondatabase/neon/issues/6373
