### ISSUE TITLE
test_tenant_delete_races_timeline_creation is flaky

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#6385]
The `test_tenant_delete_races_timeline_creation` test added by #6310 is flaky, as was already noted in the thread of #6310. It sometimes gives errors like found [here](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6384/7568415347/index.html#suites/3556ed71f2d69272a7014df6dcb02317/1548d63440520aa1/):

```
2024-01-18 10:35:49.81  INFO [neon_fixtures.py:2039] not allowed error: 2024-01-18T10:35:41.855944Z ERROR request{method=POST path=/v1/tenant/b881497cb505658654093a9da48e1892/timeline request_id=2118e566-6abd-4fe6-ad5a-1f629b2085a5}:timeline_create{tenant_id=b881497cb505658654093a9da48e1892 shard=0000 timeline_id=965833c923199ffa69d008dcf0068792 lsn=None pg_version=Some(15)}: Failed to remove temporary initdb directory '/tmp/test_output/test_tenant_delete_races_timeline_creation[debug-pg15]-3/repo/pageserver_1/tenants/b881497cb505658654093a9da48e1892/timelines/basebackup-965833c923199ffa69d008dcf0068792.___temp': No such file or directory (os error 2)
2024-01-18 10:35:49.81  INFO [neon_fixtures.py:2039] not allowed error: 2024-01-18T10:35:44.299372Z ERROR delete_tenant{tenant_id=b881497cb505658654093a9da48e1892 shard_id=0000}: Error: timelines dir not empty: Timelines directory is not empty after all timelines deletion: ["basebackup-965833c923199ffa69d008dcf0068792.___temp"]
2024-01-18 10:35:49.81  INFO [neon_fixtures.py:2039] not allowed error: 2024-01-18T10:35:44.299488Z  WARN delete_tenant{tenant_id=b881497cb505658654093a9da48e1892 shard_id=0000}: Marking Stopping tenant as Broken state, reason: timelines dir not empty: Timelines directory is not empty after all timelines deletion: ["basebackup-965833c923199ffa69d008dcf0068792.___temp"]
```

The issue is that the `remove_dir_all` function for the temporary directory against which initdb is running encounters a not found error `No such file or directory (os error 2)` and bails out, leaving behind traces on disk.

One attempt for a fix is in #6352, making the `remove_dir_all` function tolerate not found errors. This is not a full solution however as versions of the failure [have been encountered](https://github.com/neondatabase/neon/pull/6310#issuecomment-1889694544) that involve a `Directory not empty (os error 39)` error inside the `remove_dir_all` function, indicating parallel *write* activity in addition to parallel *read* activity.

**Comment by arssher** [comment]
one more time:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6381/7572949812/index.html#suites/3556ed71f2d69272a7014df6dcb02317/ad01fc543f86573b

**Comment by arpad-m** [comment]
Some further insights from experimentation I did:

* if one implements then the `kill().wait` based cancellation, then the `Failed to remove temporary initdb directory` error is gone, although other errors take its place, like various things taking too long, [allure report link](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6404/7586854246/index.html). this might be turned into a proper fix however.
* #6352 still doesn't work, not sure why. [allure report](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6352/7589106684/index.html)

At least now I have a direction into which to "stab"

**Comment by arpad-m** [comment]
Some further experiments:

* removing cancellation from initdb makes the test in #6404 extremely robust ([allure report](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6404/7618713685/index.html), before it was failing like 5 times as often), which strengthens the theory that it is initdb still messing with the directory. I put the remaining failures onto due to how we retry the deletion request and how we handle allowed errors: if the allowed error occurs, it is not failing the test but it exists the retry loop. I added a wait to the PR which is ugly, waiting on CI for that as I write this.
* John's PR  #6436 is adding a test that lets me reproduce the cancellation racing with directory being deleted issue locally. It works really great. Removing cancellation from `run_initdb` makes me not reproduce the issue.
* I ran `strace` with initdb and it did launch multiple processes. These will not be killed (immediately) when the parent initdb process gets killed, meaning that the way we cancel actually doesn't really work well at all.
* I have tried using process groups for this together with `killpg`, see [this patch](https://github.com/neondatabase/neon/compare/arpad/run_initdb_pgroups#diff-bfd1b153b1f900ef0cbd50a1dc308bf5ba812176e5ad65c8ae2a245bf0f12f84), but I can still reproduce the failure with John's PR's test (just do git merge of that branch with `origin/jcsp/issue-6423`).

**Comment by arpad-m** [comment]
To validate the `killpg` patch, I have built a small program that tries different approaches using three processes "pgtest" (the root/grandparent/pageserver), an intermediate "parent" (what would be initdb in our case), "child" (the leaf process):

* using kill, like done currently on main. you see that only the parent gets killed but the children still print their "reached end" messages
* using killpg, like done in my patch. you see that no child prints anything any more, they are killed successfully
* just waiting for the processes to exit, to validate that all processes print a "reached end" message

You can see how there is a new pgid for the child processes, so that works pretty well.

```Rust
use std::os::unix::process::CommandExt;

#[derive(Debug, Copy, Clone)]
enum Strategy {
    Kill,
    Wait,
    KillPg,
}

fn main() {
    run_strategy(Strategy::Wait);
    run_strategy(Strategy::Kill);
    run_strategy(Strategy::KillPg);
}

fn run_strategy(strategy: Strategy) {
    let pgid = nix::unistd::getpgid(None).unwrap();
    let pid = nix::unistd::getpid();
    println!("------------------------");
    println!("Runner started, strategy={strategy:?}, pid={pid}, pgid={pgid}.");

    let mut parent_path = std::env::current_exe().unwrap().parent().unwrap().to_owned();
    parent_path.push("parent");
    let mut child = std::process::Command::new(parent_path)
        .process_group(0)
        .spawn()
        .unwrap();
    std::thread::sleep(std::time::Duration::from_millis(500));
    match strategy {
        Strategy::Kill => {
            println!("Killing parent using normal kill...");
            child.kill().unwrap();
            println!("Parent killed.");
        },
        Strategy::KillPg => {
            println!("Killing process group of parent...");
            let pgid = nix::unistd::Pid::from_raw(child.id() as _ );
            nix::sys::signal::killpg(pgid, nix::sys::signal::Signal::SIGKILL).unwrap();
            println!("process group killed.");
        },
        Strategy::Wait => {
            println!("Doing nothing...");
        },
    }
    std::thread::sleep(std::time::Duration::from_millis(3_000 + 3000));
    println!("Runner ends after wait.");
}
```

```
------------------------
Runner started, strategy=Wait, pid=439316, pgid=439316.
  Parent started, pid=439318, pgid=439318.
    Child started, pid=439319, pgid=439318.
    Child started, pid=439320, pgid=439318.
    Child started, pid=439321, pgid=439318.
Doing nothing...
    Child reached end, pid=439319, pgid=439318.
    Child reached end, pid=439320, pgid=439318.
    Child reached end, pid=439321, pgid=439318.
  Parent reached end, pid=439318, pgid=439318.
Runner ends after wait.
------------------------
Runner started, strategy=Kill, pid=439316, pgid=439316.
  Parent started, pid=439322, pgid=439322.
    Child started, pid=439323, pgid=439322.
    Child started, pid=439324, pgid=439322.
    Child started, pid=439325, pgid=439322.
Killing parent using normal kill...
Parent killed.
    Child reached end, pid=439323, pgid=439322.
    Child reached end, pid=439324, pgid=439322.
    Child reached end, pid=439325, pgid=439322.
Runner ends after wait.
------------------------
Runner started, strategy=KillPg, pid=439316, pgid=439316.
  Parent started, pid=439326, pgid=439326.
    Child started, pid=439327, pgid=439326.
    Child started, pid=439328, pgid=439326.
    Child started, pid=439329, pgid=439326.
Killing process group of parent...

process group killed.
Runner ends after wait.
```

full crate, including "parent" and "child" processes [pgtest-0.1.0.crate.zip](https://github.com/neondatabase/neon/files/14024136/pgtest-0.1.0.crate.zip)

So the approach of the killpg patch seems to work well. I don't know why it doesn't work in our instance. Further debugging might find the reason, maybe it's because initdb launches sh and that resets the process group ID? I don't know.

I also don't want to spend my entire week on debugging initdb cancellation, as I have other responsibilities, so I will follow John's suggestion to *not* have the pageserver cancel a running initdb but run it to its end.
