### ISSUE TITLE
Add easy way to patch safekeeper control files

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#6397]
Currently it's hard to modify control files manually, since they're stored on disk in a binary format and have a checksum.
We might want to create a tool or API for that.

I suggest to make an API endpoint that will accept arbitrary JSON and apply it to the current `TimelinePersistentState`. What I currently have in mind is the request like this:

```
PATCH /v1/tenant/:tenant/timeline/:timeline/control_file

{
    "updates": {
        "remote_consistent_lsn": "0/12345",
        "timeline_start_lsn": "0/1080"
    },
    "apply_fields": [
        "remote_consistent_lsn",
        "timeline_start_lsn"
    ]
}
```

That will get a response like this:
```
{
    "old_control_file": {
        "tenant_id": ...,
        ...
    },
    "new_control_file": {
        "tenant_id": ...,
        ...
    }
}
```

It also can be useful to add an API to get current control_file content without modifying it, OTOH we already have `debug_dump` or you can pass an empty object to this new API.

**Comment by arssher** [comment]
Probably better do it as a standalone thing like --dump-control-file instead of API endpoint? Sometimes we don't want to load cfile before modification.

**Comment by arssher** [comment]
I needed this again today, so 
https://github.com/neondatabase/neon/pull/6417

**Comment by petuhovskiy** [comment]
> Probably better do it as a standalone thing like --dump-control-file instead of API endpoint? Sometimes we don't want to load cfile before modification.

That is not what I need from this issue. I want to have an endpoint to avoid restarts, otherwise it can be inconvenient to patch many timelines.

**Comment by arssher** [comment]
Ok, let's have both?
