### ISSUE TITLE
Move keyspace utils into `Key` impl

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#6438]
I see those imports. I think if we move these functions to inherent impls on the `Key` type then we won't need as many of them, but I think it should be a separate PR.

_Originally posted by @arpad-m in https://github.com/neondatabase/neon/pull/6406#discussion_r1462286662_

**Comment by koivunej** [comment]
I wonder if we'll win much by this. While working with the "keytool" in #7890 and looking at the auxfilesv2 work happening at the same time, I started thinking that:

Before we make the relation metadata key change to be always on shard0 in finite number of layers, we should make this `Key` be actually structural, like a `enum` of the different meanings.

Then it will be easy to write the two different (v1, v2) mapping functions from this logical key to what is our less-logical key (**u128**).
