### ISSUE TITLE
use CI to get some exposure to tokio-epoll-uring

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6508]
- merge integration PR without the CI changes (i.e., default off, code not tested at runtime)
- after this week's release, for 48h, switch tests to use it)
- switch tests back so next release gets
- fix issues that arose from running it for these 48h
- repeat until no more issues
- switch staging over & observe impact on benchmarks

**Comment by jcsp** [comment]
Already happened, ticket is just open for investigation of flaky tests

**Comment by problame** [comment]
All flaky test failures found were already tracked as flaky for std-fs in the flaky tests db.

https://neondb.slack.com/archives/C036U0GRMRB/p1706524588253939?thread_ts=1706288637.028629&cid=C036U0GRMRB
