### ISSUE TITLE
pageserver: `test_statvfs_pressure_usage` instability

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6510]
`test_statvfs_pressure_usage` and `test_statvfs_pressure_min_avail_bytes` are among the most frequent flaky failures.

**Comment by koivunej** [comment]
There seems to be two modes:
- [needing to use global LRU](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6506/7694815442/index.html#testresult/ed6dc371b4a3421a/retries)
    - [pg14](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6506/7694815442/index.html#/testresult/9eec3772333f6c1e) at least
- [evicting too much](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6447/7695408313/index.html#testresult/ee09a510c10f7e41/retries)
    - [pg14](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6491/7668095676/index.html#testresult/7d47284c3eaee953/retries)
    - [pg16](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6475/7659796723/index.html#testresult/58fff8f3c0bc186d/retries)

**Comment by koivunej** [comment]
Downloads are caused by initial logical size calculation, it's a bit of a toctou fight. I'll add a wait until we have calculated all timelines sizes.
