### ISSUE TITLE
pageserver: `test_emergency_mode`, `test_secondary_mode_eviction` instability

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6511]

**Comment by koivunej** [comment]
I was initially thinking this could be handled the same way as #6510 since it's copypasted, but now spotting in local testing:

```
2024-01-30T17:20:44.124841Z ERROR disk_usage_eviction_task:iteration{iteration_no=1}:panic{thread=background op worker location=pageserver/src/statvfs.rs:106:21}: mocking error: used_blocks > total_blocks: 225030 > 225024
```

In other cases the problem seems to be that the layers disappear from heatmap:

```
2024-01-30T17:23:55.556039Z  INFO secondary_download{tenant_id=aacba81487a33c340272667c4aab2cb3 shard_id=0000}:secondary_download_timeline{tenant_id=aacba81487a33c340272667c4aab2cb3 shard_id=0000 timeline_id=dd087dd2c3682c5d6803e39d645db2f3}: Removing secondary local layer 000000067F000000050000400C0000000AF0-000000067F000000050000400C0000000DF9__00000000014EF420-0000000005F90379 because it's absent in heatmap
```

This happens before disk usage based eviction runs, and so it never gets to relieve any pressure. The latter was `test_secondary_mode_eviction[debug-pg16-47]`, I don't understand why would those become absent in heatmap.

**Comment by koivunej** [comment]
Recent example of the first: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6549/7725331961/index.html#/testresult/ea57888c979067e0

**Comment by koivunej** [comment]
Now I understand the `test_secondary_mode_eviction`, the problem is that I failed to notice in review the use of mocked statvfs. That is unnecessary, if the secondary hosting ps was not restarted and http method used to run the eviction, it would probably be stable right away.

**Comment by jcsp** [comment]
The failures on `test_secondary_mode_eviction` where we hit "Removing secondary layer" are a side effect of tenants going through the more sophisticated attachment_service bits -- the test is trying to migrate tenants all to one pageserver to leave the other one with just secondaries, but the live migration process it itself triggering heatmap uploads, and the heatmap eventually uploaded from the new location can be smaller, leading to a condition where we go from a larger to smaller heatmap.

**Comment by jcsp** [comment]
`test_secondary_mode_eviction` still failing sometimes with
```
statvfs.rs:106:21}: mocking error: used_blocks > total_blocks: 358550 > 358544
```

This is kind of an over-strict condition: it is requiring that the pageserver writes _nothing_ to its tenants dir between startup and calling statvfs (since the total_blocks is set based on the on-disk size after shutdown).

Since this is still failing, I'll go with Joonas's earlier suggestion and refactor the test to avoid using mocked statvfs at all.

**Comment by jcsp** [comment]
In last 48h:
- no failures of test_emergency_mode
- 3 failures of test_secondary_mode_eviction, but they were all on a release pR https://github.com/neondatabase/neon/pull/6758 that doesn't include #6698.

I'm calling this fixed.
