### ISSUE TITLE
Add pgvector 0.7.0

### ISSUE THREAD

**Issue by raoufchebri** [neondatabase/neon#6516]
Update the current pgvector extension version 0.5.1 to 0.6.0 to include parallel index build
https://github.com/pgvector/pgvector/releases/tag/v0.6.0

**Comment by andreasscherbaum** [comment]
Waiting for Autoscaler team, requires more memory in shmem.

**Comment by bayandin** [comment]
Reopening the issues, as it's not done yet, and blocked by https://github.com/neondatabase/autoscaling/issues/800

**Comment by andreasscherbaum** [comment]
The blocker is basically that we do not have enough for memory for many use cases, and we run out of memory.
To avoid that, we need to enable swap. From there we autoscale up.

**Comment by andreasscherbaum** [comment]
Current blockers:
- Swap changes (proposed for May 20th)
- Increase max_worker_processes

**Comment by andreasscherbaum** [comment]
Release scheduled for week 22, 2024.
