### ISSUE TITLE
Multixid wraparound handling

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#6520]
In `walingest.rs`, we have this:
```
        if xlrec.mid >= self.checkpoint.nextMulti {
            self.checkpoint.nextMulti = xlrec.mid + 1;
            self.checkpoint_modified = true;
        }
        if xlrec.moff + xlrec.nmembers > self.checkpoint.nextMultiOffset {
            self.checkpoint.nextMultiOffset = xlrec.moff + xlrec.nmembers;
            self.checkpoint_modified = true;
        }
```
That doesn't do the right thing if multixid has wrapped around. Need to do wraparound aware comparison, as iin Postgres' MultiXactAdvanceNextMXact function, or as we do for XIDs in `update_next_xid`.

**Comment by ololobus** [comment]
@hlinnaka I see a fix merged recently, is it done? Is there any way to verify that this fix was enough?
