### ISSUE TITLE
test_neon_superuser is flaky, relies on sleep(1)

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6561]
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6471/7733161123/index.html#/testresult/c2a0ee73e6268429

```
AssertionError: assert 0 == 4
 +  where 0 = len([])
```

The test sleeps 1 second to wait for something to propagate.  This is a recipe for flaky test: use `wait_until` instead.

**Comment by save-buffer** [comment]
Wow that's a very handy function!
