### ISSUE TITLE
delta layer file writer errors leak the layer temp file on disk

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6623]
## Motivation

https://neondb.slack.com/archives/C033RQ5SPDH/p1707083892302179

## DoD

TBD

## Impl

```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/6612
- [ ] https://github.com/neondatabase/neon/pull/6625
```

**Comment by jcsp** [comment]
I think this can close: the action to cover the other cases where we potentially leak __temp files is https://github.com/neondatabase/neon/issues/6627
