### ISSUE TITLE
safekeeper: cut remote deletions into chunks of size 1000 

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#6635]
According to [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html), AWS only supports deleting up to 1000 batched objects per deletion API request.

In the pageserver, we have the [deletion queue](https://github.com/neondatabase/neon/tree/5e8deca26862f190e6f38b31ccea5f0a22c36c69/pageserver/src/deletion_queue) which does this cutting. The deletion in the safekeepers added by #6381 doesn't do such cutting, it collects the whole list of remote files and then deletes them in one go, which causes the call to be retried very often until it eventually succeeds.

As the problem has already been solved in the pageserver, should we maybe move the deletion queue to the `remote_storage` crate so that the safekeeper can use it as well? Should it be in a different crate?

cc https://neondb.slack.com/archives/C04KGFVUWUQ/p1707066000456149

**Comment by arssher** [comment]
this is already done in s3_object.rs
