### ISSUE TITLE
walredo bench should be switched to a single multi-threaded runtime

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6648]
It currently spawns single-threaded runtimes on `n` threads (where `n` is controlled by criterion).

Instead, spawn a multi-threaded runtime where `n` clients run, all pounding against _one_ walredo manager.

**Comment by calinanca99** [comment]
Hi @problame! Opened #6743 to address this. Would appreciate your review! 🙏🏻

**Comment by problame** [comment]
Thanks for your contribution, @calinanca99
