### ISSUE TITLE
Revise initdb handling on shard >0 

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6649]
We currently run initdb on all shards:
- Most shards don't need most of the data from initdb
- There is a risk that non-determinism of initdb results in different shards having different start LSNs
- It generates extra load, e.g. when doing big parallel timeline creations in scale testing, we bottleneck on disk doing all these initdbs.

**Comment by arpad-m** [comment]
If there is no relevant needed data from the initdb, it can just be removed. If there is relevant data, we could download the initdb that shard 0 uploaded. There is already download code present, all one needs to do is change some checks (and enforce some order where we make sure shard 0's initdb is uploaded before the other shards do the download).

We could also press forward with the plan of doing initdb on the compute and sending it as part of the WAL.

**Comment by jcsp** [comment]
Realization: currently we need SLRUs on all shards for teh get_slru_page_at_lsn that is done during GC preparation.
