### ISSUE TITLE
Epic: grant either pg_monitor or pg_read_all_stats to neon_superuser

### ISSUE THREAD

**Issue by YanicNeon** [neondatabase/neon#6682]
## Motivation
We sometimes have customers asking to be granted the role pg_monitor or pg_read_all_stats in order to have visibility on various statistics related extensions, even those normally visible only to superusers.

At the moment, when executing a simple `select * on pg_stat_statements`, the neon_superuser doesn't have the required privileges to view the query text of queries executed by other users.

Example:

> neondb=> select * from pg_stat_statements limit 1;
> userid|10
> dbid|5
> toplevel|t
> queryid|
> query| < insufficient privilege >
> [output truncated]
> neondb=> 

See: https://neondb.slack.com/archives/C03QLRH7PPD/p1707339228209559

**Comment by Bodobolero** [comment]
A similar problem exists for view `pg_stat_progress_vacuum`
see https://github.com/neondatabase/neon/issues/6686
