### ISSUE TITLE
find a solution to centralize RUSTFLAGS

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6782]
Yep, my assessment as well. Dismissing this conversation for now, but, longer term, we should find a solution to centralize RUSTFLAGS

_Originally posted by @problame in https://github.com/neondatabase/neon/pull/6764#discussion_r1492170303_

**Comment by jcsp** [comment]
Does this belong in storage team's backlog?  Should it be CI/CD team?

**Comment by problame** [comment]
I'm "happy" with the situation we have right now.

IMO each team should be able to have high ownership & control of their build (same argument as for why each team should have high ownership & control of their deployment process).

Then again, it makes sense to have a central team (prob CI/CD) provide a build platform / interface. (Use the Dockerfile more?)
