### ISSUE TITLE
Flakiness in test_sharding_split_smoke

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6813]
Example:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6805/7957035402/index.html#suites/140824de6e814b5b1ae2b622c3f67840/6cd46f9911ed5b0f

In that run, the compute hook (local version, using neon_local `Endpoint`) is hanging, causing migration to time out.

**Comment by jcsp** [comment]
Having fixed spurious reconciles, the logs are cleaner in this failure:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6828/7964818040/index.html#/testresult/dd6a70cde8671f8

In this example we see an error configuring compute node, but we're only giving it 2 seconds to complete because the earlier part of the migration (switching origin to stale mode) took 8 seconds.  So it may be that we're just not giving it enough time, and the apparent failure of compute configuration is actually just the compute notification taking a while (although I'm still a bit concerned that the compute configuration in a neon_local environment isn't sub-second, it shouldn't be slow).

**Comment by jcsp** [comment]
zero flakes of this in last 24h -- I suspect that #6814 made it much much rarer.

**Comment by arpad-m** [comment]
Recently it started to re-occur again:

![Screenshot_20240321_175543](https://github.com/neondatabase/neon/assets/19521842/d6df095d-5284-42fd-8ac2-c4656883bbf5)
