### ISSUE TITLE
utilization api:  pageserver fitness for the next tenant

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#6835]
Original text after offsite:

> Once we work to a target disk size, the control plane can no longer use available disk to drive selection of pageserver for placing new tenants. The pageserver should instead report a "active set size" that can be used to identify which pageserver is a good candidate to place work onto (least active set size relative to disk size)

Later iteration realizes a `/v1/utilization` on pageserver providing disk usage **AND** score for how bad the pageserver would be for the next tenant. The actual logic is not yet implemented, but it will need to consider each tenant being conformtable at it's synthetic size or an estimate out of other factors.
```[tasklist]
### Tasks
- [ ] https://github.com/neondatabase/neon/pull/6831
- [ ] actual background task to calculate the utilization score periodically
```

**Comment by koivunej** [comment]
Steps this week:
- Might get to sketching out the periodic score calculation "backend"

**Comment by jcsp** [comment]
Closed in https://github.com/neondatabase/neon/pull/8703
