### ISSUE TITLE
storage controller: node heartbeats

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6844]
We need a piece of code that sends requests to pageservers in the background to get their latest utilization and implicitly check that they're alive.

Later, we may also use this code path to automatically mark a node offline if it fails to respond past some threshold, but that's not this ticket.

- We should use the new utilization endpoint in https://github.com/neondatabase/neon/pull/6831
- Add state to SchedulerNode to record the score/space reported by that utilization endpoint, and use it when making decisions about where to place shards (i.e. don't base scheduling purely on shard counts).
- If a node is currently Offline and the heartbeat code notices it is online, then set it to an active state.  This is important because otherwise if a node was offline when the controller started, it will remain offline forever.

**Comment by problame** [comment]
* Vlad will get reviewable PR published this week
