### ISSUE TITLE
storage controller: prometheus metrics & dashboard 

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6875]
Extend metrics, including at least:
- HTTP API status counters + latency histograms for the controller's HTTP API
- Latency/error counters tagged by node_id for outbound calls to pageserver
- Database client metrics: error counter, query latency histogram (wrap `with_conn`)

Then create a re-usable grafana dashboard for the storage controller that takes the controller container name as a dropdown variable.

**Comment by VladLazar** [comment]
Dashboard still pending

**Comment by VladLazar** [comment]
v1 dashboard here: https://neonprod.grafana.net/d/edgqpf8ka8jr4a/storage-controller-dashboard?orgId=1

I didn't add the passthru latencies and error rates because I've got no data for them yet (logs agree). I'll come back later and add them.
