### ISSUE TITLE
docs: GetPage@Lsn description is TBD

### ISSUE THREAD

**Issue by fansehep** [neondatabase/neon#6887]
I want to know how neon pageserver to process the `GetPage` Request. Request updated documentation for `neon/docs/pageserver-processing-getpage.md` which currently has only placeholder text.

**Comment by koivunej** [comment]
In the meantime to providing proper docs, some pointers:
- [pageserver::page_service](https://github.com/neondatabase/neon/blob/main/pageserver/src/page_service.rs) handles serving requests from postgres (compute)
    - https://github.com/neondatabase/neon/blob/8283779ee84d351f520c4f95327e646e2db0f7d7/pageserver/src/page_service.rs#L550 is where we enter a "pagestream" mode because compute requested it
    - in this mode the actual queries are executed
- there is also a http api for getpage@lsn: https://github.com/neondatabase/neon/blob/8283779ee84d351f520c4f95327e646e2db0f7d7/pageserver/src/http/routes.rs#L1729 via `/v1/tenant/:tenant_shard_id/timeline/:timeline_id/getpage`

Eventually both arrows go reach `Timeline::get` which first gathers everything we need to **reconstruct** a page at particular LSN. We could also find a ready image, or have cached a previously constructed image.

The topic of "gathers everything we need to reconstruct a page" is described a bit in https://neon.tech/blog/persistent-structures-in-neons-wal-indexing. There is ongoing work to vectorizing the `Timeline::get` in #6296.

**Comment by fansehep** [comment]
Thanks your reply. I probably know how `GetPage` does it.
