### ISSUE TITLE
test_remote_timeline_client_calls_started_metric is flaky

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6889]
8 failures in the last 24h.

---

(@problame is taking over editing of this issue description)

```[tasklist]
### Impl
- [ ] https://github.com/neondatabase/neon/pull/6911
```

**Comment by problame** [comment]
Comparing a good run with a bad run (with `debug` logging enabled).

The good run has additional layers 

![image](https://github.com/neondatabase/neon/assets/956573/dcea86b1-deaa-4bc2-8928-671795cfbdb4)
