### ISSUE TITLE
cleanups following removal of `metadata` file

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6890]
This is follow-up to https://github.com/neondatabase/neon/pull/6769 once it has been rolled out and we won't roll it back.

- make `remote_storage` non optional (https://github.com/neondatabase/neon/pull/7752)
- remove the migration code that removed the `metadata` file 
  - spot-check prod logs of deployment first & maybe check the filesystem?

**Comment by jcsp** [comment]
Starting the process of making remote storage mandatory here: https://github.com/neondatabase/neon/pull/7722

We can require it in the config, and then proceed to weed out all the places where we have a spurious Option<> that's always Some.
