### ISSUE TITLE
compute_ctl: `PG: ... WARNING:  invalid configuration parameter name "neon.primary_is_running", removing it`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6908]
Found while debugging `test_bulk_insert` benchmark, but, probably affects other components.

Smells like some TODO code cleanup that was forgotten.

**Comment by skyzh** [comment]
Is this warning showing up with the vanilla Postgres benchmark or the Neon Postgres benchmark? Vanilla pg does not install the Neon extension and therefore it does not have access to the `neon.primary_is_running ` GUC, so the warning looks fine.

And I did not reproduce it in my local environment over the current lastest commit :( https://github.com/neondatabase/neon/commit/b2bbc20311ad95baafb8430250f43b07233ce1ff -- is that showing up in stdout/stderr?

**Comment by skyzh** [comment]
Or you are using an older version of Postgres. I saw https://github.com/neondatabase/neon/pull/6901 got merged 3 days ago. Probably you will need to recompile Postgres 🤪
