### ISSUE TITLE
bare log line: `INFO starting to wait for the gc'd layers to be dropped total=1` 

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#6910]
Observed in `test_remote_timeline_client_calls_started_metric`

Should probably have tenant / timeline id in span fields, along with a `debug_span_contains...` assert to prevent regressing this.

Feel free to close if that's infeasible.

**Comment by koivunej** [comment]
Unsure why there was not any request scoped span... Perhaps because there is this additional hop:

1. hyper request handling
2. our "middleware" spawns a request handler with a span
3. this tenant_mgr immediate_gc spawns yet another request handler

I'll look at it at one point.
