### ISSUE TITLE
Epic: Local File Cache Enhancements

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#6919]
## Motivation

The local file cache implemented in `file_cache.c` is the bridge to close the performance gap between vanilla Postgres and Neon Postgres. Neon fetches data from the page server, which is over the network and cannot be cached in the operating system page cache. The local file cache caches such data. LFC creates a file on the file system and maintains blocks of data inside that file.

https://www.notion.so/neondatabase/Local-File-Cache-What-s-Now-and-What-s-Next-cf8ca77d25f64173a918b059651c8284

Besides the main purpose of being a cache, the LFC also serves several other purposes when it is combined with autoscaling:

* Multi-tenancy. By dynamically resizing the LFC, we can share the local disk space among multiple tenants based on workloads.
* Dynamic shared buffer. Postgres cannot scale its shared buffer when the memory size scales, but we can use LFC to make the working set of Postgres dynamic. We expect the LFC file to be cached in the OS page cache so that it does not issue I/Os to the disk. 

## Implementation ideas

* How much does the LFC benefit us compared with a large shared buffer?
* Performance analysis and improvement.
* Physical size control and dynamic resize.

### Tasks

```[tasklist]
- [ ] Raw block device support.
- [ ] Benchmark plans.
```

## Other related tasks and Epics
-

**Comment by andreasscherbaum** [comment]
Please gather benchmark data for a blog posting as well, and how this can be compared to vanilla PostgreSQL.

**Comment by skyzh** [comment]
Benchmark result: https://www.notion.so/neondatabase/Local-File-Cache-Benchmark-ec3bae94bc1a407eb2c7db941a9d4d21

**Comment by skyzh** [comment]
update: will wait until a cross-team meeting before taking next steps.

* set LFC size to be 2x guest memory (gradually increase, 0.1x per week from 0.6 now)
* allocate more than 2x guest memory depending on available space on bare metal server
* autoscaling based on LFC miss rate

**Comment by andreasscherbaum** [comment]
A blog post does not need to include our weak sides, just the data and results showing how the OS behaves.

**Comment by skyzh** [comment]
* 80% quota goes into prod
* https://github.com/neondatabase/autoscaling/pull/878 under review and still discussing the best way to expose LFC statistics to autoscaling
* need to remove the limit in https://github.com/neondatabase/neon/blob/main/libs/vm_monitor/src/filecache.rs in order to further increase the quota

**Comment by lubennikovaav** [comment]
LFC is in a decent shape now. We can reopen this if any future work is needed.
