### ISSUE TITLE
neon.neon_lfc_stats errors in compute logs

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#6982]
## Steps to reproduce

Go to https://neonprod.grafana.net/goto/BtsffeoIg?orgId=1 to look at compute logs.

## Expected result

No `ERROR:  relation "neon.neon_lfc_stats" does not exist` in the logs

## Actual result

Quite a lot of such errors. But they are not persistent, probably this is just a race condition on the compute start: monitoring tries to collect lfc stats before compute initiailizes this relation?

## Environment

prod/staging

## Logs, links
-

**Comment by knizhnik** [comment]
View `neon_lfc_stats` was added in 1.1 version of neon extension.
So I see three possible reasons of this error:
1. neon extension was not created but we have some metrics which tries to collect this infortmation,
2. neon extension was created but was not upgraded, so it is still on 1.0 version
3. User under which metrics collector tries to execute this query has no access to neon extension. On case of another view `NEON_STAT_FILE_CACHE` I see the following grant statement in neon--1.--1.2.sql:
```
GRANT SELECT ON NEON_STAT_FILE_CACHE TO PG_MONITOR;
```
Should it one done fort the views as well?

**Comment by skyzh** [comment]
should be fixed by https://github.com/neondatabase/neon/pull/7029
