### ISSUE TITLE
[RFC] Separate wal-redo postgres from compute postgres

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#709]
I can see two possibilities here:
* different branch (which is a bit hard to deal with)
* wrap wal-redo changes (it is small amount of changes) with #ifdefs and create different Makefile target that enables some #ifdef's and produces separate wal-redo binary -- I'm inclined towards that option
* just be more explicit about wal-redo-related changes in code comments

**Comment by shanyp** [comment]
@kelvich can this be closed ?
