### ISSUE TITLE
auto regress to std fs backend if io_uring is not usable on Linux

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#7116]
## Steps to reproduce

Run page server on <del>Docker for macOS</del> OrbStack. io_uring cannot be used. Page server starts normally, and will only error when new tenants are attached.

Probably it would be good to run some quick kernel version checks before deciding to use io_uring backend by default.

## Expected result

Error at an early stage or automatically regress to std fs backend.

## Logs, links
-

**Comment by problame** [comment]
Will take a look tomorrow.

Out of curiosity, what kernel version and distribution are running in the Docker VM?

```
cat /etc/os-release
uname -a
```

**Comment by skyzh** [comment]
Inside the page server container,

```
neon@add5f88ee4ab:~$ cat /etc/os-release
uname -a
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux add5f88ee4ab 6.5.13-orbstack-00122-g57b8027e2387 #1 SMP Tue Feb  6 07:48:26 UTC 2024 aarch64 GNU/Linux
```

I'm on OrbStack Pro trial and it's really easy to use 😅 except I don't know what modifications they did to the kernel.

**Comment by arpad-m** [comment]
Seems related: https://github.com/moby/moby/issues/39396

**Comment by arpad-m** [comment]
esp: https://github.com/moby/moby/issues/39396#issuecomment-1835709369

**Comment by arpad-m** [comment]
I suppose if we want auto-detection, kernel versions won't do. We'll have to check by trying out the `io_uring` API directly.

**Comment by problame** [comment]
I already do feature-checking in tokio-epoll-uring, just need to turn it into a public API

**Comment by problame** [comment]
PR is out: https://github.com/neondatabase/neon/pull/7120
