### ISSUE TITLE
performance regression test for `pagebench ondemand-download-churn`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7146]
In PR https://github.com/neondatabase/neon/pull/6992 I added `pagebench ondemand-download-churn` to manually perf-test ondemand download throughput.

We should turn that into a performance regression test like we have for pagebench.

The Results document (public Notion page) contains all instructions required:

https://neondatabase.notion.site/Benchmarking-tokio-epoll-uring-on-demand-downloads-2024-04-15-newer-code-03c0fdc475c54492b44d9627b6e4e710?pvs=4

Adding the "good first issue" label because it is a nice self-contained exercise, but, it's probably 2 days of work to get this done for a new hire / first-time contributor.

**Comment by jbajic** [comment]
Is it ok if I start working on this one?

**Comment by problame** [comment]
Sorry for the late reply. AFAIK nobody is working on this yet, so, feel free to take a stab. 

I suggest to try running `test_runner/performance/pageserver/pagebench/test_pageserver_max_throughput_getpage_at_latest_lsn.py` on your machine first, check out `test_runner/performance/pageserver/README.md` for instructions.

Please request review from me when opening any PRs, otherwise I'm unlikely to notice.

**Comment by jbajic** [comment]
Since I cannot request a review I have tagged you in the PR @problame
