### ISSUE TITLE
pageserver: implement Serialize for SystemTime with RFC3339 format

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7151]
Since https://github.com/neondatabase/neon/pull/7131 we have two places that use a helper (`ser_rfc3339_millis`) to get serde to string-ize SystemTimes into the format we want.

It would be nice to just have a Serialize implementation so that we don't have to decorate structs.

**Comment by kevinmingtarja** [comment]
Hi, I'd like to contribute to this!

**Comment by jcsp** [comment]
Thanks, feel free to open a PR
