### ISSUE TITLE
`test_ondemand_activation` is flaky

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7158]
37 failures in last 7 days.

**Comment by arpad-m** [comment]
it was quite flaky but [isn't any more now](https://neonprod.grafana.net/d/fddp4rvg7k2dcf/regression-test-failures?orgId=1&var-test_name=test_ondemand_activation&var-max_count=100&var-restrict=true).

![Screenshot_20240318_125140](https://github.com/neondatabase/neon/assets/19521842/f02ada89-8d0a-4bac-96a6-79a2794e3363)

**Comment by VladLazar** [comment]
This is unrelated to the storage controller. Tenant warm-up happens on a different task and we add the entry to the tenant map optimistically. The test expects that once the tenant map has been updated, all the tenants should have finished warming-up, which is not racy.

We need to wrap the metrics wait in a `wait_until`.
