### ISSUE TITLE
pageserver: near overload benchmark fails to generate `/metric`s

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#7161]
My best guess for cause is the remaining `with_label_values` calls because missed metrics only happen during the busiest times but are fine before and after.

Requests to `/metrics` fail because of collection time is high on this line: https://github.com/neondatabase/neon/blob/1d3ae57f18462e150a74d044c4f59c34a6c27e69/libs/utils/src/http/endpoint.rs#L275

Such cases like look like this for example:

```
2024-03-04T20:06:10.836918Z  WARN request{method=GET path=/metrics request_id=edba3aef-656c-415a-82d4-16576f98952c}:blocking: failed to write out /metrics response: Io(Kind(BrokenPipe)) after_bytes=0 total_ms=32828 spawning_ms=85 collection_ms=32742 encoding_ms=0
```

Possible culprits are can be found with `rg with_label_values`. What we should do instead is to store the value `with_label_values` call created somewhere and only do this query once.

**Comment by koivunej** [comment]
Discussion from planning meeting: this should be a higher priority fix.

**Comment by jcsp** [comment]
afaik we haven't seen this in a while
