### ISSUE TITLE
deal with running_xacts to hot standby replica

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#7236]
## Steps to reproduce

A previous fix to ensure hot standby replicas to have running transactions information caused replicas fail to start or take a long time to start (tracked by https://github.com/neondatabase/neon/issues/7204). To fix this issue, we reverted part of https://github.com/neondatabase/neon/pull/6705 and removed `test_replication_start` test, via https://github.com/neondatabase/neon/pull/7209. We need to fix this issue and add back the test cases.

## Logs, links
-

**Comment by skyzh** [comment]
Discussion at https://github.com/neondatabase/neon/issues/6211#issuecomment-2020965697

**Comment by kelvich** [comment]
PR: https://github.com/neondatabase/neon/pull/7288

**Comment by hlinnaka** [comment]
PR #7288 was merged. That hopefully fixes most of the issues, although there are still known cases with lots of subtransactions, where the read replica might not immediately start up, or might crash with an error later. We are betting that those cases won't happen very often in practice.

**Comment by kelvich** [comment]
so let's close this one then. we track overall phys replication re-launch in parent epics
