### ISSUE TITLE
pageserver: revise time-based layer rolling

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7241]
```
Currently, we roll a layer if checkpoint_period has passed since last_freeze_at.
That's okay if we presume that the last time we froze a layer, we also opened a layer (i.e. it's the age of the current inmemory layer).  But if we [close a layer while idle](https://github.com/neondatabase/neon/pull/7218), last_freeze_at is a weird thing to use: if we last froze an hour ago, but only just opened our current layer, we shouldn't roll it!
So the minimal change would be to track the last time we opened a new layer, instead of the last time we froze one. (edited) 

However, it's not obvious to me that we should use layer age at all to drive this: if we are rolling layers in order to allow the safekeeper to see remote_consistent_lsn catch up, and let a timeline go idle, then we really care about idle time, not the age of a layer.
So we would compare checkpoint_interval to the time since we last wrote something to the layer.  If someone writes a little bit of data every 10 minutes, their layer stays open.
```

via https://neondb.slack.com/archives/C033RQ5SPDH/p1711384549132359

So, we should:
- Change last_freeze_at to store a "last written at" time
- Update it on drop of a HeatmapWriter if that writer wrote something

**Comment by VladLazar** [comment]
> So, we should:
    * Change last_freeze_at to store a "last written at" time
    * Update it on drop of a HeatmapWriter if that writer wrote something

This doesn't make sense to me. 

"if we last froze an hour ago, but only just opened our current layer, we shouldn't roll it!`
With the proposed approach we would roll since the last write was an hour ago. I think the thing that we want to track
is the first write into an open layer.
