### ISSUE TITLE
tiered compaction: fails to meet target file size on many updates to a single key

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7243]
We have a test but it's ignored because the code to handle the case hasn't been implemented yet.

https://github.com/neondatabase/neon/blob/045bc6af8bae53305cf30771faa2d8478299868b/pageserver/compaction/tests/tests.rs#L4-L13

**Comment by problame** [comment]
Solution is there, needs impl; PR to be created this week, @hlinnaka will review since @problame is on vacation starting Thu.

**Comment by arpad-m** [comment]
took a stab at this today and got until an infinite loop: there needs to be some changes in the tier identification logic to ignore stacked single-key deltas, i.e. treat them as one.

Issue #7296 might be related, my changes had to add some additional sorting there...

**Comment by problame** [comment]
Arpad to publish a draft PR that demonstrates the infinite loop problem.
Then go over the problem with @hlinnaka

**Comment by arpad-m** [comment]
Draft PR with the infinite loop problem: #7671 

(still has debug prints, I have removed the stuff I have since upstreamed however)
