### ISSUE TITLE
new compaction: Fix failure in staircasing test

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7244]

**Comment by arpad-m** [comment]
[slack link](https://neondb.slack.com/archives/C06Q6MQ2QSC/p1710959383410039)

Error msg:

```
ERROR layer_delete{tenant_id=61e66dc7e243450d90a8ed5624ad9d26 shard_id=0000 timeline_id=df0ea8a3bad847e88802a4b6a809c533}: 000000000000000000000000000000000000-000000067F00000001000004E70000000016__000000000DBC0841 was unlinked but was not dangling
```

**Comment by koivunej** [comment]
Replied already here: https://neondb.slack.com/archives/C06Q6MQ2QSC/p1710964895205409?thread_ts=1710959383.410039&cid=C06Q6MQ2QSC

**Comment by arpad-m** [comment]
I've investigated this today.

* The affected files are all image layers
* Before the mentioned error message, the files produce log lines like:
```
INFO request{method=PUT path=/v1/tenant/b4ed2fb5d2020a52930b09b5fdefb8e4/timeline/3a3a25d547a6b9a801621ff43c090713/do_gc request_id=678ea518-ebb7-477c-a9f9-fdd0d9e145d4}:manual_gc{tenant_id=b4ed2fb5d2020a52930b09b5fdefb8e4 shard_id=0000 timeline_id=3a3a25d547a6b9a801621ff43c090713}:gc_timeline{timeline_id=3a3a25d547a6b9a801621ff43c090713 cutoff=0/21853860}: Deleting layer 000000067F00000001000004E70000000016-000000067F0000000100000A280300000000__000000000DBBCAE1 not found in latest_files list, never uploaded?
```
* Those unlinked errors show up, timestamp wise, before the `Physical storage size` log entry (for step=2), so most of the steps are not needed to reproduce this issue (giving shorter iteration time)
