### ISSUE TITLE
tiered compaction: assertion failed: last.last_key <= key

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#7296]
The following assertion error is hit with new compaction:

```
panic{thread=mgmt request worker location=pageserver/compaction/src/compact_tiered.rs:757:13}: assertion failed: last.last_key <= key
```

I have a local test that reproduces it, extracted from/based on `test_deletion_queue_recovery`.

I think the problem is that the `merge_delta_keys` function does not return keys in key order.

originally part of #6768
moved to #7554

**Comment by arpad-m** [comment]
I confirm, this is also reproducible with the `test_deletion_queue_recovery` test, now that #7282 has been merged.

**Comment by problame** [comment]
No progress last week, plan to address this week.

**Comment by arpad-m** [comment]
I looked at it this on Tuesday and I haven't made much progress. I have found issues with the k-merge though (`MergeDeltaKeys`):

* The items are modified while inside the heap in a way that it influences their ordering relative to other entries of the heap. One has to remove the item, modify it, and then reinsert it.
* The order should also depend on the lsn: we want lower lsn to come before higher lsn. There is no such sorting right now, it all sorts based on keyspace. If you are fed a bunch of delta layers for `0000-FFFF` keyspace with increasing lsn intervals, then the order they get chosen depends on the order of feeding, or some other arbitrary choice. Not what we want :).

I have fixed both issues in a local branch but this is sadly not enough to make the assert not fire. I have however filed a PR to make us assert a little bit more early on: #7648.

**Comment by problame** [comment]
Meeting decision:

- we'll remove the stream-based k-merge and use the primitive in-memory kmerge from the compact_legacy instead
- Arpad to create a follow-up in the "Backlog" list of the epic to add back stream-based k-merge

**Comment by arpad-m** [comment]
The changes to remove the streaming based k-merge are in #7661, also with the two (insufficient) correctness fixes for the stream-based k-merge.

**Comment by arpad-m** [comment]
Closing as #7661 has been merged
