### ISSUE TITLE
`get_vectored_sequential_impl` does not catch all missing key errors

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#7380]
## Steps to reproduce

`could not find layer with more data for key` might need to be caught as missing key error in `get_vectored_sequential_impl`? This happened in https://github.com/neondatabase/neon/pull/7375 and I am still figuring out why this error is thrown at the first place.

cc @VladLazar 

## Logs, links
-

**Comment by VladLazar** [comment]
Interesting. I've never seen the non-vectored read path hit that code path. I though that concern was mostly theoretical. Do you happen to have logs?

**Comment by jcsp** [comment]
We think this issue is no longer relevant given the latest approach to reading aux keys -- please re-open if not
