### ISSUE TITLE
Coalesce non-vectored get with vectored code (use vectored get for single key gets)

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7381]
Anticipate some performance work to make vectored get equally fast for single key case (e.g. https://github.com/neondatabase/neon/issues/6932)

```[tasklist]
### Ordered list of changes 
- [ ] https://github.com/neondatabase/neon/pull/7486
- [ ] https://github.com/neondatabase/neon/pull/7490
- [ ] https://github.com/neondatabase/neon/pull/7477
- [ ] https://github.com/neondatabase/neon/pull/7498
```

**Comment by jcsp** [comment]
Last week:
- this shook out a bug that was fixed.
- investigated why it's slower in some cases.

This week:
- A fix for difference in how we handled aux files
- Continue optimizing

**Comment by VladLazar** [comment]
Last week:
* Merged aux file handling fix
* Subtle fix for materialized page cache usage
* Optimised
* Benchmarking - looks on par with legacy read path (even a bit better)
* Ran with validation in staging over the weekend - no correctness issues

This week:
* Run in staging without validation to qualify perf
* Start staged roll out if above is ok

**Comment by VladLazar** [comment]
Last week:
* Qualified perf & correctness in staging/pre-prod

This week:
* Deploy to ap-southeast regions & monitor

**Comment by VladLazar** [comment]
Last week:
* Deployed to ap-southeast-*. Small latency increased, but tput was much higher. CPU utilisation was better

This week:
* Deploy to us-east-*

**Comment by koivunej** [comment]
#7939 should be reverted when the default is changed.

**Comment by VladLazar** [comment]
Rollout was completed a few weeks ago. At this point, the non-vectored read path is no longer in use (apart from validation which will be removed by #8005)
