### ISSUE TITLE
basebackup: don't classify network errors as error (client hang-up, connection timeout)

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7391]
# Problem

Pageserver 4GS dashboard showed basebackup errors

https://neonprod.grafana.net/d/d061a222-a79b-4c4b-8e77-16b11545b1fe/pageserver-4-golden-signals?orgId=1&from=1713114248600&to=1713121930134&viewPanel=1

=> but when excluding the two network errors, there are no results

[Logs Query](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22e74%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bunit%3D%5C%22pageserver.service%5C%22%7D%20%7C%3D%20%60ERROR%60%20%7C%3D%20%60basebackup%60%20%21%3D%20%60%20Connection%20reset%20by%20peer%60%20%21%3D%20%60Connection%20timed%20out%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221713114248000%22,%22to%22:%221713121930000%22%7D%7D%7D&orgId=1)

```
{unit="pageserver.service"} |= `ERROR` |= `basebackup` != ` Connection reset by peer` != `Connection timed out`
```

# Solution

Clean up error handling path so that we can correctly classify these network errors (likely some `impl From<...> for QueryError` impl.

**Comment by skyzh** [comment]
alert set up for staging, waiting on https://github.com/neondatabase/neon/pull/7523
