### ISSUE TITLE
pageserver: metric for very deep walredo

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7428]
Internal ref: INC-186

Some compaction bugs manifest as failure to generate image layers promptly, where the impact can be hard to catch earlier, because they show up as a gradual slowdown as more deltas accumulate.

Ideally we would scrub the data to proactively find these, but as a tactical improvement it would make sense to look at the depth of a stack of deltas in walredo and if it's over some threshold (e.g. 100?) then set a prometheus metric (we shouldn't do this for all timelines because cardinality would be too high).

Then we can alert on that metric to notice if a tenant is experiencing extra-deep walredo as a warning sign that something might have gone wrong with compaction.

**Comment by VladLazar** [comment]
> look at the depth of a stack of deltas in walredo and if it's over some threshold

Not sure this is a great proxy for how many layers were visited. It should be pretty cheap to just track that on the read path.

Here's my plan:
1. Track number of layers visited on the read path
2. Add a node wide histogram for layer visits
3. Add a rate limited per tenant log line when we breach a certain limit (say 50)

**Comment by VladLazar** [comment]
Huh. Turns out we do have a node wide metric for this. It's called `pageserver_read_num_fs_layers`
https://neonprod.grafana.net/goto/Smc8pnfIg?orgId=1

**Comment by VladLazar** [comment]
Last week:
* Metrics were added in https://github.com/neondatabase/neon/pull/7464

This week:
* Find a good upper bound for logging
* Merge the rate limited log in https://github.com/neondatabase/neon/pull/7465
* Add alert

**Comment by VladLazar** [comment]
Further investigation revealed that the number of layer visits at P99 and upwards is a lot worse than I thought (https://neonprod.grafana.net/goto/kbsOqFYSg?orgId=1). Adding a rate limited log wouldn't be useful since the limit
would have to be very high to accommodate for the current state of affairs. Perhaps we should investigate that and
revisit the logging later.

**Comment by VladLazar** [comment]
Alerts created under `Storage / Pagserver Layer Visits Per Read`.
