### ISSUE TITLE
Reduce Page/WAL sizes

### ISSUE THREAD

**Issue by patins** [neondatabase/neon#753]
Spoke with @hlinnaka about a few cases/areas we can optimize

- zero pages
- blank spaces in the middle of pages
- wal record header data (checksum, pointer previous awl record, ...)
- wal record relfilenode
- simplify format for clog + slru

**Comment by MMeent** [comment]
See also: https://github.com/zenithdb/rfcs/pull/14

**Comment by shanyp** [comment]
@MMeent @hlinnaka while combing the backlog found this one, any work has been done on this one ?

**Comment by jcsp** [comment]
Very old ticket.
