### ISSUE TITLE
test_partial_evict_tenant is flaky

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7536]
Looking at last 5 failures, they're all _barely_ failing the `abs_diff < 0.05` assertion, with values like 0.50123.

This appears to have regressed around the 20th of April:
![image](https://github.com/neondatabase/neon/assets/944640/a1851b97-bb42-4d69-8e40-64f9d9bfc308)

Assigning @koivunej as the person most familiar with the test's expected behavior

**Comment by koivunej** [comment]
It is both `[relative-spare]` and `[relative-equal]`. It is interesting why it has started.

Samples:
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7585/8922601186/index.html#testresult/cfdfdf77eaccec69/retries
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7585/8922601186/index.html#/testresult/b5d5826988ba2b0a
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7568/8913573652/index.html#/testresult/cb1cff1f0cf01c88
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/8921491575/index.html#/testresult/7a81a8c11c4b6120

**Comment by jcsp** [comment]
> This is not a new regression, this has just been noticed now.

I was calling it a regression because we see failures before 2024-04-19, then we see lots of failures after that -- if it's not a regression, what changed?

**Comment by koivunej** [comment]
Again: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7708/9058185709/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/8ffe1a15e28a0b94

**Comment by koivunej** [comment]
> > This is not a new regression, this has just been noticed now.
> 
> I was calling it a regression because we see failures before 2024-04-19, then we see lots of failures after that -- if it's not a regression, what changed?

I agree after re-checking the failures. None of the commits around 2024-04-19 or even at 2024-04-11 when the first 2 appeared look interesting.

Still unable to reproduce these locally with pg15, tried:
- re-runs
- sleeps growing the time endpoint and safekeepers are alive

For pg14 the sleep helps. I think that means that the bound was just wrong, and #7589 is the fix (bumps it from 0.05 -> 0.06).

Perhaps it is too strict and perhaps too lazily modelled, but apart from implementing the full logic I don't think there is a better middle-ground way to test this.
