### ISSUE TITLE
storage controller: be more tolerant of a pageserver's startup time

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7552]
We mark a node offline after `MAX_UNAVAILABLE_INTERVAL_DEFAULT` (30 seconds) of failures to respond to heartbeats.

We should be more generous during startup: when a pageserver sends us a re-attach request, we should tip off the heartbeater to be more generous.  Currently the pageserver's processing of the re-attach respond can be  quite time consuming.

This is similar to the k8s distinction between a readiness check and a status check: we should be more tolerant when waiting for readiness during startup, than when checking for responsiveness during normal runtime.

(The actual init_tenant_mgr slowness is addressed in https://github.com/neondatabase/neon/pull/7553, but this ticket still stands: we should be more tolerant during startup than we are during normal operation.)

**Comment by VladLazar** [comment]
2024-07-08
* https://github.com/neondatabase/neon/pull/8222 destabilised a bunch of tests
* I fixed a few, but it's a slow going process
