### ISSUE TITLE
flaky test: test_vm_bit_clear_on_heap_lock

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#7641]
## Steps to reproduce

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7638/8988505085/index.html#suites/8545ca7650e609b2963d4035816a356b/7bd2619e57a5db74

This test case has been super flaky for a few days from my observation. It fails on both pg15/16.

## Logs, links
-

**Comment by knizhnik** [comment]
I have created PR two weeks ago:
https://github.com/neondatabase/neon/pull/7499

**Comment by koivunej** [comment]
There is an earlier: #6967, let's focus efforts there. Also no need to repeat the template if one is not going to use it :)
