### ISSUE TITLE
scrubber: simplify S3 SDK setup 

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#7667]
The s3 client setup code in scrubber

https://github.com/neondatabase/neon/blob/3a2f10712ad557c978f966579c9bfa89ad6f4bae/s3_scrubber/src/lib.rs#L279-L326

looks quite copy-pasted from `remote_storage`

https://github.com/neondatabase/neon/blob/c18d3340b5e3c978a81c3db8b6f1e83cd9087e8a/libs/remote_storage/src/s3_bucket.rs#L84-L138

The differences appear to be:

- scrubber explicitly handles `AWS_ENDPOINT_URL`, pageserver doesn't
  - best practice would probably be to just use `aws_config::from_env()` and let the AWS SDK handle this (AWS_ENDPOINT_URL is a standard env var in AWS SDK land)
  - the `remote_storage` code will default to this as of in https://github.com/neondatabase/neon/pull/7664

Note that this isn't advocating for sharing a piece of code with `remote_storage`.
I think it makes sense for the scrubber to be very deliberate about how it sets up its S3 client to have its own S3 client.

Then again, if we want to support another cloud storage, maybe it would be better for the scrubber to use an abstraction layer like `remote_storage` 🤔

**Comment by jcsp** [comment]
This might make sense to clean up as we add Azure support to the scrubber in https://github.com/neondatabase/neon/issues/7547 -- that might involve just using remote_storage everywhere.

**Comment by arpad-m** [comment]
Btw since #7189 we now have this also in the proxy:

https://github.com/neondatabase/neon/blob/c6d5ff944db91f498e46fa24eb0d667abdf94dba/proxy/src/bin/proxy.rs#L288-L308

**Comment by arpad-m** [comment]
for the credentials, we recently had #8299.

**Comment by arpad-m** [comment]
closing as #8299 has been merged.
