### ISSUE TITLE
don't set wal_keep_size to 10 TB

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#767]
in `setup_pg_conf`, in control_plane/src/compute.rs, we have this:
```
        // Never clean up old WAL. TODO: We should use a replication
        // slot or something proper, to prevent the compute node
        // from removing WAL that hasn't been streamed to the safekeeper or
        // page server yet. (gh issue #349)
        conf.append("wal_keep_size", "10TB");
```
issue #349 has been closed, we use a replication slot now. So I guess that can be just removed?

**Comment by petuhovskiy** [comment]
I looked at `postgresql.conf` in the console and it seems that we already using default `wal_keep_size=0` in staging and production. So I updated wal_keep_size in control_plane and added a test for it in #1507.
