### ISSUE TITLE
`test_lock_time_tracing` is flaky

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7691]
This test was added recently, and is failing ~3% of the time.

An example failure:
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7663/9022743601/index.html#testresult/45c20a5d0b81d6cd/retries

```
test_runner/regress/test_storage_controller.py:1312: in test_lock_time_tracing
    env.storage_controller.assert_log_contains(
test_runner/fixtures/neon_fixtures.py:2003: in assert_log_contains
    assert res is not None
E   assert None is not None
```

**Comment by jcsp** [comment]
@jbajic are you available to fix this?

**Comment by jbajic** [comment]
> @jbajic are you available to fix this?

Yes I am. I will take a look at it
