### ISSUE TITLE
`test_gc_aggressive` regression with `tried to request a page version that was garbage collected`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7692]
Test became unstable on ~2024-05-06, failing ~7% of runs.

Example failures:
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7663/9022743601/index.html#testresult/d3a7621bd7d14c7a/retries
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/9022735863/index.html#testresult/b199cd9684bb94d5/retries
- https://neon-github-public-dev.s3.amazonaws.com/reports/main/9022735863/index.html#testresult/fca6313f5a0aa48d/retries

```
asyncpg.exceptions.PostgresIOError: [NEON_SMGR] [shard 0] could not read block 74 in rel 1663/5/16389.0 from page server at lsn 0/023B8E10
DETAIL:  page server returned error: Bad request: tried to request a page version that was garbage collected. requested at 0/23B8E10 gc cutoff 0/23B91D8
```

![image](https://github.com/neondatabase/neon/assets/944640/053181e0-cf21-45ef-bd78-d904b0538b36)

**Comment by hlinnaka** [comment]
This was fixed in https://github.com/neondatabase/neon/pull/7708
