### ISSUE TITLE
storage broker might be unavailable for several minutes if k8s node is scaled down

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#7695]
because apparently termination doesn't wait then for new pod readiness in this case.
https://neondb.slack.com/archives/C06K38EB05D/p1715323626025939?thread_ts=1715098337.721849&cid=C06K38EB05D

**Comment by Bodobolero** [comment]
potentially related https://github.com/neondatabase/cloud/issues/5234

**Comment by jcsp** [comment]
In the helm chart, we should consider:
- `safe-to-evict=false` on the broker pod
- or create a PodDisruptionBudget with maxUnavailable set to 0

To prevent the cluster autoscaler from voluntarily stopping the broker.

**Comment by arssher** [comment]
merged with
https://github.com/neondatabase/cloud/issues/5234
