### ISSUE TITLE
tiered compaction: refactor and re-enable iterator based k-merge

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#7703]
PR #7661 has switched to a completely in-memory based k-merge due to assertion errors in the iterator based k-merge. This has a non-zero memory impact bounded on the number of delta layers considered at a time multiplied by the maximum layer size. Ideally, we'd find and fix the bugs in the k-merge implementation.

Also, tests for the k-merge would be very helpful.

@skyzh has expressed interest in this, or at least in refactoring the k-merge.

**Comment by problame** [comment]
Meeting notes: Chi authored https://github.com/neondatabase/neon/pull/7760 which fixes this. Still missing test case.
Should be able to use the test that failed before we switched to buffered kmerge.

Time budget to understand with what was wrong with the prior kmerge: 1/2 day.

**Comment by problame** [comment]
This week:
- evolve / rewrite k-merge implementation in #7760 to support garbage collection
