### ISSUE TITLE
test_compatibility snapshot is flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#7705]
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7639/9034227206/index.html#suites/0fbaeb107ef328d03993d44a1fb15690/463911a4a21e1ef3

Because of timeout waiting for the Lsn in create snapshot. I don't understand how can this happen, we were stuck 10s at the same Lsn, pageserver went through all of the safekeepers. After the failure sync safekeepers the safe safekeepers were above the waited Lsn.

Marking this for pageserver so we might triage this, but this might be something interesting to look for compute team. Or maybe I missed something obvious.

--

Similar report by @knizhnik in [internal slack thread](https://neondb.slack.com/archives/C04DGM6SMTM/p1716992341369809), waiting for 80 bytes. Thread summary: @jcsp thought we should make the wait time configurable, because not all waits are equal. For example, the `test_compatiblity` snapshot creation does a non-trivial pgbench init vs. some of other tests doing just a few rows.

**Comment by jcsp** [comment]
This one is not actively flaky looking at recent results.
