### ISSUE TITLE
pgvector 0.7.0 integration and test

### ISSUE THREAD

**Issue by Bodobolero** [neondatabase/neon#7780]
Upgrade the pgvector extension supported in Neon from 0.5.x to 0.7.0

See PR https://github.com/neondatabase/neon/pull/7726

Discussed in this internal slack channel [#proj-pgvector070](https://neondb.slack.com/archives/C0732L0A4AH)

Sizing: medium (about 1 person week)

**Comment by bayandin** [comment]
Last week
- created compute image with 0.7.0 with 
- manual testing pgvector SQL regression tests on neon project (with pg 14, 15, 16)
- uploaded 1m documents from openai dataset

This week
- automation of these test
- a perf test for 1m documents
