### ISSUE TITLE
fsync() parent directory after creating a new relfile

### ISSUE THREAD

**Issue by andreasscherbaum** [neondatabase/neon#7789]
> If you create an empty table, it is not fsync'd. As soon as you insert a 
row to it, register_dirty_segment() gets called, and after that, the 
next checkpoint will fsync it. But before that, the creation itself is 
never fsync'd. That's obviously not great.

> The lack of an fsync is a bit hard to prove because it requires a 
hardware failure, or a simulation of it, and can be affected by 
filesystem options too. But I was able to demonstrate a problem with 
these steps:

https://www.postgresql.org/message-id/CA%2BhUKGLDdKOays2Z%2BpkOyr5y89YCS1yg%3DBPDeeL%2BEALZ6pWURQ%40mail.gmail.com

**Comment by jcsp** [comment]
This appears to be marked done in the Postgres team tasks board
