### ISSUE TITLE
Bug in load_layer_map() treatment of future layers

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#783]
```
        for filename in &deltafilenames {
            ensure!(filename.start_lsn < filename.end_lsn);
            if filename.end_lsn > disk_consistent_lsn {
                warn!(
                    "found future delta layer {} on timeline {}",
                    filename, self.timelineid
                );

                rename_to_backup(timeline_path.join(filename.to_string()))?;
                continue;
            }
```

Now we skip delta files that are partially in the future.
`filename.end_lsn > disk_consistent_lsn`

It can lead to losing data between filename.start_lsn and disk_consistent_lsn
@hlinnaka , @patins , FYI

Maybe it's the same issue as #470

**Comment by shanyp** [comment]
@lubennikovaav is this still relevant ?

**Comment by koivunej** [comment]
Hmm the above code snippet is still very much with us: https://github.com/neondatabase/neon/blob/2153d2e00a917b675b454ae8d222e2946900e4d1/pageserver/src/tenant/timeline.rs#L1371-L1379

I'd say that the same bug could still happen, had not considered this ... Might chance some problematic issues in staging with missing layer files, unless those are deleted already.

**Comment by knizhnik** [comment]
It can easily happen after abnormal pageserver restart (when it is stoped without waiting checkpoint to be completed)
It this case there can be layers newer than disk consistent LSN and them should be removed (renamed) on startup.

**Comment by shanyp** [comment]
@knizhnik is there an actionable given that we have safekeeprs and the WAL will be sent again ?
Is there anything else needed to do except from removing the "renamed" files ?
@lubennikovaav

**Comment by knizhnik** [comment]
Sorry, I do not understand what you mean by actionable?
Our storage is non-transactional. I.e. we can not enforce any ACID guarantees  when saving layers to the disk.
So current policy is the following:
1. Write data to the disk
2. Flush (fsync) changes
3. Advance disk consistent LSN

After restart we should remove all files with LSN > disk consistent LSN because we can not guarantee their consistency.
This layer files are not currently removed by renamed to  "*backup". It is done mostly for debugging reasons. This backup files can be safely removed and we replay from WAL all require changed.

**Comment by shanyp** [comment]
The bug stated that we can actually lose data
From your explanation, I understand that it is not the case, and whenever we process "future" delta layers we rename them and discard them from loading (they will be recreated by safekeeper replaying the WAL) and we rename these layers to backup

The actionable work that we are left with here is to remove these backup files

**Comment by koivunej** [comment]
> The actionable work that we are left with here is to remove these backup files

And this was #3660.

**Comment by shanyp** [comment]
closing this one as #3660 has the missing work
