### ISSUE TITLE
static musl builds

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#7889]
Explore doing static musl builds to allow easier deployment.

- [x] https://github.com/neondatabase/neon/pull/7883
- [ ] https://github.com/neondatabase/neon/pull/7884
- [x] https://github.com/neondatabase/tokio-epoll-uring/pull/51 / https://github.com/neondatabase/tokio-epoll-uring/pull/52
- [x] https://github.com/neondatabase/neon/pull/7918
- [x] ~~make storage controller work~~ --> not required as we use docker to deploy the storage controller 
- [ ] make walredo work

**Comment by problame** [comment]
This week:
- work with compute team to get a static `postgres --wal-redo` build
- write up rollout plan

**Comment by arpad-m** [comment]
Closing as the only remaining todo item is handled by #7956.
