### ISSUE TITLE
`test_pageserver_restarts_under_worload` is unstable

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#7897]
Three recent examples are pgbench timeouts:
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7893/9267925200/index.html#suites/542b1248464b42cc5a4560f408115965/1bc1310f2acda525/retries
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7892/9267197497/index.html#suites/542b1248464b42cc5a4560f408115965/9708ffe68ccbdd0b/retries
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7887/9247014243/index.html#suites/542b1248464b42cc5a4560f408115965/7ac2671cd1003788/retries

```
pytest.PytestUnhandledThreadExceptionWarning: Exception in thread Thread-8

Traceback (most recent call last):
  File "/home/nonroot/.pyenv/versions/3.9.18/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/nonroot/.pyenv/versions/3.9.18/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/__w/neon/neon/test_runner/regress/test_pageserver_restarts_under_workload.py", line 23, in run_pgbench
    pg_bin.run_capture(["pgbench", f"-T{n_restarts}", connstr])
  File "/__w/neon/neon/test_runner/fixtures/neon_fixtures.py", line 2768, in run_capture
    base_path, _, _ = subprocess_capture(
  File "/__w/neon/neon/test_runner/fixtures/utils.py", line 145, in subprocess_capture
    raise subprocess.CalledProcessError(r, " ".join(cmd))
subprocess.CalledProcessError: Command '/tmp/neon/pg_install/v15/bin/pgbench -T10 host=localhost port=17344 user=cloud_admin dbname=postgres options='-cstatement_timeout=120s '' returned non-zero exit status 1.
```

This regressed last week:
![image](https://github.com/neondatabase/neon/assets/944640/b49b4c0c-192e-4936-8475-fcb9be25f5a5)

**Comment by jcsp** [comment]
Can get the same failure by running 32 instances of the test in parallel: in a failure case, I see the pageserver restarting ~5 times in the 10 second pgbench timeout period.  So _maybe_ postgres timeout/retry logic is getting unlucky and repeatedly hitting the pageserver in between restarts while it's unavailable?

I'm a bit suspicious of https://github.com/neondatabase/neon/pull/7688 -- not that it contains a bug, just that it might impact some retry logic in a way that makes this test less robust.

**Comment by jcsp** [comment]
I bisected this to https://github.com/neondatabase/neon/pull/7611, which contains changes to retry logic.

@MMeent could you investigate please?  Strictly speaking, a change to retry logic isn't necessarily a bug, but we should understand what changed and make sure it's intentional.

**Comment by jcsp** [comment]
Noted -- will check in next week.

One last note here: I tried modifying the test to use a longer sleep between restarts, and interestingly it actually made it fail _more_ frequently, so something weird is going on here.

**Comment by andreasscherbaum** [comment]
@MMeent Please prioritize this during this week.

**Comment by jcsp** [comment]
Note that we have also seen unexpected "could not connect to pageserver" errors from postgres clients in staging, so I think it's quite likely that this is a real regression rather than a test issue.
