### ISSUE TITLE
RelFileNumber reuse protection is broken

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#7981]
GetNewRelFileNumber() checks the filesystem directly with `access()`, to see if a relfilenumber is already in use. That doesn't work with Neon storage, because the relations don't have files in local filesystem. As a result, after oid wraparound, a new relation might be assigned a relfilenumber that's already in use by another relation, with catastrophic consequences.

**Comment by kelvich** [comment]
@hlinnaka is there any related slack thread / error message? Or you just spotted it?

**Comment by hlinnaka** [comment]
No thread or error message.

We were chatting with Konstantin about something different, when I remembered that that code exists. I then went to see if we had did something to make it work in neon, and turns out we had not.

**Comment by kelvich** [comment]
@tristan957 can you please take a look

**Comment by ololobus** [comment]
@knizhnik rebase PR
