### ISSUE TITLE
Epic: 2024Q2/Q3 compaction work

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8001]
This epic is a tracking issue for the 2024Q2 compaction efforts.

Originally, the plan was to make the tiered compaction code from Q1 production-ready and ship it:

- https://github.com/neondatabase/neon/issues/7554

We **paused the tiered compaction efforts** because we keep hitting new bugs and substantial TODOs in the code.

We expect to deliver
* The test infrastructure that lets us validate the efficiency of compaction changes
  * DoD: we have a set of well-defined metrics that help us quantify a compaction algorithm's outcome (wrt request performance, space efficiency, CPU usage) and we can gather these metrics in the test suite and (possibly a subset) in production.
  * Epic: https://github.com/neondatabase/neon/issues/7770
* Some space efficiency improvements through GC’ing parts of layers that are no longer needed.
  * We continue using the legacy compaction and improve on the the inability to GC layers. Approach sketched in https://github.com/neondatabase/neon/pull/7948.
  * DoD: the pathological case in `test_gc_feedback` is no longer one
  * Epic: https://github.com/neondatabase/neon/issues/8002

```[tasklist]
### Ref child epics for GH metadata
- [ ] https://github.com/neondatabase/neon/issues/7770
- [ ] https://github.com/neondatabase/neon/issues/8002
```

**Comment by skyzh** [comment]
closing the issue b/c all children issues are marked complete; the current Q4 work is to run the new gc-compaction in prod reliably https://github.com/neondatabase/neon/issues/9114
