### ISSUE TITLE
Remove validation code and non-vectored read path

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#8005]
Now that https://github.com/neondatabase/neon/issues/7381 is done, the vectored read path is being used everywhere. At this point we can remove the non-vectored read path and all adjacent validation code.

Also update the defaults and consider https://github.com/neondatabase/neon/pull/7939

**Comment by problame** [comment]
Please hold off with this until #6967  is resolved.

**Comment by VladLazar** [comment]
> Please hold off with this until #6967 is resolved.
> 
> See comment [#6967 (comment)](https://github.com/neondatabase/neon/issues/6967#issuecomment-2158477818) for details.

ack
