### ISSUE TITLE
`ignoring failure to find gc cutoffs: timeline shutting down` should be `info!` level

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8012]
Log message `ignoring failure to find gc cutoffs: timeline shutting down` should be at `info!` level IMO.

Logged here:

https://github.com/neondatabase/neon/blob/7e60563910936cf6643edb686a8163b0b03c7108/pageserver/src/tenant.rs#L2932

Two tests have it in `allowed_errors`, so, as part of working on this ticket, one should clean up `allowed_errors`.

Found this while checking prodlike cloudbench logs for this week's release: https://neondb.slack.com/archives/C06K38EB05D/p1718117355604419?thread_ts=1718115200.692949&cid=C06K38EB05D

Please do not act on this before bug triage meeting has decided this should be info! level.

**Comment by koivunej** [comment]
Just a snarky reminder that we did have a discussion about it on the PR which introduced it, but I still agree, it would be fine as `info!`.

**Comment by jcsp** [comment]
The existing "ignoring" code path is rather indiscriminate -- probably need to make it more fine-grained and do things like explicitly ignoring cancellation, rather than just ignore _all_ possible errors

**Comment by jcsp** [comment]
There was a potential PageReconstructError buried behind this log issue, which we shouldn't be ignoring.
