### ISSUE TITLE
storcon / CLI: unclear how to undo tenant-warmup

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8017]
On 2024-06-11, Chi and I messed up and ran `storcon_cli tenant-warmup` against a storage controller in the wrong region.

The command completed without error and report `0/0 layers`. Even though there was no heatmap.json present for that tenant in that region's S3 bucket.

That is probably ok. But, it would have been nice to have a command to undo the tenant-warmup.

We worked around it using

1. `tenant-drop` and then
2. manually detaching from the PS

```
root@pageserver-11:~# curl -v -XPOST -H "Authorization: Bearer $PS_JWT" http://localhost:9898/v1/tenant/$tenant_id/detach 
```

**Comment by jcsp** [comment]
`tenant-drop` is pretty much sufficient for this case: the secondary location we leave behind on a pageserver will take no disk space and just do occasional S3 gets until the next time the pageserver or controller restart.  We can doc-tape this with an extra line that sets a tenant's policy to detached first, then drops it, to have a totally clean path.

**Comment by jcsp** [comment]
Updated docs here: https://github.com/neondatabase/docs/commit/a24f1c47b5d1c4c39492f5e91ce5c7ce0f14ccb9
