### ISSUE TITLE
storcon: initial placement of new tenants does not take into account number of attached shards

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#8041]
When creating a new shard the storage controller schedules via `Scheduler::schedule_shard`. This does not take into account the number of attached shards. What it does take into account is the node affinity: when a shard is scheduled, all its nodes (primaries and secondaries) get their affinity incremented.

For two node clusters and shards with one secondary we have a pathological case where all primaries are scheduled on the same node. Now that we track the count of attached shards per node, this is trivial to fix. Still, the "proper" fix is to use the pageserver's utilization score.

**Comment by jcsp** [comment]
We have the attached tenant count now, so this should be an easy tweak to the scheduler.
