### ISSUE TITLE
Grant optional lease to get_lsn_by_timestamp request

### ISSUE THREAD

**Issue by yliang412** [neondatabase/neon#8072]
Part of #7497.

An `with_lease` field is added to the `get_lsn_by_timestamp` request so we can optionally grant leases to valid LSNs eligible for branch creation.

**Comment by skyzh** [comment]
should there be a new field `grant_lease` for this API call, or making all get_lsn_by_timestamp a lease request?

**Comment by yliang412** [comment]
> should there be a new field `grant_lease` for this API call, or making all get_lsn_by_timestamp a lease request?

Based on the [slack discussion](https://neondb.slack.com/archives/C033RQ5SPDH/p1718312132166459), I'm inclined to add `grant_lease` as an optional request parameter (default being no lease). If later we think granting lease should always be the case, we can then change the default to always grant the lease?

**Comment by skyzh** [comment]
sounds good

**Comment by yliang412** [comment]
Last week: finished implementation.

This week: merge PR after metrics are added in.
