### ISSUE TITLE
pageserver: abort process on fsync errors

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8140]
We added the infrastructure for this a while back (`maybe_fatal_err` etc), but there's lots of code that doesn't use it.

We hit these kinds of errors when an EC2 instance is dying.

We should be aborting the process on I/O errors when writing to layer files.

**Comment by skyzh** [comment]
Write path done, need to investigate read path.

**Comment by skyzh** [comment]
christian: panic when we we run out of place; disk-based eviction?
tenant config (?) fsync after rename

final thoughts: panic on fsync failure, discuss no space issue later
