### ISSUE TITLE
Building RUM index with large amounts of data causes PANIC: evicted with zero LSN

### ISSUE THREAD

**Issue by mededmentor** [neondatabase/neon#8251]
## Steps to reproduce

We create a table and fill it with 2.5 million random ts_vectors. My actual database has a similar number of rows but even more complex text data.
```
CREATE EXTENSION rum;
```

```
CREATE TABLE large_test_rum_index (
    id SERIAL PRIMARY KEY,
    content_tsvector tsvector
);
```

```
CREATE OR REPLACE FUNCTION complex_random_tsvector() RETURNS tsvector AS $$
DECLARE
    words text[] := ARRAY[
        'apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape', 'honeydew', 
        'innovation', 'juxtapose', 'kinetic', 'leverage', 'metamorphosis', 'nuance', 
        'oscillate', 'paradigm', 'quintessential', 'resilience', 'serendipity', 'threshold', 
        'ubiquitous', 'vortex', 'watershed', 'xenial', 'yield', 'zenith', 'abstract', 
        'brevity', 'cognition', 'diligence', 'empirical', 'facetious', 'gregarious', 'hypothetical'
    ];
    result text;
BEGIN
    -- Generate a string of 100 random words
    SELECT string_agg(words[ceil(random() * array_length(words, 1))], ' ')
    INTO result
    FROM generate_series(1, 100);
    
    RETURN to_tsvector('english', result);
END;
$$ LANGUAGE plpgsql;
```

```
-- Takes ~5 minutes
INSERT INTO large_test_rum_index (content_tsvector)
SELECT complex_random_tsvector()
FROM generate_series(1, 2500000);
```

```
CREATE INDEX large_rum_index_test ON large_test_rum_index USING rum (content_tsvector rum_tsvector_ops);
```

This will cause the server to crash and no index will be created.

```
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'large_test_rum_index' AND indexname = 'large_rum_index_test';
```

## Expected result
The index should be created.

## Actual result
The server crashes and we get a panic message:
```
PANIC: [NEON_SMGR] Page 0 of relation XXXXX is evicted with zero LSN (SQLSTATE XX000)
```

Note that the index creation will succeed if we generate only 500,000 rows.

## Environment
Autoscale 0.25 CU to 4 CU. (The crash happens even if the CU is pinned to 4 CU)
Postgres 15

## Logs, links

Based on the panic message, I believe that this crash has to do with:
https://github.com/neondatabase/neon/blob/main/docs/core_changes.md#mark-index-builds-that-use-buffer-manager-without-logging-explicitly
(And an associated PR https://github.com/neondatabase/neon/pull/7440)

pgvector has a Neon-specific patch to call the smgr_unlogged_build functions.
https://github.com/neondatabase/neon/blob/ea0b22a9b0e5dd03605a285ce6560926299628d8/patches/pgvector.patch#L4

However I do not think that RUM has such a patch.
https://github.com/postgrespro/rum

-

**Comment by kelvich** [comment]
Hey, thank you for great analysis! Yes, correct we need to instrument RUM the way you suggested. We've noticed that crash some time ago and were not sure whether to just drop RUM from supported extensions or fix it. Since you are using it -- makes sense to fix. I'll get back to you with ETA on Monday

**Comment by mededmentor** [comment]
Confirming that this is fixed now on Neon — thank you!
