### ISSUE TITLE
replication with clickhouse as a subscriber causes a crash of the compute node

### ISSUE THREAD

**Issue by save-buffer** [neondatabase/neon#8349]
## Steps to reproduce
Follow this [instruction](https://clickhouse.com/docs/en/integrations/postgresql#using-the-materializedpostgresql-database-engine), but don't create a role and a database in Postgres, don't modify pg_hba.conf etc, use the neon default user and the default database instead. Crash will happen after the database connection creation in the ClickHouse.

## Expected result
No crash

## Actual result
Crash

## Environment
Staging (`ep-holy-fog-w2aoqekg`)

## Logs, links
Discussion:
https://neondb.slack.com/archives/C0756AKBMU0/p1720032475503459
-

**Comment by a-masterov** [comment]
To reproduce follow this [instruction](https://clickhouse.com/docs/en/integrations/postgresql#using-the-materializedpostgresql-database-engine), but don't create a role and a database in Postgres, don't modify pg_hba.conf etc, use the neon default user and the default database instead. Crash will happen after the database connection creation in the ClickHouse.

**Comment by knizhnik** [comment]
Were you able to get core dump?

**Comment by a-masterov** [comment]
> Were you able to get core dump?

Unfortunately https://github.com/neondatabase/neon/pull/8272 is not yet merged, still needs approve from the code owners

**Comment by a-masterov** [comment]
The backtrace is attached to the slack discussion.

**Comment by kelvich** [comment]
```
#1  0x00007f5505fbeecf in NeonWALReadRemote (state=0x5652093cd200, buf=0x5652093cf200 "s", buf@entry=0x5652093cd200 "\023\321\002", startptr=140737453845920, startptr@entry=16777216, count=140737453845916, count@entry=8192, tli=tli@entry=1) at neon_walreader.c:373
```

so in https://github.com/neondatabase/neon/blob/main/pgxn/neon/neon_walreader.c#L373

**Comment by save-buffer** [comment]
With https://github.com/neondatabase/neon/pull/8360 merged, we should try again and confirm it doesn't crash with clickhouse

**Comment by a-masterov** [comment]
I confirm that starting a logical replication using ClickHouse doesn't cause crashes anymore.
