### ISSUE TITLE
Ensure there are no unconstrained reads

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#842]
We may use `read_to_end` from time to time to read files which are expected to be small, e.g. configs. However, if the file turns out to be very big by an accident (e.g. FS crash or accidental overwrite via sloppy `cp`/script) we may end up eating a lot of memory.

I'm not sure how important the issue is, but having some limits in place and banning unconstrained reads seems like a good idea to me. Maybe a helper like `read_to_end(..., but_not_more_than_bytes)`.

See initial discussion here: https://github.com/zenithdb/zenith/pull/784#discussion_r742695898

**Comment by KlimentSerafimov** [comment]
Proposal: 
Create a wrapper class SafeFile that inherits from File and re-implements read_to_end and read_from_string with the desired size check in place. @kelvich @yeputons any thoughts?

**Comment by kelvich** [comment]
Hm, so `read_to_end(..., but_not_more_than_bytes)` isn't in the stdlib. We can just `fstat` file before reading it. But it is not clear what the limit should be. On a second thought IMO it would be clearer to just leave `read_to_end()` as it is now, accept the risk with big files and close this issue =)

**Comment by KlimentSerafimov** [comment]
We can add logging and run bunch of experiments on real-world workloads to see what is the usual maximal file size.

**Comment by LizardWizzard** [comment]
It is typically used for config files, certificates etc. So shouldn't be a big problem
