### ISSUE TITLE
timeline archival: slimmed down timeline object

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#8460]
for archived timelines, we want things like walreceiver and walredo to be shut down. We should shut down/start up both according to the incoming network requests.

Part of https://github.com/neondatabase/neon/issues/8088

**Comment by jcsp** [comment]
This was covered by creating `OffloadedTimeline` in https://github.com/neondatabase/neon/pull/8907, right?

**Comment by arpad-m** [comment]
yeah, it can be closed I'd say.
