### ISSUE TITLE
The refresh icon does not reflect changes such as addition/deletion of columns in the tables (NextJS + Prisma)

### ISSUE THREAD

**Issue by sudarshanmg** [neondatabase/neon#8507]
## Steps to reproduce
- nextJS + Prisma + PostgresSQL
- create a model in the beginning
- run `npx prisma generate` and `npx prisma db push`
- add new columns/fields to the model
- re-run step 2

## Expected result
The refresh icon when clicked should reflect the changes made wrt addition of new columns to the table in the db

## Actual result
I have to do a full-page reload when I add new fields/cols to the table

## Environment
```
"next": "14.2.5",
"@prisma/client": "^5.17.0"
"prisma": "^5.17.0",
```

## Logs, links
-

**Comment by skyzh** [comment]
not sure what you mean for the refresh button, but i've relayed your request to the corresponding team.

**Comment by skyzh** [comment]
seems that this is an issue with your own app instead of the service, so closing it for now
