### ISSUE TITLE
Docs have a lot of empty links

### ISSUE THREAD

**Issue by firatoezcan** [neondatabase/neon#8535]
## Steps to reproduce
Go to https://github.com/neondatabase/neon/blob/main/docs/SUMMARY.md and f.e. click on "Proxy"

## Expected result

Proxy docs

## Actual result

No docs. Or remove the link alltogether

**Comment by jcsp** [comment]
That page is a bit of a graveyard indeed.  Please visit https://neon.tech/docs/introduction for info about the product.

https://github.com/neondatabase/neon/pull/8665

**Comment by jcsp** [comment]
You may also find the #neon-oss [discord](https://neon.tech/blog/neon-is-now-on-discord)  channel useful.
