### ISSUE TITLE
Partial upload is not working well together will pull_timeline

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#8542]
This issue is specific to how partial upload files are managed in control files. Each safekeeper uploads its own partial segment to remote storage, and keeps the name of the remote object in `PartialRemoteSegment` struct stored on disk. (more info in `wal_backup_partial.rs`).

pull_timeline request copies timelines between safekeepers. Control files are directly copied from one safekeeper to another, and references to the remote partial segments are copied as well. The issue is that safekeepers are not expecting that their own uploaded partials are modified by other safekeepers. This leads to inconsistent state.

## Steps to reproduce

1. Create a normal timeline
2. Shutdown all computes
3. Wait until partial segments are uploaded to remote storage
4. Migrate from {sk1, sk2, sk3} to {sk1, sk2, sk4} using pull_timeline {sk1} -> {sk4}

This is enough to reproduce invalid state, but it won't cause any issues until something will try to read the file.

To actually cause errors in the logs, you need to also:
1. Enable offloading and wait until all timelines are switched to offloaded state
2. Stop {sk1}
3. Start the compute, write some WAL
4. Wait until partial segments are uploaded to remote storage for {sk4}
5. Wait until gc deletes previously uploaded partial segment on {sk4} (the same segment was used on sk1!)
6. Start {sk1}

## Expected result

Everything works with no issues

## Actual result

{sk1} cannot restore offloaded timeline becuase the partial segment was removed from remote storage

**Comment by jcsp** [comment]
Assigning to @arssher for refinement: let's make a plan for how to fix this, and then assign someone to write the code
