### ISSUE TITLE
Proxy: billing events sent to Vector and S3 should use the same idempotency key

### ISSUE THREAD

**Issue by stradig** [neondatabase/neon#8564]
The idempotency key is used to make sure that events are not recorded more than once, although they may be submitted multiple times in some cases to make sure they are not lost.

The background jobs that send the billing events to S3 and Vector are distinct. The idempotency key is generated in those jobs. We should move the generation to an earlier stage to fix that.

Relates: https://github.com/neondatabase/cloud/issues/9826

**Comment by cloneable** [comment]
Since today all regions have the new proxy release. The still running old releases will stop pushing to S3 within 24h, so there won't be inconsistent keys from them, too.
