### ISSUE TITLE
Reduce in-memory overhead of on-disk layers

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#857]
Currently, reading from a delta layer requires loading and deserializing the blk # + LSN -> offset mapping. That makes reading the a single page expensive, and keeping the map in memory consumes memory. We have a crude "load/unload" system to keep the memory usage in check, but it's hacky. Rewrite that in a smarter way.

**Comment by stepashka** [comment]
this would probably be resolved together with #753

**Comment by MMeent** [comment]
See also: zenithdb/rfcs#14

**Comment by hlinnaka** [comment]
https://github.com/zenithdb/zenith/pull/1459 fixes this.
