### ISSUE TITLE
Local build fails for release-6210 and current git

### ISSUE THREAD

**Issue by clauspruefer** [neondatabase/neon#8578]
## Steps to reproduce

System: Ubuntu 22.04.4 VM on Intel i9, 24 cores Win11

```
mkdir ~/src
cd ~/src

apt-get install build-essential libtool libreadline-dev zlib1g-dev flex bison libseccomp-dev \
libssl-dev clang pkg-config libpq-dev cmake postgresql-client protobuf-compiler \
libcurl4-openssl-dev openssl python3-poetry lsof libicu-dev curl

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

### Current git

```
git clone git@github.com:neondatabase/neon.git

cd neon
git submodule update --init --recursive --depth 2 --progress .
make -j 12
```

### Latest release-6210 Source

```
cd neon-release-6210 && make -j 12
```

### Latest release-6210 Docker Container

```
docker build .
```

## Expected result

Working build.

## Actual result

None working. See attached log and comments.

## Environment

Ubuntu Linux 22.04.4 VM on Win11 Oracle Virtual Box transparent HW CPU virtualization.

### Latest release-6210 and included Docker Container

Building source or Docker Container, same result:

```
---> Running in 921dca43afc4
Configuring Postgres v14 build
Configuring Postgres v15 build
Configuring Postgres v16 build

Postgres submodule not found in /home/nonroot//vendor/postgres-v14/, execute 
'git submodule update --init --recursive --depth 2 --progress .' in project root.

Postgres submodule not found in /home/nonroot//vendor/postgres-v15/, execute 
'git submodule update --init --recursive --depth 2 --progress .' in project root.

Postgres submodule not found in /home/nonroot//vendor/postgres-v16/, execute 
'git submodule update --init --recursive --depth 2 --progress .' in project root.
```

> Looks like submodules have not been added.

### Current git

```
Caused by:
  process didn't exit successfully: `/home/cpruefer/src/neon/target/debug/build/storage_broker-0d0dbbbd5810127a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto/broker.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at storage_broker/build.rs:9:29:
  failed to compile protos Custom { kind: Other, error: "protoc failed: broker.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
     Running `/home/cpruefer/src/neon/target/debug/build/postgres_ffi-0d7f4b15969dd8ab/build-script-build`
make: *** [Makefile:86: neon] Error 101
```

> Looks like protobuf`s experimental feature (proto3 optional fields) has been used in ```storage_broker/proto/broker.proto``` and flag ```--experimental_allow_proto3_optional``` was not set

I am currently exploring the build system and have no clue where to set this flag.

**Comment by clauspruefer** [comment]
Postgres submodule not found in /home/nonroot//vendor/postgres-v14/, execute.

Seems like a hardcoded path somewhere ```/home/nonroot```.

**Comment by skyzh** [comment]
need to update your protobuf installation?

**Comment by clauspruefer** [comment]
I will check it out. But this does not fix the release-6210 **Postgres submodule not found** (also in Docker Container).

**Comment by clauspruefer** [comment]
Updating to https://github.com/protocolbuffers/protobuf/releases/tag/v27.3 fixed building subdir `/storage_broker` for current git.

Latest Ubuntu 22.04.4 nevertheless contains a non-compatible `protobuf-compiler` .deb / apt package.

**Comment by clauspruefer** [comment]
> Postgres submodule not found in /home/nonroot//vendor/postgres-v14/, execute.
> 
> Seems like a hardcoded path somewhere `/home/nonroot`.

Blame me: thats inside the docker container.

**Comment by arpad-m** [comment]
Currently we require protoc 3.15+ . The requirement on the higher version was introduced by #3883 .

It's already mentioned in README:

> Building Neon requires 3.15+ version of `protoc` (protobuf-compiler). If your distribution provides an older version, you can install a newer version from [here](https://github.com/protocolbuffers/protobuf/releases).

There is a docker file provided if you want to build Neon yourself, you can find it in `Dockerfile.build-tools`. Alternatively, you can try to use a docker container building on top of Ubuntu `24.04`, it should have a recent enough protoc.

For the "Postgres submodule not found" error, the suggested command to address it is described in the error message you quoted above.

**Comment by clauspruefer** [comment]
> Currently we require protoc 3.15+ . The requirement on the higher version was introduced by [#3883](https://github.com/neondatabase/neon/pull/3883) .
> 
> It's already mentioned in README:
> 
> > Building Neon requires 3.15+ version of `protoc` (protobuf-compiler). If your distribution provides an older version, you can install a newer version from [here](https://github.com/protocolbuffers/protobuf/releases).

After reading the quite "non-structured" documentation i realize this now and **my build is working**. I did propose a much more structured one in the PR (this is the wrong place i suppose). I will close issue / PR and file a new one with the documentation proposal.

> 
> There is a docker file provided if you want to build Neon yourself, you can find it in `Dockerfile.build-tools`. Alternatively, you can try to use a docker container building on top of Ubuntu `24.04`, it should have a recent enough protoc.
> 
> For the "Postgres submodule not found" error, the suggested command to address it is described in the error message you quoted above.

The proposed `git init recursive` cmd is inside the building docker container (which is a **non**-git repo), so git commands will not work, i suppose. I am not 100% sure, if this is really an error i will re-open a new issue.

# Small Summary

1. If you are on Ubuntu 22.04.4 current and want to build the system, the first README.md topic is the package installation including the **non-compatible** protobuf-compiler, so the quite time intensive debug build will fail!
2. Now you try running the Docker Container which also fails.
3. Frustration! The documentation should mention the PROTOBUF topic early!

# Documentation Proposal

Please checkout my documentation update proposal (a bit more structured):

https://github.com/clauspruefer/neon/blob/doc-proposal/README.md
https://github.com/clauspruefer/neon/blob/doc-proposal/docs/build/BUILD.md
https://github.com/clauspruefer/neon/blob/doc-proposal/docs/build/RUN-LOCAL.md
https://github.com/clauspruefer/neon/blob/doc-proposal/docs/build/TESTS.md

**Comment by clauspruefer** [comment]
Build is working.

**Comment by arpad-m** [comment]
Great to hear that the build works now! For the split of the README.md file, it can be discussed in #8593.
