### ISSUE TITLE
pageserver: fix L0 criteria

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#8579]
currently we regard layers with Key::MIN..Key::MAX as L0 layers. If an image layer is generated with this range, it will be loaded as a delta layer and cause problems. We need to fix `is_l0` function.

**Comment by koivunej** [comment]
Can you see a situation where an image layer would cover keys up to KEY::MAX, could you elaborate on that?

**Comment by jcsp** [comment]
Per Christian: new bottom-most compaction can create 0000-ffff image layers.
