### ISSUE TITLE
Drizzle studio in table editor crashed when toggle columns

### ISSUE THREAD

**Issue by namegalt** [neondatabase/neon#8596]
## Steps to reproduce
1) Log in to https://console.neon.tech/
2) Go to table editor
3) Try to toggle some column
## Expected result
Column toggled
## Actual result
Crash with report
## Environment
https://console.neon.tech/

## Logs, links
- 

[bug-report.zip](https://github.com/user-attachments/files/16489483/bug-report.zip)

The problem disappears only after clearing the application data

**Comment by jcsp** [comment]
Hi - this github project is for the open source neon components.

Please open a support ticket if you're on a paid plan, or otherwise visit Discord (links on https://neon.tech/docs/introduction/support)
