### ISSUE TITLE
pageserver: during testing, `assertion failed: self.field2 <= 0xFFFF || self.field2 == 0xFFFFFFFF ||     self.field2 == 0x22222222`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8636]
As far as we know this issue hasn't occurred in the field, but let's investigate how it happened in testing.

**Comment by skyzh** [comment]
The invalid key is found in a delta layer:

```
2024-08-08T06:17:21.592838Z ERROR panic{thread=main location=libs/pageserver_api/src/key.rs:110:9}: invalid key: 00000100010001A290000000000000000001
```

in the L0 layer file:

```
[  6]  key:000000000000000000000000000000000000-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
       lsn:0/2AD81791-0/2CB99849
       delta:true
```

**Comment by skyzh** [comment]
This is a RelDir key

```
Key { field1: 0, field2: 65537, field3: 107152, field4: 0, field5: 0, field6: 1 }
rel_block:         false
rel_vm_block:      false
rel_fsm_block:     false
slru_block:        false
inherited:         true
rel_size:          false
slru_segment_size: false
recognized kind:   Some(RelDir(65537/107152))
```

**Comment by skyzh** [comment]
Maybe related: https://github.com/neondatabase/neon/pull/8232 https://github.com/neondatabase/neon/issues/8237

We added the functionality to track this key in https://github.com/neondatabase/neon/pull/8276

**Comment by skyzh** [comment]
probably need some discussion on what is the proper fix; meanwhile, I created https://github.com/neondatabase/neon/pull/8648 to error on the write path instead of getting such keys persisted inside pageserver.

**Comment by jcsp** [comment]
The change to make postgres reject unencodable tablespaces has merged & can be considered to fix this.
