### ISSUE TITLE
vectored read: only read each stx_dio_offset_align/stx_dio_mem_align-sized section once

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8719]
Currently, VectoredReadPlanner issues separate reads as soon as there is a gap between the required reads.

E.g., if we have a reads `[0,20)`, `[20, 30)` and `[50,60)` the result will be two read system calls for `[0,30)` and `[50,60)`.

With direct IO,
* read system calls will have higher latency
* we have  `stx_dio_offset_align` / `stx_dio_mem_align` alignment requirements

So, if `[0,30)` and `[50,60)` fall within the same `stx_dio_offset_align`/`stx_dio_mem_align` section of the file, we should only be issuing one read for these two, using a short-lived IO buffer, and reference or memcpy the data we're actually interested in.

# DoD

Mode for `VectoredReadPlanner` or a wrapper around it that batches reads together into  `stx_dio_offset_align`/`stx_dio_mem_align`-sized reads.

The `max_read_size` still needs to be respected.

**Comment by yliang412** [comment]
Based on investigation into our code + discussion with @skyzh, the reads issued by `VectoredReadPlanner` does not have gap (the reads are always mergable up to `max_read_size`. Only need to make the buffer aligned.

**Comment by yliang412** [comment]
> ~Based on investigation into our code + discussion with @skyzh, the reads planned by VectoredReadPlanner on delta/image layer do not have gap (the reads are always mergable up to max_read_size. Only need to make the buffer aligned.~

Take it back. Not true b/c `BlobFlag::ReplaceAll` and `BlobFlag::Ignore`.
