### ISSUE TITLE
flaky test `test_timeline_ancestor_detach_errors[debug-pg16-True]`: Cancelled request finished with an error: Conflict("no ancestors")

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8773]
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-8769/10471179129/index.html#suites/a1c2be32556270764423c495fad75d47/40c0837eeee95828/

AssertionError: First log error on pageserver_2: (82, '2024-08-20T12:42:16.673484Z ERROR request{method=PUT path=/v1/tenant/e32914afcfd84a76a18b10986fb747dd-0102/timeline/c54c185846996d9cdce23a8f585c46a6/detach_ancestor request_id=84838b1d-07a4-46d6-b562-2362deb15058}: Cancelled request finished with an error: Conflict("no ancestors")\n')
Hint: use scripts/check_allowed_errors.sh to test any new allowed_error you add

**Comment by koivunej** [comment]
I do not understand why wouldn't this problem have every time.

**Comment by koivunej** [comment]
Ok, this is reproducable with random sleep at the before returning that error.
