### ISSUE TITLE
Update pg_uuidv7 to 1.5

### ISSUE THREAD

**Issue by austinm911** [neondatabase/neon#8793]
Noticed this extension is 1.0 while pg_uuidv7 is currently on 1.5

https://github.com/fboulnois/pg_uuidv7

**Comment by ololobus** [comment]
Updated to 1.6 for all PG versions, see
https://github.com/neondatabase/neon/blob/b853f7813606a02af226d2ef80a92d10dafca527/compute/compute-node.Dockerfile#L725C1-L725C105
