### ISSUE TITLE
Epic: Support pinned readonly nodes

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#882]
The feature allows to start a compute node pinned at particular LSN. Currently it is possible to start such a node with `zenith pg start <name_of_the_branch>@<lsn>`. 

Missing pieces:

- [x] #883
- [x] #884
- [x] #885
- [x] https://github.com/neondatabase/neon/issues/3532
- [x] https://github.com/neondatabase/neon/issues/3596

Feel free to add to this list

**Comment by LizardWizzard** [comment]
@vadim2404 should we merge this with read-only replica efforts tracking?

**Comment by stepashka** [comment]
@shanyp , isn't this already supported?
what is the status of teh tasks listed here, are they complete, not relevant anymore or smth else?

**Comment by stepashka** [comment]
is this about the storage, compute or both? @vadim2404 @shanyp

**Comment by vadim2404** [comment]
it's about compute. It seems that we had this capability from the very beginning, but no one tested it.

**Comment by LizardWizzard** [comment]
Tests exist in neon repo. And feature is available in `neon_local`
