### ISSUE TITLE
Lsn at which readonly node is started is not validated, it can be in the future (pageserver will wait for future lsn which might result in a timeout), it can be pre initdb lsn.

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#884]
This might also be true for branch creation. As mentioned in #883 if readonly nodes are implemented via branching there is a possibility to share this logic

**Comment by LizardWizzard** [comment]
Cases with using pre initdb lsn and lsn which was garbage collected are covered in #933

**Comment by jcsp** [comment]
LSNs are validated in getpage requests: a bad compute will have its requests rejected.
