### ISSUE TITLE
Handling of readonly nodes in zenith cli is incomplete, when node is started it cannot be restarted etc.

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#885]
There is a bug in config path construction (`/` in LSN is not escaped) ```target/debug/zenith pg start "main@0/16F98F0"
command failed: failed to open config file in .zenith/pgdatadirs/tenants/5a083464007723f2371b807abda0b2d5/main@0/postgresql.conf```

**Comment by jcsp** [comment]
neon_local has many limitations, not sure this is still relevant.
