### ISSUE TITLE
Epic: implement SCRAM for e2e auth 

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#888]
We want to avoid storing any kinds of passwords in the control plane or proxy. We could use secrets storage like Vault or network auth like Kerberos. But not having passwords in a first place is a better option.

Current thinking:
* Usual login is done via SCRAM, where proxy performs MITM. Same user/password is used to establish user<->proxy and proxy<->postgres connection.
* Web console generates special user account with random password which is stored in the browser cookie. Cookie is encrypted so user can't see it and console will see that password only during the request.
* We setup two differently configured proxy services for link-based auth and password-based one (instead of looking on `@zenith` suffix)
* Postgres management operations are done through zenith_ctl http api (and that is fixed set of operations, arbitrary query is not allowed)
* Onboarding login/creation is done by "trust" to the proxy hostname. Here login process itself involves github oauth, which should be good enough. However, this login method should be optional and we should promote it usage only for dev clusters. Optionally we can pass github oauth token to the proxy and made postgres validate it. That way we will protect ourselves from connecting to a wrong cluster. 

Sub-tasks:
- [x] neondatabase/cloud#373
- [x] #918
- [x] neondatabase/cloud#532
- [x] neondatabase/cloud#478
- [x] neondatabase/cloud#1182
- [x]  neondatabase/cloud#1314

**Comment by stepashka** [comment]
#431
could be related, but is unconfirmed

**Comment by stepashka** [comment]
reopened to track the task for deployment of this to prod
