### ISSUE TITLE
On-demand WAL download in create logical replication slot

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#8931]
We have 3 open PRs to all Postgres versions
- https://github.com/neondatabase/postgres/pull/480
- https://github.com/neondatabase/postgres/pull/470
- https://github.com/neondatabase/postgres/pull/469
- Also do not forget to add the same change to PG17 version?

All are approved, so let's properly merge and bump submodule versions

Heikki also mentioned the tests' absence (can we write some?) and other discrepancies https://neondb.slack.com/archives/C04DGM6SMTM/p1725445174109119?thread_ts=1724867700.274789&cid=C04DGM6SMTM

**Comment by knizhnik** [comment]
There 5 where now we install our on-demand download functions:
3 times this set of functions is replaced:
```
       xlr.page_read = read_local_xlog_page;
	xlr.segment_open = wal_segment_open;
	xlr.segment_close = wal_segment_close;
```
and two times this set of function is replaced:
```
xlr.page_read = logical_read_xlog_page;
xlr.segment_open = WalSndSegmentOpen;
xlr.segment_close = wal_segment_close;
```

Where are using three different callbacks for it: `SlotFuncs_Custom_XLogReaderRoutines`, `WalSender_Custom_XLogReaderRoutine` and `LogicalFuncs_Custom_XLogReaderRoutines` all of which are not install the same set of functions:
```
	xlr->page_read = NeonWALPageRead;
	xlr->segment_open = NeonWALReadSegmentOpen;
	xlr->segment_close = NeonWALReadSegmentClose;
```

All this contexts are passed to `CreateInitDecodingContext` and  `CreateDecodingContext` which in turn call `StartupDecodingContext`.

I wonder if we should define just one callback and call it from `StartupDecodingContext`.

**Comment by ololobus** [comment]
Looks like all PRs have been merged, slosing
