### ISSUE TITLE
noisy `Oversized vectored read (131100 > 131072) for keys` in prod logs

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8967]
[Sample](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22f3i%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_region%3D%5C%22eu-central-1%5C%22,neon_service%3D~%5C%22pageserver%7Cstorage-controller%5C%22%7D%20%7C~%20%60WARN%7CERR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221725825075489%22,%22to%22:%221725867990905%22%7D%7D%7D&orgId=1)

```
synthetic_size_worker:calculate_synthetic_size{tenant_id=$TENANT shard_id=0000}:gather_size_inputs{tenant_id=$TENANTshard_id=0000}:find_gc_cutoffs{timeline_id=$TENANT}: Oversized vectored read (131100 > 131072) for keys 01000000000000000100000006000000001F@F/B10B6FB8
```

**Comment by VladLazar** [comment]
Don't think it pug per say, but will take a look.

**Comment by problame** [comment]
One more occurence with a different oversize

```
2024-09-09T10:38:00.505829Z  WARN initial_size_calculation{tenant_id=$TENANT_ID shard_id=0000 timeline_id=$TIMELINE_ID}:logical_size_calculation_task: Oversized vectored read (165376 > 131072) for keys 000000067F00004002000000000000000001@32/84139CE0
```

**Comment by VladLazar** [comment]
We print this when trying to read a key value that's larger than 128KiB. Wondering why those values are that big,
but we can bump this soft limit up to say 256KiB if we are okay with that. Alternatively, we can downgrade the log line.

**Comment by VladLazar** [comment]
Only `eu-central-1` is warning about this consistently.

There's three problematic tenant/timelines:
* tenant_id=72f0f5a7500f8de1c38e47b35c60df5c timeline_id=c9fec91a93c71ecc050cfbd609e67063: 01000000000000000100000006000000001F
* tenant_id=b16d9159b86d0e93d5b3db1852334249 timeline_id=0892d9bf5539f39cd75e4380fdaaa99e: 000000067F00006000000000000000000001
* tenant_id=b16d9159b86d0e93d5b3db1852334249 timeline_id=390b053b08448683791cafe3d4af9590 000000067F00006000000000000000000001

`000000067F00006000000000000000000001` is a reldir and `01000000000000000100000006000000001F` is an SLRU block. Pageserver doesn't have control for either of these.

**Comment by VladLazar** [comment]
Action items:
* allow list reldir & dbdir keys
* ask compute about the slru block

**Comment by VladLazar** [comment]
From [chat with Heikki](https://neondb.slack.com/archives/C04DGM6SMTM/p1727773237642709): it's okay for slru deltas to be slightly above 128KiB due to overhead in the storage format. Let's bump the threshold to 130KiB and allow list unbounded key types (reldir & dbdir).
