### ISSUE TITLE
basebackup errors due to client timeout are mis-attributed as error in metrics

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8970]
During today's release, according to metrics, there was a basebackup error on ps-14 eu-central-1 because a client hung up:

```
2024-09-09T10:52:12.309115Z  INFO page_service_conn_main{peer_addr=10.7.89.193:56278}: query handler for 'basebackup $TENANT_ID $TIMELINE_ID 0/40C27328 --gzip' failed with expected io error: Connection timed out (os error 110)
```

The [metrics](https://neonprod.grafana.net/d/d061a222-a79b-4c4b-8e77-16b11545b1fe/pageserver-4-golden-signals?orgId=1&var-datasource=ZNX49CDVz&var-group_by=instance&var-getpage_latency_percentiles=0.99&var-getpage_latency_percentiles=0.999&var-instance=All&var-neon_region=eu-central-1&var-basebackup_latency_percentiles=0.99&var-basebackup_latency_percentiles=0.999&from=1725878987568&to=1725879424068&viewPanel=1) count this as an error.

It
* either shouldn't be counted as an error or
* if we want to treat it as an error, the log message should be adjusted to be WARN, or
* we need a third `result` field tag, i.e., instead of `ok|error` we need `ok|client_problem|server_problem`
  * would require adjustment of the dashboard -,-

**Comment by skyzh** [comment]
I think I'll use the alert condition https://neonprod.grafana.net/alerting/grafana/fdl736167lc74a/view as the source of truth for basebackup errors, which captures `basebackup pageserver error`, instead of the messages coming from the postgres protocol backend

**Comment by skyzh** [comment]
well, I didn't realize there's also a prometheus metrics on basebackup error; I feel a better fix is to add a `result="client_error"` type to the series

**Comment by skyzh** [comment]
need to update the 4GS dashboard after next week's deployment

**Comment by skyzh** [comment]
...thus leaving the issue open for now

**Comment by skyzh** [comment]
no update required for the dashboard b/c it's already using the `error` series: the patch splits the original `error` label into `error` (server error only) and `client_error`.
