### ISSUE TITLE
safekeeper: root-cause `WAL sender: failed to open WAL file`

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#8974]
```
2024-09-09T16:15:14.448108Z  WARN {cid=987 ttid=$TTID application_name=Some("pageserver")}:WAL sender: failed to open WAL file /storage/safekeeper/data/$TENANT_ID/$TIMELINE_ID/0000000100000802000000D7
```

[Query](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22f3i%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_region%3D~%5C%22us-east-2%5C%22,neon_service%3D~%5C%22safekeeper%7Cpageserver%7Cstorage-controller%5C%22%7D%20%7C~%20%60WARN%7CERR%60%20%21%3D%20%60ingesting%20record%20with%20timestamp%20lagging%20more%20than%60%20%21%3D%20%60Oversized%20vectored%20read%20%28131100%20%3E%20131072%29%60%20%21%3D%20%60unexpected%20message%20type:%20CopyData%60%20%21%3D%20%60this%20timeline%20is%20using%20deprecated%20aux%20file%20policy%20V1%60%20%21~%20%60Timed%20out%20after.%2Adownloading%20layers%60%20%21%3D%20%60Oversized%20vectored%20read%20%28165376%20%3E%20131072%29%20for%20keys%60%20%21%3D%20%60Oversized%20vectored%20read%20%28131584%20%3E%20131072%29%60%20%21%3D%20%60Correcting%20drift%20in%20progress%20stats%60%20%21~%20%60query%20handler%20for%20%27IDENTIFY_SYSTEM%27%20failed.%2Awas%20not%20found%20in%20global%20map%60%20%21%3D%20%60is%20ahead%20of%20available%20WAL%60%20%21%3D%20%60failed%20while%20offloading%20range%60%20%21%3D%20%60failed%20to%20send%20ErrorResponse:%20Broken%20pipe%20%28os%20error%2032%29%60%20%21%3D%20%60failed%20to%20send%20ErrorResponse:%20Connection%20reset%20by%20peer%20%28os%20error%20104%29%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22to%22:%221725900941482%22,%22from%22:%221725897341482%22%7D%7D%7D)

Likely a race condition, for example with timeline deletion.

Maybe same condition as https://github.com/neondatabase/neon/issues/8972

**Comment by arssher** [comment]
Yes, very likely a race with timeline deletion, it should be made graceful (waiting for walsender shutdown).
