### ISSUE TITLE
[Proxy] Can't connect to compute with new password

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#8989]
## Steps to reproduce
The control plane and proxy have been configured to different proxies
Proxy service is able to connect to Redis, but because of misconfiguration, it will not receive any notifications
As a user, I am changing the password via console UI. And I'm not able to connect to my compute (the cache wasn't cleaned after some time even though only a proxy restart was helpful)

## Expected result
After some time, I'll be able to connect to my compute

## Actual result
The cache lives forever

## Environment
Prod

## Logs, links
- https://neondb.slack.com/archives/C06SJG60FRB/p1726043630662139?thread_ts=1726043601.679529&cid=C06SJG60FRB

**Comment by conradludgate** [comment]
Tentatively closing this as I don't think it's a real issue that needs tracking
