### ISSUE TITLE
Failures in test_pageserver_compaction_smoke

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9160]
This became unstable around 2024-09-16

Example:

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9159/11046480008/index.html#testresult/4f81916b62299f3d/retries
```
AssertionError: assert 8.003249451766134 < 8
```

**Comment by skyzh** [comment]
pg17 might be generating too many WAL records, and for the test case, after we trigger the compaction, new layers are still being flushed, probably because they didn't get handled before the compaction. will submit a fix to ensure all written data are flushed/uploaded before compaction takes place.
