### ISSUE TITLE
[tech debt] proxy: abstract away connection pools

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#9284]
Proxy now has several copy-pasted implementations of similar connection pools to postgres, serving various purposes. Would be good to try and abstract them in a nicer format that allows us to delete some code and reduce some complexity.

## Scram Proxy -> Postgres

https://github.com/neondatabase/neon/blob/6c05f89f7da0711e672d6e99258d4223abf47671/proxy/src/serverless/conn_pool.rs

In the `conn_pool.rs` we have a map from `(Endpoint) -> (DatabaseName, Username) -> Vec<Client>`.
We have limits in place per endpoint. Clients are fully removed from the pool while in use.

Adjacent to the `tokio_postgres::Client` is a `tokio_postgres::Connection` which is spawned into a separate task, and also has a hook into the pool, to try and remove the registered client upon connection closure.

## Auth Broker -> Local Proxy

https://github.com/neondatabase/neon/blob/6c05f89f7da0711e672d6e99258d4223abf47671/proxy/src/serverless/http_conn_pool.rs

In `http_conn_pool.rs`, we have a map from `(Endpoint) -> Vec<SendRequest>`.
There are no limits in place per endpoint, but due to the fact clients can stay in the pool and be re-used (http2 multiplexing), we don't expect many clients to ever be in each vec.

Adjacent to the `SendRequest` is a `hyper::client::conn::http2::Connection` which is spawned into a separate task, and also has a hook into the pool, to try and remove the registered client upon connection closure.

## Local Proxy -> Postgres

https://github.com/neondatabase/neon/blob/7dc9c36ef05f070d22cd5ed2f391c8c0f7776925/proxy/src/serverless/local_conn_pool.rs

In the `local_conn_pool.rs` we have a map from `(DatabaseName, Username) -> Vec<Client>`.
We have limits in place globally. Clients are fully removed from the pool while in use.

Adjacent to the `tokio_postgres::Client` is a `tokio_postgres::Connection` which is spawned into a separate task, and also has a hook into the pool, to try and remove the registered client upon connection closure.

**Comment by awarus** [comment]
I landed 2 PRs, and want to make one more for http connection pool (~1-2 days)
