### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [neondatabase/neon#9305]
## Steps to reproduce
In the last row in my table, when double-clicking on a certain field value, It pops up a dropdown for options like `NULL` or `empty string`, but because it is the last row there is no space under, I can not access the menu tho.
![Image](https://github.com/user-attachments/assets/cb20f289-6c30-46fa-b17b-05cce29383ed)

## Expected result
add a little bottom margin or padding after the whole table for better accessibility

## Environment
win11, chrome Version 129.0.6668.90 (Official Build) (64-bit)

## Logs, links
-

**Comment by jcsp** [comment]
Hi @Ebrahim-Ramadan - this github project is for the open source neon components only.

Guidance on reporting issues in the website:

If you're on one of our paid plans, we recommend using our dedicated Support help desk to report issues and get help from the Neon Support Team. You can easily open a ticket through the Neon Console. For step-by-step instructions, check out [How to Open a Support Ticket](https://neon.tech/docs/introduction/support#standard-support).

If you use our Free Plan, you can join the [Neon Discord Server](https://discord.gg/92vNTzKDGp) to ask questions or see what others are doing with Neon. You will find Neon users and members of the Neon team actively engaged in our Discord Server.

If want help, post a question in the #gpt-help or ⁠#questions-and-answers channels.

If you wish to report an issue, use the #feedback channel.
