### ISSUE TITLE
safekeeper: add metric for per-timeline queue depth/buffer size

### ISSUE THREAD

**Issue by erikgrinaker** [neondatabase/neon#9328]
When shipping WAL from safekeepers to pageservers, we presumably buffer the WAL records. We should have a metric tracking how much WAL is buffered or in-flight.

Ideally per timeline, but this has very high cardinality. Optionally, we can consider a histogram.

Also investigate current buffer sizes and limits.

**Comment by erikgrinaker** [comment]
cc @jcsp @VladLazar safekeeper buffering ^

**Comment by VladLazar** [comment]
> This is basically negligible, and can be ignored.

Interesting. This is what we theorised in London.
