### ISSUE TITLE
GitHub doesn't highlight our Dockerfiles with any syntax highlighting

### ISSUE THREAD

**Issue by tristan957** [neondatabase/neon#9369]
We can tell GitHub how to highlight the files by configuring it in the `.gitattributes` file. I was looking into this, and found that you can use the extension `.dockerfile`, and GitHub will automatically use it, or we can do something like `Dockerfile.* linguist-language=Containerfile` in the `.gitattributes` file.

Which of the two approaches should we take?

**Comment by bayandin** [comment]
I think we should use `.dockerfile` extension.

> A common convention is to name these `<something>.Dockerfile` 

From https://docs.docker.com/build/concepts/dockerfile/#filename
