### ISSUE TITLE
CPU/heap profiling at runtime

### ISSUE THREAD

**Issue by erikgrinaker** [neondatabase/neon#9534]
Having access to CPU and heap profiles would be very useful while debugging production incidents. We should add support for taking such profiles at runtime.

It's probably too expensive to always enable profiling, but taking e.g. a 10-second profile on demand (via some API) would typically be sufficient.

We can either add profiling to the binaries themselves or explore integrating with some third-party observability service that supports taking such profiles.

**Comment by erikgrinaker** [comment]
Some options:

* [Grafana Cloud Profiles](https://grafana.com/products/cloud/profiles-for-continuous-profiling/): continuous profiling. Wraps pprof-rs.
* [Polar Signals](https://www.polarsignals.com): continuous profiling. Uses pprof profiles.
* [pprof-rs](https://github.com/tikv/pprof-rs): in-process profiler. No heap profiles.
* [cpuprofiler](https://github.com/AtheMathmo/cpuprofiler): in-process profiler. Supports pprof.

**Comment by mickael-carl** [comment]
See also: neondatabase/cloud#14888

**Comment by erikgrinaker** [comment]
CPU and heap profiling is in place for Pageserver and Safekeeper, so I'll close this out.

* https://github.com/neondatabase/neon/pull/9764
* https://github.com/neondatabase/neon/pull/9778

The heap profiles aren't automatically symbolized, this will be handled in #9964. Continuous profiling is tracked in https://github.com/neondatabase/cloud/issues/14888.
