### ISSUE TITLE
pageserver: generation numbers for manifest objects

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9543]

**Comment by arpad-m** [comment]
https://github.com/neondatabase/neon/pull/9545

**Comment by arpad-m** [comment]
Second PR: https://github.com/neondatabase/neon/pull/9555

**Comment by arpad-m** [comment]
The missing item here is tests, which will be addressed by https://github.com/neondatabase/neon/pull/9609

**Comment by arpad-m** [comment]
The PR merged, closing.
