### ISSUE TITLE
pageserver: aux keys go to all shards

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#9641]
While reading some unrelated code, I noticed that we write aux keys to all shards. Apparently, they should only be on shard 0.
I checked out the code prior to my sharded ingest work and believe that has always been the case.

We should:
* make sure that's the current state of affairs (I'm pretty sure - but let's check)
* only write aux keys to shard 0

**Comment by jcsp** [comment]
I'm picking this up in https://github.com/neondatabase/neon/pull/9786 where we're also changing SLRUs to only go on shard 0
