### ISSUE TITLE
Epic: Avoid data bloat in gc for branch hierarchies

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#970]
In https://github.com/zenithdb/zenith/pull/879 I've mentioned that we might keep more data than needed when branching is involved. So when we have parent and child branches parent cannot delete data which might be referenced by the child, but if child overwrites this data parent no longer needs to keep the data. Currently this may result in bloat because we keep such data forever.

**Comment by koivunej** [comment]
(Just browsing the list here), related to more recent epic, https://github.com/neondatabase/neon/issues/3064#issuecomment-1346436977 (branch an existing timeline, don't need ancestor anymore).

**Comment by stepashka** [comment]
@shanyp suggested we close this
we have some otehr tasks in motion that address the issue

**Comment by koivunej** [comment]
No fixes have gone in but my original comment was just because of @vk creating that newer epic :)
