### ISSUE TITLE
WAL redo processes leak DSM segments, i.e. files in `/dev/shm/`

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#9738]
Each WAL redo process creates a tiny DSM segment, like `/dev/shm/PostgreSQL.3449905360`. They are not always (never?) cleaned up on exit, not even on pageserver restart, so a pageserver host can accumulate tens of thousands of these files over time. Each file is small, 3-5 kB, but they add up to a lot of wasted memory over time.

slack discussion: https://neondb.slack.com/archives/C033RQ5SPDH/p1731486990179549?thread_ts=1731445405.348699&cid=C033RQ5SPDH

A WAL redo process should not need DSM for anything, so let's remove the DSM initialization step altogether, so that the files are not created in the first place.

**Comment by problame** [comment]
After this is fixed, rolled out, and won't be rolled back, ping

- https://github.com/neondatabase/cloud/issues/20348 

so we can do the cleanup.

**Comment by knizhnik** [comment]
PR solving this problem is merged

**Comment by problame** [comment]
For posterity, that PR is https://github.com/neondatabase/neon/pull/9793

**Comment by skyzh** [comment]
fyi, the command to remove the files:

```
sudo find /dev/shm -name 'Postgres.*' -depth -mtime +7 -type f -print
sudo find /dev/shm -name 'Postgres.*' -depth -mtime +7 -type f -delete
```

**Comment by problame** [comment]
I just manually checked that the bug is truly fixed, because the PR doesn't have any tests.

It appears to be fixed for walredo.

However, whenever I create a new tenant, initdb runs and creates a new file in `/dev/shm`.
If initdb completes with success, it cleans up the file.

But, it would be nice if it didn't create the file in the first place.
Is that possible?

**Comment by ololobus** [comment]
> But, it would be nice if it didn't create the file in the first place.
> Is that possible?

Discussed on the compute planning. It's (initdb) is upstream code, so it's likely not a quick fix, and we'd like to avoid patching it

**Comment by hlinnaka** [comment]
Using `initdb --set dynamic_shared_memory_type=mmap` option helps somewhat. Normally, initdb creates and deletes many files in /dev/shm, as it works through different phases of bootstrapping. With that option, it still does it once, but it reduces the window where you might fail and leave it behind.

**Comment by problame** [comment]
I'll mark this as resolved. If the initdb thing becomes a practical problem, we'll create a new issue.
