### ISSUE TITLE
pageserver: optimize `HashMap::insert()` in `SerializedValueBatch::extend()`

### ISSUE THREAD

**Issue by erikgrinaker** [neondatabase/neon#9848]
During bulk ingestion in the WAL receiver, `HashMap::insert` shows up prominently in profiles under `SerializedValueBatch::extend` via `validate_lsn_order`. This likely contributed to pathologically slow bulk ingestion in [this Slack thread](https://neondb.slack.com/archives/C07R3GZ9AQN/p1732186338497579).

* [profile.svg.gz](https://github.com/user-attachments/files/17868666/profile.svg.gz)

**Comment by erikgrinaker** [comment]
Regression caused by https://github.com/neondatabase/neon/pull/9579. Profile on the parent doesn't show the hashmap inserts:

* [profile-before.svg.gz](https://github.com/user-attachments/files/17868870/profile-before.svg.gz)

**Comment by hlinnaka** [comment]
Hmm, all the `validate_lsn_order` calls are guarded by `if cfg!(any(debug_assertions, test))`. Are you sure you used a release build? 

I don't actually see `validate_lsn_order` in the flamegraphs you included though.

**Comment by erikgrinaker** [comment]
Oof, you're right. Was just blindly following the profiles. This is a red herring then.

>I don't actually see validate_lsn_order in the flamegraphs you included though.

Should be in the link on the main comment: https://github.com/user-attachments/files/17868666/profile.svg.gz
