### ISSUE TITLE
Epic: implement migration of a tenant between safekeeper nodes

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#985]
## Motivation

We want to be able to assign tenants and timelines to the safekepeepers running on the appropriate EC2 instances, to be able to distribute the tenants and their workloads on EC2 instances fairly. This helps achieve the stable user query latencies and avoid noisy neighbor issues and when necessary perform maintenance and upgrades on the nodes where the safekeeper runs.

See #886 for a similar issue in pageservers

## DoD

Add possibility to move tenant from one storage node to another. For now it is okay to require compute node restart to do that.

## Tasks

Right now control plane assigns new cluster to the set of 3 random safekeepers. If one of that safekeepers is overloaded or down we may want to change that set of safekeepers. To ensure safety during the reconfiguration we need to change only one safekeeper at a time. That way majority still has term/epoch information and would protect us from split brain. If we pass pageserver connection info from the compute node to safekeeper then we can change safekeeper set by updating `postgresql.conf` and restarting compute -- that way new safekeeper will connect to the same pageserver. New safekeeper that does not have that compute timeline will accept it the same way it accepts newly created timeline.

- [x] #1170
- [x] #893
- [x] #892
- [x] #894
- [x] #895
- [x] #808

**Comment by petuhovskiy** [comment]
Basic support for this recently landed in main and on cloud staging. Follow ups are in https://github.com/neondatabase/cloud/issues/348
