### ISSUE TITLE
Support for common extensions

### ISSUE THREAD

**Issue by MMeent** [neondatabase/neon#986]
Locally, we can't currently use extensions, while at least some / most of the contrib extensions should be included to have some parity with Aurora.

Topics to consider:

- Does the extension directly interface with FS?
- Does the extensions use custom WAL? Does pageserver need to take special care of this WAL?
- Can the default zenith user install the extensions?
- Is the extension secure?

Steps:

 - [x] zenithdb/console#344
 - [ ] follow up with curating, extending the list of common extentions zenithdb/console#345

**Comment by stepashka** [comment]
I'm re-closing this as we've provided the support for some common extentions and confirmed that it works
I'm leaving the follows up in neondatabase/colud#345  for considering more extensions
