### ISSUE TITLE
Investigate performance degradation of pgvector 0.8.0 at neon

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#9892]
New version of the extension is available, but it shows performance degradation in our benchmark.
We need to investigate and fix the issue before merging the PR.

https://github.com/neondatabase/neon/pull/9733

The pgvector 0.8.0 bench has run to completion successfully but pgvector indexing time in this run has been 1h47m while prior run with 0.7.4 was 1h12 minutes.

- pgvector 0.8.0

Run 1 1h47
https://github.com/neondatabase/neon/actions/runs/11804399332/job/32884522153

Run 2 - 5h53 (!!)
https://github.com/neondatabase/neon/actions/runs/11809885891/job/32900971252

- pgvector 0.7.4: 1h12

https://github.com/neondatabase/neon/actions/runs/11789984141/job/32839684091

---
relevant [slack thread](https://neondb.slack.com/archives/C04DGM6SMTM/p1731343604259169)

**Comment by hlinnaka** [comment]
per slack discussion, this was an issue with autoscaling, not pgvector. Latest benchmark runs with 0.8.0 don't show a regression anymore.
