### ISSUE TITLE
pageserver: clean up stray VM pages

### ISSUE THREAD

**Issue by erikgrinaker** [neondatabase/neon#9927]
In #9855 and #9914, we saw that `ClearVmBits` updates may be applied on shards that aren't responsible for VM pages. This can lead to stray writes to these keys, which can be incomplete since the shards will not have seen WAL records for these pages. We should clean these keys up, to avoid them cropping up again later and causing problems.

Bonus question: if we only apply `ClearVmBits` but not the page images on stray shards, why don't these error out during compaction when we presumably try to reconstruct the VM pages?

**Comment by erikgrinaker** [comment]
@jcsp indicated in https://github.com/neondatabase/neon/pull/9786#discussion_r1866229753 that it's probably too expensive to force a recompaction of all tenants, since it requires downloading all layers from S3. So we'll just do this best-effort during compactions.

Let me know if I misinterpreted you @jcsp.

**Comment by jcsp** [comment]
> Bonus question: if we only apply ClearVmBits but not the page images on stray shards, why don't these error out during compaction when we presumably try to reconstruct the VM pages?

Speaking from memory: the `ShardedRange` that we use to build the list of pages to include in compaction excludes them
