### ISSUE TITLE
configuration file "/var/db/postgres/compute/pgdata/postgresql.conf" contains errors

### ISSUE THREAD

**Issue by Bodobolero** [neondatabase/neon#9945]
https://github.com/neondatabase/neon/pull/9843 is not fixed, see https://neondb.slack.com/archives/C04DGM6SMTM/p1732886142706659?thread_ts=1732885753.887279&cid=C04DGM6SMTM

## Expected result

Neon control plane and compute_ctl generate valid postgresql.conf

## Actual result

configuration file "/var/db/postgres/compute/pgdata/postgresql.conf" contains errors; unaffected changes were applied

https://neonprod.grafana.net/goto/uFIPUqnHg?orgId=1

## Environment

staging and prod

## Logs, links
- 
Note that in staging we had 230k of these errors in last day
[https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22dab%22:%7B%22datasourc[…]221732886093418%22,%22from%22:%221732799693418%22%7D%7D%7D](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22dab%22:%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bnamespace%3D%5C%22default%5C%22,%20container%3D~%5C%22neonvm-runner%5C%22%7D%20%20%20%7C%20unpack%20%7C%3D%20%5C%22PG:%5C%22%20%7C%3D%20%5C%22configuration%20file%20%5C%5C%5C%22%2Fvar%2Fdb%2Fpostgres%2Fcompute%2Fpgdata%2Fpostgresql.conf%5C%5C%5C%22%20contains%20errors%5C%22%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22to%22:%221732886093418%22,%22from%22:%221732799693418%22%7D%7D%7D)
[2:16](https://neondb.slack.com/archives/C04DGM6SMTM/p1732886184623989?thread_ts=1732885753.887279&cid=C04DGM6SMTM)
in prod we had 400k in one day [https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22dab%22:%7B%22datasourc[…]221732886156058%22,%22from%22:%221732799756058%22%7D%7D%7D](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22dab%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bnamespace%3D%5C%22default%5C%22,%20container%3D~%5C%22neonvm-runner%5C%22%7D%20%20%20%7C%20unpack%20%7C%3D%20%5C%22PG:%5C%22%20%7C%3D%20%5C%22configuration%20file%20%5C%5C%5C%22%2Fvar%2Fdb%2Fpostgres%2Fcompute%2Fpgdata%2Fpostgresql.conf%5C%5C%5C%22%20contains%20errors%5C%22%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22to%22:%221732886156058%22,%22from%22:%221732799756058%22%7D%7D%7D)

**Comment by tristan957** [comment]
Ok, I figured out what our problem is. We initially write the extension server port into the `postgresql.conf` file, but on reconfigure, we remove it. I'll see what the best solution is.

**Comment by Bodobolero** [comment]
good catch, thanks for reacting quickly @tristan957
