### ISSUE TITLE
Instability in `test_prefetch`

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9961]
Test was added in https://github.com/neondatabase/neon/pull/9847/files

Is failing with a timeout, about 10% of the time.

The test does a tight loop of reads for many minutes: should this be in `test_runner/performance` instead?  Even if we adjust the timeout on this test, I worry that a test like this will destabilize others when run in parallel.

**Comment by ololobus** [comment]
Seems to be stable after the fix

<img width="841" alt="Image" src="https://github.com/user-attachments/assets/f539ac18-bc43-4b5e-a031-d0b7ac37706e" />

> The test does a tight loop of reads for many minutes: should this be in test_runner/performance instead? Even if we adjust the timeout on this test, I worry that a test like this will destabilize others when run in parallel.

Discussed with @hlinnaka and @knizhnik, it's needed for correctness test at this moment. Making it less heavy will decrease the chance that it will catch the actual problem

Considering that and that it's not flaky atm, closing. Feel free to reopen if you still see a problem
